go/def.bzl
Pull in upstream security and bug fixes.
=> Update to go 1.6.2

go/def.bzl
=> Fix build errors in cgo_library rules at the top level package

go/def.bzl
Implement the old behavior of File.short_path by myself
Fixes #35.
=> Workaround of bazelbuild/bazel#1462

go/tools/generate_test_main.go
Hi @yugui, this is for issue #64.
=> Basic TestMain support

go/tools/gazelle/gazelle/main.go, go/tools/gazelle/generator/generator.go, go/tools/gazelle/generator/generator_test.go, go/tools/gazelle/rules/BUILD, go/tools/gazelle/rules/generator.go, go/tools/gazelle/rules/generator_test.go, go/tools/gazelle/rules/resolve.go, go/tools/gazelle/rules/resolve_structured.go, go/tools/gazelle/rules/resolve_structured_test.go, go/tools/gazelle/rules/resolve_test.go, go/tools/gazelle/testdata/repo/lib/deep/thought.go
* Extracted from #51 
* Depends on #57
=> Support dependencies to go_library rules in the same repository

go/tools/gazelle/generator/generator.go, go/tools/gazelle/generator/generator_test.go
Merged #79 into another branch than master by mistake.
Let me try again.
=> Generate go_prefix even if repo root is not a go package

go/def.bzl
Adds dependency to crosstool
Fixes #82
=> Fix build failures of cgo targets in OSX sandbox

go/def.bzl
I'm not sure this is the *correct* fix for #97 , but it resolves the issue for us.
=> Include execroot-relative include paths in cgo command line

README.md, WORKSPACE, go/def.bzl, go/tools/fetch_repo/BUILD, go/tools/gazelle/gazelle/main.go, go/tools/gazelle/rules/BUILD
c.f. #15 and https://github.com/bazelbuild/rules_go/issues/16#issuecomment-216218578
=> Add go_repository and new_go_repository rules

go/def.bzl
=> Resolve workspace warning from io_bazel_rules_go_toolchain

examples/cgo/BUILD, examples/cgo/import_example.go, go/def.bzl
=> Apply the given copts to cgo code generation

examples/cgo/BUILD, examples/cgo/import_example.go
=> Fixes a build error introduced in #123

go/tools/gazelle/gazelle/main.go
After this and the go_prefix PR https://github.com/bazelbuild/rules_go/pull/128 in most cases after the initial setup, you can just run 'gazelle' with no arguments.
=> Gazelle: make the default mode 'fix'

examples/proto/lib/BUILD, examples/proto/lib/lib.proto, proto/go_proto_library.bzl
fixes
https://github.com/bazelbuild/rules_go/issues/134
=> fix go_proto_library to handle transitive imports of external protos

go/private/go_repositories.bzl
=> Remove unused and undefined reference to external repositories

go/tools/gazelle/rules/resolve_external.go, go/tools/wtool/BUILD, go/tools/wtool/main.go
=> add wtool for simple adding of new_go_repository to the WORKSPACE file

go/tools/gazelle/rules/generator.go
Fixes https://github.com/bazelbuild/rules_go/issues/178
=> do not create a go_library if there are no srcs

proto/go_proto_library.bzl
it should have been doing this all along.
=> have go_proto_library output to genfiles 

examples/cgo/skip_go_library/BUILD, examples/cgo/skip_go_library/cgo_foo.go, examples/cgo/skip_go_library/types.go, go/def.bzl
=> support cgo_libraries that should not create go_libraries

go/tools/generate_test_main.go
Currently we are passing nil for benchmarks to Main/MainStart for
benchmarks. With this change benchmark tests should work.
=> Adding support for go benchmark tests

go/tools/gazelle/README.md
This commit should have been part of #228.
=> Gazelle: remove fixed shortcoming from README.md

proto/go_proto_library.bzl
See Issue #242 
Also fix .bzl style to better match Google Python style (these came from clang-format).
=> Fix go_proto_library to support importing repo-root protos.

go/private/go_repositories.bzl, go/tools/gazelle/gazelle/BUILD, go/tools/gazelle/gazelle/diff.go, go/tools/gazelle/gazelle/fix.go, go/tools/gazelle/gazelle/fix_test.go, go/tools/gazelle/gazelle/main.go, go/tools/gazelle/gazelle/print.go, go/tools/gazelle/generator/BUILD, go/tools/gazelle/generator/generator.go, go/tools/gazelle/generator/generator_test.go, go/tools/gazelle/merger/BUILD, go/tools/gazelle/merger/merger.go, go/tools/gazelle/merger/merger_test.go, go/tools/gazelle/rules/BUILD, go/tools/gazelle/rules/construct.go, go/tools/gazelle/rules/generator.go, go/tools/gazelle/rules/generator_test.go, go/tools/wtool/BUILD, go/tools/wtool/main.go
switch to new import path in go and BUILD files
=> point to latest buildifier

README.md
=> Fix misunderstanding about gazelle and dependencies in README.md

Vendoring.md
=> Update Vendoring.md to mention new_go_repository

go/tools/gazelle/gazelle/main.go
=> gazelle: only rename BUILD files in "fix" mode

go/def.bzl
It's  a shell script, which is not executable on windows.
=> Change from executable to command

README.md
And a link to the Bazel website
=> Clarify README title by adding "Bazel"

go/def.bzl, go/tools/filter_tags/filter_tags.go, tests/tags_os/BUILD, tests/tags_os/baz_darwin.s, tests/tags_os/baz_linux.s, tests/tags_os/baz_other.s, tests/tags_os/tags_os_test.go
=> Filter .s sources with build tags and suffixes

go/tools/gazelle/gazelle/main.go, go/tools/gazelle/testdata/repo/lib/doc.go
=> Change 'Gazel' to 'Gazelle' in usage message and testdata comment

go/tools/gazelle/gazelle/diff.go
buildifier/differ supports both graphical and non-graphical
diff. The graphical diff doesn't work though: it generates a
command line for tkdiff, but tkdiff doesn't actually accept commands
in that format.
With this change, we just print diffs in the simple unified format by
executing `diff -u`.
Fixes #342
=> Gazelle: remove support for graphical multidiff

README.md
=> Add announcement for new tags with buildifier rename fix

go/private/go_repositories.bzl
=> Support Go 1.8.1

README.md
Also fix whitespace issue in table of contents.
=> Update README.md in preparation for 0.4.3

README.md
Added some additional documentation for `go_prefix`, `go_library`,
`cgo_library`, and `go_test`.
Fixes #394
[skip ci]
=> Improve documentation in README.md for build rules

README.md, go/tools/bazel/BUILD, go/tools/bazel/README.md, go/tools/bazel/bazel.go, go/tools/bazel/bazel_test.go
After the discussion in bazelbuild/rules_webtesting#108 I figured I'd put together a PR to see what people think.
@DrMarcII, what do you think about this? Are you okay with me moving it? Are you okay with me making it //visibility:public?
@jayconrod what do you think about putting it here?
=> Add bazel helper library

README.md
=> Update README.md in preparation for 0.4.4 release

go/private/go_repository.bzl, go/tools/gazelle/gazelle/diff.go, go/tools/gazelle/gazelle/fix.go, go/tools/gazelle/gazelle/fix_test.go, go/tools/gazelle/gazelle/main.go
Fixes https://github.com/bazelbuild/rules_go/issues/456
=> Determine valid build file names from buildFileName flag

README.md, go/private/go_repository.bzl, tests/popular_repos/WORKSPACE.in
Replace url with urls attribute.
Require commit or tag only if urls is not set.
Disallow commit and tag if urls are set.
=> Improve go_repository when downloading from url

go/def.bzl, go/tools/generate_test_main.go
Add test coverage for rules_go.
=> Instrument test coverage, and modify the generated main test program

tests/coverage/BUILD, tests/coverage/coverage.bash, tests/coverage/coverage_test.go, tests/coverage/lib.go, tests/non_bazel_tests_common.bash, tests/run_non_bazel_tests.bash
=> Add test to verify coverage information is recorded

go/tools/gazelle/packages/walk.go, go/tools/gazelle/rules/construct.go, tests/build_gazelle_with_1.7/WORKSPACE.in, tests/build_gazelle_with_1.7/build_gazelle_with_1.7.bash, tests/run_non_bazel_tests.bash
* Removed calls to sort.Slice.
* Added manual test to verify Gazelle still builds.
Fixes #469
=> Restore compatibility with Go 1.7 for Gazelle

go/def.bzl, go/private/BUILD.sdk.bazel, go/private/go_tool_binary.bzl, go/private/go_toolchain.bzl, go/toolchain/toolchains.bzl
This transforms the includes used by the asm compiler from a filegroup to a cc
header library.
=> include -> headers

go/tools/gazelle/rules/generator.go
Minor refactoring in preparation for a much larger change.
Related #409
=> Gazelle select (9/x): refactor rules/generator.go

go/tools/gazelle/packages/BUILD, go/tools/gazelle/packages/package.go, go/tools/gazelle/packages/package_test.go
=> Gazelle select (8/x): methods for adding files to Package

go/tools/filter_tags/filter_tags_test.go
It was not actually using cgo.go or darwin.go in the tests, and was not testing
most of the combinations.
=> Improve the filter tag test

tests/cgo_multi_dir/BUILD, tests/cgo_multi_dir/bar/bar.go, tests/cgo_multi_dir/cgo_multi_dir_test.go, tests/cgo_multi_dir/foo/foo.go
=> Add test case for cgo building sources in multiple directories

go/tools/gazelle/rules/generator_test.go, go/tools/gazelle/testdata/repo/main_test_only/BUILD.want, go/tools/gazelle/testdata/repo/main_test_only/foo_test.go
=> Add test case for #516

README.md
=> Update README.md in preparation for 0.5.0 release

go/private/go_repository.bzl, go/private/repository_tools.bzl
=> In repository rules, wrap execute commands with "env -i".

go/private/cgo.bzl
Many of the copies were not needed, all the filtering ones.
This also removes 3 of the 4 directories that only existed to hold the copies.
_cgo_codegen was removed, it was not being used any more.
This also kills a bunch more uses of bash
=> Change cgo rules to not copy so much

go/private/cgo.bzl
This merges all the cgo codegen steps to 1 core rule.
This is all the logic that needs to happen before the cc_library rule in one
place, so we can easily replace the bash script with a single tool.
=> Merge cgo codegen steps

go/private/cgo.bzl, tests/cgo_sys_hdr/BUILD, tests/cgo_sys_hdr/foo.go, tests/cgo_sys_hdr/foo_test.go, tests/cgo_sys_hdr/sub/foo.h, tests/popular_repos/popular_repos.bash
=> Let cgo access headers using system paths relative to the package directory

tests/run_non_bazel_tests.bash, tests/test_filter_test/BUILD, tests/test_filter_test/test_filter_test.bash
from external bash test to internal bazel test.
=> Migrate test_filter_test

go/tools/wtool/main.go
Also, automatically load go_repository if it isn't loaded already.
=> wtool: add go_repository rules instead of new_go_repository

go/tools/gazelle/rules/resolve_external.go, go/tools/gazelle/rules/resolve_external_test.go
=> Gazelle: cache negative results in external dependency resolution

.travis.yml, README.md
=> Bump minimum version of Bazel to 0.5.2

go/private/common.bzl, go/private/go_tool_binary.bzl, tests/bazel_tests.bzl
This should fix breakage or rules_go on the CI: https://github.com/bazelbuild/bazel/issues/3387
=> Fix usage of declared providers

README.md
=> Update README.md in preparation for release 0.5.2

README.md
[skip ci]
[ci skip]
Fixes #624
=> Clarify WORKSPACE instructions in README.md

go/private/library.bzl
Don’t cover the same file twice
Make the names more unique
=> Fixing issues with cover generation

WORKSPACE, examples/bindata/BUILD.bazel, examples/bindata/bindata.bzl, examples/bindata/bindata_test.go, examples/bindata/data/message.txt
The basic rule is sufficient for normal use as well.
=> An example using go-bindata

README.md, Vendoring.md, go/tools/wtool/README.md
Also fix some typos in the README.
=> doc: remove refs to deprecated API

README.md
I was confused about the syntax for doing these two things with Bazel
- basically how to match the output of "go test", so it might be
helpful to explicitly show users what command they should be running
with "bazel test".
=> README: show how to run equivalent of ./... and stream output

README.md
=> Announce Bazel 0.5.3 breaking change in README.md

README.md
=> Fix Jenkins icon in README.md

go/tools/gazelle/merger/merger.go, go/tools/gazelle/merger/merger_test.go
* Gazelle is now more careful about discarding old attributes that
weren't in generated rules.
* Scalar attributes (like library or cgo) may now be annotated with
"# keep". They will not be changed or deleted.
* Multi-line lists with single elements will be kept multi-line after
merge.
* Merged lists with "# keep" elements will be forced multi-line.
Fixes #686
=> Gazelle: fix merger bugs with keep comments

go/tools/gazelle/gazelle/integration_test.go
Also removed go_prefix-related items from the TODO list, as we don't
plan to support the current behavior in the future.
=> Gazelle: add a few more integration tests

README.md
=> Update README.md in preparation for release 0.5.3

proto/go_proto_library.bzl
=> Update com_github_google_protobuf dependency to v3.3.0

go/tools/gazelle/rules/generator.go
=> Fix break in flat mode due to #722

README.md
=> Add note about depending on static binaries to README.md

README.md
=> Fix tags in README.md

go/private/repositories.bzl, go/toolchain/BUILD, go/toolchain/toolchains.bzl, tests/cgo_sys_hdr/sub/foo.h, tests/popular_repos/WORKSPACE.in, tests/popular_repos/popular_repos.bash
=> Adding go1.9

go/private/asm.bzl, go/private/binary.bzl, go/private/cgo.bzl, go/private/go_tool_binary.bzl, go/private/go_toolchain.bzl, go/private/library.bzl, go/private/test.bzl, go/private/tools/path.bzl, go/private/tools/vet.bzl, tests/bazel_tests.bzl
This is a small cleanup before the bigger change which will add the actions
struct to the toolchain, that carries all the toolchain methods.
=> Add structure to the go toolchain to group functionally related things.

go/private/rules/cgo.bzl, go/private/rules/library.bzl
=> Expose cgo_exports

go/private/repository_tools.bzl
Also have the default match the normal sdk default
Fixes #771
=> Allow the sdk used by repository tools to be overriden

go/private/actions/compile.bzl, go/private/actions/library.bzl, go/private/rules/binary.bzl, go/private/rules/test.bzl
And send it on to the -p flag of the compiler
Fixes #211
=> Add the import path to compile commands

go/private/go_repository.bzl
Written as a contribution to the discussion in #736
=> Drop hidden go_repository attributes

README.md
=> Update README.md in anticipation of 0.5.5

go/tools/gazelle/gazelle/main.go
Based on the work by Jannis Andrija Schnitzer (@xjs) in #821
=> Fix gazelle isDecendingDir on windows

go/private/BUILD.sdk.bazel, go/private/go_repository.bzl, go/private/repository_tools.bzl, go/private/toolchain.bzl
Based on the work by Jannis Andrija Schnitzer (@xjs) in #821
=> Windows .exe support

proto/toolchain.bzl
This saves writing new nearly identical rules for alternate plugin
implementations.
=> Make go proto plugin configurable

go/extras.rst
=> Document gazelle and go_embed_data rules

go/deprecated.rst, go/providers.rst, go/workspace.rst, proto/core.rst
This adds all the rules and headings so the links should all work, and also
helps me see what I still need to document.
More work on #810
[skip ci]
[ci skip]
=> Adding some more basic structure to the docs

README.rst
This is mostly because I want the FAQ entries listed and hyperlinkable
[skip ci]
[ci skip]
=> Change contents of README

go/deprecated.rst
More work on #810
[skip ci]
[ci skip]
=> Documentation for the deprecated rules

go/workspace.rst
More work on #810
[skip ci]
[ci skip]
=> Adding documentation for the workspace rules

go/platform/BUILD.bazel
We really need a single value we can select on, there are too many things that might mean windows right now....
=> Change config_setting cpu match for windows

go/deprecated.rst, go/modes.rst, go/providers.rst, go/toolchains.rst
More work on #810
[skip ci]
[ci skip]
=> Documentation for toolchains

BUILD.bazel, tests/bazel_tests.bzl, tests/go_embed_data/BUILD.bazel, tests/go_embed_data/embed_test.go, tests/test_rundir/BUILD.bazel, tests/test_rundir/rundir_test.go
I love it when documentation changes break tests, always makes me feel warm and
fuzzy inside...
=> Fix tests after documentation change

go/private/BUILD.bazel, go/private/actions/compile.bzl, go/private/actions/link.bzl, go/private/go_toolchain.bzl, go/private/rules/binary.bzl, go/private/rules/library.bzl, go/private/rules/test.bzl, proto/def.bzl
=> Fix debug mode and add dwarf stripping behavior

examples/proto/grpc/BUILD.bazel, proto/toolchain.bzl
=> Making it so multiple go proto compile rules can co-exist

go/private/rules/cgo.bzl
This fixes an error that occurred when cc_library generates multiple
archive files (.lo and .pic.lo) in some configurations (-c
opt). Rather than requiring a single file, _cgo_collect_info will now
choose a file based on extension.
Fixes #896
=> Cgo: choose archive by extension

README.rst
=> Announce new mailing list: bazel-go-discuss

go/private/BUILD.sdk.bazel, go/private/actions/action.bzl, go/private/go_toolchain.bzl, go/private/info.bzl, go/private/providers.bzl, go/private/rules/stdlib.bzl, go/private/tools/path.bzl, go/private/tools/vet.bzl, tests/bazel_tests.bzl
Also move the environment into the stdlib rather than the sdk and add parameters
for eventually controlling CGO_ENBALED variants.
=> Add the concept of a goos-goarch targetted stdlib

go/tools/gazelle/README.rst
=> Fix sublist formatting

go/tools/gazelle/resolve/resolve.go, go/tools/gazelle/resolve/resolve_test.go
* When resolving proto_library dependencies, a vendor/ prefix will no
longer be added in any case. These rules can't build because the
protoc import paths are not modified (and can't be right now).
* go_proto_library dependencies for Well Known Types will be resolved
to something in //vendor/github.com/golang/protobuf. This will
change in the future when we have better support for alternative
proto toolchains.
* There is now a special case for google/protobuf/descriptor.proto.
Fixes #888
Related #940
=> Gazelle: fix import resolution for vendored WKT protos

go/tools/gazelle/resolve/resolve_external.go, go/tools/gazelle/resolve/resolve_external_test.go
=> Gazelle: add gopkg.in to known repositories

go/toolchain/toolchains.bzl, go/toolchains.rst
=> bump Go version to 1.9.2

tests/race/BUILD.bazel
This actaully runs the race test we already had and checks it fails.
=> Add race test

README.rst
=> Add FAQ on testdata to README.rst

examples/proto/BUILD.bazel, examples/proto/embed/BUILD.bazel, examples/proto/embed/embed.go, examples/proto/embed/embed.proto, examples/proto/proto_test.go
This adds an example of how to include extra source files along with
your proto.
Fixes: #973
=> Add an example of additional files with protos

README.rst
=> Update README.rst for 0.7.0 release

go/private/actions/archive.bzl, go/private/actions/binary.bzl, go/private/mode.bzl, go/private/rules/cgo.bzl, go/private/rules/info.bzl, go/private/rules/library.bzl, go/private/rules/test.bzl, go/private/tools/vet.bzl, proto/def.bzl
Use the deps, not the direct dependancies of the deps
Fixes reported in person issue with pure="on"
Get the toolchain_flags from the rule not the aspect
Fixes #993
=> Fixes for aspect based builds

go/tools/gazelle/merger/merger_test.go, go/tools/gazelle/rules/sort_labels.go
=> Gazelle: add missing copyright notice in two files

go/workspace.rst
=> go_repository: document build_file_proto_mode attr

README.rst
=> README: Add Travis CI FAQ

go/private/actions/library.bzl, go/private/common.bzl, go/private/rules/cgo.bzl, go/private/skylib/README.rst, go/private/skylib/lib/dicts.bzl, go/private/skylib/lib/paths.bzl, go/private/skylib/lib/sets.bzl, go/private/skylib/lib/shell.bzl, go/private/skylib/lib/structs.bzl
Only one use so far (removing our implementation of struct->dict)
=> Initial drop of skylib

go/private/actions/archive.bzl, go/private/actions/asm.bzl, go/private/actions/compile.bzl, go/private/actions/cover.bzl, go/private/actions/library.bzl, go/private/actions/link.bzl, go/private/common.bzl, go/private/go_repository.bzl, go/private/rules/cgo.bzl, go/private/rules/test.bzl, go/toolchain/toolchains.bzl, proto/toolchain.bzl
Much less bouncing between them.
Also, no more ambiguious += statements
All in the name of performance,
=> Cleaning up lists, tuples and depsets

README.rst
=> Update README.rst for version 0.7.1

go/tools/gazelle/gazelle/integration_test.go, go/tools/gazelle/wspace/finder_test.go
=> Gazelle: skip some tests when repo WORKSPACE is visible

tests/popular_repos/popular_repos.bzl, tests/popular_repos/popular_repos.py
=> Make all popular_repo external repositories safe 

go/def.bzl
=> Declare rules version

README.rst
=> Update README.rst for 0.8.0 release

go/private/mode.bzl
Seems like this has not worked since cross compilation was added...
Fixes #1115
=> Fix --features=pure

go/tools/gazelle/rules/generator.go, go/tools/gazelle/testdata/repo/default_visibility/BUILD.want, go/tools/gazelle/testdata/repo/default_visibility/a_test.go, go/tools/gazelle/testdata/repo/default_visibility/cmd/BUILD.old, go/tools/gazelle/testdata/repo/default_visibility/cmd/BUILD.want, go/tools/gazelle/testdata/repo/default_visibility/cmd/main.go, go/tools/gazelle/testdata/repo/default_visibility/foo.proto, go/tools/gazelle/testdata/repo/default_visibility/lib.go
=> Gazelle: don't set visibility in proto rules with default visibility

go/tools/gazelle/resolve/index.go, go/tools/gazelle/resolve/resolve_test.go
Fixes bazelbuild/bazel-gazelle#23
=> Gazelle: fix logic bug in go proto dependency resolution

go/private/go_toolchain.bzl, go/private/mode.bzl
Also if pure is set, disable race
Fixes #1133
Fixes #1016
=> Force bootstrap toolchain to be non race

README.rst
=> Update README.rst for release 0.8.1

README.rst
=> Add FAQ on accessing binaries from tests

go/private/common.bzl, go/private/go_repository.bzl, go/private/rules/stdlib.bzl, go/private/sdk.bzl, go/private/skylib/lib/paths.bzl, tests/bazel_tests.bzl
No env command
.exe extensions
c:/ is an absoulute path
some arguments need quoting
=> Fixes for windows

go/private/common.bzl, go/private/context.bzl, go/private/go_repository.bzl, go/private/repository_tools.bzl, go/private/rules/stdlib.bzl, go/private/sdk.bzl
A basic build of a pure go binary on windows now fully works.
=> Working binaries built on windows

go/private/rules/info.bzl, go/tools/builders/info.go, tests/info/BUILD.bazel, tests/info/info_test.sh
Does not use bazel_test any more.
=> A faster non flakey go_info test

go/private/tools/gazelle.bzl
=> Fix gazelle script

examples/proto/gogo/BUILD.bazel, examples/proto/gogo/gogo_test.go, examples/proto/gogo/values.proto, go/private/repositories.bzl, proto/BUILD.bazel, proto/gogo.bzl
Adds all the plugins, and automatic support for the ptypes and options, along
with a working example
Fixes 816
=> Working support for gogo proto

go/private/actions/archive.bzl, go/private/actions/asm.bzl, go/private/actions/link.bzl, go/private/common.bzl, go/private/context.bzl, go/private/rules/aspect.bzl, go/private/rules/cgo.bzl, go/private/rules/test.bzl, go/private/tools/path.bzl, go/tools/builders/link.go, tools/bazel.rc
Turn on --all_incompatible_changes
Fix all the problems it shows up
Reduce depset collapses (may make builds faster)
Fixes #837
=> Skylark compatability

proto/go_proto_library.bzl
We need to be noisy for a bit in preparation for deleting the now defunct rules.
Progress on #812
=> Start complaining if people are using the old proto rules

go/tools/builders/asm.go, go/tools/builders/cgo.go, go/tools/builders/compile.go, go/tools/builders/filter.go
Should also make compilation faster as we no longer reparse for strict deps
Fixes #1081
=> Clean up filtering logic

go/private/sdk.bzl
=> Strip uname stdout before comparing known values

proto/compiler.bzl, proto/def.bzl
=> A better fix for prorto import paths

README.rst, go/private/rules/wrappers.bzl
It's functionality has been replaced by embed for some time, we shoud start
complaining when people use it.
=> Deprecate the library attribute

README.rst
=> Add FAQ on using beta versions of Go SDK

go/private/actions/compile.bzl, go/private/actions/link.bzl, go/private/rules/stdlib.bzl
=> Bootstrap reproducibility

go/private/common.bzl
=> Fix version string parsing for Bazel 0.10.0rc1

go/tools/builders/asm.go, go/tools/builders/cgo.go, go/tools/builders/compile.go, go/tools/builders/cover.go, go/tools/builders/env.go, go/tools/builders/generate_test_main.go, go/tools/builders/info.go, go/tools/builders/link.go, go/tools/builders/pack.go
This is called after args are parsed for calculated values to be updated.
=> Give GoEnv an update method

go/private/repositories.bzl
Changed protobuf source code id to the latest one.
=> Changed protobuf source code id to the latest one

README.rst
=> Announce release 0.9.0

go/tools/builders/cgo.go
=> Trim sandbox prefix from cgo generated line directives

go/private/go_toolchain.bzl
=> Bootstrap toolchains should not care what the target platform is

go/private/go_repository.bzl
=> go_repository: fail when http / vcs attributes are mixed

go/private/rules/wrappers.bzl
This cleans up the wrappers, and makes it much easier to see what is going on.
=> Wrapper clean up

go/private/actions/archive.bzl, go/private/actions/compile.bzl, go/private/context.bzl, go/private/rules/test.bzl, go/tools/builders/compile.go, go/tools/builders/generate_test_main.go, tests/core/go_test/BUILD.bazel, tests/core/go_test/README.rst, tests/core/go_test/flag_test.go
=> Adding combined internal and external test mode

go/workspace.rst
=> Add private git repository documentation

go/core.rst, go/private/rules/wrappers.bzl, go/toolchains.rst
Also:
* Fixed formatting of a list in toolchains.rst.
* Fixed deprecation message for go_test importpath.
=> Documentation and example for link stamping

go/private/go_repository.bzl
=> go_repository: raise timeout for fetch_repo

README.rst
Remove importpath from binary block in readme coz deprecated
=> Remove importpath from binary block

README.rst
=> Update README.rst ahead of 0.10.0 release

go/private/actions/link.bzl
=> Don't force external linking for static builds

go/tools/builders/replicate.go
=> Remove previously copied files before building stdlib

README.rst, roadmap.rst
=> roadmap.rst: a public roadmap for rules_go and Gazelle

go/private/tools/path.bzl
This PR adds the `runfiles` from `go_library` in the fake `GOPATH`.
Some packages try to find support files via `GOPATH` introspection, so this ensures the files are there.
=> Add runfiles to the fake GOPATH

proto/core.rst
=> Documentation for proto rules

go/tools/builders/generate_test_main.go, tests/core/go_test/BUILD.bazel, tests/core/go_test/example_test.go
fixes https://github.com/bazelbuild/rules_go/issues/1341
=> generate_test: implement example testing

go/tools/builders/protoc.go
The grpc_gateway plugin only creates output files for .proto files
that includes service definitions. We still need to declare output .go
files, since we don't know which .proto files have services during
analysis, but we don't need to report errors.
Related #1388
=> protoc: create trivial files for missing outputs

README.rst
=> Announce Gazelle 0.10.1

go/tools/builders/generate_test_main.go
=> Include import paths in coverage file names

README.rst
Fixes #1418
[skip ci]
[ci skip]
=> Test sharding works now

README.rst
=> Announce release 0.10.3

go/tools/builders/generate_test_main.go, tests/core/go_test/BUILD.bazel, tests/core/go_test/README.rst, tests/core/go_test/only_testmain_test.go
=> Fix build error when go_test contains TestMain but no tests

go/toolchains.rst
While learning about toolchains in Bazel I ended up here, and figured I'd chime in with some itty bitty typo fixes. 🙆‍♂️
=> Fix typos in Toolchain docs

.bazelci/presubmit.yml, README.rst, go/def.bzl, go/toolchain/toolchains.bzl, go/tools/builders/generate_test_main.go, tests/core/go_test/BUILD.bazel, tests/core/go_test/README.rst, tests/core/go_test/only_testmain_test.go
Will push directly to release-0.10 and tag a release when CI shows this is green.
=> Release candidate 0.10.4

README.rst
=> Update README.rst for 0.11.1

README.rst
=> Announce 0.12.0 release

go/private/rules/cgo.bzl, go/private/rules/wrappers.bzl
=> Propagate restricted_to and compatible_with attributes in cgo rules

go/private/actions/archive.bzl, tests/core/go_library/BUILD.bazel, tests/core/go_library/README.rst, tests/core/go_library/inc.go, tests/core/go_library/inc_bar.s
=> Allow .s files to include other .s files

go/tools/builders/generate_test_main.go, tests/core/README.rst, tests/core/go_test/BUILD.bazel, tests/core/go_test/README.rst, tests/core/go_test/pwd_test.go
=> Set PWD environment variable in generated testmain

README.rst
Also, fix gazelle example to use prefix directive instead of
attribute.
=> Announce release 0.14.0 [skip ci]

README.rst, go/workspace.rst
=> Document how to override go_rules_dependencies [skip ci]

tests/core/go_binary/BUILD.bazel, tests/core/go_binary/README.rst, tests/core/go_binary/many_deps.bzl
=> Add test generates long compile/link command lines

WORKSPACE
=> Update @bazel_toolchains in WORKSPACE

go/nogo.rst
Fix typos, formatting issues, and improve consistency in writing.
=> Further nogo documentation improvements

go/tools/builders/generate_test_main.go
Use a temporary directory instead of piggybacking into symlinked runfiles directories, as those might not be there on Windows.
Fix #1720
=> Fix non-root package testing on Windows

go/private/rules/cgo.bzl
=> Do not depend on stdlib for CGo Codegen anymore

WORKSPACE, extras/bindata.bzl, go/private/actions/asm.bzl, go/private/actions/compile.bzl, go/private/actions/cover.bzl, go/private/actions/link.bzl, go/private/actions/pack.bzl, go/private/rules/cgo.bzl, go/private/rules/info.bzl, go/private/rules/stdlib.bzl, go/private/rules/test.bzl, go/private/tools/path.bzl, proto/compiler.bzl, tests/bazel_tests.bzl
Also: replace most calls to args.add_all([key, value]) with
args.add(key, value).
=> Fix some incompatible warnings and run buildifier

go/BUILD.bazel
=> Define the toolchain_type target used by go rules.

BUILD.bazel, third_party/org_golang_x_tools-extras.patch
=> Add go_tool_library targets for analysis passes

go/private/sdk.bzl
https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#execute
=> Fix execute arguments to use list see github.com/bazelbuild/rules_go/issues/1782

go/nogo.rst
Create a "Setup" section similar to the core rules_go README
that gives direct instructions on how to get run nogo. Also,
make miscellaneous improvements to other section of nogo.rst.
Related #1777
=> Improve nogo documentation

tests/bazel_tests.bzl
This PR modifies `bazel_test` so that it is no longer required that bazel analyzes the targets in the host workspace.
Context: #1614, bazelbuild/bazel-gazelle#352
=> Don't analyze bazel_test targets in host workspace

go/private/skylib/README.rst, go/private/skylib/lib/collections.bzl, go/private/skylib/lib/dicts.bzl, go/private/skylib/lib/new_sets.bzl, go/private/skylib/lib/partial.bzl, go/private/skylib/lib/paths.bzl, go/private/skylib/lib/selects.bzl, go/private/skylib/lib/sets.bzl, go/private/skylib/lib/shell.bzl, go/private/skylib/lib/structs.bzl, go/private/skylib/lib/types.bzl, go/private/skylib/lib/unittest.bzl, go/private/skylib/lib/versions.bzl
=> Update vendored skylib to 0.5.0

WORKSPACE, go/def.bzl, go/private/repositories.bzl
- Update proto version
- Update Gazelle version
- Fix a remaining issue
Tested:
bazel test //... --all_incompatible_changes
Fixes #1829
=> Fix for remaining Bazel incompatible changes

go/extras.rst
=> Add link to gomock rule

go/private/rules/info.bzl
=> Pass all SDK files as inputs to go_info

README.rst, go/nogo.rst, go/toolchains.rst, go/workspace.rst
Also, change def.bzl to deps.bzl in documentation where needed.
=> Announce 0.17.0 release [skip ci]

go/tools/builders/nogo_main.go, tests/core/nogo/vet/BUILD.bazel, tests/core/nogo/vet/fmtwrap.go, tests/core/nogo/vet/has_errors.go
=> nogo: register fact types before encoding / decoding

WORKSPACE
=> Update bazel_toolchains to latest release

go/private/rules/cgo.bzl
When we analyze C dependencies in cgo, we try to locate static
archives that can be packed with the Go archives the compiler
produces. Currently, we expect cc_library to produce some kind of
static archive. It doesn't actually produce anything though if all .c
files are filtered out.
With this change, if a cc_library file doesn't produce any files, it
won't be built or packed.
Fixes #1930
=> cgo: don't require cc_library to produce files

README.rst, go/workspace.rst
Also, update "Overriding dependencies" documentation.
Fixes #1966
=> Announce Gazelle 0.17.0 [skip ci]

go/private/compat/compat_repo.bzl, go/private/compat/v18.bzl, go/private/compat/v23.bzl, go/private/rules/cgo.bzl, go/private/rules/test.bzl, go/private/tools/files_equal_test.bzl
Added a new compatibility function for InstrumentedFilesInfo.
Fixes #2012
=> Fix warnings from --incompatible_disallow_struct_provider_syntax

go/private/skylib/lib/unittest.bzl
=> Update code for Bazel change --incompatible_new_actions_api

go/private/platforms.bzl, tests/core/cross/BUILD.bazel
=> Fix iOS cross compilation and enable test

go/private/actions/stdlib.bzl, go/private/mode.bzl
=> Fail earlier with a message when C/C++ toolchain is needed but not configured

README.rst, WORKSPACE
* Update boilerplate in WORKSPACE
* Upgrade to 0.18.0 for testing.
Fixes #2145
=> Announce Gazelle 0.18.0

go/private/actions/link.bzl
=> De-duplicate coverdata for link action

go/tools/builders/cover.go
As part of instrumentation, all source files are made to import the coverdata package. This is done by inserting a declaration in the AST. This inserted declaration currently does not set a valid token position, and so is not inserted properly when there are comments for the first declaration in the original AST.
The code in this change is inspired by the [astutils package](https://github.com/golang/tools/blob/8bb11ff117ca820938b6d899b13b3f2832ef244c/go/ast/astutil/imports.go#L104).
Fixes #2156
=> Set token position of coverdata import declaration

go/platform/apple.bzl
=> Properly detect version-min on apple platforms

BUILD.bazel, go/platform/list.bzl, go/private/compat/v23.bzl, go/private/compat/v25.bzl, go/private/context.bzl, go/private/go_toolchain.bzl, go/private/platforms.bzl, go/tools/builders/stdlib.go
=> Fix cc_toolchain sandboxing and stdlib's CGO_LDFLAGS

go/private/sdk_list.bzl
Created using github.com/jayconrod/misc/cmd/format-releases
=> Support go1.13

go/private/sdk_list.bzl
=> Support go1.13.1

go/private/actions/link.bzl, tests/core/go_binary/BUILD.bazel, tests/core/go_binary/static_bin.go, tests/core/go_binary/static_test.go
Related to #2175, this fixes #2216.
Also adds tests for both #2216 and #2168.
=> GoLink: do not force external link for pure binaries

go/tools/bazel_testing/bazel_testing.go
=> go/tools/bazel_testing: fix slice append bug

go/private/sdk_list.bzl
=> Support go1.13.2 and 1.12.11

go/private/sdk_list.bzl
=> Support go1.13.4, 1.12.13

go/tools/bazel_testing/bazel_testing.go, tests/core/go_bazel_test/dataargtest_test.go
=> Add SetUp method to Args for go_bazel_test

go/tools/bazel_testing/bazel_testing.go
Previously, Bazel arguments resolved with $(location) or $(locations)
always included an "external/workspace/" prefix. We used this prefix
to map arguments to runfiles. Upcoming versions of Bazel won't add
this prefix to files in the main workspace.
Witht this change, bazel_testing will read the workspace name from the
WORKSPACE file from the main workspace (which must be among the
arguments). This makes sure that go_bazel_test targets in the main
workspace will continue to work.
Updates #2285
=> go/tools/bazel_testing: support location args without external prefix

go/private/sdk_list.bzl
=> Support go1.13.5, 1.12.14

go/tools/bazel_testing/bazel_testing.go
* When detecting the name of the main workspace, we use
bazel.Runfile("WORKSPACE") instead of assuming the file exists.
* BazelCmd sets "--output_user_root" if we can detect it. Bazel 2.0.0
by default puts this in some deeply nested directory by default (not
sure how it's derived), so we hit path length limits.
Updates #2310
=> go/tools/bazel_testing: fix Windows problems with test framework

.bazelci/presubmit.yml, WORKSPACE, go/private/repositories.bzl, proto/gogo.bzl, tests/core/go_proto_library/BUILD.bazel, tests/core/go_proto_library_importmap/BUILD.bazel, tests/integration/googleapis/BUILD.bazel, tests/legacy/examples/proto/dep/BUILD.bazel, tests/legacy/examples/proto/embed/BUILD.bazel, tests/legacy/examples/proto/gogo/BUILD.bazel, tests/legacy/examples/proto/gostyle/BUILD.bazel, tests/legacy/examples/proto/grpc/BUILD.bazel, tests/legacy/examples/proto/lib/BUILD.bazel, tests/legacy/proto_ignore_go_package_option/BUILD.bazel
=> Migrate to rules_proto

.bazelci/presubmit.yml, go/private/platforms.bzl
=> Test with --incompatible_enable_cc_toolchain_resolution

deprecation.rst
=> Deprecate go_rule wrapper [skip ci]

go/private/sdk_list.bzl
=> Support Go 1.13.6, 1.12.15

README.rst
missing minor release in the announcements
=> Announce rules_go 0.19.10, 0.20.4

go/private/sdk_list.bzl
=> Support Go 1.13.7, 1.12.16

go/private/sdk_list.bzl
=> Support go1.13.8, 1.12.17

BUILD.bazel, WORKSPACE, go/private/repositories.bzl, tests/grpc_repos.bzl, tests/integration/popular_repos/popular_repos.py, third_party/com_github_golang_protobuf-gazelle.patch, third_party/go_googleapis-deletebuild.patch, third_party/go_googleapis-gazelle.patch, third_party/org_golang_google_genproto-gazelle.patch, third_party/org_golang_x_tools-deletegopls.patch, third_party/org_golang_x_tools-extras.patch, third_party/org_golang_x_tools-gazelle.patch
=> Update dependencies in preparation for v0.22.0 release

tests/legacy/examples/stamped_bin/stamped_test.go
=> tests/legacy/examples/stamped_bin: work around go1.14 bug

go/private/sdk_list.bzl
=> Support Go 1.14

BUILD.bazel
=> nogo: disable cgocall

go/tools/builders/generate_test_main.go, tests/core/go_test/BUILD.bazel, tests/core/go_test/tempdir_test.go
=> Setting TMPDIR to TEST_TMPDIR

go/private/sdk_list.bzl
=> Support Go 1.14.1, 1.13.9

BUILD.bazel, go/def.bzl, go/nogo.rst
=> Export `TOOLS_NOGO` deps list.

go/private/sdk_list.bzl
=> Support Go 1.14.2, 1.13.10

README.rst, go/dependencies.rst
=> Fix com_google_protobuf examples in documentation [skip ci]

go/tools/testwrapper/wrap.go, tests/core/go_test/xmlreport_test.go
Resolves https://github.com/bazelbuild/rules_go/issues/2364.
Do not add `-test.v` automatically to each testrun, as this can lead to very verbose testlogs. Instead let users control this with env variable `GO_TEST_WRAP_TESTV=1` from `--test_env=` if they want full XML reports including passed/skipped tests reports.
=> Don't add -test.v by default in testwrapper

go/crosstool.rst
=> doc: add warning to crosstool.rst and fix links [skip ci]

.bazelci/presubmit.yml, go/tools/BUILD.bazel, go/tools/bazel_testing/BUILD.bazel, go/tools/bazel_testing/def.bzl, tests/integration/README.rst, tests/integration/gazelle/BUILD.bazel, tests/integration/gazelle/README.rst, tests/integration/gazelle/gazelle_test.go
catch errors building and running Gazelle in the future.
=> tests/integration/gazelle: test that gazelle builds and runs

go/tools/builders/nogo_main.go
=> nogo: fix nil pointer dereference for nilness checker

go/private/sdk_list.bzl
=> Support Go 1.14.3, 1.13.11

go/tools/windows-testrunner/windows-testrunner.go
* Find presubmit.yml automatically.
* If arguments are given, run those specific tests with flags from
presubmit.yml.
=> go/tools/windows-testrunner: two small improvements

go/private/sdk_list.bzl
=> Support Go 1.14.4, 1.13.12

third_party/README.txt
=> third_party: add README.txt [skip ci]

go/tools/builders/env.go
Bug fix
Windows has 32KB limit for CLI argument length and when too many dependencies are passed into the builder, it can exceed the limit. This CL fixes it by using a "response file" (mostly from https://go-review.googlesource.com/c/go/+/110395/).
Fixes #2561
=> go/tools/builders: use Windows response files to avoid arg length limits

README.rst
* Added information to "protobuf and gRPC".
* Made "protobuf and gRPC" a top-level section and added it to ToC
to make it more visible.
* Organized FAQ into sections on Go, protobuf, and dependencies.
Fixes #2549
=> doc: add information on protobuf, organize FAQ [skip ci]

go/private/sdk_list.bzl
=> Support Go 1.14.6, 1.13.14

go/private/sdk_list.bzl
=> Support Go 1.14.7 and 1.13.15

go/private/repositories.bzl
Bug fix
Documentation
Fixes a broken link in the comments
Fixes #2593 
=> Update broken link

go/private/sdk_list.bzl
=> Support Go 1.15

go/core.rst
Documentation
`importpath` listed twice in `go_test` documentation
Fixes #
=> importpath listed twice in go_test documentation

go/private/actions/link.bzl
=> Force external linking on Windows when race/msan enabled

go/private/actions/link.bzl
=> go: add comment on why external linking is needed

go/private/sdk_list.bzl
=> Support Go 1.15.2, 1.14.9

go/toolchains.rst
Documentation
When I copy and paste this line, I get
Error in label: label() got unexpected positional argument
from bazel.
=> Fix positional argument in docs

README.rst
Announce releases 0.24.3, 0.23.11 [skip ci]
=> Announce releases 0.24.3, 0.23.11 [skip ci]

README.rst, WORKSPACE
Update bazel_gazelle to v0.22.2
=> Update bazel_gazelle to v0.22.2

go/private/sdk_list.bzl
=> Support Go 1.15.3, 1.14.10

go/private/sdk_list.bzl
=> Support Go 1.15.4, 1.14.11

tests/legacy/test_chdir/data_test.go
> Test coverage
Adds test coverage for #2696
=> go_test: add tests for #2696

go/tools/builders/stdlib.go
=> GoStdLib: add CGO_LDFLAGS to CGO_LDFLAGS_ALLOW

go/private/sdk_list.bzl, go/tools/builders/stdlib.go
=> Support Go 1.15.5, 1.14.12

go/private/actions/link.bzl
=> link: force internal linking in pure mode

WORKSPACE, go/tools/builders/info.go
* Set `GO111MODULE=off` in `go_info`
* Switched to Gazelle `v0.22.3` which also includes fixes.
=> Test Go 1.16beta1

README.rst
Documentation
Fixes misspelled word: exisitng -> existing
=> Typo fixed: exisitng -> existing

go/private/sdk_list.bzl
=> Support Go 1.15.7, 1.14.14

WORKSPACE
=> Test Go 1.16rc1 in CI

go/core.rst
Update the documentation about Go test wrapping given the changes in #2456.
Documentation
The information here isn't exactly correct given #2456.
None.
=> Improve documentation regrading test wrapping

.bazelci/presubmit.yml, go/private/sdk_list.bzl
=> Support Go 1.15.8, 1.14.15

go/private/sdk_list.bzl, tests/core/go_binary/package_conflict_test.go
=> Support Go 1.16

go/private/mode.bzl
See #2795.
Feature
**What does this PR do? Why is it needed?**'
Support plugins on ARM-64/Darwin.
=> Support plugins on Darwin/ARM-64.

BUILD.bazel
Documentation
By exporting `LICENSE.txt`, Bazel projects depending on rules_go can easily consume its license text.
=> Export `LICENSE.txt`

README.rst
Updates README.md for 0.30.0 release.
=> v0.30.0: update README

BUILD.bazel, go/tools/bzltestutil/BUILD.bazel
Other
Clean up of some old references left behind from #2755.
Fixes up some Gazelle references. Makes it so it doesn't edit this file every time we run gazelle.
=> BUILD: cleaned up some old gazelle ignores

README.rst
This PR updates README with the new v0.31.0 release information. 
Show latest release information
=> v0.31.0: Update README

extras/gomock.bzl
Feature
This copies https://github.com/jmhodges/bazel_gomock/blob/4f2ee840432b1a08ccc46ee4f2c1f5a2bad8fade/gomock.bzl with some formatting and the original license as comments. DO NOT USE this version, as there will be some significant changes in the later pull requests.
Fixes #3101
=> Adding gomock rule

go/def.bzl
Forgot the bump the version in #3146...
=> Bump the version to 0.32.0

README.rst
Update README to use rules_go v0.32.0 and Gazelle 0.25.0
=> Update README to use rules_go v0.32.0

README.rst
Fixed: #3161
>
> Bug fix
> Feature
> Other
Fixes #
=> Fix download url in README

tests/integration/popular_repos/popular_repos.py
=> Make popular_repos.py compatible with Python 3

MODULE.bazel
https://github.com/bazelbuild/bazel-central-registry/pull/95#discussion_r913097841
=> Use repo-relative labels in MODULE.bazel

README.rst
Documentation
v0.34.0 is out. Updated README for that.
This supersedes #3171
=> Update README for v0.34.0

go/tools/releaser/file.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
> Other
Just cleanup duplicate return
Fixes #
=> delete duplicate return

README.rst
Update readme with new WORKSPACE and announce the minimal Bazel version support
=> Update README for v0.35.0

go/tools/bzltestutil/wrap.go
We have sporadically seen issues where tests appear to fail with `No pass/skip/fail event found for test`. This is apparently because the test output from `go test` is interspersed with normal `stderr` output from the test process (notice how the `PASS:` line is split by stderr output):
```
--- PASS: TeI220916 15:19:35.406930 702 3@pebble/event.go:649  [pebble,s?] 2  [JOB 1] MANIFEST created 000001
I220916 15:19:35.407183 702 3@pebble/event.go:677  [pebble,s?] 3  [JOB 1] WAL created 000002
...
I220916 15:19:35.414755 702 sql/colexec/colexectestutils/utils.go:691  [-] 22  batchSize=1/sel=false
stWindowFramer/mode=Groups/start=OffsetFollowing/end=UnboundedFollowing#01/count=17 (0.00s)
```
Here we avoid this by adding extra synchronization to ensure we only write a whole line from one of the …
=> synchronize when writing to the JSON converter

.bcr/config.yml
https://github.com/bazel-contrib/publish-to-bcr/pull/18
=> bzlmod: Update Publish to BCR app config

MODULE.bazel, go/def.bzl
> Other
Updates release versions in go/def.bzl and MODULE.bzl
=> prepare for v0.36.0 release

README.rst
Also requested mirror of artifact: https://github.com/bazelbuild/bazel/issues/16934
=> chore: update readme post release

MODULE.bazel, go/def.bzl, go/private/repositories.bzl, third_party/go_googleapis-gazelle.patch, third_party/org_golang_google_genproto-gazelle.patch, third_party/org_golang_x_sys-gazelle.patch
Other
Updating dependencies and version according to https://github.com/bazelbuild/rules_go/wiki/Release-process
=> Preparing 0.38.0 release

go/private/repositories.bzl, third_party/org_golang_x_tools-gazelle.patch
Bug fix
> Feature
> Other
Regenerate golang/x/tools patch with https://github.com/bazelbuild/bazel-gazelle/pull/1433
Fixes #3431
=> Regenerate golang/x/tools patch

tests/integration/popular_repos/BUILD.bazel, tests/integration/popular_repos/popular_repos.py
Feature
We add build_test target since we cannot run tests in those packages, while the name need_test is confusing. To make it more clearly, I changed the name from need_test to build_only.
Fixes #3448 
=> change build test name from 'need_test' to 'build_only'

go/nogo.rst
Documentation
fix a grammer issue
Fixes #
=> fix a grammer issue

go/private/extensions.bzl
This API is still very new and there are no modules in the BCR declaring their own Go SDK.
=> bzlmod: Prohibit undesirable SDK registrations in non-root modules

README.rst, go/dependencies.rst
Documentation
Updates an out-of-date link.
=> update links to gazelle docs

MODULE.bazel, WORKSPACE
Other
Updates the Go SDK versions to the latest patch release of the oldest supported minor version.
=> Raise Go version

go/private/rules/transition.bzl
Bug fix
If the current target platform differs from the default value (the host platform), then we don't want to override it with a value inferred from the legacy --cpu and --crosstool_top flags. Otherwise it would become impossible to "platformize" a Go build without having a matching platform mappings file.
This is not expected to break any existing use cases and if it does, it can and should be worked around with a platform mappings file that maps the legacy flag values to `//go/platform` targets.
=> Only infer platforms from crosstool/cpu if at default

go/private/sdk.bzl
=> Use `ctx.readdir` instead of `ls` for SDK platform detection

README.rst, examples/basic-gazelle/WORKSPACE
Update various code examples in `README.md` and `examples/` to reflect the new release and its integrity.
=> update README.md to reflect new version

go/private/context.bzl
This was never used.
Other
Fixes #
=> context: remove unused import

go/private/repositories.bzl, third_party/com_github_gogo_protobuf-gazelle.patch, third_party/com_github_golang_mock-gazelle.patch, third_party/com_github_golang_protobuf-gazelle.patch, third_party/go_googleapis-gazelle.patch, third_party/org_golang_google_genproto-gazelle.patch, third_party/org_golang_google_protobuf-gazelle.patch, third_party/org_golang_x_sys-gazelle.patch, third_party/org_golang_x_xerrors-gazelle.patch
>
> Bug fix
> Feature
Other
Run deps upgrader pre 0.40.0 update
N/A
=> chore(deps): update deps

proto/wkt/BUILD.bazel, proto/wkt/well_known_types.bzl
Other
This PR is a modified version of [this patch](https://github.com/wyattanderson/googleapis-reproducer/blob/main/patches/io_bazel_rules_go-alias.patch), in order for https://github.com/bazelbuild/bazel-gazelle/pull/1561 to work
Credits to @wyattanderson
Fixes #3574
=> Creating alias to well-known types

go/private/repositories.bzl, third_party/go_googleapis-gazelle.patch
>
Bug fix
> Feature
> Other
Reverted googleapis that got inadvertently upgraded in my upgrade diff.
Fixes #
=> fix: revert googleapis

MODULE.bazel, go/def.bzl
>
> Bug fix
> Feature
Other
Prepare 0.40 release
Fixes #
=> prepare release 0.40.0

go/tools/gopackagesdriver/packageregistry.go
>
Bug fix
> Feature
> Other
Fixes #3604
=> Expand stdlib packages when queried

.bcr/presubmit.yml
https://github.com/bazelbuild/bazel-central-registry/pull/765#discussion_r1265439093
=> Run BCR tests on macOS arm64

go/tools/bzltestutil/test2json.go
Bug fix
This PR will fix incorrect test.xml parsing of the go_test results from test.log, which xml can be showing errors while go_test exited with exit code 0 without any errors. 
Fixes #3568
=> [test2json] Sync with test2json from golang upstream

go/tools/bzltestutil/init.go, tests/legacy/test_chdir/data_test.go
Also adjust test_chdir accordingly.
>
> Bug fix
> Feature
> Other
Fixes #
=> bzltestutil: document init() behavior change in Go 1.21

MODULE.bazel
Fixes https://github.com/bazel-contrib/bazel_features/issues/25.
=> Update `bazel_features` to v1.1.1

go/tools/releaser/upgradedep.go
Bug fix
This skips prerelease versions when determining the latest version.
=> Do not choose prereleases as highest versions

go/tools/go_bin_runner/BUILD.bazel
Feature
This improves compatibility with external tooling.
Fixes https://bazelbuild.slack.com/archives/CDBP88Z0D/p1703093430939699?thread_ts=1702968419.952619&cid=CDBP88Z0D
=> Let `@rules_go//go` file path end with `/bin/go`

MODULE.bazel, go/def.bzl
Create a patch release to include https://github.com/bazelbuild/rules_go/pull/3810
=> patch release 0.44.2

MODULE.bazel, go/private/BUILD.bazel, go/private/context.bzl, go/private/extensions.bzl, go/private/repositories.bzl
=> Rename bazel_features polyfill to prevent conflicts

WORKSPACE
Bug fix
The repository moved.
Fixes #3862
=> Update toolchains_llvm URL and hash

WORKSPACE
Fixes https://github.com/bazelbuild/rules_go/issues/3868
CC @mai93 @meteorcloudy
=> Fixes the Bazel CI error

README.rst
Documentation
Fixes the links in the release notes in the main README to point to the correct GH tags.
N/A.  Small doc fix.
=> Update README.rst to point to correct GH release tags

docs/go/core/bzlmod.md
Documentation
Fix type
No issue raised
Fixes #
=> Update bzlmod.md fix typo

go/private/BUILD.bazel
Bug fix
> Stardoc documentation generation failed: File /home/coder/.cache/bazel/_bazel_coder/c91ea700cafcab35837a5ae95cae9020/sandbox/linux-sandbox/42/execroot/services/bazel-out/k8-opt-exec-2B5CBBC6/bin/bazel/docs/rules/java/image_stardoc.runfiles/io_bazel_rules_go/go/private/repositories.bzl imported '//go/private:polyfill_bazel_features.bzl', yet /home/coder/.cache/bazel/_bazel_coder/c91ea700cafcab35837a5ae95cae9020/sandbox/linux-sandbox/42/execroot/services/bazel-out/k8-opt-exec-2B5CBBC6/bin/bazel/docs/rules/java/image_stardoc.runfiles/io_bazel_rules_go/go/private/polyfill_bazel_features.bzl was not found.
Target //bazel/docs/rules/java:image failed to build
Fixes #
**Other …
=> Add //go/private:polyfill_bazel_features.bzl to sources.

MODULE.bazel, go/def.bzl
Prepare a patch release to include: 54c451550c520d4a26f491fa5f52a97b2dcfa0d7
=> prepare patch release 0.47.1

docs/go/core/bzlmod.md
>
> Bug fix
> Feature
Documentation
> Other
Update docs to cover new Update docs to cover new FilePath ReplaceDirective Support added by: https://github.com/bazelbuild/bazel-gazelle/pull/1776
Fixes #
=> Update docs to cover new FilePath ReplaceDirective Support

MODULE.bazel, go/def.bzl
This PR helps prepare the patch release to include f81ce9fda489f5c18538b25d9266325e51783887
=> prepare patch release 0.48.1

docs/go/core/rules.bzl, docs/go/core/rules.md, go/core.rst
Documentation
Link to "data dependencies" section was broken. Fix it.
https://bazel.build/concepts/dependencies#data-dependencies
=> Fix broken link to https://bazel.build/concepts/dependencies#data-dependencies

CONTRIBUTORS, README.rst, examples/basic-gazelle/WORKSPACE, go/dependencies.rst, go/toolchains.rst
This PR updates the readme contents for the latest releases of rules_go and gazelle
=> update readmes for latest release

go/private/actions/archive.bzl, go/private/common.bzl
We split them up only to combine all 7 lists again. It doesn't seem useful.
Perf improvement/cleanup
Fixes #
=> Stop splitting sources in emit_archive

go/private/common.bzl, go/private/rules/test.bzl
This should be identical and is much simpler.
Code cleanup
=> Remove split_srcs

go/private/actions/stdlib.bzl, go/private/rules/stdlib.bzl
Code simplificaiton
This is simple to reason about than smuggling it through `source.stdlib`.
Fixes #
=> Simplify how we emit GoStdLib

go/private/actions/binary.bzl, go/private/context.bzl, go/toolchains.rst
Starlark cleanup/perf improvement
We only need the extension for binary actions, not all go-related actions. Remove them from the context.
Fixes #
=> Cleanup binary extension computation

docs/go/core/bzlmod.md
This PR adds missing documentation
=> add docs for `go_deps.gazelle_default_attributes`

go/private/rules/nogo.bzl
This is one of the sources of feeding structs into `deps`.
Fixes #
=> Tweak nogo archive handling

go/private/platforms.bzl
Bug fix
This change was requested in https://github.com/bazelbuild/bazel-gazelle/issues/1735#issuecomment-2285850060
=> Add qnx and osx platforms

go/private/context.bzl
`runfiles.merge` should not be called in a loop to avoid deep depsets
Fixes #
=> Create shallower runfiles

go/private/context.bzl, go/private/mode.bzl
This PR simplifies and optimizes `get_mode`. It's now around 2-3x faster, which is a 100ms win on the buildbuddy repo.
Fixes #
=> Cleanup get_mode

go/private/context.bzl
Since only one the lib or one of the embeds can specify cgo, we can simplify this a bit
Fixes #
=> Cleanup _merge_embed

go/private/mode.bzl
starlark cleanup
It's unused
Fixes #
=> Remove mode_tags_equivalent

go/private/context.bzl, proto/def.bzl
Starlark fixup
Make the migration process a little smoother
https://github.com/bazelbuild/rules_go/pull/4030#issuecomment-2310491357
=> Handle targets provided in deps as a result of GoSource.resolver

go/private/actions/compilepkg.bzl
A bit less special-casing for the cover archive
Fixes #
=> Cleanup coverdata handling in compilepkg

go/tools/gopackagesdriver/flatpackage.go, go/tools/gopackagesdriver/gopackagesdriver_test.go
Bug fix
When we create a new dedicated package for all external tests, we should not override the list of CompiledGoFiles by the list of GoFiles.
Fixes: #4113
=> fix(gpd): keep compiled files from stdlib packages

docs/go/core/bzlmod.md
=> bzlmod.md: update style of code

go/private/extensions.bzl
=> go_sdk: Add missing arguments to cross-platform SDKs

MODULE.bazel
=> Let the Publish to BCR app maintain the module version

go/providers.rst
=> Fix `GoArchiveData` docs

go/runfiles/BUILD.bazel, go/runfiles/caller_repository_example_test.go, go/runfiles/example_test.go, go/runfiles/rlocationpath_xdefs_example_test.go, go/runfiles/runfiles.go, go/tools/bazel/bazel.go, go/tools/bazel/runfiles.go
=> Improve runfiles docs with examples and more deprecations

go/private/rules/test.bzl, tests/core/strip/strip_test.go
=> fix: tests respect --strip like binaries (#4103)

.bazelci/presubmit.yml
Verifying if https://github.com/bazelbuild/continuous-integration/issues/2153 is fixed
=> enabling Mac CI

go/runfiles/runfiles.go
Documentation
Old URL is now a redirect to the new one
=> Update documentation reference

README.rst
Documentation
The bullet points under `Initial project setup` were lacking the proper indentation to get correctly formatted.
=> Fix bullet point format in readme

go/private/extensions.bzl
=> Mention `dev_dependency` in `go_sdk.host` error

go/tools/builders/nogo.go
=> Don't swallow errors when running nogo

go/tools/builders/nogo_main.go, tests/core/nogo/custom/flags/flags_test.go
Bug fix
Some analyzers require their subanalyzers to be configured. For instance nilaway has dedicated nilaway_config subanalyzer. 
Fixes #4329 
=> Pass config to subanalyzers

.bcr/presubmit.yml
Other
* Adding coverage on Linux arm64 and Bazel 8
* Upgrading Debian version
* Dropping coverage on macOS amd64. Those machines are very old now.
=> Update BCR presumit matrix

.bazelrc
Work around https://github.com/bazelbuild/continuous-integration/issues/2269
=> Work around incompatibility between zlib and clang 17

go/private/actions/archive.bzl, go/private/actions/compilepkg.bzl, go/private/rules/binary.bzl, go/private/rules/library.bzl, go/private/rules/test.bzl
=> Rename `out` to `out_diagnostics`

go/runfiles/BUILD.bazel, go/runfiles/fs.go, go/runfiles/runfiles.go, tests/runfiles/BUILD.bazel, tests/runfiles/runfiles_internal_test.go
Feature
Implements support for the new format added in https://github.com/bazelbuild/bazel/issues/26262.
Fixes #
=> Add support for `--incompatible_compact_repo_mapping_manifest`

go/private/actions/compilepkg.bzl, go/tools/builders/nogo.go, go/tools/builders/nogo_main.go
Performance improvement
Avoid unnecessary work by skipping analyzers that don't emit facts when reported diagnostics are known to be ignored.
Work towards #4327
=> Skip analyzers that don't emit facts when ignoring diagnostics

go/tools/builders/nogo_main.go
Bug fix
After #4402, it is no longer possible to use a custom analyzer without having to declare a new `Fact` type. The build of a Go library will fail if the library contains any external dependencies.
That's the case for executing gazelle by example (if we don't use a precompiled binary):
```
$ bazel run //:gazelle
ERROR: .../external/gazelle++go_deps+org_golang_x_sync/errgroup/BUILD.bazel:3:11: output 'external/gazelle++go_deps+org_golang_x_sync/errgroup/errgroup.facts' was not created
ERROR: .../external/gazelle++go_deps+org_golang_x_sync/errgroup/BUILD.bazel:3:11: Running nogo on @@gazelle++go_deps+org_golang_x_sync//errgroup:errgroup failed: not all outputs were created or valid
ERROR: …
```
=> Fix generation of facts file when diagnostics are ignored

go/runfiles/runfiles.go, tests/runfiles/runfiles_test.go
Feature
https://bazelbuild.slack.com/archives/CDBP88Z0D/p1751654245992999?thread_ts=1751654245.992999&cid=CDBP88Z0D
=> Find runfiles when a binary is executed from PATH

CONTRIBUTING.md
Documentation
Fixes Contributing.md reference to README. The file is no longer a `.md` file, it is now a `.rst` file. 
Fixes # 
None.
=> fix(contributing): Fix readme reference

go/private/common.bzl, go/private/context.bzl, go/private/rules/binary.bzl, go/private/rules/test.bzl
Cleanup/perf improvement
Fixes #
=> A bit of starlark micro-optimization

go/private/rpath.bzl, tests/core/cgo/BUILD.bazel, tests/core/cgo/wrapped_cgo_test.go
Bug fix
This is based on the corresponding logic in rules_cc.
Fixes #4451
=> Cover all cases for rpath generation
