- examples/bin/bin.go
Fixes CI, see http://ci.bazel.io/job/rules_go/1/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console.
> Fix import path

- go/def.bzl
RELNOTES: go_prefix references the //:go_prefix rule in the repository
the BUILD file using go_* is in, not the repository where def.bzl lives
(probably @io_bazel_rules_go).
> Fix go_prefix to resolve to the right repository

- go/def.bzl
Fixes #12, which was caused by #10.
* Adds a workaround for a bug of `ld` in XCode 7.2 or earlier.
* Avoid depending on a behavior of old GNU `ld` so that it works on Ubuntu 15.04.
Make the link process more similar to `cc_binary` to avoid the issue.
> Fix CI build failures on Ubuntu 15.04 and Mac OS X

- README.md
- examples/bin/bin.go
- examples/lib/BUILD
- examples/lib/add.s
- examples/lib/asm.go
- examples/lib/lib_test.go
- examples/lib/sub.s
- go/def.bzl
- go/toolchain/BUILD
…in Go; add examples for go_asm_library; change go_library to take multiple cgo_objects; update README for go_asm_library and go_library.
This replaces the pull request #22 with a new implementation since I messed it up. The new impl followed Yugui's suggestions.
> Allow rule go_library to accept ASM source files

- examples/lib/BUILD
- examples/lib/lib_x_test.go
- go/def.bzl
Put library archives into the right places in the standard layout of Go workspace by omitting  "go_default_library" from their paths. This lets linker symbols in the final binary output have right values.
It also allows us to specify -X linker flag with the importpath we expect.
c.f. https://github.com/bazelbuild/rules_go/pull/27#issuecomment-220780509
> Correct importpath of generated go_library archives

- WORKSPACE
- examples/external/BUILD
- examples/external/main.go
- go/def.bzl
Uses go_prefix attr of individual dependencies to calculate their
importpaths.  This allows users to use Bazel's external dependency
resolution -- {,new_}git_repository rules -- to manage Go libraries.
c.f. https://github.com/bazelbuild/rules_go/issues/16#issuecomment-216010843
Supports case 1 and 3 in #16.
>  Respect go_prefix attr of dependencies

- go/def.bzl
Fixes a bug that go_binary() fails if it is in an external dependency.
This is a followup of #30.
> Generate intermediate files in GoLink action in the right place

- examples/lib/BUILD
- examples/lib/deep/BUILD
- examples/lib/deep/doc.go
- examples/lib/deep/thought.go
- examples/lib/lib.go
- go/def.bzl
`go_library_impl` used to ignore dependencies in `ctx.attr.library` when it calculates transitive dependencies.  This PR makes it correctly propagate such transitive dependencies in `ctx.attr.library`.
Fixes #6.  Replaces #32.
> Propagates transitive dependencies from direct deps in library

- examples/cgo/BUILD
- examples/cgo/generated.go.tpl
- examples/cgo/import_example.go
- examples/cgo/sub/floor.go
- go/def.bzl
* The current package name might be empty.
* The current package might be in a non-root workspace.
* fixes #35
* cgo source files might be generated files and they might be in `$(GENDIR)` or in `$(BINDIR)`.
* cgo source files might be in a subdirectory of the bazel package directory.
> Support more edge cases in CGoCodeGen action

- README.md
- examples/cgo/BUILD
- go/def.bzl
`cgo_library` has both Go-related attributes `srcs` and `library`, and
C-related attributes `deps`, `copts`, `linkopts`.  And their naming was not
strategic nor consistent.
Actually `deps` attribute had a different meaning from `go_library`.
And even worse, there was no way to add `go_library` dependency to
`cgo_library`.
This change make attributes of `cgo_library` a superset of the ones of
`go_library`. And it consistently prefixes C/C++ related attributes with
"c".
NOTE: This breaks backward-compatibility of `cgo_library`.
> [Incompatible Change] Prefixes C/C++ related attributes with "c".

- README.md
Here's a draft of release note
https://github.com/bazelbuild/rules_go/releases/tag/untagged-e20c0eb0db5c557ee2d4
> Bump version to 0.0.3

- AUTHORS
- BUILD
- go/private/files_equal_test.bzl
- go/private/lines_sorted_test.bzl
@pmbethe09 said in #47 that these files are to be sorted. So I've added a regression test to help contributors know that.
I've also removed Googlers from the AUTHORS file, as this file is intended for copyright holders. Google Inc. owns the code. See the comments in the AUTHORS and CONTRIBUTORS files to learn more about this policy.
**Recommended TODOs**
1. Consider auditing other AUTHORS to find out if their employer is actually the copyright holder. For instance, I noticed one contributor is employed by Fitbit Inc. Perhaps that's what should go in the AUTHORS file.
2. Consider changing copyright headers on source files to read "The Bazel Go Rules Authors" rather than the Bazel Authors, since this project has an independent AUTHORS file.
> Test that AUTHORS and CONTRIBUTORS are sorted

- README.md
@pmbethe09 I'm going to release 0.0.4 to ship two important changes described in https://github.com/bazelbuild/rules_go/releases/tag/untagged-f7b118df27e01fcc5046.
Could you take a look?
This branch should be merged just before releasing 0.0.4.
> Bump version to 0.0.4

- WORKSPACE
- go/tools/gazelle/gazelle/BUILD
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/BUILD
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/packages/BUILD
- go/tools/gazelle/packages/doc.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/BUILD
- go/tools/gazelle/rules/construct.go
- go/tools/gazelle/rules/doc.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/BUILD
- go/tools/gazelle/testdata/repo/bin/main.go
- go/tools/gazelle/testdata/repo/lib/doc.go
- go/tools/gazelle/testdata/repo/lib/lib.go
- go/tools/gazelle/testdata/testdata.go
* Extracted from #51
* c.f. #15
> Import minimal version of gazelle, a BUILD file generator

- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/repo/lib/lib_external_test.go
- go/tools/gazelle/testdata/repo/lib/lib_test.go
* Extracted from #51 
* Depends on #57 and #58 
* Supports generation of `go_test` rules for internal and external tests
* Supports generation of `go_prefix` rules
* Supports generation of `load` of the rules.
* Not yet support generation of `cgo_library`.
> Support more rules in Gazel

- go/tools/gazelle/gazelle/BUILD
- go/tools/gazelle/gazelle/diff.go
- go/tools/gazelle/gazelle/fix.go
- go/tools/gazelle/gazelle/fix_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/gazelle/print.go
* Extracted from #51 
* Depends on #57, #58 and #59 
* c.f. #15
> Make output modes configurable

- README.md
- Vendoring.md
Hi @yugui, I tried to write down some of the instructions that I thought might have helped me when I first set out to use Go with Bazel. Are any of these worth pulling into the main repo?
> Some suggested updates to the README

- go/def.bzl
- go/toolchain/BUILD
Resolve a go toolchain for the build platform earlier because it does not make sense to download toolchains for other build platforms.
* this makes it easier to support even more platform
* this makes it easier to support locally installed toolchain, c.f. #46
* this prevents "bazel query" from forcing users to download a toolchain for the other platform
> Avoid involving a toolchain for the other build platform

- WORKSPACE
- go/tools/gazelle/rules/BUILD
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/resolve_external.go
- go/tools/gazelle/rules/resolve_external_test.go
- go/tools/gazelle/rules/resolve_structured.go
- go/tools/gazelle/rules/resolve_structured_test.go
> Support external dependency in gazelle

- go/def.bzl
The issue was introduced at #72. This commit reverts a part of #72
to let Bazel manage go toolchain archives, but it still resolves a tool
chain for the current build platform in the analysis phase.
> Avoid downloading go toolchain whenever go/def.bzl changes

- go/def.bzl
Go compile command now written to executable file to avoid arg list being too long.
Fixes #42
> add executable for go compilation

- go/tools/gazelle/gazelle/main.go
Otherwise, if no packages are passed, the script appears to work but
does nothing.
CC @pmbethe09
> Add an error message to gazelle when no package directories are given

- go/def.bzl
- go/tools/gazelle/rules/generator.go
this is particularly useful for github.com/golang/protobuf
which has things like //ptypes/any/any.pb.go and //ptypes/any/any.proto
This change detects the .pb.go, and then adds a filegroup called "go_default_library_protos" for the .proto files.
> Gazelle: add filegroup for .proto whenever .pb.go found

- go/tools/gazelle/wspace/finder_test.go
Fixes #125 
`$TEST_TMPDIR` looks to be under `execroot` and `wspace.Find` finds out a `WORKSPACE` in `execroot`
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
--- FAIL: TestFind (0.00s)
finder_test.go:54: Find("/private/var/tmp/_bazel_ci/34fe1368fbe38faf999248c2d68f258a/execroot/darwin-x86_64/_tmp/go_default_test_1/195401717") got "/private/var/tmp/_bazel_ci/34fe1368fbe38faf999248c2d68f258a/execroot/darwin-x86_64", want ""
FAIL
```
> Fixes a test failure on darwin

- go/tools/generate_test_main.go
Without this change, you would get an unused import error. It's common to have empty test packages with only GoDoc Example functions.
> support example only test packages

- go/def.bzl
- go/private/go_repositories.bzl
- go/private/go_root.bzl
- go/toolchain/BUILD
- Captures the absolute path of GOROOT at the time of toolchain
configuration.  This becomes necessary for cross-compile support
(#70).
- Symlinks @io_bazel_rules_go_toolchain{src, bin, pkg} to platform
toolchain paths to avoid workspace name mismatch warnings (closes
#104).
- Introduces the RULES_GOROOT environment variable to allow use of a
pre-existing go toolchain.
> Adds go_root rule.

- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
e.g. same-package generated sources like in buildifier
> add support for '# keep', on srcs/deps 

- WORKSPACE
- examples/proto/BUILD
- go/private/go_repositories.bzl
- go/private/go_repository.bzl
- go/tools/gazelle/gazelle/BUILD
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/BUILD
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/merger/BUILD
- go/tools/gazelle/wspace/BUILD
- proto/go_proto_library.bzl
* Removes a `local_repository` which points the main workspace itself. Fixes #135.
* Add another workaround of recursive workspace reference issue in buildifier.
We can remove this workaround when we drop support of Bazel 0.3.2.
> Remove an alias of the main workspace

- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/rules/resolve_external.go
- go/tools/gazelle/rules/resolve_external_test.go
This avoids a lot of network calls in vcs.RepoRootForImportPath.
Testing in repos like google.golang.org/genproto took
runtime from ~9s on average to ~0.01s
> Add well-known special case paths to externalResolver

- go/def.bzl
Fixes https://github.com/bazelbuild/rules_go/issues/159
> workaround for cgo_library in root of repo

- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/repo/bin_with_tests/bin_test.go
- go/tools/gazelle/testdata/repo/bin_with_tests/main.go
When gazelle runs on a Go main package, it now creates a private
go_library for the package so that any tests in that main package can be
run on it.
Previously, gazelle was creating only a go_binary for the go_test to
depend on which fails at `bazel test` time.
Fixes #157
> perform the main sandwich for go_binary

- go/private/go_repositories.bzl
This provides a means to have go_repositories() load what rules_go needs
to work, but also provide a way for the user to specify newer versions
of Go. rules_go may not be able to keep up with the pace of change that
the user needs in the face of Go bugs or security problems.
This implementation takes a cue from rules_closure by adding an omit_go
boolean to go_repositories.
> add the ability to use newer versions of Go

- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/repo/bin_with_tests/bin_test.go
- go/tools/gazelle/testdata/repo/bin_with_tests/main.go
Reverts bazelbuild/rules_go#169
Will send fix for merging shortly after.
> Revert "Revert "perform the main sandwich for go_binary""

- .travis.yml
The bazel installer shell script build output from jenkins seems to have changed from `bazel--installer.sh` to `bazel-0.4.0rc1-installer.sh`.  This update tests for a version string matching a release candidate and uses ci.bazel.io as the base url for that artifact.
> Update Jenkins build artifact name change

- go/def.bzl
- go/private/go_repositories.bzl
- go/toolchain/BUILD
Tools that generate go code an use [go/build](http://godoc.org/go/build) often require all source to be present. This allows rules that use go_env_attrs to declare GOROOT/src as input.
> add go_srcs to toolchain

- BUILD
- examples/proto/dep/BUILD
- examples/proto/gostyle/BUILD
- examples/proto/gostyle/gostyle.proto
- examples/proto/grpc/BUILD
- examples/proto/grpc/my_svc.proto
- examples/proto/lib/BUILD
- proto/go_proto_library.bzl
This method requires a one-time "go_google_protobuf()" in your root BUILD file, but after that, engineers don't have to worry about setting their import paths/maps.
> go_proto_library: attempt to make the well known protos Just Work

- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/asm_linux.S
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/asm_other.S
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/foo.go
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/foo.h
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/foo_linux.c
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/foo_other.c
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/foo_test.go
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/pure_linux.go
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/pure_other.go
This solves issues where new_go_repository() fails for some open-source go repositories. After setting these, new_go_repository() appropriately filters source files by OS and architecture.
> Set GOOS and GOARCH as BuildTags in Gazelle's generator

- proto/go_proto_library.bzl
also use faster http_archive for google/protobuf
> update go_proto_repositories to use the latest external tags

- CONTRIBUTORS
- README.md
- go/private/go_repository.bzl
1. Allows optional attribute 'remote' in go_repository and new_go_repository rules, which will override importpath if provided.  Note: importpath is still required, still provides the go_prefix and is still the default value for the remote repository.
2. Auxiliary updates to documentation and CONTRIBUTORS file as needed.
> Add optional attribute 'remote' to go_repository and new_go_repository

- go/def.bzl
This allows additions of tags attrs and such and will improve backwards compatibility of the rule.
> add **kwargs to cgo_genrule

- go/tools/gazelle/gazelle/diff.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
Start of fix for 
https://github.com/bazelbuild/rules_go/issues/144
After this, use it in new_go_repository.
> gazelle: Add ability to read/write to BUILD.bazel instead of BUILD

- go/private/go_repository.bzl
- go/tools/gazelle/gazelle/BUILD
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/BUILD
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
Add flag for explicitly specifying build tag directives in Gazelle.
The parameters are a comma-delimited list of build tags.
If no build_tags are specified, GOOS and GOARCH are the default build tags.
If build_tags are specified, they are used explicitly.
Add attribute to new_go_repository definition to allow using explicit build tags.
> Support setting build tags explicitly in Gazelle and new_go_repository

- go/private/go_repositories.bzl
This is the change I made to try out Go 1.8beta1 in my bazel repo. However, I'm still getting errors from my bazel repository about `go tool: no such tool "yacc"` (even after a `bazel clean --expunge`). See the pasted error below. I don't have a `io_bazel_rules_go_repository_tools` repository defined in my own repo's WORKSPACE, so that seems like this must be coming from the `rules_go` stack.
With
git_repository(
name = "io_bazel_rules_go",
remote = "https://github.com/jmhodges/rules_go.git",
commit = "6f57106f725ce225c5d697c373c5073f38befd13",
)
I get this error from my go builds:
ERROR: /Users/jmhodges/founding/src/founding/go/svc/convolabeler/BUILD:5:1: no such package '@com_github_lib_pq//': no such package '@io_bazel_rules_go_repository_tools//': Traceback (most recent call last): …
> allow Go 1.8 by updating to latest buildifier

- go/private/go_repositories.bzl
Changes the repositories.bzl script to use a file that is part of the
actual archive, instead of a file generated by Bazel.
This is the root cause of the breakage in
https://github.com/bazelbuild/bazel/issues/2252
> Remove hard-coded depdence on BUILD.

- go/private/go_repository.bzl
- go/tools/gazelle/gazelle/diff.go
- go/tools/gazelle/gazelle/fix.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
This PR builds on the work in #219 and includes the ability to use `BUILD.bazel` files in `new_go_repository`, for example:
```
new_go_repository(
name = "org_golang_x_text",
build_file_name = "BUILD.bazel",
commit = "a8b38433e35b65ba247bb267317037dee1b70cea",
importpath = "golang.org/x/text",
)
```
> Fix support for BUILD.bazel files

- go/tools/gazelle/gazelle/BUILD
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/BUILD
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/rules/BUILD
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/rules/resolve_vendored.go
This PR adds support for external packages in `vendor/` in addition to `new_go_repository`.
When passed the `-external=vendored` flag, Gazelle will generate dependencies of the form (for example):
deps = ["//vendor/golang.org/x/text/language:go_default_library"],
instead of
deps = ["@org_golang_x_text//language:go_default_library"],
> gazelle: add support for vendored external packages

- go/private/go_repositories.bzl
https://github.com/bazelbuild/buildifier/commit/4190564903f61ddc94bcfda3dc2cdd32d4b330e5 is the important commit.
> bump buildifier again to really support Go 1.8

- examples/proto/BUILD
- examples/proto/proto_test.go
- go/def.bzl
I am getting ready to resubmit https://github.com/bazelbuild/bazel/issues/1262,
which significantly changes execroot paths (external/foo becomes ../foo, essentially).
Without this patch, the execroot change messes up the symlink tree the go rules
create.
This compensates for the path change in a backwards-compatible way:
bazel test //... passes for me with old & patched versions of bazel.
> Get go rules working with execroot rearrangement

- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
> sort the args in loadExpr's output

- proto/go_proto_library.bzl
go_proto_library.bzl creates a work dir and copy all the protos. It
removes it in each invocation but the 'rm' shell command does not
include the -r option.
> Fix 'protoc' work directory deletion in go_proto_library.bzl

- README.md
- examples/stamped_bin/BUILD
- examples/stamped_bin/main.go
- examples/stamped_bin/stamp.go
- go/def.bzl
for a workspace with BUILD_SCM_VERSION=10 defined as a volatile status and a go binary rule:
```
go_binary(
....
stamp = True,
linkstamp = "my/pkg/version",
)
```
The go binary will be linked with the option `-X my/pkg/version.BUILD_SCM_VERSION`
> add support for injecting build stamps with link options

- go/def.bzl
Got rid of complicated `sed` command. `read` now does the heavy lifting.
> link stamp: simplify shell commands to generate flags

- examples/lib/lib_x_test.go
- go/tools/generate_test_main.go
This broke in Go 1.8. testing.MainStart now expects a testing.testDeps
interface as its first argument. testing.internal.testdeps.TestDeps is
a public implementation of this, used by "go test".
This may not be stable, but examples/lib:lib_external_test will break
if this changes when we update our Go dependency in the future, so
we'll catch problems like this.
Fixes #273
> fix go_test when a TestMain function is defined

- go/def.bzl
Empty go_prefix is useful for projects not hosted in public repositories. rules_go handles empty prefix well, except for gcc linking where it produces "-L" flag without arguments. This PR removes "-L" if prefix is empty.
> Handle empty go_prefix in gcc invocation

- go/tools/generate_test_main.go
Modified generate_test_main.go to map the TESTBRIDGE_TEST_ONLY
environment variable (set by Bazel for --test_filter) onto the
-test.run flag, which is defined and used by the testing package.
Fixes #272
> Enable test filtering with --test_filter

- go/def.bzl
- tests/cgo_pthread_flag/BUILD
- tests/cgo_pthread_flag/cgo_pthread_flag.go
- tests/cgo_pthread_flag/cgo_pthread_flag_test.go
This matches behavior of "go build", which compiles and links C code
with -pthread (or -mthreads on Windows).
> cgo libraries are now built with -pthread

- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
Previously, Gazelle would avoid merging files with a "#
gazelle:ignore" comment, but it would still rewrite them. This could
result in small changes, e.g., whitespace.
Gazelle will no longer rewrite these files at all.
Fixes #266.
> gazelle: don't rewrite files with gazelle:ignore

- .travis.yml
- tests/run_non_bazel_tests.bash
- tests/test_filter_test/BUILD
- tests/test_filter_test/test_filter_test.bash
- tests/test_filter_test/test_filter_test.go
- Included an initial test case to check that --test_filter is
observed by go_tests.
- The test framework is run through Travis CI.
Fixes #287
> Add a framework for testing things that can't be checked through bazel

- README.md
- go/def.bzl
- tests/gc_opts_unsafe/BUILD
- tests/gc_opts_unsafe/empty_main.go
- tests/gc_opts_unsafe/empty_test.go
- tests/gc_opts_unsafe/gc_opts_unsafe.bash
- tests/gc_opts_unsafe/unsafe.go
- tests/gc_opts_unsafe/unsafe_cgo.go
- tests/run_non_bazel_tests.bash
go_library, cgo_library, go_binary, and go_test now support the
gc_goopts attribute. This is a list of flags to pass to the Go
compiler.
go_binary and go_test also support the gc_linkopts attribute. This is
a list of flags to be passed to the Go linker.
Note that _emit_go_compile_action and _emit_go_link_action have had
small interface changes and are now private. I didn't see any uses of
these functions on GitHub, and I'd like to avoid having people depend
on them in the future.
Fixes #217
> Support gc_goopts and gc_linkopts attributes

- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/rules/construct.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/BUILD
- go/tools/gazelle/testdata/repo/tests_with_testdata/external_test.go
- go/tools/gazelle/testdata/repo/tests_with_testdata/internal_test.go
If a directory named "testdata" is present in a Go package, now adds a
"data" attribute to newly generated rules that globs the contents of
the directory.
go_test(
name = "go_default_test",
...
data = glob(["testdata/**"]),
)
This attribute is included in newly generated internal and external
tests. It is not merged into existing test rules.
Related to #294
> gazelle adds a data dependency for tests on testdata files

- go/def.bzl
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/repo/lib/asm.h
- tests/asm_include/BUILD
- tests/asm_include/foo_amd64.go
- tests/asm_include/foo_amd64.h
- tests/asm_include/foo_amd64.s
- tests/asm_include/foo_other.go
- tests/asm_include/foo_test.go
- .h files are now allowed in srcs for go_library, go_binary, and
go_test. _emit_go_asm_action will include directories containing
.h files.
- Gazelle now adds .h files to srcs of go_library if no cgo_library
is present.
Fixes #303
> Allow .h files in srcs

- go/tools/gazelle/README.md
- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
Previously, Gazelle only searched comments after top-level statements
for the "gazelle:ignore" comment. This caught comments at the top of
the file (since the buildifier parser adds an implicit top-level
statement to hold comments), but only if there was a blank line before
the first real statement.
With this change, comments before top-level statements are now
recognized.
Fixes #302
> Gazelle finds "gazelle:ignore" before and after top-level statements

- README.md
- go/def.bzl
- go/private/go_tool_binary.bzl
- go/tools/extract_package/BUILD
- go/tools/filter_tags/BUILD
- go/tools/filter_tags/filter_tags.go
- tests/tags_os/BUILD
- tests/tags_os/bar_d.go
- tests/tags_os/bar_l.go
- tests/tags_os/bar_unknown.go
- tests/tags_os/foo_darwin.go
- tests/tags_os/foo_linux.go
- tests/tags_os/foo_unknown.go
- tests/tags_os/tags_os_test.go
- _emit_go_compile_action now executes filter_tags (which is a thin
wrapper over go/build.Context.MatchFile) before invoking the
compiler with the filtered source files. The cgo flag is set based
on whether the package has any cgo code.
- filter_tags now prints one filtered filename per line to avoid
problems with filenames containing spaces.
- filter_tags and extract_package are built with a new macro,
go_tool_binary, which invokes "go build" through a genrule.
Credit to @robotoer for the initial implementation in #267.
Fixes #310
> Support for build constraints (tags)

- go/private/go_repository.bzl
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/repo/lib_with_ignored_main/lib.go
- go/tools/gazelle/testdata/repo/lib_with_ignored_main/main.go
Since #311, the Bazel rules filter sources with build tags and
filename suffixes automatically.
Gazelle will no longer produce BUILD files which are pre-filtered.
This allows the same BUILD files to be used on multiple platforms.
Fixes #310
> Remove support for tags from gazelle

- go/def.bzl
Previously, when calling filter_tags, _emit_go_compile_action set the
cgo tag conditionally, based on whether any cgo code was present. This
did not match the behavior of "go build", which has the cgo tag based
on the CGO_ENABLED environment variable.
The cgo tag is now enabled whether any cgo code is present or not.
> Enable cgo tag by default during compilation

- tests/gc_opts_unsafe/gc_opts_unsafe.bash
- tests/run_non_bazel_tests.bash
run_non_bazel_tests.bash now prints how many tests passed and
failed. It also prints a prefix before each message to make the
failing tests easier to find.
> Improve non-Bazel integration test output

- README.md
- go/private/go_repository.bzl
- go/tools/fetch_repo/BUILD
- go/tools/fetch_repo/fetch_repo_test.go
- go/tools/fetch_repo/main.go
This change allows fetch_repo to fetch repositories without attempting
to determine the repo root if the user supplies the information
themselves. This allows users to be able to fetch repositories that the
vcs package would otherwise not be able to recognize.
This change also changes the behavior of the --remote flag to match the
git_repository rule.
> go_repository: add importpath and vcs flags (#313)

- go/def.bzl
- tests/transitive_data/BUILD
- tests/transitive_data/empty.go
- tests/transitive_data/empty_cgo.go
- tests/transitive_data/transitive_data_test.go
This fixes a bug where data files specified in a go_library or other
dependency weren't visible in a go_test or go_binary.
Fixes #322
> Propagate runfiles from data attributes

- README.md
- proto/go_proto_library.bzl
- tests/proto_ignore_go_package_option/BUILD
- tests/proto_ignore_go_package_option/a.proto
- tests/proto_ignore_go_package_option/b.proto
Once the option is on, we will first strip the option go_package = ... line from
the .proto file then compile, which avoids the problem where the compiled .pb.go
file is in the directory unexpected by bazel.
This partially resolves https://github.com/bazelbuild/rules_go/issues/323.
> Adding a ignore_go_package_option option to the go_proto_library.

- go/tools/gazelle/wspace/finder.go
On windows, you get something that matches none of the terminating conditions, but filepath.Dir(dir) returns dir unchanged.
> Fix infinite recursion

- proto/go_proto_library.bzl
Fixes https://github.com/bazelbuild/rules_go/issues/329
> go_proto_library: Add ability to override protoc and protoc_gen_go binaries

- go/private/go_repository.bzl
rather than relying on searching for a WORKSPACE
> always set repo root

- README.md
- go/private/go_repositories.bzl
- tests/custom_go_toolchain/BUILD
- tests/custom_go_toolchain/custom_go_toolchain.bash
- tests/custom_go_toolchain/print_version.go
- tests/run_non_bazel_tests.bash
go_repositories accepts three optional new arguments which allow
developers to use a custom version of Go.
* go_version: Go version string to use. Defaults to "1.8". Only "1.8"
is supported now, but support will be added for new version in the
future.
* go_linux, go_darwin: name of a repository containing the Go
toolchain. This is useful for developers who want to fetch Go from
an alternate source.
If go_linux or go_darwin is provided, go_version cannot also be
provided.
The omit_go argument is no longer supported.
TODO: manual (non-CI) tests.
TODO: update README.md.
Fixes #223
> Allow setting custom Go version in go_repositories

- go/def.bzl
- tests/test_build_constraints/BUILD
- tests/test_build_constraints/bar_l_test.go
- tests/test_build_constraints/bar_unknown_test.go
- tests/test_build_constraints/baz_linux_test.go
- tests/test_build_constraints/baz_unknown_test.go
- tests/test_build_constraints/foo_linux_test.go
- tests/test_build_constraints/foo_unknown_test.go
generate_test_main now receives a list of source files filtered
according to build constraints (build tags and suffixes) using
filter_tags. This prevents generate_test_main from emitting calls to
functions that won't be compiled or linked into the test binary.
Fixes #340.
> Filter go_test sources before generating test main file

- go/private/go_repositories.bzl
- go/tools/generate_test_main.go
- tests/run_non_bazel_tests.bash
- tests/test_filter_test_1.7.5/BUILD
- tests/test_filter_test_1.7.5/test_filter_test.go
- tests/test_filter_test_1.7.5/test_filter_test_1.7.5.bash
This PR fixes issues with not backward compatible unit test generator. This should unblock support for Go1.7.5. See #321
> Adds support for Go 1.7.5

- go/tools/generate_test_main.go
> Make generate_test_main.go work with future versions

- go/tools/gazelle/rules/resolve_external.go
This reverts commit bfa3601d9ab664b448ddb4cc7e48eea511217aaf.
This fails for "http://gopkg.in/natefinch/lumberjack.v2" for example.
> Revert "Add gopkg.in to knownImports (#260)"

- go/private/go_repositories.bzl
The github.com/bazelbuild/buildifier repository was renamed to
buildtools. With this change, we download from the new location but
keep the old import path.
Fixes #361
> Fetch buildifier from new location

- README.md
- go/private/go_repositories.bzl
- go/private/go_repository.bzl
- go/tools/fetch_repo/BUILD
- go/tools/fetch_repo/fetch_repo_test.go
- go/tools/fetch_repo/main.go
Cherrypicked the following changes:
* **#319 go_repository: add importpath and vcs flags.** This allows us to have separate import paths and remote URLs for repositories.
* **#362 Fetch buildifier from new location**. This allows the buildifier zip to be extracted with the new name.
Note that this PR is onto a new branch, release/0.3, which currently points to 0.3.3.
> Cherrypicks for 0.3.4 release

- README.md
- go/private/go_repositories.bzl
- go/private/go_repository.bzl
- go/tools/fetch_repo/BUILD
- go/tools/fetch_repo/fetch_repo_test.go
- go/tools/fetch_repo/main.go
Cherrypicked the following changes:
* **#319 go_repository: add importpath and vcs flags**. This allows us to have separate import paths and remote URLs for repositories.
* **#362 Fetch buildifier from new location**. This allows the buildifier zip to be extracted with the new name.
Note that this PR is onto a new branch, release/0.4.2, which currently points to 0.4.1.
> Cherrypick 0.4.2

- go/private/go_repositories.bzl
_fetch_repository_tools_deps is used to fetch
github.com/bazelbuild/buildtools (née buildifier) and
golang.org/x/tools into GOPATH so we can bootstrap fetch_repo and
gazelle. Previously, it used repository_ctx.download_and_extract to
download zip files and strip the first directory component.
The first directory component depends on the real name of the
repository, not the name we fetched it as. Bazel fails with an
IOException if the name doesn't match.
With this change, we download an archive with repository_ctx.download,
then use tar to remove the first component of the path, ignoring the
actual name of that component.
Fixes #361 (this is a more robust fix).
> Harden _fetch_repository_tools_deps against repository renames

- WORKSPACE
- go/private/go_repositories.bzl
- go/private/go_repository.bzl
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/generator.go
- proto/go_proto_library.bzl
- tests/test_filter_test_1.7.5/test_filter_test_1.7.5.bash
This reverts commit 6fb0656d40af9de82bcaec78324a251eaf70f338.
Also disabled sandboxing for test_filter_test_1.7.5 (manual test),
which started failing with this change. custom_go_toolchain already
needed sandboxing disabled; not sure why this one didn't before.
Fixes #151
Fixes #344
> Revert "Add another workaround instead of the previous commit for Bazel 0.3.2

- go/def.bzl
- tests/build_constraints/BUILD
- tests/build_constraints/build_constraints_test.go
- tests/build_constraints/cgo_group_linux.c
- tests/build_constraints/cgo_group_unknown.c
- tests/build_constraints/cgo_linux.c
- tests/build_constraints/cgo_linux.go
- tests/build_constraints/cgo_unknown.c
- tests/build_constraints/cgo_unknown.go
C and C++ sources are now filtered using build constraints (tags and
suffixes) in cgo_library. This matches behavior in "go build".
Fixes #330
> Support build constraints in C sources in cgo_library

- go/private/go_repository.bzl
- tests/new_go_repository_build_name/local/BUILD
- tests/new_go_repository_build_name/local/WORKSPACE.in
- tests/new_go_repository_build_name/local/local_test.go
- tests/new_go_repository_build_name/new_go_repository_build_name.bash
- tests/new_go_repository_build_name/remote/build/build.go
- tests/run_non_bazel_tests.bash
Generated BUILD files may conflict with other files or directories
named "build" on case insensitive file systems. "BUILD.bazel" is less
likely to conflict, and Bazel supports these files since 0.4.1.
The filename can still be overridden by specifying the build_file_name
attribute. This just changes the default.
Fixes #144
> In new_go_repository, generate BUILD.bazel files by default

- go/def.bzl
- tests/cgo_library_root_dir/BUILD
- tests/cgo_library_root_dir/WORKSPACE.in
- tests/cgo_library_root_dir/cgo.go
- tests/cgo_library_root_dir/cgo_library_root_dir.bash
- tests/cgo_library_root_dir/cgo_test.go
- tests/cgo_library_root_dir/foo.c
- tests/run_non_bazel_tests.bash
The script name for this rule is based on the label package and
name. Previously, if the library was in the root directory of a
repository, the package name would be "", and the script name would
start with a "/", which prevented it from building.
This fix removes the "/" if the package is "".
Fixes #382
> Fix path to _cgo_filter_srcs script

- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
If Gazelle finds .go files in a directory with multiple distinct
package declarations, it will now only generate rules to build .go
files where the package declaration matches the directory name. If
there are multiple packages, and none match the directory name,
Gazelle will report a build.MultiplePackageError, as bove. If is a
single package that doesn't match the directory name, Gazelle will
still generate rules for it.
This change helps address #339. When we are no longer applying build
constraints by default, multiple packages are much more common; many
files are hidden with "// +build ignore".
> Ignore extra packages in Gazelle

- .test-bazelrc
- .travis.yml
- tests/cgo_library_root_dir/cgo_library_root_dir.bash
- tests/custom_go_toolchain/custom_go_toolchain.bash
- tests/gc_opts_unsafe/gc_opts_unsafe.bash
- tests/new_go_repository_build_name/new_go_repository_build_name.bash
- tests/non_bazel_tests_common.bash
- tests/test_filter_test/test_filter_test.bash
- tests/test_filter_test_1.7.5/test_filter_test_1.7.5.bash
* Test flags are now stored in .test-bazelrc. This is referenced by
.travis.yml and by all non-Bazel test scripts.
* Common functionality for non-Bazel test scripts is now in
non_bazel_tests_common.bash. This includes Bash functions that help
run Bazel with appropriate options. All test scripts source this.
* Scripts that create new workspaces now run in batch mode. This
prevents Bazel servers from hanging around in memory.
> Consolidate Bazel flags in a single place for tests

- go/def.bzl
- go/private/single_output_test.bzl
- tests/binary_test_outputs/BUILD
- tests/binary_test_outputs/bin.go
- tests/binary_test_outputs/test.go
Previously, go_binary and go_test provided both an executable and the
library built from srcs as outputs to other rules. This was
inconsistent with other binary rules (cc_binary, etc.) and confusing
for rules that expected a single output. With this change, only the
executable file is exposed through the files provider.
Fixes #379
> go_binary and go_test no longer provide a library to other rules

- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
The Go rules now apply build constraints to files in srcs of
go_library, cgo_library, go_test, and go_binary, so it's not usually
necessary to perform this filtering in Gazelle as well. Gazelle will
not apply build constraints (GOOS and GOARCH) by default anymore.
Generated BUILD files will be the same for all platforms.
Build tags can still be specified on the command flag, with -build_tags.
This can still be done with new_go_repository.
Fixes #339
> Gazelle no longer applies build constraints by default

- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
Gazelle determines a default package name for each directory. Usually
this is the directory base name, but semantically, it should be the
last component of the import path.
With this change, the default package name for the root directory of
the repository is now the last component of the import path in
go_prefix. This accounts for repositories checked out under names that
differ from their import paths, which is always the case inside
new_go_repository.
Fixes #406
> Gazelle: use go_prefix to determine default package name in root directory

- go/def.bzl
This removes the source linking from the compile script.
It also removes the cd from the top, and thus removes all need for external dectection and relative path generation.
> Remove source linking behavior

- go/def.bzl
This removes the excessive bazel paths from the stack traces.
It does mean that stack traces no longer have an absolute path in them, but I suspect that any tooling trying to use that from a bazel build is already in trouble as it used to get a path to a temporary softlink not the real source anyway.
> Add trimpath to compile action

- go/def.bzl
_emit_generate_params_action uses ctx.new_file, which already bakes in the directory, so the path from the exec root is duplicated, this removes that
> Don’t stutter the directory

- tests/popular_repos/WORKSPACE.in
- tests/popular_repos/popular_repos.bash
- tests/run_non_bazel_tests.bash
popular_repos.bash is a new test which sets up a new WORKSPACE with a
number of new_go_repository rules pointing to golang.org/x
repositories. It tests most targets (with a few exceptions) in these
repositories. This should give both the Go rules and Gazelle more
coverage on real world code.
> Add an integration test targets in popular repositories.

- go/def.bzl
Only the compile step is changed so far.
It now uses separate bazel actions per file, and uses copy rather than link.
This means that you no longer need to manage directories, or wipe out the tree each time, instead each entry is updated when it needs to be.
It is also more portable.
Incremental building should be faster, and a clean build should not be much slower if at all, except in the presence of huge libraries that take a long time to copy.
> Don’t build symlink trees in bash

- go/tools/gazelle/packages/walk.go
Fixes https://github.com/bazelbuild/rules_go/issues/423
> Stop skipping directories that start with '_'

- .travis.yml
Bazel added an additional build artifact to Jenkins builds:
bazel--without-jdk-installer.sh. This confused our installer script,
which was grepping the artifact name out of the build page. Now there
are two matching artifacts instead of one.
With this change we always fetch bazel--installer.sh for builds with
Bazel HEAD.
> Fix Bazel install script in Travis CI

- go/def.bzl
This is required as bazel CROSSTOOL intends on making "darwin_x86_64" the canonical default for osx systems going forward.
> support darwin_x86_64 cpu value

- go/def.bzl
Previously, If none of the .go sources in a cgo_library pass build
constraints, we pass an empty source list to cgo, which prints out
usage information and exits with an error code. This is confusing and
unhelpful.
With this change, we emit an error messages when there are no
buildable .go sources. This is consistent with what go_library and "go
build" do.
Related to #399
> Improve error message when all cgo sources are filtered out

- go/def.bzl
This rips out all the cd’s in the scripts, kills all the softlinks and removes all the code that tries to work out depts and wether a file is “external”
This result in far simpler code, much shorter bash scripts, and far far less work at build time, at the cost of larger command lines due to the package search paths being added.
> Kill symlink_tree_commands

- .travis.yml
Previously, we always fetched bazel--installer.sh. It turns out there
can be a prerelease tag between the dashes, e.g.,
bazel-0.5rc2-installer.sh. We'll handle this again with this change.
This will still filter out non-JDK installers (see #426).
> Fix Travis CI flakiness for Bazel HEAD builds

- go/def.bzl
This removes duplicate entries from the list passed to the compile step
> Switch library search path to a depset

- go/def.bzl
This changes the compile step to output a .o in all cases, and then use a subsequent pack step to build the .a
This removes the last read modify write action from the bash scripts, and reduces the compile bash script to something we can retool
> Split the pack and compile steps

- examples/stamped_bin/BUILD
- examples/stamped_bin/stamp/stamp.go
- examples/stamped_bin/stamped_bin_test.go
It was not actually doing any stamping, or testing wether the stamping worked.
It has been converted from a binary to a test, that validates that the timestamp variable in the included library is correctly replaced.
> Fix stamped_bin

- go/tools/gazelle/packages/walk.go
This is the first of several changes which will make Gazelle put
platform-specific sources, dependencies, and options into select
expressions.
This groups several related values into a new struct,
packageReader. This avoids passing the same parameters to every
function. I will add several more methods on this struct in an
upcoming change.
Related: #409
> Gazelle select (1/x): consolidate parameters in packageReader

- go/tools/gazelle/packages/BUILD
- go/tools/gazelle/packages/package.go
Added three structs that contain metadata for a Go package in a
directory. These will be used to generate rules in place of
go/build.Context.
The main difference between these and go/build.Context is that these
structs divide files by target instead of type, and they are capable
of list platform-specific files, imports, and flags for multiple
platforms.
Related: #409
> Gazelle select (2/x): add Package, Target, PlatformStrings

- go/def.bzl
- go/tools/filter_exec/BUILD
- go/tools/filter_exec/filter_exec.go
- go/tools/filter_tags/filter_tags.go
Add the ability to filter a command line and then run it to filter_tags
Add the ability to abs arguments to filter_tags
Use the new filter tags to kill the remnants of the compile bash script
> Kill the compile script

- README.md
- go/private/go_repository.bzl
- tests/popular_repos/WORKSPACE.in
This is a proof of concept change to merge new_go_repository into
go_repository.
Instead it autmatically runs gazelle on repositories that do not
supply a build file.
It also adds the ability to fetch a go repository by source blob
instead, with the same automatic running of gazelle if needed.
This is fully backwards compatible, but going forward would allow
gazelle to only generate go_repository rules, and to automatically
switch to source blobs when it knows it can resolve one (rather
than using the vcs)
> merge go_repository rules

- go/tools/gazelle/rules/resolve_external.go
- go/tools/gazelle/rules/resolve_external_test.go
This change fixes a performance problem in the external
resolver.
For each import path in a repository, Gazelle determines a label for
the corresponding dependency. For external dependencies, the external
name in the label is based on the repository root URL, so Gazelle
looks this up using the vcs package. The lookup process is expensive,
since it involves HTTP requests and redirects for unqualified paths.
This change caches lookup results. It also unifies the special case
logic into this cache.
Fixes #353
Related #427
> Gazelle: cache lookups using vcs.RepoRootForImportPath

- go/tools/gazelle/packages/BUILD
- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/packages/walk.go
fileInfo holds information used to decide how to build a file.
packageReader.goFileInfo and .otherFileInfo create fileInfo. These
methods examine file name, build tags, package declaration, imports,
and cgo directives.
The functions in this change imitate logic from go/build. Unexported
functions from go/build are copied where possible.
Related: #409
> Gazelle select (3/x): add fileInfo and related methods

- go/tools/gazelle/rules/BUILD
- go/tools/gazelle/rules/construct.go
newValue now converts maps to to a call to the select function with a
dictionary argument. The keys of the dict are the keys of the map
converted to strings. The values are converted recursively with
newValue.
newValue also supports packages.PlatformStrings. This is converted
into a list if it only has generic strings, a select call if it only
has platform-specific strings, or a concatenation of the two if it has
both.
These cases are not used yet, since rules doesn't use packages.Package
yet. This prepares for later PRs.
Related: #409
> Gazelle select (4/x): convert and maps to select expressions

- BUILD
- go/private/bzl_format.bzl
- go/private/go_repositories.bzl
This downloads and "builds" yapf
It also adds a special sh_binary target such that
bazel run //:bzl_format
Will reformat all the bzl files in the repository.
We need to pick a style we like before we actually do this for the first time,
but this allows us to fully automate it.
> Automatic bzl formatting using yapf

- examples/monobuild/cmd/BUILD
- examples/monobuild/cmd/mycmd.go
- examples/monobuild/lib1/BUILD
- examples/monobuild/lib1/lib1.go
- examples/monobuild/lib2/BUILD
- examples/monobuild/lib2/lib2.go
- go/def.bzl
The previous work on cleaning up the library system now allows arbitrary remapping of library import paths.
This exposes that functionality directly on the library rule, and adds an example of using it.
The enables “mono” repos, where different sub directories represents radically different import paths.
> Enable mono repos

- go/private/repositories.bzl
- go/private/toolchain.bzl
They are all now independantly declared, with their own correct build file.
This allows to hide the toolchain selection logic, and rely on only the
toolchains in use being downloaded on demand.
> Explode the toolchain repositories

- WORKSPACE
- go/private/repositories.bzl
- go/private/repository_tools.bzl
This splits the stuff needed to build the tools during repository download from
the normal build process.
> Clean up repository tools

- go/private/repositories.bzl
- go/private/toolchain.bzl
Changing the way we do sdk repositories, and then adding all the 1.7.6 and 1.8.3 sdk's
> Skd versions

- go/def.bzl
- go/private/go_root.bzl
- go/tools/BUILD
This modifies all the rules to access the tools and files of a go toolchain
through a single struct, in preparation for that struct being an automatically
selected toolchain.
Accessing this struct is hidden behind a get_toolchain function for now, to
allow it's behaviour to be easily modified.
> Write rules in terms of a toolchain object

- .travis.yml
- tests/run_non_bazel_tests.bash
The "manual" flag is replaced with the "ci" flag, which has the
opposite meaning. Travis CI runs with the "ci" flag, so it won't run
slow tests. When the script is run by hand with no flag, the slow
tests will be run.
> Reverse sense of manual flag in run_non_bazel_tests.bash

- .travis.yml
- README.md
- go/def.bzl
- go/private/go_tool_binary.bzl
- go/private/go_toolchain.bzl
- go/private/repositories.bzl
- go/private/repository_tools.bzl
- go/private/toolchain.bzl
- go/toolchain/BUILD
- go/toolchain/toolchains.bzl
- go/tools/BUILD
- go/tools/builders/BUILD
- go/tools/extract_package/BUILD
- go/tools/filter_exec/BUILD
- go/tools/filter_tags/BUILD
This changes the way toolchains are implemented to be ready for the full
toolchain concept to arrive.
It stubs out the functions that will be provided by bazel in a semi compatible
way, with basically broken selection logic.
> Preparation for full toolchain support

- go/private/BUILD.sdk.bazel
- go/private/toolchain.bzl
It's going to grow quite a lot, and having it in a file is much cleaner and
better for maintanance than in a string.
> Move the sdk build file content into a file

- proto/go_proto_library.bzl
Some projects will have vendored or otherwise locally-present versions
of the context, grpc, and proto dependencies that the go_proto_library
adds implicit dependencies on.  In these cases, allow users to specify
which targets should be used.
> Allow overriding dependencies for go_proto_library (#442)

- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
* Merging logic now handles calls to select with dictionaries for
conditional srcs and deps.
* Most of the merging logic is rewritten. Instead of having "src and
"dest" and modifying dest in place, most functions now have "old"
and "gen" and return "merged".
Fixes #480
Related to #409
> Gazelle select (5/x): rewrite merge logic

- go/private/binary.bzl
- go/private/cgo.bzl
- go/private/def.bzl
- go/private/library.bzl
- go/private/test.bzl
This is a step towards refactoring def.bzl and breaking it into it's major
functional areas.
This is basically a simple move of go/def.bzl -> go/private/def.bzl and leaving
a new def.bzl in it's place that rexports all the symbols from def.bzl that
should be public, via what will be their new homes.
This is not a fully backwards compatible change, because there are symbols in
def.bzl that we do not re-export because they should never have been part of the
public interface.
> Move def.bzl

- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
- go/tools/gazelle/rules/construct.go
* In exprListAndDict, improve error messages when matching binary exprs.
* Force multi-line formatting for lists that are part of binary exprs
and lists that are dict values. This is done for both generated and
merged expressions.
* Fix a recursive call to newValue for map values.
Related #409
> Gazelle select (6/x): polish

- go/private/common.bzl
- go/private/library.bzl
There is no reason now we have importpath to ever set the go_prefix attribute
directly on a rule.
> Hide go_prefix

- go/private/library.bzl
The previous implementation returned the expanded form from a provider to
another rule, resulting in possibly incorrect expansions.
> Do expand_make_variables on gc_goopts as late as possible

- go/private/binary.bzl
- go/private/cgo.bzl
- go/private/common.bzl
- go/private/library.bzl
- go/private/test.bzl
It makes it much harder to read a rule and understand it's parameters.
This is also needed for me to remove attributes that don't belong on rules but
were there in the shared blocks, and to change the acceptable provider types
accepted in shared names (like deps, srcs and library)
> Don't use shared attribute declarations

- go/private/binary.bzl
- go/private/library.bzl
- go/private/test.bzl
go_library_impl -> emit_library_actions
a rule implementation function is not a useful building block for other
functions, and treating it as one was causing us to leak implementation details
into our public interface.
Now the action emitting functions are decoupled from the code that looks into
attributes, we are free to change and clean up the attributes and return values
of our rules, which is neccesary in the change to true providers.
> Rule implementation functions are not general purpose

- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/testdata/repo/lib/lib.go
Bogus import paths sometimes exist in .go files that won't actually
get built. For example, in
golang.org/x/tools/cmd/bundle/testdata/src/initial/b.go.
Gazelle won't always be able to tell if a .go file is actually a
source file or a data file, but we should attempt to generate a BUILD
file anyway. Gazelle should log a warning and continue instead of
failing.
> Gazelle: don't abort on import path resolution errors

- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/BUILD
- go/tools/gazelle/testdata/repo/allcgolib/BUILD.want
- go/tools/gazelle/testdata/repo/bin/BUILD.want
- go/tools/gazelle/testdata/repo/bin_with_tests/BUILD.want
- go/tools/gazelle/testdata/repo/cgolib/BUILD.want
- go/tools/gazelle/testdata/repo/lib/BUILD.want
- go/tools/gazelle/testdata/repo/lib/internal/deep/BUILD.want
- go/tools/gazelle/testdata/repo/lib/relativeimporter/BUILD.want
- go/tools/gazelle/testdata/repo/tests_with_testdata/BUILD.want
* Remove redundant tests from generator/generator_test.go. These are
somewhat tautological. This functionality is covered by
rules/generator_test.go anyway.
* In rules/generator_test.go, move expected content of BUILD files
out of the test source and into "BUILD.want" files in testdata.
> Gazelle: refactor tests

- README.md
- examples/stamped_bin/BUILD
- examples/stamped_bin/stamp/stamp.go
- examples/stamped_bin/stamped_bin_test.go
- go/private/binary.bzl
- go/private/test.bzl
This PR fixes #432 by augmenting the `x_defs` attribute of `go_binary` and `go_test` rules to refer to variables in the workspace status files.
This uses the unofficial `{VAR}` syntax I [implemented](https://github.com/bazelbuild/rules_docker/pull/17) in the `rules_docker` repo, as suggested by @mikedanese in https://github.com/bazelbuild/rules_go/issues/432#issuecomment-300245203; I'm not sure if there's a consensus style for this sort of thing, yet.
As of now this implicitly turns on stamping if it finds any `x_defs` in the `{VAR}` style, but we could also potentially make it explicit with a `stamp=1` attribute.
> Support stamping in x_def attributes

- go/tools/gazelle/gazelle/fix.go
- go/tools/gazelle/gazelle/fix_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/merger/merger.go
Gazelle will no longer rename files in any situation. This was
previously done using the first name in -build_file_name.
Fixes #506
> Remove renaming functionality from Gazelle

- go/private/cgo.bzl
- tests/cgo_select/BUILD
- tests/cgo_select/cgo_darwin.go
- tests/cgo_select/cgo_linux.go
- tests/cgo_select/cgo_select_test.go
- tests/cgo_select/cgo_windows.go
- tests/cgo_select/darwin.c
- tests/cgo_select/linux.c
- tests/cgo_select/windows.c
`cgo_library` should allow `srcs` and `cdeps` to be arbitrary expressions
that produce lists of appropriate sources. In particular, they should
allow calls to select, which allows sources and dependencies to be
included conditionally.
This change introduces a new rule, `_cgo_select_files`, which copies
files that match a given set of suffixes (possibly inverted).
`_setup_cgo_library` and related functions are rewritten to
use this. Some other small fixes are included, such as demangling cgo
outputs.
In the future, we'll use output groups with filegroups instead of
`_cgo_select_files`, but they aren't supported in Bazel 0.4.4 (our
current minimum).
Fixes #510
> Support select in cgo_library srcs and deps

- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
readTags misclassified golang.org/x/net/route/route.go due to a
misunderstanding of the algorithm used in go/build.Context.shouldBuild.
This change re-implements readTags using a very similar two-pass
algorithm.
> Gazelle select: fix error in readTags

- go/private/test.bzl
- go/tools/builders/BUILD
- go/tools/builders/generate_test_main.go
This kills one more use of bash, normalises the filtering logic, and cleans up
the rules a little more.
> Move filtering logic into test harness generator

- go/private/repositories.bzl
- go/private/repository_tools.bzl
- go/toolchain/toolchains.bzl
Use underscores instead of dots and dashes. Bazel doesn't allow these
characters in workspace names, but it appears it doesn't enforce this
restriction in Skylark repository names.
> Rename SDK repositories

- go/tools/gazelle/gazelle/fix_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/construct.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
* Most errors in Gazelle are non-fatal. Most entry points in each
package no longer return errors. Errors will generally be logged
using log.Print, and a nil value or a partial success value will be
returned.
* packageReader.warn is replaced by log.Print. There is no longer a
meaningful difference between warnings and errors.
* In cases where errors could only occur due to bugs in Gazelle (i.e.,
most of rules), log.Panic is used instead of log.Print.
> Gazelle: simplify error handling

- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/packages/package.go
Non .go files (example: foo_test.py) were being included as go_test
sources despite fileInfo.isTest's comment indicating that it should
never be true for non-go files.
This change moves the detection of isTest after the extCategory is
calculated and only sets isTest to true if category is not .
Tested:
* go test github.com/bazelbuild/rules_go/go/tools/gazelle/packages
* bazel test //...
> Don't include non-.go files as go_test srcs

- go/tools/gazelle/config/BUILD
- go/tools/gazelle/config/config.go
- go/tools/gazelle/config/config_test.go
- go/tools/gazelle/gazelle/diff.go
- go/tools/gazelle/gazelle/fix.go
- go/tools/gazelle/gazelle/fix_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/gazelle/print.go
- go/tools/gazelle/generator/BUILD
- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/packages/BUILD
- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/packages/package.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/BUILD
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
* Added a new "config" package with a "Config" struct that contains
most of the configuration information that Gazelle gets from flags
(go prefix, repo root, etc.). Defaults and utility methods are also
moved to this package.
* Added newConfiguration, a function which builds this
configuration. Tags are preprocessed, and paths are canonicalized so
we don't have to worry about that later.
* Functions which previously accepted arguments that are found in
Config now just accept *config.Config.
* Deleted packageReader, since it had a very similar purpose.
> Gazelle: refactor configuration plumbing

- go/private/cgo.bzl
- go/private/common.bzl
- go/private/test.bzl
- go/tools/builders/generate_test_main.go
- tests/run_non_bazel_tests.bash
- tests/test_chdir/local/BUILD
- tests/test_chdir/local/WORKSPACE.in
- tests/test_chdir/local/sub/BUILD
- tests/test_chdir/local/sub/local_test.go
- tests/test_chdir/remote/BUILD
- tests/test_chdir/remote/WORKSPACE.in
- tests/test_chdir/remote/sub/BUILD
- tests/test_chdir/remote/sub/remote_test.go
- tests/test_chdir/test_chdir.bash
The main go file generated by go_test includes a call to os.Chdir to
change to the package directory so that data files may be accessed by
package-relative paths. This is the same behavior as "go test".
The chdir now includes the workspace directory, which is necessary
for tests in remote workspaces. We also detect errors when changing
directories.
Fixes #540
> Fix go_test chdir to package directory

- go/tools/gazelle/generator/generator.go
- go/tools/gazelle/generator/generator_test.go
- go/tools/gazelle/packages/package.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/repo/tests_import_testdata/BUILD.want
- go/tools/gazelle/testdata/repo/tests_import_testdata/external_test.go
- go/tools/gazelle/testdata/repo/tests_import_testdata/internal_test.go
- go/tools/gazelle/testdata/repo/tests_import_testdata/testdata/data.go
- tests/popular_repos/popular_repos.bash
Gazelle will now recurse into "testdata" directories and generate
BUILD files if there are buildable .go files present.
Generated go_test rules will only have 'data = glob(["testdata/**"])'
if a "testdata" directory exists and does not contain .go files or
BUILD or BUILD.bazel files in any subdirectory.
Fixes #415
> Gazelle: generate BUILD files for "testdata" directories containing code

- go/tools/gazelle/config/config.go
- go/tools/gazelle/gazelle/main.go
Flags are no longer declared globally in main.go. newConfiguration
takes os.Args[1:] and parses the flags using a FlagSet.
> Gazelle: move flag parsing into newConfiguration

- .travis.yml
Adding "dev" to a tests tags now causes it to be excluded from ci builds.
> Allow tests to be tagged as "not ci"

- BUILD
- examples/cgo/BUILD
- examples/lib/BUILD
- examples/proto/BUILD
- examples/stamped_bin/BUILD
- go/tools/bazel/BUILD
- go/tools/builders/BUILD
- go/tools/extract_package/BUILD
- go/tools/fetch_repo/BUILD
- go/tools/gazelle/config/BUILD
- go/tools/gazelle/merger/BUILD
- go/tools/gazelle/packages/BUILD
- go/tools/gazelle/rules/BUILD
- go/tools/gazelle/wspace/BUILD
- tests/asm_include/BUILD
- tests/binary_test_outputs/BUILD
- tests/cgo_select/BUILD
- tests/cgo_sys_hdr/BUILD
- tests/cgo_trans_deps/BUILD
- tests/extldflags_rpath/BUILD
- tests/gc_opts_unsafe/BUILD
- tests/new_go_repository_build_name/local/BUILD
- tests/slash_names/BUILD
- tests/test_build_constraints/BUILD
- tests/test_chdir/local/sub/BUILD
- tests/test_chdir/remote/sub/BUILD
- tests/transitive_data/BUILD
Tagging them as such so bazel stops complaining and test filters work as
expected.
> Our tests are all small

- go/tools/gazelle/config/config.go
Commit cafe930223abe6f5faa0561d40435b52fbea77b9 inadvertently changed
the flag value from `vendored` to `vendor`.
> Restore -external flag value to vendored

- go/tools/gazelle/config/config.go
- go/tools/gazelle/config/config_test.go
- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/testdata/repo/platforms/release.go
Gazelle will no longer filter files based on release tag
(e.g., "go1.8"). Release tags are not currently part of the
config_settings used to select files, and they are difficult to detect
at that point. So we'll include files with these tags, whether or not
they are negated, and we'll let the rules sort it out.
Fixes #563
> Gazelle: treat release tags as unknown

- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/packages/BUILD
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/generator_test.go
This is in preparation for increased awareness of generated
code. packages.Walk now discovers and parses existing BUILD files. A
*bzl.File is passed to the callback if one was found.
Gazelle will need to read BUILD files in order to build
packages.Package structures for two reasons:
1. Gazelle will discover generated files by examining attributes of
rules in existing BUILD files.
2. Some files can be excluded using comments in BUILD files.
Related #557
> Gazelle: parse BUILD files in packages.Walk

- tests/bazel_tests.bzl
bazel_tests time out when run concurrently because Bazel takes a long
time to unpack itself in a new workspace. Increasing the timeout works
around failures until we have a proper fix.
> Set bazel_test timeout to moderate

- go/private/go_repository.bzl
- go/private/repository_tools.bzl
- go/tools/gazelle/gazelle/main.go
- go/tools/wtool/README.md
- go/tools/wtool/main.go
- proto/go_proto_library.bzl
Also adds a print to the compatibility shim to warn people to switch, and changes the documentation to not refer to new_go_repository any more.
> Switching from new_go_repository to go_repository

- tests/bazel_tests.bzl
- tests/trans_dep_error/BUILD
We need to return the result code no matter what the "check" part does
> Fix bazel test result

- BUILD
- go/def.bzl
- go/private/gazelle.bzl
These are still experimental, and subject to change, but they seem useful.
Add
load("@io_bazel_rules_go//go:def.bzl", "gazelle")
gazelle(name = "gazelle")
to your build file, and then do
bazel run //:gazelle
to automatically fix all build files.
You can make as many of these rules as you like with different names to run
gazelle in different modes or with different options.
> Adding rules for running gazelle

- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/repo/gen_and_exclude/BUILD.old
- go/tools/gazelle/testdata/repo/gen_and_exclude/BUILD.want
- go/tools/gazelle/testdata/repo/gen_and_exclude/gen_static_darwin.go
- go/tools/gazelle/testdata/repo/gen_and_exclude/gen_static_ignore.go
- go/tools/gazelle/testdata/repo/gen_and_exclude/static.go
- tests/popular_repos/popular_repos.bash
Gazelle now detects files generated inside rules of existing BUILD
files and incorporates them into the rules it generates. For example,
if a genrule lists "foo.go" in its "outs" attribute, Gazelle will add
"foo.go" to the go_library it generates.
Files may be excluded by adding a comment of the form:
"# gazelle:exclude foo.go"
The exclusion applies both to existing files and generated files.
Fixes #557
> Gazelle: be aware of generated and excluded files

- go/tools/gazelle/gazelle/diff.go
- go/tools/gazelle/gazelle/fix.go
- go/tools/gazelle/gazelle/fix_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/gazelle/print.go
- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/construct.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/wtool/main.go
This is in response to a review comment on an earlier Gazelle PR. The
package is "github.com/bazelbuild/buildtools/build", but "build" is
easy to confuse with "go/build". "bzl" is the suffix for Skylark files
(containing rule and macro definitions), so it doesn't seem
appropriate. "bf" can stand for "BUILD file" or "Bazel format".
> Rename import symbol bzl to bf in all tools

- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/resolve_external.go
- go/tools/gazelle/rules/resolve_external_test.go
The repo root cache and the repoRootForImportPath function pointer are
now fields of externalResolver instead of global. This reduces timing
dependencies between test cases.
Note that currently, only one instance of externalResolver is
created. If we go back to having multiple instances, we'll need to
find a way to share the cache.
> Gazelle: refactor resolve_external.go to eliminate global state

- go/tools/gazelle/gazelle/main.go
merger.MergeWithExisting returns nil when it finds a
"# gazelle:ignore" directive. run must check for this before
formatting and writing the file.
> Gazelle: check for ignored files before emitting

- go/private/library.bzl
- go/private/test.bzl
- go/tools/builders/compile.go
They have all the transitive data they need inside them.
This should make complex builds considerably faster, although we have no useful
benchmark to prove it.
Also cleaned up the compile argument handling while I was in there.
> Only pass direct targets to compile

- go/tools/gazelle/gazelle/main.go
The directories here should come from the flagSet we have parsed from the passed in args and not from the global Flag.args()
> Get directories from parsed FlagSet

- README.md
- go/private/go_repository.bzl
Also removed documentation for go_linux and go_darwin parameters
of go_repositories, since they no longer work.
[skip ci]
[ci skip]
Fixes #593
> Update README.md information on go_repository and new_go_repository

- go/private/go_repository.bzl
This allows fetching external dependencies that are stored in private Git repositories served via SSH.
> Propagate `SSH_AUTH_SOCK` to `fetch_repo` if set.

- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
This change adds copts and clinkopts to the list of attributes Gazelle
will merge. Gazelle still won't merge data and visibility, since any
change in these normally implies user intent.
Fixes #525
> Gazelle: merge copts and clinkopts

- go/tools/gazelle/gazelle/integration_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/rules/BUILD
- go/tools/gazelle/rules/sort_labels.go
This is a workaround for bazelbuild/buildtools#122. When buildifier
sorts lists, it only processes list expressions as arguments for
certain attributes. It doesn't process lists inside select or lists
concatenated with select. When that bug is fixed, this code can be
removed.
Fixes #584
> Gazelle: sort srcs and deps string lists in buildifier order

- README.md
> Update README.md in preparation for 0.5.1 release

- go/private/common.bzl
- go/private/go_toolchain.bzl
- tests/bazel_tests.bzl
Now declared providers are used for both go_bootstrap_toolchain and go_toolchain.
In the future it will be possible to return a single declare provider (not in a list), but now due to a bug such providers are treated like old-style structs, therefore both rule implementation functions return singleton lists now for compatibility.
> Don't mix declared and old-style providers

- README.md
- go/private/binary.bzl
- go/private/library.bzl
- go/private/test.bzl
- tests/race/BUILD.bazel
- tests/race/race.go
- tests/race/race_main.go
- tests/race/race_test.go
- tests/race/racy/BUILD.bazel
- tests/race/racy/racy.go
This is stacked on top of #633 and #634, putting it up now so you can review it while I am afk.
This is the full implementation of race detector, without using toolchains.
From the commit message..
Tests:
Without race detector
bazel test //tests/race:go_default_test
will pass, but with it turned on
bazel test —features race //tests/race:go_default_test
Binares:
Without race detector
bazel build //tests/race
builds bazel-bin/tests/race/race
With race detector
bazel build //tests/race --output_groups=race
builds bazel-bin/tests/race/race.race
> Race detector

- go/private/binary.bzl
- go/private/library.bzl
- go/private/test.bzl
- tests/coverage/BUILD
- tests/coverage/bin.go
- tests/coverage/bin_lib.go
Coverage is now applied in emit_library_actions instead of
emit_go_compile_action. emit_library_actions accepts a want_coverage
parameter, which is only true for go_library. go_test and go_binary
should not apply coverage to their own sources, but will continue to
apply coverage to sources from the library attribute.
In the future, we may want to apply coverage before running cgo
(#641), so this provides an easy way to prevent coverage being applied
a second time in go_library.
Fixes #629
> Don't apply coverage to go_binary or go_test sources

- .travis.yml
Bazel has renamed the project on their Jenkins server. The old links
still work for HEAD builds, but those builds are three weeks stale.
> Make Travis use Bazel HEAD again

- .travis.yml
- README.md
The URL for the last successful build has changed a couple times in
the last week. We'll re-enable when
bazelbuild/continuous-integration#95 is resolved. We are still testing
at HEAD in Jenkins.
This change also fixes broken status icon links to Jenkins.
Related #649
> Stop testing Bazel HEAD in Travis CI

- README.md
bazel test //... runs all tests in the entire workspace, not just under
the current working directory, as "go test ./..." implies. Note that and
clarify that "go test ./..." is only equivalent if it were run from the
go_prefix directory inside GOPATH.
bazel test ...:all could be used to run all tests under the CWD, but in
my experience it is more common to remain at workspace root anyways, and
specify packages you care about (//pkg/...) rather than changing to that
directory.
@kevinburke @jayconrod
> README: clarify sample bazel test command

- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/packages/package.go
This allows groups of options like "-framework IOKit" to be passed to
Bazel in the same string. Bazel applies Bourne shell tokenization and
label expansion to cc_library opts and linkopts. The label expansion
causes problems for arguments like "IOKit", which are not labels.
Fixes #646
> Gazelle: represent lists of cgo options as single strings

- go/private/gazelle.bzl
Args coming from the naked `args` parameter were overridden immediately, making it for example impossible to override the `build_file_name` option.
> don't ignore raw arguments passed to gazelle

- go/tools/gazelle/config/config.go
- go/tools/gazelle/gazelle/BUILD
- go/tools/gazelle/gazelle/flags.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/resolve/resolve.go
- go/tools/gazelle/resolve/resolve_external.go
- go/tools/gazelle/resolve/resolve_external_test.go
Private repositories can take a long time to resolve, and if the repo
host does not properly support go-import meta tags then gazelle may not
be able to resolve them at all.
This change allows the author of WORKSPACE files to add specially
crafted comments which instruct gazelle to update the external
resolver's repo cache. As a result, gazelle can be instructed to skip
resolution of certain imports.
> Add -known_import flag

- go/private/repository_tools.bzl
- go/private/toolchain.bzl
Bazel repository rules may be restarted if they depend on a file that
isn't available yet using a Label. If a download has already occurred,
this means the download will happen again (unless
--experimental_repository_cache is in use).
We should download archives after Labels have been resolved.
Fixes #671
> Only download SDK once

- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
In external mode, nothing will depend on rules in vendor
directories. They are not likely to build.
Fixes #660
> Gazelle: don't recurse into vendor directories in external mode

- tests/bazel_tests.bzl
Fix
http://ci.bazel.io/blue/organizations/jenkins/Global%2Frules_go/detail/rules_go/52/pipeline/21
@dslomov
> Make test_environment rule depend on environment variables it uses

- README.md
- go/private/test.bzl
- go/tools/builders/generate_test_main.go
- tests/test_rundir/BUILD
- tests/test_rundir/rundir_test.go
This lets developers specify the directory where a test will run.
Fixes #670
> go_test: add rundir attribute

- go/tools/gazelle/README.md
`# gazelle:exclude` was added in #581 but the README wasn't updated.
I think this explanation is correct, but please correct me if I'm misunderstanding it.
> Update README with details about `# gazelle:exclude`

- go/tools/builders/cgo.go
- tests/cgo_filtered/BUILD
- tests/cgo_filtered/pure.go
- tests/cgo_filtered/pure_test.go
This happens when a go library has cgo files that are only present in some
configurations.
Fixes #678
> Cope with cgo=True when there is no cgo

- go/tools/gazelle/merger/fix.go
- go/tools/gazelle/merger/fix_test.go
squashCgoLibrary will no longer be as careful around library
attributes. It will squash go_library and cgo_library (with default
names) even if they were not linked.
> Gazelle: fix how squashCgoLibrary deals with library attributes

- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/packages/package.go
- go/tools/gazelle/rules/construct.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/testdata/repo/allcgolib/BUILD.want
- go/tools/gazelle/testdata/repo/cgolib/BUILD.want
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/BUILD.want
- go/tools/gazelle/testdata/repo/platforms/BUILD.want
Gazelle will no longer generate new cgo_library rules. cgo sources,
deps, and options will be placed in a combined go_library with
cgo = True.
There will be another change soon to squash existing cgo_library rules
into go_library.
> Gazelle: generate consolidated go_library rules with cgo

- go/private/gazelle.bzl
- go/tools/gazelle/gazelle/fix_test.go
- go/tools/gazelle/gazelle/integration_test.go
- go/tools/gazelle/gazelle/main.go
Gazelle will now accept a command verb as a first argument, which will
determine what should be done. Currently, two commands are supported:
update - Gazelle will create new BUILD files or update existing
BUILD files. This is the default; if Gazelle is run without a
command, it will do this.
fix - in addition to the changes made in update, Gazelle will make
potentially breaking changes. Currently, it will squash
cgo_library and consolidate load statements.
More commands will be added in the future, for example for managing
dependencies.
> Gazelle: add fix and update commands

- go/def.bzl
- go/private/cgo.bzl
- go/private/go_repository.bzl
This adds the compatability shims to def.bzl written in terms of the correct
rules, with deprecation warnings, and removes the deprecated implementations.
> Compatability shims

- go/tools/gazelle/merger/fix.go
- go/tools/gazelle/merger/fix_test.go
* We won't mark a file as changed if load statements if no Go symbols
are used and no existing Go load statements were found.
* We will delete empty Go load statements in any case.
> Gazelle: fix spurious warnings in non-Go BUILD files

- examples/bindata/bindata.bzl
This PR makes a few changes to the `bindata` example:
* Added a couple of common options, `metadata = False` improves reproducibility.
* Save generated Go code to `bazel-genfiles/` rather than `bazel-bin/` (thanks @zlalanne).
> Improve bindata example

- go/def.bzl
- go/private/asm.bzl
- go/private/binary.bzl
- go/private/cgo.bzl
- go/private/common.bzl
- go/private/library.bzl
- go/private/providers.bzl
- go/private/test.bzl
GoSource gets in the way more than it helps.
This removes it, and also rationalises all source list splitting and joining
into some helpers, and then always passes unified source lists across action
boundaries rather than exploded ones.
This is a preparatory step for cleaning up both the library attribute and the
cover rules.
> Remove the GoSource provider

- go/private/binary.bzl
- go/private/library.bzl
- go/private/providers.bzl
- go/private/test.bzl
We create them directly inside emit_library_actions now, so we dont have to do a
struct to provider field by field copy.
the cgo_object is now passed in it's own provider, this is partly to enable a
future clean up of the cgo chain, and partly because it contains mutable fields.
This leaves GoLibrary as something that can now be put in a depset.
> Fix up creation of GoLibrary providers

- go/private/binary.bzl
- go/private/library.bzl
- go/private/test.bzl
This prevents duplicating the compile and pack logic, and cleans up replicating
the handling of special cases (that was actaully wrong in the test code)
> Rewrite go_test in terms of emit_library_actions

- go/private/binary.bzl
- go/private/library.bzl
- go/private/test.bzl
Instead of having the GoLibrary provider have lots of transitive fields, we now
have one transitive field full of GoLibrary providers.
This cleans up a lot of code, and also allows much more powerful tools to be
written on top of the new collated GoLibrary set.
> Clean up transitive information

- go/tools/gazelle/config/config.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/resolve/BUILD
- go/tools/gazelle/resolve/labeler.go
- go/tools/gazelle/resolve/labeler_test.go
- go/tools/gazelle/resolve/resolve.go
- go/tools/gazelle/resolve/resolve_external.go
- go/tools/gazelle/resolve/resolve_external_test.go
- go/tools/gazelle/resolve/resolve_structured.go
- go/tools/gazelle/resolve/resolve_structured_test.go
- go/tools/gazelle/resolve/resolve_vendored.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
This is a prerequisite for flat mode.
* Labeler is responsible for generating names for library, binary, and
test rules in a directory described by a relative path from the
repository root.
* Labeler has two implementations: hierarchicalLabeler is the current,
default behavior. flatLabeler will be used in flat mode.
* Resolver resolves absolute import paths to labels. It uses Labeler
in its implementation. The caller is now responsible for cleaning
relative import paths.
> Gazelle: Split LabelResolver into Labeler and Resolver

- go/private/library.bzl
- go/private/test.bzl
- go/tools/builders/BUILD
- go/tools/builders/generate_test_main.go
This works by tracking all coverage variables from the full transitive dependacy
set, which allows multiple packages to be covered at once.
This also normalises the names of cover variables so that two separate covers of
the same file will produce actions that merge.
It also tracks the cover variables directly, rather than inferring them from the
file names, which also means the test generator does not need to process the
generated files.
@linuxerwang you might want to check these changes, as it's based heavily on the work you did.
> Switching coverage to a better mechanism

- go/private/binary.bzl
- go/private/library.bzl
This produces a better fake import path for binaries.
This becomes important because I am using the import path when building the fake GOPATH
> importpath for binaries

- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/packages/package.go
- go/tools/gazelle/packages/package_test.go
- go/tools/gazelle/resolve/resolve_structured.go
- go/tools/gazelle/rules/construct.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
* GeneratePrefix, GenerateRules, and GenerateLoad are now separate
methods. Generate is a convenience method that calls them together.
* generator has a new property, buildRel, the path from the repository
root to the directory containing the build file. In flat mode, this
will be different from pkg.Rel.
This is a prerequisite for flat mode.
> Gazelle: prepare rules.Generator for flat mode

- go/tools/gazelle/gazelle/integration_test.go
- go/tools/gazelle/gazelle/main.go
When given the -experimental_flat flag on the command line, Gazelle
will generate a single BUILD.bazel file at the top of the repository
that contains rules for everything in the repository.
This flag is intended to be used on external repositories. Files
generated with this flag may be checked in and used with
new_git_repository or new_http_archive. We hope to eventually remove
go_repository.
Related to #460
> Gazelle: flat mode

- go/private/repositories.bzl
- go/tools/gazelle/rules/BUILD
- go/tools/gazelle/rules/construct.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/testdata/repo/cgolib/BUILD.want
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/BUILD.want
- go/tools/gazelle/testdata/repo/platforms/BUILD.want
* Replace generator.generateRule with commonAttrs, which just returns
[]keyvalue containing attributes relevant for all rules. Other
methods add kind-specific attributes to this, then call newRule
directly.
* newRule sorts attributes using the same order as buildifier.
> Gazelle: simplify rule generation

- go/private/cgo.bzl
cgo runs from the execroot, so there's no need to add it to include
paths anymore.
Fixes #724
> Remove _exec_path in cgo.bzl

- BUILD
- go/def.bzl
- go/private/go_tool_binary.bzl
- go/private/library.bzl
- go/private/path.bzl
- go/private/providers.bzl
- go/tools/fetch_repo/BUILD
This is used to produce a GOPATH like export of the transitive set of sources
used to build specific targets.
You can run it in either copy or link mode.
Link mode allows tools that mutate the original source to run as well
> Add go_path rule

- go/private/binary.bzl
- go/private/gazelle.bzl
- go/private/library.bzl
- go/private/test.bzl
- tests/no_prefix/BUILD
- tests/no_prefix/cmd.go
- tests/no_prefix/no_prefix.go
- tests/no_prefix/no_prefix_test.go
go_prefix is used to generate Go import paths from Bazel labels. Until
now, it has been mandatory, since there's an implicit dependency from
all go_library, go_binary, and go_test rules on //:go_prefix. With
this change, that dependency is not present when the importpath
attribute is specified. This means that if all of the Go rules in a
repository specify importpath, there's no need to define a go_prefix
rule in the repository root.
Fixes #720
Related #721
> Make go_prefix optional

- go/tools/gazelle/gazelle/integration_test.go
- go/tools/gazelle/gazelle/main.go
Fixed a bug where we forgot to read the root build file and merge the
generated file with it. Oops.
> Gazelle: in flat mode, merge with existing build file

- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/packages/package.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/testdata/repo/cgolib/BUILD.want
- go/tools/gazelle/testdata/repo/cgolib/foo.go
generator.options now transforms package-relative paths in cgo options
into repo-root relative paths.
> Gazelle: transform paths in cgo options

- go/private/cgo.bzl
- proto/go_proto_library.bzl
In Bazel 0.6 the `+=` operator on lists will have mutating semantics instead of copying. Some .bzl files have to be updated to be compatible with both semantics.
Protobuf is updated for the same reason.
> Make .bzl files compatible with future versions of Bazel

- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/packages/walk.go
"go build replaces ${SRCDIR} in cgo directives with the absolute
path of the source directory. Gazelle did the same thing when
extracting copts from source files. This caused builds to be
non-hermetic when the path was used in defines.
With this change, ${SRCDIR} is replaced with the relative path from
the repo root. This will probably break some projects, requiring some
manual tweaking of BUILD files, but hermeticity is more important.
Fixes #704
> Gazelle: Fix substitution of ${SRCDIR} in cgo directives

- go/private/BUILD
- go/private/go_toolchain.bzl
- go/private/library.bzl
Triggered when -c dbg is specified on the hazel command line.
Turns of inlining and optimizations
Fixes #741
> Add debug compile flags

- go/private/binary.bzl
- go/private/cgo.bzl
- go/private/go_toolchain.bzl
- go/private/test.bzl
- go/toolchain/toolchains.bzl
This collects the information needed into the go toolchain, rather than
accessing the cpp fragment all over the place.
Theoretically this would make pure go cross compilation easier, in practice you
still have to set --cpu correctly, and bazel still sulks if it has no valid cc
toolchain for that cpu.
> Isolate access to the cpp fragment

- go/tools/gazelle/rules/generator.go
> Gazelle: don't treat -framework options as paths

- BUILD
- go/private/info.bzl
This adds a special target so that
`bazel run @io_bazel_rules_go//:go_info`
Will tell you information about the go toolchain being used by the rules.
This is useful for debugging, checking cross compile platform settings or just
replicatiing the internal commands for normal shell use.
> Adding info command

- go/def.bzl
Currently if you call go_repositories(), it fails with "no matching
toolchains found", as calling go_register_toolchains(go_version=None)
overrides the default value.
> Fix the backwards-compatible go_repositories()

- go/tools/gazelle/gazelle/integration_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/packages/package.go
- go/tools/gazelle/packages/package_test.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/repo/allcgolib/BUILD.want
- go/tools/gazelle/testdata/repo/bin/BUILD.want
- go/tools/gazelle/testdata/repo/bin_with_tests/BUILD.want
- go/tools/gazelle/testdata/repo/cgolib/BUILD.want
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/BUILD.want
- go/tools/gazelle/testdata/repo/default_visibility/BUILD.want
- go/tools/gazelle/testdata/repo/gen_and_exclude/BUILD.want
- go/tools/gazelle/testdata/repo/lib/BUILD.want
- go/tools/gazelle/testdata/repo/lib/internal/deep/BUILD.want
- go/tools/gazelle/testdata/repo/lib/relativeimporter/BUILD.want
- go/tools/gazelle/testdata/repo/main_test_only/BUILD.want
- go/tools/gazelle/testdata/repo/platforms/BUILD.want
- go/tools/gazelle/testdata/repo/tests_import_testdata/BUILD.want
- go/tools/gazelle/testdata/repo/tests_with_testdata/BUILD.want
* go_prefix is no longer generated. In a future change, existing
go_prefix rules will be removed in fix mode.
* All go_library, go_test, and go_binary rules are generated with an
importpath attribute.
* importpath is now a mergeable attribute; Gazelle will replace
existing importpath attributes unless they have a keep comment. This
helps keep libraries up to date after they are moved to a new
location.
Related #721
> Gazelle: add importpath attributes to rules

- go/def.bzl
- go/private/repositories.bzl
- go/private/toolchain.bzl
They are going to become part of the public interface to allow custom
toolchains.
This simplifies that interface, and then adds the ability to specify either an
archive or an already unpacked goroot
> Clean up go sdk rules

- go/private/actions/compile.bzl
- go/private/actions/library.bzl
- go/private/actions/pack.bzl
- go/private/go_toolchain.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/compile.go
- go/tools/builders/pack.go
The Go compiler can produce either an .a file (with -pack; contains
export data and compiled code) or an .o file (embeds export data and
compiled code). Additional .o files may be packed into an .a file.
The Go rules have not previously used -pack. We used "go tool pack c"
whether we had extra objects or not to simplify our logic. This is not
safe, since the Go compiler does not embed export data in .o files in
a format that can safely be extracted.
With this change, we always pass -pack to the compiler to produce an
.a file directly. If we have extra objects, we copy it, then append to
the copy. This is what "go build" does (minus the copy).
Fixes #769
> Compile archives (not objects) and pack extra objects only when needed

- README.md
One for the stable release (0.5.4) and one for commits near HEAD.
Fixes #767.
> README: create two WORKSPACE examples

- go/private/repositories.bzl
> Make all our dependancies (including the sdk's) conditional

- go/def.bzl
- go/private/actions/library.bzl
- go/private/providers.bzl
- go/private/rules/binary.bzl
- go/private/rules/library.bzl
- go/private/rules/test.bzl
This removes the concept of the "library" at the action level, instead allowing GoLibrary providers to be used as source entries.
This enables all the features by library, whilst also allowing other uses (in particular, code generators can use this mechanism to provide source and deps pairs to go library rules easily, looking at you proto...)
I would like to deprecate the library attribute in favour of this. For example
```
go_test(
name = "go_default_test",
size = "small",
srcs = ["bindata_test.go"],
library = ":go_default_library",
)
```
would become
```
go_test(
name = "go_default_test",
size = "small",
srcs = [
"bindata_test.go",
":go_default_library",
],
)
```
> Library as source

- go/private/toolchain.bzl
In _go_sdk_impl, swap order of _sdk_build_file and
_remote_sdk. _remote_sdk resolves a label in @io_bazel_rules_go. This
may cause _go_sdk_impl to be restarted, downloading the SDK again.
Fixes #671
> Fix redundant SDK download

- go/toolchain/toolchains.bzl
The structs were more hassle than help, and can't be used in BUILD files where
you want to declare custom toolchains.
> Simplify os_arch declarations

- WORKSPACE
- examples/bindata/bindata.bzl
- go/private/repositories.bzl
- proto/go_proto_library.bzl
They are all installed in one place, using the same _maybe mechanism so that we
can move the whole function body back into the workspace when nested workspaces
arrive and it will behave identically.
> Rationalise rules_go dependancies

- go/tools/builders/cgo.go
- tests/cgo_opts/BUILD.bazel
- tests/cgo_opts/cgo_opts.go
- tests/cgo_opts/cgo_opts_test.go
Bazel's cc_library and cc_binary automatically apply Bourne shell
tokenization to copts and linkopts. We keep groups of flags such as
"-framework CoreFoundation" together so that label resolution is not
applied to later arguments. However, this breaks cgo, since no
tokenization is performed there.
This change copies the splitQuoted method from go/build into the cgo
builder. This is applied to copts before passing them to cgo.
Related #646
> Apply Bourne shell tokenization in cgo builder

- go/def.bzl
- go/private/BUILD.bazel
- go/private/go_toolchain.bzl
- go/toolchain/toolchains.bzl
Defaults and bootstraps are warts that I don't really want the user to have to
think about when declaring custom toolchains, so this hides them beneath the
go_toolchain macro.
> Clean up default and boostrap toolchain declaration

- go/private/repositories.bzl
These archives are prepared on-the-fly by GitHub and are not
guaranteed to be the same every time (for example, the order of files
within the archive could change).
All archives are fetched over https; this should be as secure as
git_repository and still faster.
Related #820
> Remove sha256 from dependencies fetched from codeload.github.com

- go/private/go_toolchain.bzl
- go/private/repository_tools.bzl
- go/private/toolchain.bzl
- go/private/tools/go_tool_binary.bzl
The go toolchain on windows requires TMP to be a place it can work in.
Based on the work by Jannis Andrija Schnitzer (@xjs) in #821
The original approach did not quite work, and had some conflicts over TMP vs TMPDIR.
I am not really happy with this approach either, but it does seem to work.
> Temporary directory handling

- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
Gazelle reads source files to extract package names, imports, build
tags, and other information. If an error is encountered when reading
this information, Gazelle will log a message and include the file in
the srcs list with as much information as is available. Previously,
Gazelle skipped these files.
Fixes #835
> Gazelle: don't skip files with errors

- README.rst
The old documentation is still there so I can keep moving stuff
over, and is still the one shown by default.
I am switching to rst format because it's much more flexible, especially for when it comes to documenting the functions (table support is way way better)
> Initial shell of new documentation

- go/tools/gazelle/config/BUILD.bazel
- go/tools/gazelle/config/config.go
- go/tools/gazelle/config/directives.go
- go/tools/gazelle/config/directives_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/generator_test.go
Added config.ParseDirectives, which looks for comments of the form
Directives related to the configuration will be applied to a copy of
the current configuration, which is returned. This is passed down
through subdirectories by packages.Walk.
A full list of directives is returned. These may be processed by other
packages, for example gazelle:ignore and gazelle:exclude.
> Gazelle: initial support for generalized directive comments

- go/tools/gazelle/config/constants.go
- go/tools/gazelle/merger/fix.go
- go/tools/gazelle/merger/fix_test.go
This is needed to support proto rules, since they are loaded from a
different file. We must be careful not to override rules with the same
name loaded from a different file (pubref or our own legacy proto
rules).
> Gazelle: support loading symbols from multiple files

- go/core.rst
More for #810
Still need the x_ref section filled in, and some more about embedding and why we do it, but even without that it is strictly better and more accurate than what we have right now.
[skip ci]
[ci skip]
> Document the core rules

- go/private/actions/link.bzl
In the future versions of Bazel += will mutate lists instead of copying them. Because of that lists in the left-hand side can't be frozen, if they are they should be copied in the current mutability scope first.
> Make bzl files compatible with mutating behavior of += on lists

- go/private/repositories.bzl
- go/private/toolchain.bzl
We have standardised on urls with string list for fallback downloads, but go_sdk
still took a single url.
> go_sdk should use urls

- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/cover.bzl
- go/private/actions/library.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/toolchain/toolchains.bzl
All action parameters have default values, so they are forced to be passed by
name.
This will allow us to deprecate them and add new ones safely.
> Preparing actions for future changes

- go/private/actions/binary.bzl
- go/private/go_toolchain.bzl
- go/private/rules/binary.bzl
- go/toolchains.rst
This will allow other rules that also want to build go binaries to do so in a
compatible way with the go_binary rule.
This is progress towards fixing #815
> Write go_binary in terms of a binary action generator

- go/modes.rst
- go/private/actions/binary.bzl
- go/private/actions/link.bzl
- go/private/common.bzl
- go/private/rules/binary.bzl
This builds all modes the same way, adds them all to the GoBinary provider, and
uses features to switch the effective mode of the default executable output.
Builds on top of #876
More work on #815
>  Normalise the mode handling

- go/private/repositories.bzl
- go/toolchain/BUILD.bazel
- go/toolchain/toolchains.bzl
Also updates the default to 1.9.1. This is a security release:
https://groups.google.com/forum/m/#!topic/golang-nuts/sHfMg4gZNps
> toolchain: add 1.8.4 and 1.9.1 releases.

- README.rst
Without this, `gazelle` will generate unbuildable targets when you have `.proto` files.
> Add a reference to the proto rules in the Setup section.

- go/private/go_repository.bzl
- tests/popular_repos/WORKSPACE.in
- tests/popular_repos/popular_repos.bash
This allows configuring what form of protobuf generation to do in a `go_repository` rule.
The main reason that I'd like this feature is that it allows us to use `grpc-gateway` (and, I'm sure, other projects) that have already-generated protobuf code in their repositories.  By default, when using `go_repository`, Gazelle will generate a BUILD file that attempts to build the protobufs; since importing external protobufs isn't yet supported, this fails.
With these changes, it's now possible to manually create the correct `go_repository` rules with `--proto disable`, which allows builds to succeed.
I've created a repository that demonstrates this problem here: https://github.com/andrew-d/rules_go-gateway-demo
If you check it out and run `bazel build //example:greeter`, you'll get the …
> Allow configuring what type of protobuf generation to do in go_repository

- go/tools/gazelle/README.md
The example that follows this sentence shows `# keep`  being used after a dependency label.
> Fix README: before -> after

- go/private/repositories.bzl
- go/workspace.rst
* org_golang_google_grpc is updated to v1.6.0
* org_golang_x_net is updated to master.
* org_golang_x_text is added.
* org_golang_google_genproto is added.
Fixes #892
> Update gRPC-related dependencies

- go/private/go_repository.bzl
This attribute can be used to enable building a depended-on repository
with its own vendored dependencies, instead of workspace dependencies.
This PR is a reduced version of https://github.com/bazelbuild/rules_go/pull/601 that doesn't allow custom vendor prefixes.
> Add `build_external` option to `go_repository`.

- proto/toolchain.bzl
The proto path is not really a file path, it's the path to the proto that was seen when the descriptor file was generated, which is suprisingly hard to work out after the fact.
Fixes #909
> Fix proto path

- go/private/actions/action.bzl
- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/cover.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/go_toolchain.bzl
- go/private/rules/cgo.bzl
- go/private/rules/test.bzl
The go toolchain now provides a helper for running a command with the correct go
environment.
This is a neccesary isolation for future improvements where we no longer hard
code the GOROOT and the GOOS and GOARCH can vary per rule.
> Abstract the environment setting

- go/tools/gazelle/resolve/resolve.go
- go/tools/gazelle/resolve/resolve_test.go
- go/tools/gazelle/rules/generator.go
This is a temporary hack until we have indexed proto import
resolution. It doesn't make sense for protos in vendor to import
protos outside of vendor, and protos can't import anything from
external repositories, so this seems reasonable for now.
Fixes #900
> Gazelle: add //vendor prefix to proto imports in vendor/

- go/private/actions/action.bzl
- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/cover.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/go_toolchain.bzl
- go/private/rules/cgo.bzl
- go/private/rules/test.bzl
I thought about it a bit more and decided it should not even be public for now,
if we decide it should be it's easy to add it back, but for now we just invoke
it directly rather than through the toolchain.
Also bootstrap actions have to work differently.
> Don't expose the env action

- go/tools/gazelle/merger/merger.go
- go/tools/gazelle/merger/merger_test.go
* '# keep' can now be used on an entire rule.
* Gazelle no longer recognizes comments that start with keep but
contain other words.
* '# keep' may be used in an earlier line comment, not just a suffix
comment.
Also:
* mergeLoad and ruleUsed are removed. Load statements are no longer
generated and don't need to be merged. FixLoads takes care of this.
Fixes #884
> Gazelle: don't merge or delete rules with keep comments

- go/private/actions/action.bzl
- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/cover.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/rules/cgo.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/asm.go
- go/tools/builders/cgo.go
- go/tools/builders/compile.go
- go/tools/builders/cover.go
- go/tools/builders/env.go
- go/tools/builders/generate_test_main.go
- go/tools/builders/link.go
- go/tools/builders/pack.go
This pushes the handling of the environment into the helpers rather than
actually setting the environment in skylark.
This will allow us to do things like abs the paths during execution
> Normalise go environment handling

- go/private/actions/compile.bzl
- go/private/go_toolchain.bzl
- go/tools/builders/compile.go
Now uses the @go_sdk//:packages.txt file instead of stating the source tree
Statting the source tree does not work because compile actions are going to
loose visibility into the sdk source soon
Statting the package tree does not work because unsafe has no package
> Change direct deps standard library detection

- go/private/go_toolchain.bzl
This was causing errors when building with custom toolchains.
> Consistently apply visibility to toolchain implementations.

- tests/bazel_tests.bzl
- tests/build_with_1.7.5/BUILD.bazel
- tests/cgo_library_root_dir/BUILD.bazel
- tests/coverage/BUILD.bazel
- tests/custom_go_toolchain/BUILD.bazel
- tests/info/BUILD.bazel
- tests/no_prefix/BUILD.bazel
- tests/package_named_build/BUILD.bazel
- tests/test_filter_test/BUILD.bazel
- tests/test_filter_test_1.7.5/BUILD.bazel
- tests/trans_dep_error/BUILD.bazel
This is so they can be individually processed.
Also rename config=loose to config=fetch so we can understand it's purpose
> Make bazel test targets a list

- tests/bazel_tests.bzl
- tests/coverage/BUILD.bazel
- tests/custom_go_toolchain/BUILD.bazel
We now run them one at a time, but all in the same folder.
This makes them much faster to run in total, and safer.
> Change the bazel test methods

- go/private/tools/gazelle.bzl
This is necessary so that user specified gazelle commands can
specify package_dir arguments
> Gazelle: Put user specified args at end of command line

- go/private/actions/action.bzl
- go/private/actions/asm.bzl
- go/private/actions/binary.bzl
- go/private/actions/compile.bzl
- go/private/actions/cover.bzl
- go/private/actions/library.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/common.bzl
- go/private/go_toolchain.bzl
- go/private/mode.bzl
- go/private/providers.bzl
- go/private/rules/binary.bzl
- go/private/rules/cgo.bzl
- go/private/rules/info.bzl
- go/private/rules/library.bzl
- go/private/rules/stdlib.bzl
- go/private/rules/test.bzl
- go/private/tools/vet.bzl
- proto/def.bzl
This changes the way we handle compilation modes to be a fully strucutred form.
It does not change (yet) the way we pick the mode, but it gives all the actions
a fully structured mode that is capapble of supporting all the combinations.
As a bonus we get full support for msan in this pr.
Fixes #963
> Structured compilation modes

- go/private/actions/archive.bzl
- go/private/actions/library.bzl
- go/private/go_toolchain.bzl
- go/private/providers.bzl
- go/providers.rst
actions.library is now responsible for preparing a go_library, whereas
ations.archive is repsonsible for compiling a library to a linkable archive.
At the moment actions.archive is only called from inside actions.library, and
the behvaiour of the system has not changed.
> Separate GoArchive from GoLibrary

- go/tools/builders/env.go
- tests/reproducible_binary/BUILD.bazel
- tests/reproducible_binary/hello.go
- tests/reproducible_binary/reproducible_binary_test.go
Set GOROOT_FINAL to a constant string ('GOROOT') when
linking. Normally, the actual path to GOROOT is set in linked
binaries, which results in non-reproducible builds. GOROOT_FINAL
provides a constant replacement.
Also, added a test for common reproducibility problems.
Fixes #969
> Strip stdlib paths from binaries

- go/private/actions/binary.bzl
- go/private/actions/library.bzl
- go/private/rules/test.bzl
- go/private/rules/wrappers.bzl
- go/toolchains.rst
This makes the go_test macro build a go_library rule for the package under test,
and then a go_test rule to actually test it.
Makes sure that the library is built the same way it would be for real, and also
cleans up the need for the "synthetic" library parameter
> Use go_library for go_test

- examples/proto/BUILD.bazel
- examples/proto/dep/BUILD.bazel
- examples/proto/embed/BUILD.bazel
- examples/proto/gostyle/BUILD.bazel
- examples/proto/grpc/BUILD.bazel
- examples/proto/lib/BUILD.bazel
* Renamed proto_library rules to follow "foo_proto" convention.
* Renamed go_proto_library and go_grpc_library to follow
"foo_go_proto" convention.
* Ran buildifier on build files in examples/proto.
> examples/proto: fix rule names and run buildifier

- proto/toolchain.bzl
The default protoc for golang emits .pb.go files but some other
compilers create .pb.gw.go. This makes that suffix configurable with a
default of .pb.go.
> Make go_proto_toolchain's suffix configurable

- .travis.yml
This will put us on macOS 10.12 instead of 10.11. I'm mostly changing
this experimentally to see if we can fix some flaky link warnings and
errors.
> Travis CI: use xcode8.3

- go/tools/gazelle/resolve/resolve_external.go
- go/tools/gazelle/resolve/resolve_external_test.go
Fixes https://github.com/bazelbuild/rules_go/issues/998
> Make gopkg.in's resolution logic aware of multiple path levels.

- tests/cgo_pure/BUILD.bazel
- tests/cgo_pure/cgo.c
- tests/cgo_pure/cgo.go
- tests/cgo_pure/cgo_pure_test.go
- tests/cgo_pure/common.go
- tests/cgo_pure/pure.go
This test currently fails, and is marked as manual so it does not run.
Once #1009 is fixed, we will enable the test
> Add unit test for pure and cgo

- go/private/rules/cgo.bzl
clang keeps warning us that we don't need this, so let's remove it.
> cgo: remove -pthread flag on darwin

- go/private/actions/archive.bzl
- go/private/actions/library.bzl
* Duplicated direct deps in emit_archive and srcs in emit_library. The
former change caused #1023, though I don't fully understand why.
* In _go_archive_aspect_impl, direct now contains deps from library,
not library itself.
* In emit_archive, transitive is built using the depset
constructor. We no longer iterate over transitive.
TODO: understand depset performance and optimize all depset use.
Fixes #1023
> Go rules: several small fixes for analysis performance

- .travis.yml
- examples/bindata/bindata.bzl
- go/private/actions/action.bzl
- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/cover.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/rules/cgo.bzl
- go/private/rules/info.bzl
- go/private/rules/test.bzl
- go/private/tools/embed_data.bzl
- proto/toolchain.bzl
- tests/bazel_tests.bzl
All ctx.action.run actions now use ctx.actions.args to build the arguments.
This allows depsets and paths to be lazily expanded, which should help with
performance.
> Using ctx.actions.args

- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/packages/fileinfo_go_test.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/generator_test.go
Walk now calls its callback in all directories it traverses, whether
or not they have buildable code or are outside of the subtrees Gazelle
was asked to update.
This is needed for import path indexing, since we'll need to scan
rules in all directories.
Related #859
> Gazelle: packages.Walk now calls back in all subdirectories

- go/tools/gazelle/gazelle/main.go
This will make it simpler to separate indexing and generating rules
and resolving dependencies into separate phases.
Related #859
> Gazelle: restructure run function in main to prepare for new phasing

- go/private/actions/archive.bzl
- go/private/actions/compile.bzl
- go/private/actions/library.bzl
- go/private/actions/link.bzl
- go/private/providers.bzl
- go/private/rules/library.bzl
- go/private/rules/test.bzl
- go/private/tools/path.bzl
Reducing the information in the transitive parts to the minimum needed.
This is to prevent the pathalogical hashing that happens in complex graphs of
deps.
> Cleaning up transitive provider fields

- go/tools/gazelle/config/constants.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/resolve/BUILD.bazel
- go/tools/gazelle/resolve/resolve.go
- go/tools/gazelle/resolve/resolve_test.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
- go/tools/gazelle/testdata/repo/allcgolib/BUILD.want
- go/tools/gazelle/testdata/repo/bin/BUILD.want
- go/tools/gazelle/testdata/repo/bin_with_tests/BUILD.want
- go/tools/gazelle/testdata/repo/cgolib/BUILD.want
- go/tools/gazelle/testdata/repo/cgolib_with_build_tags/BUILD.want
- go/tools/gazelle/testdata/repo/gen_and_exclude/BUILD.want
- go/tools/gazelle/testdata/repo/lib/BUILD.want
- go/tools/gazelle/testdata/repo/lib/relativeimporter/BUILD.want
- go/tools/gazelle/testdata/repo/platforms/BUILD.want
- go/tools/gazelle/testdata/repo/protos/BUILD.want
- go/tools/gazelle/testdata/repo/service/BUILD.want
- go/tools/gazelle/testdata/repo/tests_import_testdata/BUILD.want
- go/tools/gazelle/testdata/repo/tests_with_testdata/BUILD.want
Previously, rules.Generator performed import resolution (using the
resolve package) as it generated rules. With this change, Generator
now produces a "_gazelle_imports" attribute, which is resolved and
replaced with "deps".
This is necessary since we must be able to index generated rules. We
need to generate and index all rules, then resolve imports to deps in
a separate phase.
Related #859
> Gazelle: extract import resolution out of rules package

- go/tools/gazelle/resolve/resolve.go
Previously, when platform-specific sources import standard libraries,
Gazelle would emit empty select expressions after import
resolution. These are now correctly detected and removed.
> Gazelle: avoid emitting empty select cases

- go/private/BUILD.bazel
- go/private/actions/archive.bzl
- go/private/go_toolchain.bzl
- go/private/mode.bzl
This means we get the debug state correct in the aspect.
We will still get the strip state wrong if it's not the default, as that is not
exposed in the ctx right now.
Fixes #1050
> Use ctx.var instead of toolchain_flags

- go/private/rules/stdlib.bzl
Only map the .a files for the stdlib by default, not the sources
> Making the build faster

- go/private/actions/archive.bzl
- go/private/actions/binary.bzl
- go/private/actions/cover.bzl
- go/private/actions/library.bzl
- go/private/providers.bzl
- go/private/rules/binary.bzl
- go/private/rules/cgo.bzl
- go/private/rules/library.bzl
- go/private/rules/source.bzl
- go/private/rules/test.bzl
- go/providers.rst
- proto/def.bzl
We now do it as late as possible (just before compilation)
We also allow very fine grained control over which packages and source files are
covered.
We also properly obey configuration.coverage_enabled to disable all coverage.
This makes a few interfaces simpler, and is needed for us to handle the pure/cgo
source generation cleanly (which has to come before cover)
> Move coverage

- go/private/go_toolchain.bzl
- go/private/mode.bzl
This should enable cross compilations to not destroy the cache
> Include goos and goarch in the mode

- go/private/actions/archive.bzl
- go/private/providers.bzl
- go/private/rules/aspect.bzl
- go/private/rules/cgo.bzl
- tests/cgo_pure/BUILD.bazel
This adds a filtering mechanism to the new GoSourceList logic and uses it to
switch between the cgo processed sources and the unprocessed original sources
depending on whether the archive is being generated in pure mode.
Fixes #1009
> Select original go sources in pure mode

- go/private/go_repository.bzl
Proxies may be needed for fetching certain repositories. This change allows propagating HTTP{,S}_PROXY to fetch_repo run context. 
This approach follows https://docs.bazel.build/versions/master/external.html#using-proxies to make these env variables available for rules_go.
Fixes #1053
> Propagate HTTP{,S}_PROXY to fetch_repo_env

- go/tools/gazelle/config/constants.go
- go/tools/gazelle/resolve/BUILD.bazel
- go/tools/gazelle/resolve/index.go
- go/tools/gazelle/resolve/label.go
- go/tools/gazelle/resolve/label_test.go
- go/tools/gazelle/resolve/resolve_test.go
(Unit tests will be in the PR to wire this into Resolver).
Related #859
> Gazelle: initial implementation of rule index

- go/private/repositories.bzl
- golang.org/x/tools from 2016-09 to 2017-08-25
- github.com/golang/protobuf from 2016-12 to 2017-11-24
- github.com/google/protobuf from 2017-08 to 2017-11-14
Fixes #1059.
> Update dependent repositories

- examples/bindata/bindata.bzl
- go/extras.rst
- go/private/actions/archive.bzl
- go/private/actions/cover.bzl
- go/private/common.bzl
- go/private/rules/cgo.bzl
- go/private/rules/info.bzl
- go/private/rules/test.bzl
- go/private/tools/embed_data.bzl
- go/private/tools/gazelle.bzl
- go/private/tools/path.bzl
- go/private/tools/vet.bzl
- proto/toolchain.bzl
- tests/bazel_tests.bzl
- tests/go_embed_data/BUILD.bazel
We now direct all file generation through a function that works out an
appropriate name, including the rule label and build mode when needed.
> Be principled about generated file names

- go/core.rst
- go/def.bzl
- go/private/rules/aspect.bzl
- go/private/rules/binary.bzl
- go/private/rules/library.bzl
- go/private/rules/source.bzl
- proto/def.bzl
- tests/race/BUILD.bazel
This also fixes a double embedding case that was broken.
> Finishing go_source rule and using it in a test

- go/tools/gazelle/resolve/resolve.go
Ran into a bug whilst trying to add a check that Gazelle generated build files were up to date in CI. 
Whereby the first run of Gazelle would produce subtly differently output from the second run (creating a new file vs. merging with an existing file).
Tracked it down to the `ForceMultiLine` field of the ListExpr, which was being explicitly set for merged expressions and should have always been set for generated expressions (https://github.com/bazelbuild/rules_go/commit/2fe0791602ae90ab2f2878a80c5fb7cf4529596a)
However, whilst `ForceMultiLine` is set in construct.go (https://github.com/bazelbuild/rules_go/blob/master/go/tools/gazelle/rules/construct.go#L153) the setting was being lost when run through `mapExprStrings`.
This diff means that all fields in expressions run through …
> Prevent AST information loss in mapExprStrings

- go/tools/builders/asm.go
- go/tools/builders/cgo.go
- go/tools/builders/filter.go
- tests/cgo_pure/BUILD.bazel
- tests/cgo_pure/cgo_no_tag.go
This changes our filtering code to understand the implied build tags caused by
import "C" lines in go files that build.Context.Match does not handle.
It also changes our cgo processing code to share the same logic.
> Fix cgo filtering

- go/tools/builders/compile.go
- tests/empty_package/BUILD.bazel
- tests/empty_package/cgo.c
- tests/empty_package/cgo.go
- tests/empty_package/empty_package_test.go
- tests/empty_package/mixed_cgo.go
- tests/empty_package/mixed_pure.go
This used to be a hard failure, but pure cgo libraries need to be silent at
compile time, complaining only if they are linked.
Also add a test for this use case.
> Write an empty package if there are no source files

- go/tools/gazelle/config/config.go
- go/tools/gazelle/config/config_test.go
- go/tools/gazelle/packages/fileinfo.go
- go/tools/gazelle/packages/fileinfo_test.go
- go/tools/gazelle/testdata/repo/platforms/BUILD.want
Previously, rules_go always considered the "cgo" tag to be
true. Gazelle excluded files with !cgo.
Now that we support "pure" builds, the tag may be true or false
depending on the build mode. With this change, Gazelle will ignore the
cgo tag when deciding whether to include a file.
Fixes #1037
> Gazelle: ignore "cgo" tag

- go/private/actions/binary.bzl
- go/private/go_toolchain.bzl
- go/private/repository_tools.bzl
- go/private/rules/binary.bzl
- go/private/rules/stdlib.bzl
- go/private/rules/test.bzl
- go/private/toolchain.bzl
This fixes executable extensions and also separates executables by build mode
for better cache hits.
This requires bazel 0.8 or higher to work
> control executable names

- go/private/actions/asm.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/asm.go
- go/tools/builders/compile.go
- go/tools/builders/env.go
This uses the same solution as we did for compile, abs the path inside the
execution wrapper so that it works on all platforms.
Fixes: #1083
> Trimpath for asm

- go/private/common.bzl
- go/private/repository_tools.bzl
- go/private/toolchain.bzl
- go/tools/builders/env.go
In Bazel0.8 temp directories were fixed, so now we just rely on  them rather
than trying to make our own.
> Clean out tmp handling

- WORKSPACE
- proto/BUILD.bazel
- proto/compiler.bzl
- proto/core.rst
- proto/def.bzl
Instead of using toolchains, we are switching to allowing a per go_proto_library
specification of a compiler.
This allows easy mixing of multiple plugins, and fixes the issues with deps from
toolchains being built in the wrong mode.
Fixes #990
> Change proto compilation system (again)

- go/tools/builders/BUILD.bazel
- go/tools/builders/protoc.go
- proto/compiler.bzl
This version lets us add a much more informative message when the importpaths
are wrong for example:
```
2017/12/04 10:58:59 protoc failed to make all outputs
Got
[bazel-out/k8-fastbuild/bin/examples/proto/dep/useful_go_proto~/examples/proto/dep/useful.pb.go]
Expected
[bazel-out/k8-fastbuild/bin/examples/proto/dep/useful_go_proto~/github.com/bazelbuild/rules_go/examples/proto/dep/useful.pb.go]
Check the go package stanza is github.com/bazelbuild/rules_go/examples/proto/dep
```
> Add a protoc wrapper

- examples/proto/dep/useful.proto
- go/tools/builders/protoc.go
- proto/compiler.bzl
- proto/def.bzl
- tests/proto_ignore_go_package_option/BUILD.bazel
This uses an aspect to collect up the full set of proto imports and what their
go import path should be, and then hands that to the proto compile line.
It then attempts to map the outputs to the expected outputs by basename.
All of this means that the option go_package lines are not needed for a correct
build.
Fixes #1021
Fixes #910
Fixes #173
> Fix go proto library for once and for all

- go/private/toolchain.bzl
> Default to linux_amd64 when uname returns something we don't recognize

- go/private/actions/action.bzl
- go/private/actions/binary.bzl
- go/private/actions/compile.bzl
- go/private/actions/link.bzl
- go/private/common.bzl
- go/private/go_toolchain.bzl
- go/private/mode.bzl
- go/private/rules/aspect.bzl
- go/private/rules/binary.bzl
- go/private/rules/stdlib.bzl
- tests/cross/BUILD.bazel
- tests/cross/cross_test.go
- tests/cross/main.go
This adds goos and goarch attributes to a go_binary
If specified they force the binary to cross compile to the specified
architecture.
It also adds a test that uses this to cross compile and verify the binary was
correctly cross compiled.
This also required multiple rules for the same binary in different modes, which
meant we needed control over the binary file name (so not using the rule name)
Fixes #1104
Fixes #1030
> Allow pure go cross compilation within a single build

- go/tools/gazelle/gazelle/main.go
#1099 introduced a nil pointer exception happening when BUILD files contain a `# keep` note.
> fix(gazelle): fix nil pointer exception

- go/tools/gazelle/config/config.go
- go/tools/gazelle/config/directives.go
- go/tools/gazelle/config/directives_test.go
- go/tools/gazelle/gazelle/fix_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/packages/package.go
- go/tools/gazelle/packages/package_test.go
- go/tools/gazelle/packages/walk.go
- go/tools/gazelle/packages/walk_test.go
- go/tools/gazelle/rules/generator.go
- go/tools/gazelle/rules/generator_test.go
Gazelle now supports '# gazelle:prefix <prefix>' directives in build
files. Such a directive will set the Go importpath prefix for rules in
that directory and in subdirectories.
Prefixes may be empty, but rules cannot be generated in a directory
where the prefix is set to the empty string (an error will be
reported).
Fixes bazelbuild/bazel-gazelle#6
> Gazelle: support prefix directive

- go/tools/gazelle/config/directives.go
- go/tools/gazelle/config/directives_test.go
- go/tools/gazelle/merger/merger_test.go
Previously, directives were restricted to comments before the first
statement, including load statements. This was awkward and prevented
directives from being written contextually.
> Gazelle: allow directives in top-level comments anywhere in file

- go/private/rules/stdlib.bzl
This change adds the flags from cpp fragments as environment variables
to the go install command.
Fixes #985
> Add cpp flags to stdlib rule.

- go/tools/gazelle/gazelle/integration_test.go
- go/tools/gazelle/gazelle/main.go
- go/tools/gazelle/resolve/index.go
- go/tools/gazelle/resolve/resolve_test.go
Rules are deleted after they are merged with empty rules produced by
the generator when they have no attributes other than "name" and
"visibility".
An earlier change split merging into two phases: everything except
"deps", and then "deps".
With this change, both merge phases have a chance to delete
rules. This means that rules that had deps but are now empty will be
deleted.
Fixes bazelbuild/bazel-gazelle#22
> Gazelle: fix deletion of rules with deps

- BUILD.bazel
- README.rst
- Vendoring.md
- go/private/repositories.bzl
- go/private/repository_tools.bzl
- go/private/tools/gazelle.bzl
- go/tools/gazelle/README.rst
- go/tools/wtool/BUILD.bazel
- go/tools/wtool/main.go
- tests/bazel_tests.bzl
- tests/build_with_old_sdk/BUILD.bazel
* go_repository uses new Gazelle. @bazel_gazelle added to
go_rules_dependencies() until go_repository is moved to
@bazel_gazelle or removed.
* gazelle rule uses new Gazelle, but users should migrate to new
gazelle rule in @bazel_gazelle//:def.bzl.
* README.rst and Vendoring.md point to new Gazelle.
* wtool and tests/bazel_tests.bzl also updated. Data dependency
removed from build_with_old_sdk test (why was it there?).
* Old Gazelle left in place for now.
> Use bazel-gazelle instead of go/tools/gazelle everywhere

- .test-bazelrc
- .travis.yml
- tools/bazel.rc
* Move configuration to tools/bazel.rc so that Bazel finds it
automatically.
* Use --config=ci.
* Add --color=no; color makes Travis raw logs unreadable, and the
regular logs are too big.
> Adjust Travis CI config

- go/private/sdk.bzl
> Detect linux_ppc64le as a host platform

- go/def.bzl
- go/private/common.bzl
- go/private/repositories.bzl
When def.bzl is loaded, it will parse native.bazel_version and compare
against a defined minimum.
The implementation for this is borrowed from TensorFlow. k8s also uses
this.
Fixes #1108
> Check Bazel version in def.bzl

- examples/proto/embed/BUILD.bazel
- examples/proto/proto_test.go
- go/private/actions/archive.bzl
- go/private/repositories.bzl
- go/private/rules/aspect.bzl
- go/tools/builders/protoc.go
- proto/BUILD.bazel
- proto/compiler.bzl
- proto/def.bzl
This both adds a go_proto_compiler rule for
github.com/mwitkow/go-proto-validators and also adds support for
go_proto_libraries that are incomplete (not compilable to a package) and also
running multiple compilers to generate a single package (so you can use the
validator alongside any other compiler)
Work for #992 and #1139
> Add github.com/mwitkow/go-proto-validators

- examples/proto/dep/BUILD.bazel
- examples/proto/embed/BUILD.bazel
- examples/proto/gostyle/BUILD.bazel
- examples/proto/grpc/BUILD.bazel
- proto/BUILD.bazel
- tests/proto_ignore_go_package_option/BUILD.bazel
Fixes #944
But we also need gazelle to stop generating the deps now
> Add well known repos to the go_proto_compiler deps

- go/private/common.bzl
- go/private/rules/stdlib.bzl
- tests/bazel_tests.bzl
Set the environment correctly in env_execute on windows
Force standard library compilation into pure mode for now on windows
Add the compiler path to PATH so it can find dll's
Don't try to run mktemp on windows
> Miscelaneous windows fixes

- go/private/context.bzl
- go/private/rules/stdlib.bzl
- go/tools/builders/env.go
- go/tools/builders/pack.go
- Pass along the compiler path, so that the compiler can find its required DLLs and tools.
- Fix the `PATH` setting in `stdlib.bzl`
- `:` is the correct path separator
- Reference `$COMPILER_PATH` after it's been defined
- Convert the windows paths to bash paths (`c:/blah` contains a colon)
- Fix the env creation in `pack.go` and inherit stderr/stdout there as well.
> Windows cgo fixes.

- go/tools/builders/pack.go
The Go .a format does not allow long filenames. This is not a problem
for "go build", since all the names of files in the archive are
hard-coded. In Bazel, we extract .o files from .a archives produced by
cc_library, then append them to the .a archives produced by Go. If .o
files have long names with similar prefixes, multiple entries can end
up with the same name after truncaction. Linkers don't seem to mind
this, but it's weird and is probably going to bite us some day.
This change renames files as they are extracted from the .a archive
produced by cc_library so they have "safe" names (15 or fewer
characters; no conflicts with other files in the archive).
> cgo: change long filenames in cgo archives

- proto/def.bzl
The source name needs to match the one that was used when the proto was
compiled, not the one it would be if mapped into the sandbox by the existing
rule.
There is no direct way to get that in bazel, hence this fix.
Fixes #1193
> Strip external prefix from proto files

- README.rst
As stated here, https://github.com/bazelbuild/rules_go/blob/master/proto/def.bzl#L116, this does nothing.
> remove proto_register_toolchains()

- go/platform/list.bzl
This constraint_value is selected for ppc64le machines, but we have
no ppc64 host toolchain, so it breaks the build.
Related #1186
> Map @bazel_tools//platforms:ppc to GOARCH ppc64le instead of ppc64

- go/private/rules/source.bzl
This gives an easy way to get hold of the source files for a single go library.
Fixes #1176
> Make the source the default file output of go_source

- go/private/rules/wrappers.bzl
- tests/empty_package/BUILD.bazel
With the newer x_def code it is best to let it add the package for you, but it
can only do it if the x_def's are on the library where they belong.
> Fix empty package x_def test

- tests/cgo_pure/BUILD.bazel
- tests/cgo_pure/cgo_pure_test.go
- tests/cgo_pure/common.go
This cleans it up to put the Expect where it belongs in the test
> cgo_pure is also using x_def badly

- README.rst
I noticed this documentation is outdated.
> reflect current method of specifying go version in REAME

- go/tools/builders/generate_test_main.go
- go/tools/builders/protoc.go
- proto/compiler.bzl
- Pass the compiler path along
- Strip .exe from plugin names
- Use the system dependent path separator
> Fix go proto rules for Windows

- go/private/actions/link.bzl
- go/private/context.bzl
- go/private/rules/cgo.bzl
- go/private/rules/stdlib.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/cgo.go
- go/tools/builders/env.go
- proto/compiler.bzl
Lives on the go_context_data rather than the stdlib
Also standardise the way it is collected and handed in to the builders
> Move cc toolchain information

- go/private/common.bzl
- go/private/repositories.bzl
- go/private/skylib/README.rst
- go/private/skylib/lib/collections.bzl
- go/private/skylib/lib/paths.bzl
- go/private/skylib/lib/selects.bzl
- go/private/skylib/lib/unittest.bzl
- go/private/skylib/lib/versions.bzl
This copies all Skylib modules into go/private/skylib/lib, including modules we aren't using yet.
> Update skylib and replace our version check with versions.check

- go/private/context.bzl
- go/private/repositories.bzl
- go/private/rules/stdlib.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/replicate.go
- go/tools/builders/stdlib.go
- tests/bazel_tests.bzl
Now we have cleaned up all the context data cgo handling, we can build the
stdlib using the same builder environment, rather than a nasty && bash command
line.
This also means all the abs path handling will be fixed.
Also removed the _pure_race version that was not legal anyway
> Moving stdlib compilation to a builder

- go/private/actions/archive.bzl
- go/private/actions/compile.bzl
- go/private/context.bzl
- go/private/rules/library.bzl
- go/tools/builders/compile.go
- tests/core/README.rst
- tests/core/cross/BUILD.bazel
- tests/core/importmap/BUILD.bazel
- tests/core/importmap/README.rst
- tests/core/importmap/cross_test.go
- tests/core/importmap/import.go
- tests/core/importmap/lib.go
This adds importmap to go_library
If specified, dependancies will add a --importmap argument to the compilation
line
Fixes #1237
> Support importmap

- go/private/skylib/lib/paths.bzl
Put back the windows abs path fix added in 90a722b8963fb08810b514647b08c958a1753e13 which was clobbered in e12cbbfd0e7dfeb73df4a16ccd562369e2ef8e11
> Fix for windows (again)

- go/private/common.bzl
- go/private/context.bzl
- go/private/providers.bzl
- go/private/rules/test.bzl
- go/private/rules/wrappers.bzl
This removes a rule from the visible graph that the user does not really want to
know about, and also gives the go_test rule more power to control the
compilation of it's library
> Move the test library rule to be go_test internal actions

- go/tools/builders/generate_test_main.go
Passing shard_count=N to a go_test rule will run the test in N process, with
each process sharding the tests in a round-robin fashion.
> Support test sharding

- go/private/actions/compile.bzl
- go/private/actions/link.bzl
- go/private/mode.bzl
- go/private/rules/aspect.bzl
- go/private/rules/binary.bzl
- go/private/rules/test.bzl
- go/toolchains.rst
Related to #1264 and #54 and #539
> Propagate linkmode into the binary rules

- tests/README.rst
- tests/examples/README.rst
- tests/examples/executable_name/BUILD.bazel
- tests/examples/executable_name/README.rst
- tests/examples/executable_name/main.go
- tests/examples/executable_name/name_test.sh
This is a very simple demonstration of how to use a genrule to strip out the
compilation mode.
> Add an example of normalising the executable name

- README.rst
This has been asked here [1]. Might be worth extending the README with.
[1] https://groups.google.com/forum/#!msg/bazel-go-discuss/99cPPeMF59s/LVzfcxzQAwAJ
Let me know what you think.
> Add "how to get golang version" to README FAQ

- go/private/go_repository.bzl
go_repository will no longer pass arguments to Gazelle on the command
line when the corresponding attributes are not explicitly set.
This gives Gazelle more control over the defaults. For example,
Gazelle allows an inferred proto mode to override the default mode,
but not when the default mode is explicitly requested.
Related bazelbuild/bazel-gazelle#104
> go_repository: don't pass default values on the command line

- BUILD.bazel
- go/private/BUILD.sdk.bazel
- go/private/context.bzl
- go/private/repositories.bzl
- go/private/rules/aspect.bzl
- go/private/rules/rule.bzl
- go/private/rules/stdlib.bzl
This removes the hard coded list of standard libraries, and builds it per aspect
being propagated.
This is both cleaner and a pre-requisite for the additional link modes to work.
Related to #1264 and #54 and #539
> Build stdlib from inside the aspect

- go/private/mode.bzl
The value of COMPILATION_MODE on debug builds is "dbg", not "debug".
> Fix debug builds

- extras/bindata.bzl
- go/private/repositories.bzl
The user https://github.com/jteeuwen has disappeared earlier from github.com hosting go-bindata. Meanwhile a hard fork has been put in place by https://github.com/a-urth.
A better maintained fork is available at https://github.com/kevinburke/go-bindata which is referenced by this commit.
#1307
> go-bindata repo change as jteeuwen went AWOL

- BUILD.bazel
- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/cover.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/context.bzl
- go/private/go_toolchain.bzl
- go/private/mode.bzl
- go/private/providers.bzl
- go/private/rules/builders.bzl
- go/private/rules/cgo.bzl
- go/private/rules/rule.bzl
- go/private/rules/test.bzl
- go/toolchain/toolchains.bzl
- go/toolchains.rst
- tests/legacy/custom_go_toolchain/BUILD.bazel
To do this, we extract the builders and pass them separaetly, which means the
normal toolchain always works.
Fixes #1304
> Kill the bootstrap toolchain

- go/private/context.bzl
- go/private/mode.bzl
- go/private/rules/binary.bzl
- go/private/rules/rule.bzl
- tests/legacy/race/BUILD.bazel
Passing bootstrap = True to go_rule now only controls whether _stdlib
and _builders attributes are added. stdlib continues to do this.
The presence or absence of _builders is no longer used to force off
race mode. This prevented stdlib from being built in race mode without
the aspect. Now, go_tool_binary (the only other bootstrap rule) has a
special _race = "off" attribute, which get_mode looks for.
Fixes #1316
> Allow stdlib to be built and depended on with --features=race

- go/private/rules/cgo.bzl
- go/tools/builders/cgo.go
cgo chooses output file names by replacing slashes in source file
names with underscores. This can result in long names for source files
in deeply nested directories: names long enough to exceed length
limits on some file systems (143 on eCryptFS).
With this change, we choose unique stems that are reasonably short
(at most 130 characters). Before invoking cgo, we move filtered source
files into a temporary directory which is passed to cgo via -srcdir to
avoid further mangling.
Fixes #1224
> cgo: avoid generating long file names

- tests/bazel_tests.bzl
This allows bazel_test to be used outside of rules_go (Gazelle).
> bazel_test: fix a relative label used in the bazel_test macro

- go/private/mode.bzl
This change will ensure that unstripped binaries will be built when
the --strip=never. By default, stripped binaries should still
be created, where --compilation_mode defaults to fastbuild and
--strip defaults to sometimes.
> Set strip value to false by default.

- go/tools/bazel/README.md
- go/tools/bazel/bazel.go
- go/tools/bazel/bazel_test.go
This change adds a bunch of Bazel-specific functions to locate the
runfiles trees of built binaries and to find binaries within them.
This extra logic is required to support the recent change in the Go
rules that causes the paths to built Go binaries to not be deterministic
(issue #1239).
> Add functions to locate the runfiles tree of a binary

- go/core.rst
- go/private/actions/archive.bzl
- go/private/actions/compile.bzl
- go/private/context.bzl
- go/private/rules/test.bzl
- go/tools/builders/compile.go
- tests/core/importmap/BUILD.bazel
importpath is the source importpath. Packages can reference other
packages using import declarations with this string.
importmap is the actual importpath. The compiler and linker use this,
and it's visible in stack traces. This only needs to be set when
multiple packages with the same import path would otherwise be linked.
Related #1237 
Fixes #1253
> Reverse sense of importpath and importmap

- go/private/actions/archive.bzl
- go/toolchains.rst
Go 1.10 expects this now.
Related #1237
> compile: set -p to the actual import path, not the source import path

- go/tools/builders/replicate.go
> stdlib: dereference all symlinks before copying a directory

- go/private/tools/overlay_repository.bzl
> overlay repositories: resolve labels before downloading

- extras/bindata.bzl
- go/def.bzl
- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/cover.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/common.bzl
- go/private/context.bzl
- go/private/rules/cgo.bzl
- go/private/rules/stdlib.bzl
- go/tools/builders/asm.go
- go/tools/builders/cgo.go
- go/tools/builders/compile.go
- go/tools/builders/cover.go
- go/tools/builders/env.go
- go/tools/builders/link.go
- go/tools/builders/pack.go
- go/tools/builders/stdlib.go
- proto/BUILD.bazel
This PR is a mix of various changes and fixes we've made on https://github.com/znly/rules_go that I think are upstream-able first. Of course we can split and shrink if you guys want.
Here goes:
36bc7cc: Add runfiles to GoArchiveData and use them in the GoPath
Some binaries (such as https://github.com/golang/mobile/tree/master/cmd/gobind) rely on runtime files to be in the `GOPATH`
060c171: Expose GoPath provider
Title says it all. Useful for custom rules.
f59a93d: Add tags and environment to go_context
Title says it all.
e4a157e: Expose GoSource provider
Title says it all. Useful for custom rules.
7d1d956: Make the Go environment an update of the OS environment
This ensures that the Go environment also has the OS environment keys.
f789bcd: Propagate build tags when `go install`ing …
> Various fixes and changes

- go/def.bzl
- proto/def.bzl
- tests/README.rst
- tests/core/README.rst
- tests/core/go_proto_library_importmap/BUILD.bazel
- tests/core/go_proto_library_importmap/README.rst
- tests/core/go_proto_library_importmap/foo.proto
- tests/core/go_proto_library_importmap/importmap_test.go
Also: bump version number, since this is the first API change
since 0.10
> Add importmap attribute to go_proto_library

- proto/BUILD.bazel
- proto/well_known_types.bzl
- proto/wkt/BUILD.bazel
- proto/wkt/well_known_types.bzl
This PR includes complete support for well-known-types; which are now compiled directly via the official `proto_library` rules over at github.com/google/protobuf.
This has been tested on several repositories of us that make heavy use of both protobuf & grpc; everything appears to be working properly for both golang/protobuf & gogo/protobuf.
Thanks for your time!
cc @steeve
> proto: implemented full end-to-end support for well-known-types

- go/core.rst
Documents the functionality added in https://github.com/bazelbuild/rules_go/pull/1259.
> Document shard_count for go_test, and fix a few broken links

- go/tools/builders/replicate.go
Previously, replicateTree ignored ENOENT errors. This caused a panic
when we later checked whether a path was a directory. This change
removes the check for that error. All replicated paths must exist.
Fixes #1360
> Fix error check in stdlib builder

- .travis.yml
- README.rst
This is needed for cc_import, which was introduced in 0.9.0 (but that
version has problems with Go cross compilation).
Related #1365
> Bump minimum Bazel version to 0.10.0

- go/tools/builders/BUILD.bazel
- go/tools/builders/compile.go
- go/tools/builders/env.go
- go/tools/builders/filter.go
- go/tools/builders/filter_test.go
- go/tools/builders/protoc.go
Go can handle long file names on Windows if they are not relative. This change makes some file paths absolute so that go can handle them. See https://github.com/golang/go/blob/b86e76681366447798c94abb959bb60875bcc856/src/os/path_windows.go#L133.
The `protoc` binary cannot handle long filenames either, so this change generates go protos in the temporary folder and then moves the contents into place.
> Handle Windows long file names in a few more places.

- proto/def.bzl
- tests/core/README.rst
- tests/core/go_proto_library/BUILD.bazel
- tests/core/go_proto_library/README.rst
- tests/core/go_proto_library/embed.proto
- tests/core/go_proto_library/embed_test.go
- tests/core/go_proto_library/extra.go
In go_proto_library rule definition, embed is declared as
"embed": attr.label_list(providers = [GoLibrary]),
This causes the following error when get_imports runs:
(rule 'go_proto_library') doesn't contain declared provider 'GoProtoImports'
> proto: embed doesn't have GoProtoImports provider

- go/private/actions/asm.bzl
- go/private/actions/binary.bzl
- go/private/actions/compile.bzl
- go/private/actions/link.bzl
- go/private/common.bzl
- go/private/context.bzl
- go/private/mode.bzl
- go/private/rules/binary.bzl
- go/private/rules/cgo.bzl
- go/private/rules/stdlib.bzl
- go/private/rules/wrappers.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/ar.go
- go/tools/builders/asm.go
- go/tools/builders/compile.go
- go/tools/builders/env.go
- go/tools/builders/link.go
- go/tools/builders/stdlib.go
- tests/core/c_linkmodes/BUILD.bazel
- tests/core/c_linkmodes/README.rst
- tests/core/c_linkmodes/add.go
- tests/core/c_linkmodes/add_test_archive.c
- tests/core/c_linkmodes/add_test_shared.c
This PR does the following:
- Add `c-shared` and `c-archive` link modes
- Exports a `<name>.cc` target for rapid inclusion as dep for `cc_` rules
- Changes the link builder to know the buildmode and output files
- When using the `c-archive` mode, strips the non-deterministic data from the archive from inside the builder
- This could be reused in the pack builder, not early check suggest `go tool pack` is already deterministic (I may be wrong)
- I could have went through and did it anyway, but it would require factoring `pack` a bit to clean the duplicates with `ar.go`
> Add c-shared and c-archive link modes

- README.rst
- roadmap.rst
* Fix typo in roadmap.rst.
* Add FAQ on cross-compilation to README.rst.
* Rearrange links in README.rst.
[skip ci]
[ci skip]
> Minor documentation fixes

- go/private/actions/archive.bzl
- go/private/context.bzl
- go/private/rules/cgo.bzl
- go/private/rules/test.bzl
- go/providers.rst
go_path currently copies generated cgo and cover files, which is
almost never useful. This changes adds the original source files to a
separate field in GoArchiveData so go_path can consume them.
Also, some other go_path prerequisite changes:
* Don't mark all non-importable libraries as EXPORT_PATH. That should
only be used for synthetic paths.
* Rearrange internal cgo providers to separate generated and
transformed files. Communicate more with providers and less with
output groups.
* Add GoArchive provider to go_test so that go_path can use it.
> Add fields to GoArchiveData needed to rewrite go_path

- go/private/repositories.bzl
- tests/legacy/build_with_old_sdk/BUILD.bazel
This fixes build errors when old versions of Gazelle are used with new
versions of rules_go.
@com_github_bazelbuild_buildtools now points to an old version of the
repository, before several breaking API changes landed. Old versions
of Gazelle depend on this.
@bazel_gazelle now points to a new version of Gazelle that vendors
packages from buildtools, so it won't be broken by this change.
These repositories will be removed when we completely migrate people
to Gazelle's go_repository.
Fixes #1396
> Roll back buildtools, roll forward gazelle

- go/private/actions/link.bzl
- go/providers.rst
- go/tools/builders/link.go
The link wrapper will now print a warning when linking more than one
package with the same package path. This is dangerous, since only one
of the packages will be linked, and the compiler and linker may see
different code.
This will be a warning in 0.11.0 and an error in releases after that.
Also:
* Corrected documentation for direct / transitive members of
GoArchive.
* Marked searchpath and searchpaths members as deprecated. They will
not be needed when we switch to importcfg after dropping Go 1.8.
Related #1327
> Warn when linking archive with the same package path

- go/core.rst
Add information in core.rst on how to use --platforms. Also, caution
against using goos and goarch attributes.
[skip ci]
[ci skip]
> Improve documentation on cross-compilation

- go/private/tools/path.bzl
- go/providers.rst
This is a Bazel File that can be used to get the absolute path of the
output file or directory.
Fixes #1416
> Add GoPath.gopath_file field

- go/private/actions/compile.bzl
- go/tools/builders/filter.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/lib.go
Previously, new files that were generated by cgo (those prefixed with
_cgo, like _cgo_gotypes.go, not those ending with .cgo1.go) were
compiled automatically without any filter for tags or package
names. This broke combined tests with an external component that
depended on library that contained cgo: the _cgo files would get
compiled into the external archive since the compile builder did not
filter them by package name. This caused errors when package names in
source files did not match.
With this change, in analysis, we treat cgo files like regular source
files. In the compile builder, we filter them normally, except we
don't check build constraints (these files would always be excluded,
since they start with '_').
> go_test: fix filtering of _cgo files in external archives

- go/tools/builders/compile.go
- tests/README.rst
- tests/core/README.rst
- tests/core/go_library/BUILD.bazel
- tests/core/go_library/README.rst
- tests/core/go_library/empty_bar.go
- tests/core/go_library/empty_baz.s
- tests/core/go_library/empty_foo.go
Previously, the compile builder wrote 0-byte files when all .go
sources were filtered out. Now it will write a .go file which only
contains a package declaration, then compile that into a trivial
archive file.
This is needed because GoPack reports errors when it attempts to add a
.o file from assembly or cgo.
> compile: write empty archives instead of empty files

- go/tools/builders/generate_test_main.go
- tests/legacy/coverage/BUILD.bazel
This fixes a filename stutter bug introduced in #1407.
Related #1406
Related #1150
> coverage: Only print importpath and base name in log file

- go/private/tools/path.bzl
- tests/core/go_path/cmd/bin/BUILD.bazel
Duplicate files may happen because multiple rules have the same srcs
or data. genrule also treats all its inputs as data, so generated
source files get treated as data.
Previously, duplicate files caused problems in link mode, because
symlinks aren't automatically overwritten. They may have also been an
issue in archive mode. With this change, duplicate files won't be
passed to the go_path builder.
Fixes #1439
> go_path: de-duplicate files in manifest

- README.rst
> Announce release 0.11.0

- go/private/rules/stdlib.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/env.go
- go/tools/builders/filter_buildid.go
- go/tools/builders/stdlib.go
- tests/core/stdlib/BUILD.bazel
- tests/core/stdlib/buildid_test.go
- tests/core/stdlib/reproduce_test.sh
When go install'ing the stdlib, leverage `-toolexec` to remove the `-buildid` flag from `compile` invocations.
To run the test:
```
$ ./tests/core/stdlib/test_reproduce.sh
```
Note that this will expunge the current bazel workspace.
At the moment the everything is reproducible, save for `runtime/cgo` on Linux only. I'm investigating.
Looking at the hexdump diff, it looks like the sandbox path is built into the archive:
```
< 000076e0  2f 62 61 7a 65 6c 2d 73  61 6e 64 62 6f 78 2f 37  |/bazel-sandbox/7|
< 000076f0  33 37 34 35 37 31 39 37  32 36 32 34 30 33 31 36  |3745719726240316|
< 00007700  32 32 2f 65 78 65 63 72  6f 6f 74 2f 69 6f 5f 62  |22/execroot/io_b|
< 00007710  61 7a 65 6c 5f 72 75 6c  65 73 5f 67 6f 2f 62 61  |azel_rules_go/ba|
< 00007720  7a 65 6c 2d 6f 75 74 2f  6b 38 2d 66 …
```
> Make the stdlib reproducible by silencing the build id

- go/core.rst
- go/private/tools/path.bzl
- tests/core/go_path/BUILD.bazel
- tests/core/go_path/go_path_test.go
- tests/core/go_path/pkg/lib/BUILD.bazel
* Data files referenced by go rules are placed in their package
directories with their basenames UNLESS they have testdata in their
path, in which case, the part of the path below testdata/ is
preserved.
* New attribute: include_data. Can be set to False to prevent data
files from appearing in the output. Will be useful for tools when
data files don't matter or cause problems.
Fixes #1449
> go_path: improve handling of data files

- go/tools/builders/env.go
The rebase with the C/C++ split broke it, so fix it back!
> Ensure -fdebug-prefix-map is added to all compiler flags

- tests/core/README.rst
- tests/core/stdlib/BUILD.bazel
- tests/core/stdlib/README.rst
- tests/core/stdlib/buildid_test.go
- tests/core/stdlib/stdlib_files.bzl
> Test that the stdlib rule does not insert build ids in archives

- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/context.bzl
- go/private/rules/cgo.bzl
- go/private/rules/stdlib.bzl
- go/tools/builders/README.rst
- go/tools/builders/asm.go
- go/tools/builders/cgo.go
- go/tools/builders/compile.go
- go/tools/builders/cover.go
- go/tools/builders/env.go
- go/tools/builders/flags.go
- go/tools/builders/generate_test_main.go
- go/tools/builders/go_path.go
- go/tools/builders/info.go
- go/tools/builders/link.go
- go/tools/builders/md5sum.go
- go/tools/builders/pack.go
- go/tools/builders/stdlib.go
Builders now receive inputs through three well-defined channels:
* Builder arguments (before --) are interpreted directly by
builders. These arguments may or may not be passed on to underlying
tools.
* Tool arguments (after --) are passed on to underlying
tools. Builders may add additional arguments before or after these.
* Environment variables are passed on to underlying tools. Builders
will usually not modify these.
Fixes #1456
> Refactor how environment and arguments are passed to builders

- go/private/actions/archive.bzl
- go/private/actions/cover.bzl
- go/private/common.bzl
- go/private/context.bzl
- go/private/providers.bzl
- go/private/rules/test.bzl
- go/private/tools/path.bzl
- go/tools/builders/cover.go
* In coverage output data, source names are formatted using the same
function go_path uses to place sources in GOPATH trees. This may not
correspond to file system locations of sources, but that was already not
the case. This will probably be configurable in the future.
* Fixed logic that determines whether sources are covered.
Fixes #1466, #1467
> Fix coverage bugs

- go/private/actions/cover.bzl
- go/private/actions/link.bzl
- go/private/context.bzl
- go/private/rules/cgo.bzl
- go/providers.rst
- tests/bazel_tests.bzl
- tests/core/coverage/BUILD.bazel
- tests/core/coverage/a_cgo.go
- tests/core/coverage/b_cgo.go
- tests/core/coverage/c_cgo.go
- tests/core/coverage/coverage_test.go
* Instrumentation filter is now applied to cgo sources. Previously,
they were always instrumented if coverage was enabled.
* In coverage data, cgo sources are recorded with their original
basenames instead of the .cgo1.go generated names.
* If the final binary is linked externally, the --coverage flag is
passed to the linker. This fixes link errors with gcov functions
called from instrumented C files.
Also:
* GoSource has a new field: orig_src_map, which is used by coverage to
find original basenames.
Related #1467
> Fix coverage issues around cgo

- go/tools/builders/env.go
This turned out to be more noisy than useful.
> Don't print subcommands with error messages

- go/core.rst
- go/private/context.bzl
- go/private/providers.bzl
- go/private/rules/binary.bzl
- go/private/rules/test.bzl
- go/private/tools/path.bzl
- go/providers.rst
- tests/core/go_path/cmd/bin/BUILD.bazel
- tests/core/go_path/go_path_test.go
- tests/core/go_path/pkg/lib/BUILD.bazel
go_binary and go_test once again support the importpath
attribute. This is used by go_path to place binary and test sources in
the output tree. It may also be used by coverage for reporting sources
in a GOPATH-like format (though test sources are normally excluded
from coverage).
> Add importpath back to go_binary, go_test for use in go_path

- go/private/sdk.bzl
This allows a simple repo to be used on FreeBSD (amd64).  I manually
tested the change on a toy project and bazel build/test both worked as I
expected them to work based upon what I've come to expect on Linux.
Signed-off-by: Robert Escriva <robert@rescrv.net>
> Enable use of FreeBSD SDK

- go/private/repositories.bzl
- proto/wkt/well_known_types.bzl
- third_party/com_github_golang_protobuf/protoc-gen-go/descriptor/BUILD.bazel.in
- third_party/com_github_golang_protobuf/protoc-gen-go/generator/BUILD.bazel.in
- third_party/com_github_golang_protobuf/protoc-gen-go/grpc/BUILD.bazel.in
- third_party/com_github_golang_protobuf/protoc-gen-go/plugin/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/any/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/duration/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/empty/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/struct/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/timestamp/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/wrappers/BUILD.bazel.in
- third_party/org_golang_google_genproto/protobuf/api/BUILD.bazel.in
- third_party/org_golang_google_genproto/protobuf/field_mask/BUILD.bazel.in
- third_party/org_golang_google_genproto/protobuf/ptype/BUILD.bazel.in
- third_party/org_golang_google_genproto/protobuf/source_context/BUILD.bazel.in
There are a significant number of existing rules that depend on WKT
go_library rules directly (for example,
@com_github_golang_protobuf//ptypes/any:go_default_library). Gazelle
resolves now Go imports to @io_bazel_rules_go//proto/wkt, so it's very
easy to end up with conflicting dependencies.
With this change, WKT go_library rules are replaced with aliases
pointing to the equivalent @io_bazel_rules_go//proto/wkt rules.
protoc-gen-go itself depends on descriptor and plugin, so two
bootstrap go_library rules are introduced, visible only to
protoc-gen-go.
Related bazelbuild/bazel-gazelle#159
> Replace WKT go_library rules with aliases to //proto/wkt

- go/private/sdk.bzl
https://dl.google.com/go is now the official base linked from golang.org.
Related #1501
> Change base URL that SDKs are downloaded from

- README.rst
We don't directly use these rules in WORKSPACE or in
go_rules_dependencies, so the boilerplate was the only thing that
needs to be updated.
Fixes #1515
> Use @bazel_tools git_repository and http_archive in boilerplate [skip ci]

- tests/bazel_tests.bzl
This will be used for copying additional data files into the test
directory.
Also: quote more of the strings that go into the generated script.
> Add extra_files attribute to bazel_test

- go/platform/apple.bzl
- go/private/rules/cgo.bzl
we were unable to compile cgo for ios due to 2 issues:
- the ios minimum version should be higher than 6.1 or an error occurs at compile time with the arguments
- when cgo is called pure should always be set to off to setup the environment the right way
> fix ios cross compilation with cgo

- go/private/context.bzl
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/README.rst
- tests/core/go_test/external_importmap_dep.go
- tests/core/go_test/external_importmap_lib.go
- tests/core/go_test/external_importmap_test.go
This change allows Go rules to inherit the importmap attribute from
embedded libraries, the same way the importpath attribute is
inherited. This is particularly important for tests, which rely on an
embedded library under test to set the importpath. Test archives are
imported from the generated testmain, so their importmap does matter.
Fixes #1538
> Inherit importmap from embedded libraries

- go/private/actions/binary.bzl
- go/private/actions/link.bzl
- go/private/common.bzl
- go/private/rules/binary.bzl
- go/private/rules/cgo.bzl
- go/private/rules/test.bzl
- go/private/skylib/README.rst
- go/private/skylib/lib/collections.bzl
- go/private/skylib/lib/dicts.bzl
- go/private/skylib/lib/new_sets.bzl
- go/private/skylib/lib/partial.bzl
- go/private/skylib/lib/paths.bzl
- go/private/skylib/lib/selects.bzl
- go/private/skylib/lib/sets.bzl
- go/private/skylib/lib/shell.bzl
- go/private/skylib/lib/structs.bzl
- go/private/skylib/lib/unittest.bzl
- go/private/skylib/lib/versions.bzl
Fix Skylark deprecation warnings
Fixed several instances of deprecated Skylark behavior
* Used depset.to_list() when iterating
* Avoid depset + operator
* Remove instances of FileType
* Use native.repository_name() and package_name instead of
REPOSITORY_NAME and PACKAGE_NAME.
Also, upgraded vendored Skylib to 0.4.0, since it had some deprecated
stuff.
This change does not fix deprecated uses of args.add. That will
require more work.
Fixes #1534
Fixes #1535
> Fix deprecated skylark

- go/tools/builders/stdlib.go
Needed to fix a regression after https://github.com/bazelbuild/rules_go/pull/1503.
> Use absolute path to the compiler dir in stdlib builder

- go/platform/apple.bzl
Resolves https://github.com/bazelbuild/rules_go/issues/1554.
@steeve Can you also take a look and see if this change works for you?
> Set Xcode configuration only when building objc

- go/tools/builders/asm.go
- go/tools/builders/compile.go
- go/tools/builders/env.go
- go/tools/builders/stdlib.go
This pr can be merge as it, but it s main focus is to discuss a "rules_go" way to fix the problem.
Problem:
cgo flags will sometime be setup with relative path in the environment but Go will make its own sandbox and wont be able to use those path.
Solution:
make all the path absolute in cgo environment variable.
I have no better solution than to embbed shlex in rules_go and use it on the environmnet variables.
> turn relative path to absolute path in environment's cgo's flags

- go/toolchain/toolchains.bzl
This was used to work around a linker bug in Xcode 7.2 and earlier. We
probably don't need to support those old versions anymore.
This enables debugging binaries on macOS.
Fixes #1553
> Remove -s link flag on macOS

- go/private/rules/cgo.bzl
In the process, add `libdl` and `liblog` on Android.
Although I'm not sure `liblog` is *always* needed, since it's the only way to properly log on Android, and GoMobile requires it, add it by default.
I'm aware there is some duplication, but I figure it's better to have them correctly split.
> Add platform specific clinkopts in cgo

- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/rules/stdlib.bzl
Resolves https://github.com/bazelbuild/rules_go/issues/1470.
For rationale, see [discussion on golang-dev](https://groups.google.com/forum/#!topic/golang-dev/lI82ONL2ALg), and the [subsequent patch](https://go-review.googlesource.com/c/go/+/24180).
Tested with https://github.com/siddharthab/rgo-example.
> build c-archive as PIC

- go/private/rules/test.bzl
https://github.com/bazelbuild/rules_go/issues/1577
> Accept goos and goarch in go_test rules, pass to binary rule

- go/private/actions/link.bzl
Signed-off-by: Bin Lu <bin.lu@arm.com>
> Go link tool needs to find gcc on Arm platform

- go/tools/builders/cgo.go
- go/tools/builders/md5sum.go
- go/tools/builders/stdlib.go
- tests/bazel_tests.bzl
- tests/reproducibility/BUILD.bazel
- tests/reproducibility/cgo/BUILD.bazel
- tests/reproducibility/cgo/add.c
- tests/reproducibility/cgo/add.cpp
- tests/reproducibility/cgo/add.h
- tests/reproducibility/cgo/adder.go
- tests/reproducibility/cgo/main.go
- tests/reproducibility/test.sh
Includes a reproducibility test in travis, that will test if stdlib and binaries with cgo are reproducible across multiple builds by the same user. This still does not test if the binaries are reproducible across multiple users or machines. I am relying on tests/legacy/reproducible_binary to check that.
There are two fixes included here:
1. Supplying -fdebug-prefix-map to C compiler invocations for cgo.
2. Stripping temp dir path from generated src files (*.cgo2.c).
Resolves #1518.
Resolves #1547.
> Fixes and tests for reproducibility

- go/private/actions/link.bzl
- go/private/tools/overlay_repository.bzl
- go/tools/builders/env.go
- go/tools/builders/filter_buildid.go
- go/tools/builders/link.go
- go/tools/builders/pack.go
- Don't expect a `cp` command on Windows
- `syscall.Exec` on Windows always returns an error
- Fix path comparison in the linker
- Allow passing deps to the linker in a file rather than the command line, to allow for complex projects with lots of packages
- Fix a race condition in pack.go (doesn't affect other platforms due to sandboxes)
> Windows fixes

- go/private/repositories.bzl
- tests/legacy/examples/proto/grpc/BUILD.bazel
- third_party/com_github_golang_protobuf/protoc-gen-go/descriptor/BUILD.bazel.in
- third_party/com_github_golang_protobuf/protoc-gen-go/generator/BUILD.bazel.in
- third_party/com_github_golang_protobuf/protoc-gen-go/grpc/BUILD.bazel.in
- third_party/com_github_golang_protobuf/protoc-gen-go/plugin/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/any/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/duration/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/empty/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/struct/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/timestamp/BUILD.bazel.in
- third_party/com_github_golang_protobuf/ptypes/wrappers/BUILD.bazel.in
- third_party/org_golang_google_genproto/protobuf/api/BUILD.bazel.in
- third_party/org_golang_google_genproto/protobuf/field_mask/BUILD.bazel.in
- third_party/org_golang_google_genproto/protobuf/ptype/BUILD.bazel.in
- third_party/org_golang_google_genproto/protobuf/source_context/BUILD.bazel.in
This reverts commit ca213b3006c8eed6b3f1ea649cab36b817901b46.
Also: Update legacy example to point to //proto/wkt to avoid conflict
Related #1548
> Revert "Replace WKT go_library rules with aliases to //proto/wkt (#1498)"

- go/tools/builders/generate_test_main.go
The old code chdirs to a path relative from the
$TEST_SRCDIR/$TEST_WORKSPACE. This creates a problem when a unittest tries to
fork & exec itself to create a clone of itself. The cwd of the forked subprocess
is already at $TEST_SRCDIR/$TEST_WORKSPACE/go/src/something, and its main()
tries to chdir to go/src/something again and crashes.
A unittest trying to fork & execitself might sound strange, but Mapreduce-style
application does this regularly.
> Change the test main function to chdir using an abs path.

- go/private/common.bzl
- go/private/rules/cgo.bzl
- go/private/sdk.bzl
- go/tools/builders/filter_buildid.go
- tests/core/c_linkmodes/BUILD.bazel
- tests/core/c_linkmodes/skip.c
- tests/legacy/go_embed_data/BUILD.bazel
* Tag cgo c_archive and c_shared targets "manual". They won't build on
Windows.
* Add common functions for converting file and executable paths to
Windows friendly format.
* Fix a couple targets that wouldn't build.
> Misc fixes for Windows

- go/tools/bazel_benchmark/BUILD.bazel.in
- go/tools/bazel_benchmark/WORKSPACE.in
- go/tools/bazel_benchmark/bazel_benchmark.go
- go/tools/bazel_benchmark/hello.go.in
bazel_benchmark checks out rules_go to a temporary directory, creates
a temporary workspace, measures the time it takes to build various
targets, then appends the times to a .csv file.
This will probably be much more sophisticated in the future, but it's
good to have something basic now.
> Add a primitive benchmark

- go/tools/bazel_benchmark/BUILD.bazel
- go/tools/bazel_benchmark/bazel_benchmark.go
- go/tools/bazel_benchmark/bazel_benchmark.sh
bazel_benchmark.sh is now responsible for cloning rules_go at master
into a temp directory. This script can be copied to a bin directory
and run with a timer. The rest of the bazel_benchmark.go logic will
run at the tip of master.
Also: record Bazel version in the output file.
> go/tools/bazel_benchmark: extract some logic into bash script

- go/private/repositories.bzl
The googleapis repository seems to be of such a size that it takes a
long time to clone on a link with lower bandwidth. So long, in fact,
that it causes timeouts in my case.
> Speed up downloading of @go_googleapis by using http_archive.

- extras/bindata.bzl
- extras/embed_data.bzl
- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/context.bzl
- go/private/rules/cgo.bzl
- go/private/rules/info.bzl
- go/private/rules/stdlib.bzl
- go/private/rules/test.bzl
- proto/compiler.bzl
- tests/bazel_tests.bzl
Some of the parameters of `args.add()` are deprecated - see https://docs.bazel.build/versions/master/skylark/lib/Args.html#add. This PR changes their usage to non-deprecated analogs.
This passes `bazel test //...` on my machine, I haven't done any additional changes.
This is my first rules_go PR, let me know if something is not right.
> Use add_all(), add_joined() instead of deprecated functionality of add()

- go/def.bzl
- go/private/providers.bzl
- go/private/rules/sdk.bzl
go_sdk is a new rule that gathers information about an SDK and returns
a GoSDK provider which will get wired into the toolchain.
package_list is a new rule that generates a list of importable
packages from the sources in the SDK (previously, we invoked go list,
which is slower).
> Add go_sdk rule and GoSDK provider

- go/def.bzl
- go/private/BUILD.sdk.bazel
- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/actions/cover.bzl
- go/private/actions/link.bzl
- go/private/actions/pack.bzl
- go/private/context.bzl
- go/private/go_toolchain.bzl
- go/private/providers.bzl
- go/private/rules/cgo.bzl
- go/private/rules/info.bzl
- go/private/rules/sdk.bzl
- go/private/rules/stdlib.bzl
- go/private/sdk.bzl
- go/private/tools/vet.bzl
- go/toolchain/BUILD.bazel
- go/toolchain/toolchains.bzl
- tests/bazel_tests.bzl
- tests/core/stdlib/stdlib_files.bzl
- tests/legacy/custom_go_toolchain/BUILD.bazel
* go_toolchain has a new mandatory attribute, "sdk", which be
something that provides GoSDK.
* go_host_sdk, go_local_sdk, and go_download_sdk are now macros that
wrap the old rules. Each rule declares toolchains in its BUILD.bazel
file that work on the host architecture. The macro calls
register_toolchains with these.
* go_register_toolchains no longer calls register_toolchains, but it
will an SDK rule if "go_sdk" isn't defined. This is a step toward
allowing multiple SDKs to support multiple execution platforms.
* Action inputs are narrowed to use go.sdk.tools and go.stdlib.libs
rather than larger sets of files.
> Wire sdk toolchain

- go/private/rules/sdk.bzl
- go/toolchains.rst
This will eventually be removed when old versions of Gazelle are no
longer supported and nothing depends on the file by name.
If not provided as an input, go_sdk will generate the file itself.
> Make go_sdk's package_list optional

- .travis.yml
Also, remove logic in .travis.yml for downloading Bazel at HEAD. We're
not doing that anymore.
> Update minimum version of Bazel for Travis CI to 0.16.0

- go/private/actions/link.bzl
- go/private/context.bzl
- go/tools/builders/asm.go
- go/tools/builders/cgo.go
- go/tools/builders/compile.go
- go/tools/builders/cover.go
- go/tools/builders/env.go
- go/tools/builders/generate_test_main.go
- go/tools/builders/info.go
- go/tools/builders/link.go
- go/tools/builders/pack.go
- go/tools/builders/protoc.go
- go/tools/builders/stdlib.go
Multiple param files are now supported as well.
Related #1637
> Actions that use go.args may now use param files automatically

- go/private/repositories.bzl
- third_party/go_googleapis/google/firestore/admin/v1beta2/BUILD.bazel.in
- third_party/manifest.bzl
* `org_golang_google_genproto` to master as of 2018-08-13
* `go_googleapis` to master as of 2018-08-13
Fixes #1656
> Update genproto dependencies

- go/private/rules/binary.bzl
- go/private/rules/library.bzl
- go/private/rules/source.bzl
- go/private/rules/test.bzl
- go/private/tools/path.bzl
- go/private/tools/vet.bzl
The "data" configuration has been deprecated for a while and has no
effect.
> Remove 'cfg = "data"' from all attributes

- go/private/rules/binary.bzl
This removes the need for --incompatible_disallow_dict_plus
> Remove uses of deprecated dictionary concatenation

- go/tools/builders/compile.go
- go/tools/builders/link.go
This is a follow-up to https://github.com/bazelbuild/rules_go/pull/1647. `GOROOT` is still injected as relative path, which is considered bad practice anyway elsewhere [1]. This patch converts the importmap paths to absolute paths even if `GOROOT` is relative. (Will this break anything on any platform? E. g. OSX?)
[1] https://github.com/golang/go/issues/26917#issuecomment-412814805
> Force absolute paths in builders

- go/checks.rst
- go/tools/builders/checker_main.go
- go/tools/builders/generate_checker_main.go
- tests/core/checks/custom/BUILD.bazel
- tests/core/checks/custom/README.rst
- tests/core/checks/custom/config.json
- tests/core/checks/custom/foo_func.go
- tests/core/checks/custom/has_errors.go
- tests/core/checks/custom/import_fmt.go
- tests/core/checks/custom/return_bool/return_bool.go
Remove the option for checks to emit only warning messages. Checks that
are included in the go_checker target now fail builds. The only way to
change this behavior is to remove the check from go_checker so that it
does not run at compile time.
> Do not allow check warnings

- third_party/org_golang_google_grpc/internal/channelz/BUILD.bazel.in
Add `android` as unix when building `org_golang_x_sys`.
> third_party/org_golang_google_grpc: fix android build

- go/private/actions/link.bzl
- go/private/rules/cgo.bzl
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/README.rst
- tests/core/cgo/bar.cc
- tests/core/cgo/cc_libs_darwin_test.go
- tests/core/cgo/cc_libs_linux_test.go
- tests/core/cgo/foo.c
- tests/core/cgo/main.go
This avoids an unnecessary run-time dependency on libstdc++.so, which
may not be present in container environments.
go build only adds this dependency if C++ code is included in the
build. We now filter out this dependency from the cc toolchain flags
unless we have C++/ObjC source or we have a dependency on a cc_library
or objc_library.
Fixes #1681
Related bazelbuild/bazel#2954
> Filter out -lstdc++ for targets with no C++ code

- tests/core/go_path/BUILD.bazel
This is failing for Bazel at master.
Related #1699
> Disable //tests/core/go_path:go_path_test

- go/private/skylib/lib/versions.bzl
Users that build bazel from source (perhaps because they want to pin the bazel version via a submodule or other means) will not have a bazel version present ever.
This means every single bazel command will print out the following debug lines, which are mostly noise, since those users are probably aware they have built bazel from source. 
>DEBUG: /private/var/tmp/_bazel_jgavris/c1e7067b81f8f6fa16df07b65cd39d9c/external/io_bazel_rules_go/go/private/skylib/lib/versions.bzl:98:7:
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /private/var/tmp/_bazel_jgavris/c1e7067b81f8f6fa16df07b65cd39d9c/external/io_bazel_rules_go/go/private/skylib/lib/versions.bzl:99:7: Make sure that you are running at least Bazel 0.8.0.
> Remove noisy debug log for missing version

- go/core.rst
- tests/core/go_path/BUILD.bazel
- tests/core/go_path/go_path_test.go
go_path_test no longer checks whether files are symbolic links or
regular files. Bazel may provide either.
This is now noted in the documentation for go_path.
We will keep both modes for now to avoid breaking anyone depending on
the API. There is a difference in behavior with file / tree artifacts.
Fixes #1699
> Re-enable go_path_test and document copy behavior

- go/private/repositories.bzl
- go/private/skylib/lib/versions.bzl
Reverted #1703. This should not have modified the vendored versions.bzl.
We now just avoid calling `versions.check` if no version is defined.
Related #1711.
> Don't check bazel version on development builds

- go/private/actions/asm.bzl
- go/private/actions/compile.bzl
- go/private/mode.bzl
- go/private/rules/stdlib.bzl
Go 1.11 has its own build cache, which is enabled by default. Disable it because it doesn't make sense with bazel. See https://golang.org/cmd/go/#hdr-Build_and_test_caching
Also, only enable `-shared`/`-dynlink` on selected platforms, mimicking what `go build` does.
> Disable GOCACHE and only enable -shared/-dynlink on selected platforms

- go/tools/builders/BUILD.bazel
- proto/BUILD.bazel
- proto/wkt/BUILD.bazel
- tests/BUILD.bazel
//tests:all_rules_md5 now includes .bzl files in //proto, //proto/wkt,
and .go files in //go/tools/builders.
all_rules_md5 is an implicit data dependency of bazel_test
rules. These tests verify the rules_go implementation in an alternate
workspace, so their dependencies on .bzl files in the current
workspace is implicit. When all_rules_md5 changes, it forces them to
run again.
> Add more explicit dependencies for bazel_test

- go/private/actions/link.bzl
This makes `darwin/arm` link properly, somehow.
I haven't filtered on `darwin/arm` only because maybe some other platforms are impacted, so just in case.
Fixes #1693.
> Add fake buildid when linking

- go/private/context.bzl
- go/private/providers.bzl
- go/private/rules/aspect.bzl
go_binary and go_test apply an aspect for cross-compilation. If they
depend on other go_bianry and go_test targets, GoAspectProviders may
be emitted multiple times, which causes Bazel to report a very opaque
message. With this change, we warn about this situation before the
aspect runs.
Also: stop attaching GoAspectProviders in the default configuration.
Fixes #1733
> Warn against depending on / embedding executables

- go/extras.rst
There is a small gotcha when reading the extras.rst doc: boolean values are not capitalized as they are in Skylark. This PR capitalizes those values as they would be used in the rules.
> Capitalize bool values in extras docs

- go/private/repositories.bzl
- third_party/go_googleapis-fix.patch
- third_party/go_googleapis-gazelle.patch
- third_party/org_golang_google_genproto-gazelle.patch
* Both repositories should now be generated from googleapis at the
same commit.
* Removed the build file for @go_googleapis//google/api/experimental
and incorporated the protos into
@go_googleapis//google/api:api_proto and api_go_proto. Ideally,
there should be an alias for the old targets, but proto_library
requires proto srcs to be in the same Bazel package.
> Update and fix go_googleapis and org_golang_google_genproto

- go/platform/apple.bzl
- go/private/context.bzl
- tests/bazel_tests.bzl
ctx.fragments.cpp is deprecated.
This doesn't fully get us away from deprecated APIs. We should use
cc_common for flags and C/C++ compilation command lines.
Related #1744
> Use find_cpp_toolchain instead of ctx.fragments.cpp

- README.rst
Replaced with reference to //tests/core/cross.
Thanks to @DarienRaymond for pointing this out in #1751.
> Fix dead reference to reproducible_binary in README [skip ci]

- go/private/rules/binary.bzl
- go/private/rules/library.bzl
- go/private/rules/test.bzl
- proto/def.bzl
- tests/core/README.rst
- tests/core/output_groups/BUILD.bazel
- tests/core/output_groups/README.rst
- tests/core/output_groups/bin.go
- tests/core/output_groups/compilation_outputs_test.go
- tests/core/output_groups/lib.go
- tests/core/output_groups/lib_test.go
This behavior matches the native C++ and Java rules[1] and allows users
to easily verify a target compiles without invoking the linker
unnecessarily.
[1]: https://github.com/bazelbuild/bazel/commit/1dcd8f0f12bb582cc449381f8245f943121031fb
> Add compiled archives to compilation_outputs group

- go/tools/builders/pack.go
I recently discovered that targets requiring the GoPack builder have a relative path problem on Windows, too (recall #1647). Using absolute paths here fixes the build for targets with a `gonum.org/v1/gonum` dependency.
https://github.com/Xjs/bazel-go-pack-demo is a minimal example to reproduce.
> Use absolute paths to make GoPack work on Windows

- go/private/sdk.bzl
- go/toolchains.rst
This is needed to support unknown platforms and users that are
executing on RBE when the host and execution platforms are different.
Fixes #1760
> go_download_sdk: allow goos, goarch to be specified explicitly

- go/private/actions/cover.bzl
In kubernetes, we get a build failure when running `bazel coverage`:
```console
GoCompile: error running subcommand: exit status 2
pkg/kubelet/container/testing/os.go:143: Cover_os redeclared in this block
previous declaration during import "k8s.io/kubernetes/pkg/kubelet/container"
pkg/kubelet/container/testing/runtime_mock.go:32: Cover_os redeclared during import "k8s.io/kubernetes/pkg/kubelet/container"
previous declaration at pkg/kubelet/container/testing/os.go:143
```
The root cause appears to be at least partially self-inflicted; we have a `pkg/kubelet/container/os.go` file (in package `container`), and a `pkg/kubelet/container/testing/os.go` file (in package `testing`).
The existing `rules_go` coverage generator creates a `Cover_os` variable in each package, which would be unique, …
> Use a more unique name for the cover variable

- go/private/rules/test.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/lcov_merger.sh
When collecting coverage, Bazel now expects test rules to have an
implicit "$lcov_merger" or "_lcov_merger" attribute that points to a
binary to be run by the test driver script.
This change adds a dummy _lcov_merger attribute to go_test. The script
does nothing for now.
Related bazelbuild/bazel#6293
> lcov_merger: workaround for Bazel 0.18.0 coverage

- .travis.yml
- go/platform/apple.bzl
- go/private/actions/link.bzl
- go/private/context.bzl
- go/private/mode.bzl
- go/private/rules/cgo.bzl
- go/private/rules/stdlib.bzl
- go/tools/builders/env.go
- proto/compiler.bzl
Previously, the internal go_context_data read C/C++ paths and options
from the CcToolchainInfo provider. Most of the fields in this provider
come from CROSSTOOL and will be removed in Bazel 0.20.0 (see
https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disable-legacy-c-toolchain-api).
This change migrates us to use the new cc_common module. This change
is intended to be a quick fix to be backported to old release
branches, so no architectural changes are made.
Fixes #1744
Related #1742
> Migrate to cc_common for collecting C/C++ paths and options

- go/private/context.bzl
- tests/README.rst
- tests/core/README.rst
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/README.rst
- tests/core/go_test/data_test.go
- tests/core/go_test/data_test_dep.go
- tests/core/go_test/data_test_embed.go
- tests/core/nogo/README.rst
ctx.runfiles(collect_data = True) collects default runfiles from srcs,
deps, and data. When srcs comes from a filegroup or genrule, the
source files themselves are included in the runfiles, which is
surprising for users.
With this change, we gather data runfiles only from data and deps.
Fixes #1761
> Exclude srcs and their runfiles from Go rule runfiles

- go/private/rules/wrappers.bzl
The print() primitive should not take strings with newlines at the beginning
nor at the end: messages are automatically prefixed with their severity and
suffixed with the necessary newline.
> Remove spurious newlines from print messages

- go/platform/list.bzl
> Allow specifying the `js_wasm` toolchain.

- go/private/context.bzl
- tests/core/race/BUILD.bazel
If we do an internal link, we may have undefined references to
coverage functions.
Fixes #1801
> Don't compile cgo code with --coverage

- tests/legacy/examples/cgo/cc_dependency/BUILD.bazel
This change is needed because shared library (.so) is not built by default on Windows. Using `output_group` in `filegroup` will explicitly tell Bazel to build it.
@jayconrod 
Related https://github.com/bazelbuild/rules_go/pull/1791
> Windows: use filegroup instead of genrule to get .so file from a cc_library

- third_party/com_github_golang_protobuf-extras.patch
It's important for go_default_library not to depend on any
go_proto_library because protoc-gen-go depends on it. However, other
binaries may need to depend on generator and go_proto_library targets,
and this helps them avoid conflicts.
Fixes #1817
> Add @com_github_golang_protobuf//protoc-gen-go/generator:go_default_library_gen

- README.rst
Gazelle section has WORKSPACE commands that provide for version 0.16.1 with a hash for 0.16.2, which doesn't work. Just changed it to 0.16.2 for consistency. Tried on my computer, and it works.
> Fix mismatching version and hash in gazelle sec

- go/def.bzl
- go/private/actions/archive.bzl
- go/private/actions/asm.bzl
- go/private/actions/cover.bzl
- go/private/actions/link.bzl
- go/private/common.bzl
- go/private/context.bzl
- go/private/go_toolchain.bzl
- go/private/rules/aspect.bzl
- go/private/rules/cgo.bzl
- go/private/rules/nogo.bzl
- proto/compiler.bzl
- proto/def.bzl
- tests/bazel_tests.bzl
In the future, Bazel will not automatically re-export the symbols that come from a load. This PR is fixing that.
This diff is large, because I also reformatted all files with Buildifier. This will allow you to use Buildifier automated fixes in the future.
Progress towards #1829
> Explicitly reexport some symbols, reformat the .bzl files with Buildifier

- go/private/sdk.bzl
For at least debian, uname -m on ppc64le returns "unknown". There was
already logic to deal with that for ARM. Using the same for ppc64le.
Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>
> fix sdk download for ppc64le

- go/private/rules/cgo.bzl
- proto/def.bzl
This PR modifies `go_proto_library` to return the legacy-style provider that the IntelliJ plugin [currently expects](https://github.com/bazelbuild/intellij/blob/54f5b0709e9a74d4cd1c5a0fdcd4f7cf8c76500d/aspect/intellij_info_impl.bzl#L217-L223).
> Expose proto generated sources via OutputGroup

- go/private/actions/archive.bzl
- go/private/actions/compile.bzl
- go/tools/builders/compile.go
- tests/core/nogo/vet/BUILD.bazel
- tests/core/nogo/vet/no_errors.go
The compile builder and nogo assume the .x file to be written is in a
location based on the .a file, but analysis generates an .x output
path based on the import path, and the .a output path may vary
slightly from that.
Rather than trying to fix this assumptions, this change makes the
compile builder accept an -x parameter with the output path.
A logical extension of this would be to make paths explicit for .x
files of all dependencies. However, it would be better to get rid of
.x files altogether and store the data in a new section within .a
files instead (#1847).
Fixes #1846
> nogo: pass explicit path to .x output file

- go/private/mode.bzl
- tests/core/go_binary/BUILD.bazel
- tests/core/go_binary/README.rst
- tests/core/go_binary/broken_cgo.go
Currently, the `goos` attribute on a go_binary rule is ignored when determining whether to force pure mode. The only check being performed right now is using the toolchain target.
This change forces pure mode for a binary when the toolchain target is the same as the host, but the specific binary is cross-compiled using the goos attribute. All other cases remain the same.
> Pure mode when using the goos attribute

- README.rst
> fix README.rst indentation for gazelle

- go/nogo.rst
The findings variable isn't used and the required type doesn't seem to exist in the package, so I've deleted that line of the sample code.
> remove non-existent Finding from nogo sample

- proto/compiler.bzl
- proto/def.bzl
- tests/core/go_proto_library/BUILD.bazel
- tests/core/go_proto_library/README.rst
- tests/core/go_proto_library/adjusted_a.proto
- tests/core/go_proto_library/adjusted_b.proto
- tests/core/go_proto_library/adjusted_c.proto
- tests/core/go_proto_library/adjusted_import_test.go
In Bazel 0.22.0, proto_library will support import_prefix and
strip_import_prefix attributes. This change allows targets with these
attributes to be compiled with go_proto_library.
When invoking protoc, we pass in paths to binary proto descriptors
(the output of proto_library) and a list of .proto names. protoc loads
the descriptors corresponding to the names we pass in. Those names
must match the adjusted import paths for the .proto files.
Fixes #1851
> go_proto_library: support adjusted import prefixes

- go/private/repositories.bzl
- third_party/org_golang_google_grpc-crosscompile.patch
> Fix Windows & Darwin cross-compilation to Linux when using gRPC

- go/private/sdk.bzl
Workaround for bazelbuild/bazel#7055
Fixes #1880
> go_download_sdk: workaround bug in ctx.download_and_extract

- proto/compiler.bzl
- proto/core.rst
- proto/def.bzl
- tests/core/go_proto_library/BUILD.bazel
- tests/core/go_proto_library/protos_a.proto
- tests/core/go_proto_library/protos_b.proto
- tests/core/go_proto_library/protos_test.go
Add `protos` argument to `go_proto_library` (same as the existing `proto` argument, but supports multiple protos).
`go_proto_compile` changes one of the arguments from `proto` to `protos`, which is considered Ok (even though this is a technically public API there is no detected usages of the method anywhere else on github).
Implements https://github.com/bazelbuild/rules_go/issues/1856
> go_proto_library: support multiple proto dependencies

- go/def.bzl
- go/nogo.rst
- go/private/rules/nogo.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/compile.go
- go/tools/builders/generate_nogo_main.go
- go/tools/builders/nogo_main.go
- tests/core/nogo/vet/BUILD.bazel
nogo no longer invokes vet at all. Setting 'vet = True' is handled by
a wrapper, which adds the equivalent libraries from
@org_golang_x_tools//go/analysis/passes.
'vet = True' was originally needed before the vet analyses had been
migrated to the analysis framework. There is no need for it anymore,
and the command line interface for vet is changing in Go 1.12.
Updates #1896
Fixes #1800
> nogo: translate 'vet = True' into appropriate deps

- go/private/actions/archive.bzl
- go/private/actions/compile.bzl
- go/tools/builders/compile.go
Go 1.12 requires the assembler to generate a symabis file, which is
passed to the compiler. The compile action will now do this when there
are assembly sources.
In the future, we'll combine GoCompile, GoAsm, and other actions into
a single GoCompile action per package. Because of this plan,
generating the symabis file is not a separate action.
Updates #1896
> go/tool/compile: generate symabis for assembly

- go/private/rules/cgo.bzl
- go/tools/builders/pack.go
The .a format limits file names to 16 characters. There are various
extensions to this format which support longer names, but Go doesn't
recognize them and generally doesn't need them. Before Go 1.12, the
linker passed all extra files (other than the compiled Go code and the
export data) to the external link.
In Go 1.12, the linker only passes on .o files. The GoPack action
simply truncated long file names, which meant .o files were sometimes
ignored. GoPack will now preserve file extensions.
Updates #1896
> go/tools/builders/pack: preserve file extensions

- go/tools/builders/stdlib.go
A GOCACHE directory is required by 'go build', starting in Go
1.12. Normally the location is inferred from HOME or other environment
variables, but there's aren't set in the Bazel sandbox. To build the
standard library, we create a temporary cache that is deleted at the
end of the GoStdLib action.
Updates #1896
> go/tools/builders/stdlib: set temporary GOCACHE

- tests/reproducibility/reproducible_binary_test.go
It appears that Bazel CI is now using the username "bazel" when
running tests. This test verifies the current username does not appear
in its binary. "bazel" should be allowed though.
> Skip part of //tests/reproducibility:go_default_test in BuildKite

- WORKSPACE
Needed for go_repository that sets GOCACHE correctly, which is needed
for Go 1.12.
Updates #1896
> Update to newer version of Gazelle for testing

- tests/core/cgo/BUILD.bazel
- tests/legacy/examples/cgo/cc_dependency/BUILD.bazel
* go_proto_library now relies on the undocumented ProtoInfo instead of
the .proto field.
* go_proto_library now uses to_list() when iterating ProtoInfo
depsets.
* A test in tests/core/cgo now uses cc_binary to generate shared
libraries.
Updates #1888
> Fix some incompatibilities in Bazel 0.22.0

- go/private/rules/cgo.bzl
The cc_import attribute alwayslink should only be set when a static
library is provided. We should only set it when linkmode =
"c-archive".
Fixes #1909
> Stop passing alwayslink=1 with linkmode="c-shared"

- proto/BUILD.bazel
- tests/core/go_proto_library/BUILD.bazel
- tests/core/go_proto_library/README.rst
- tests/core/go_proto_library/gofast_grpc_test.go
- tests/core/go_proto_library/gofast_test.go
- tests/core/go_proto_library/gogofast_grpc_test.go
- tests/core/go_proto_library/gogofast_test.go
- tests/core/go_proto_library/grpc.proto
Unlike the other plugins, `gofast` does not generate `.pb.go` files that depend on `gogo`; instead, they depend on the standard `github.com/golang/protobuf`.
> Fix `gofast` `go_proto_compiler` dependencies.

- go/deps.bzl
This is a transient commit. We load @bazel_gazelle in tests, and its
WORKSPACE file needs to be valid. It needs to be able to refer to
definitions through deps.bzl before we break the symbols in def.bzl.
Updates #1924
> Add deps.bzl with compatibility definitions from def.bzl [skip ci]

- WORKSPACE
- go/def.bzl
- go/deps.bzl
- tests/bazel_tests.bzl
- tests/legacy/custom_go_toolchain/BUILD.bazel
All definitions used in WORKSPACE must now be loaded from deps.bzl
instead of def.bzl.
Files loaded from def.bzl (but not deps.bzl) may refer to repositories
declared in go_rules_dependencies() and go_register_toolchains().
This will allow us to set up a private compatibility repository, which
will have different implementations depending on the Bazel
version. That will allow us to support a wider range of Bazel
versions. We'll also be able to reference Skylib directly instead of
vendoring it.
Fixes #1924
> Move repository definitions from //go:def.bzl to //go:deps.bzl

- proto/compiler.bzl
- tests/core/go_proto_library/BUILD.bazel
- tests/core/go_proto_library/README.rst
- tests/core/go_proto_library/no_go_package.proto
- tests/core/go_proto_library/proto_package_test.go
Fixes #1596
`import_path_option` is a `go_proto_compiler` attribute with the following definition:
When true, the `importpath` attribute from `go_proto_library` rules using this compiler will be passed to the compiler on the command line as `--option import_path={}`.
When a proto file does not contain `option go_package`, go_protobuf and gogoprotobuf use the `import_path` parameter to determine the pb.go file's package name. When the `import_path` parameter is not passed in, the proto package name is used to determine the pb.go file's package name.
With the lack of `option go_package`, it appears to be the [expected behaviour](https://developers.google.com/protocol-buffers/docs/reference/go-generated) to use the proto package name for determining the generated go file's package name. …
> change import_path_option default value to false

- go/private/compat/compat_repo.bzl
- go/private/compat/v18.bzl
- go/private/compat/v22.bzl
- go/private/repositories.bzl
- go/private/rules/cgo.bzl
- proto/def.bzl
io_bazel_rules_go_compat is a new repository, which contains
compat.bzl, a symbolic link to a file in go/private/compat. There are
multiple versions that compat.bzl may point to (v18.bzl, v22.bzl
initially). These files provide the same definitions with different
implementations.
Initially, this provides abstraction for accessing cc and proto
providers, which are changing in Bazel 0.23.
Fixes #1888
> Add compatibility repository for supporting older Bazel versions

- go/private/compat/compat_repo.bzl
native.bazel_version is None in development versions. We can't compare
that against minimum thresholds, but we can assume it's a pretty new
version of Bazel.
Fixes #1935
> go/private/compat: use newest version if native.bazel_version is None

- go/nogo.rst
1. Fix package name to reflect current code (`buildtags` => `buildtag`)
2. Add a copy-paste friendly one-liner to see the list of available built-in passes
> nogo.rst: doc tweaks

- go/private/actions/compile.bzl
- go/tools/builders/compile.go
- go/tools/builders/nogo_main.go
- tests/core/nogo/coverage/BUILD.bazel
- tests/core/nogo/coverage/README.rst
- tests/core/nogo/coverage/coverage_target_test.go
nogo now allows imported archives not to have fact files (.x
files). Fact files are produced for libraries analyzed by nogo. We
already had a special case for standard libraries (which are not
analyzed by nogo), but we also need to support go_tool_library
dependencies, especially //go/tools/coverdata, which is an implicit
dependency when coverage is enabled.
Fixes #1940
> nogo: make fact files optional for dependencies

- go/tools/builders/nogo_main.go
Creates Scopes and Selections maps in types.Info. The buildssa
analyzer panics without these, and other analyzers may need them, too.
Fixes #1932
> nogo: collect more type information

- go/private/repositories.bzl
The patches that are shipped with googleapis have the intent of removing
files from the input. Though GNU patch does this properly, the copy of
patch shipped with FreeBSD does not do this explicitly. It needs the -E
flag to do so.
This makes it possible to build https://github.com/buildbarn on FreeBSD
11.2-STABLE.
> Make googleapis work on FreeBSD.

- WORKSPACE
- go/private/repositories.bzl
This stops bazel from printing about this dependency:
```
DEBUG: Rule 'com_github_golang_protobuf' modified arguments {"shallow_since": "1534281267 -0700"}
```
> Add shallow_since to git_repository dependencies

- proto/def.bzl
- tests/core/go_proto_library/adjusted_a.proto
- tests/core/go_proto_library/adjusted_b.proto
- tests/core/go_proto_library/adjusted_c.proto
- tests/core/go_proto_library/adjusted_import_test.go
During a refactor in 8670623e6e3a18123129173ba667c33631aca006, a `.proto` attribute was missed and now a `Target` gets passed into the `proto_path` function rather than a `ProtoInfo` provider.
When used with `{strip_}import_prefix`, this would result in the `import` flags passed to the `protoc-go` builder to contain incorrect paths:
```
tests/core/go_proto_library/_virtual_imports/adjusted_c_proto/adjusted/adjusted_c.proto=adjusted/c
```
instead of
```
adjusted/adjusted_c.proto=adjusted/c
```
When `go_package` isn't present in a proto file, protoc-gen-go relies in `Mfile.proto=go/importpath` to resolve proto files to import paths. With these passed incorrect packages for dependencies fail to compile.
I made a few modifications to the tests under `tests/core/go_proto_library/` to catch the …
> Pass ProtoInfo instead of Target to proto_path

- third_party/org_golang_google_grpc-crosscompile.patch
This was an internal patch that I should have upstreamed a long time ago.
> Fix gRPC cross-compilation for Android

- go/private/actions/link.bzl
- go/tools/builders/link.go
- tests/README.rst
- tests/core/README.rst
- tests/core/go_binary/BUILD.bazel
- tests/core/go_binary/README.rst
- tests/core/go_binary/stamp_bin.go
- tests/core/go_binary/stamp_dep.go
- tests/core/go_binary/stamp_embed.go
- tests/core/go_binary/stamp_test.go
- tests/core/nogo/README.rst
Previously, if x_defs were specified for the main package, either
implicitly (just a variable name) or explicitly (with the main package
path), they were not applied by the linker.
With this change, we replace -X pkg.key=value with -X main.key=value
where pkg is the main package path.
Fixes #2000
> go_binary: correctly apply x_defs to main package when linking

- tests/bazel_tests.bzl
--incompatible_disallow_struct_provider_syntax shows an error in the
bazel_test rule. This fixes it, but there are other errors in
@bazel_tools, so it's hard to be sure if there aren't more instances
of this.
> Fix incompatibility warning in bazel_test

- go/private/rules/binary.bzl
Set GOROOT explicitly when invoking "go tool compile" and
"go tool binary". The Go tool determines GOROOT automatically based on
argv[0], but this does not work in some sandbox environments.
Fixes #2005
> go_tool_binary: set GOROOT explicitly

- third_party/org_golang_google_grpc-crosscompile.patch
This PR replaces #2007. 
As discussed in that PR, we're setting goos="linux" on a go_image rule from rules_docker, which is broken unless `--platforms` flags are specified. This is change is a workaround/quality of life improvement to bring back support for `bazel build //...` and similar invocations to multi-platform repos.
> Band-aid gRPC cross-compilation for Linux

- go/private/rules/binary.bzl
Fixes #2010
Signed-off-by: John Millikin <jmillikin@stripe.com>
> Use -trimpath to make go_tool_binary deterministic.

- go/private/repositories.bzl
As provided by bazel: DEBUG: Rule 'com_google_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1551387314 -0800"
> Add shallow_since to com_google_protobuf

- go/core.rst
> Document How To Run Benchmark Test

- .bazelci/presubmit.yml
- .travis.yml
- go/toolchain/toolchains.bzl
Also, re-enable testing on Ubuntu 14.04
> Support new Go releases

- go/tools/builders/BUILD.bazel
- go/tools/builders/nogo_main.go
Recently, we tried out using nogo in our Go projects, and it failed on Windows because of too long relative path names. (I'm not surprised about this thing anymore ;))
I don't know if you think this one goes too far, feel free to adapt. This one works for me on Windows and Linux. (Haven't tried macOS)
> Make nogo work on Windows (path handling)

- go/tools/builders/cgo2.go
- go/tools/builders/stdlib.go
It seems `go tool asm` and `runtime/cgo` uses the output path, so add them.
Fixes the `stdlib` part of #1943.
> Ensure bazel paths don't leak in stdlib builds

- go/private/go_toolchain.bzl
- tests/bazel_tests.bzl
This is broken by a Bazel incompatible flag flip. With this change, we
load generate_toolchain_names from the correct file.
Fixes #2039
> bazel_test: fix load of generate_toolchain_names

- third_party/BUILD.bazel
Otherwise Bazel query fails with:
ERROR: <BAZEL>/external/io_bazel_rules_go/go/private/repositories.bzl:236:9:
no such target '@io_bazel_rules_go//third_party:com_github_kevinburke_go_bindata-gazelle.patch':
target 'com_github_kevinburke_go_bindata-gazelle.patch' not declared in package 'third_party';
however, a source file of this name exists.
(Perhaps add 'exports_files(["com_github_kevinburke_go_bindata-gazelle.patch"])' to third_party/BUILD?)
defined by <BAZEL>/external/io_bazel_rules_go/third_party/BUILD.bazel and referenced by '//external:com_github_kevinburke_go_bindata'
The reason is probably because the patches are referenced from the
root of the remote version of the repository like:
@io_bazel_rules_go//third_party:org_golang_x_tools-gazelle.patch
Fixes #2043.
> Export patches to allow Bazel query to work.

- go/tools/builders/cgo2.go
- go/tools/builders/filter.go
- Add support for C++ headers (`hh`, `hxx`, `hpp`)
- Order c/cxx flags properly, ensuring they are before the compiler input and outputs
> Various fixes in GoCompilePkg

- go/private/compat/compat_repo.bzl
- go/private/compat/v18.bzl
- go/private/compat/v22.bzl
- go/private/compat/v26.bzl
- go/private/context.bzl
This PR migrates rules_go for Bazel's incompatible change https://github.com/bazelbuild/bazel/issues/7793, which is present in 0.25.
> Migrate for Bazel's --incompatible_require_ctx_in_configure_features

- go/private/rules/cgo.bzl
The arguments of string.join should be strings. In the future,
Bazel won't perform this implicit conversion.
> Fix for Bazel upcoming change incompatible_string_join_requires_strings

- go/private/context.bzl
Declare dependency on `https://github.com/bazelbuild/bazel/issues/7260` so go rules work when C++ rules are using toolchains and platforms.
This is a migration needed for https://github.com/bazelbuild/bazel/issues/7260.
> Depend on @bazel_tools//tools/cpp:toolchain_type in go_context_data

- go/private/compat/v22.bzl
- go/private/compat/v23.bzl
- go/private/compat/v26.bzl
Made tests pass with bazel 0.26.0rc8 --all_incompatible_flags
with a few exceptions.
Flags fixed:
* --incompatible_depset_is_not_iterable: wrapped some things in
cc_libs with as_iterable.
Broken flags:
* --incompatible_remap_main_repo: breaks toolchain selection.
* --incompatible_disallow_struct_provider_syntax: breaks java
toolchain in @bazel_tools
* --incompatible_enable_cc_toolchain_resolution: adds UIKit
to link flags but does not make it available to the linker on macOS.
* --incompatible_use_python_toolchains: requires Python 3 to be
installed. Breaks native pkg_tar rule if it's not.
> Bazel compatibility updates

- go/private/tools/single_output_test.bzl
Fix single_output_test() on Windows with the new
native test wrapper.
Bazel 0.25 introduced the
--incompatible_windows_native_test_wrapper flag.
This flag enables a new test wrapper on Windows
that doesn't require Bash. On other platforms this
flag has no effect.
The new test wrapper is a C++ binary and doesn't
use Bash, but therefore test rules whose
executable is a naked shell script also don't
work with it.
The solution here is to write a special script
that does nothing and is valid both as `.bat` and
as `.sh`.
See https://github.com/bazelbuild/bazel/issues/6622
> Windows: future-proof single_output_test.bzl

- go/core.rst
Fix a typo in the docs (`imporpath` -> `importpath`)
> Fix 'importpath' typo

- go/nogo.rst
As per the documentation, the keys in `only_files` and `exclude_files`
are regular expressions, and the code verifies this:
https://github.com/bazelbuild/rules_go/blob/e284e9dafc99aac881970edf760549f5f9daf1e5/go/tools/builders/generate_nogo_main.go#L63
The example in the docs uses globs instead of regular expressions; this
seems to be a typo. This change fixes this by switching the example to
use regular expressions.
> docs/nogo: Use regular expressions in example
