- .bazelci/presubmit.yml
- .travis.yml
Ubuntu 14.04 is about to be end-of-life and Bazel CI will stop supporting it shortly afterwards.
Context: https://groups.google.com/d/msg/bazel-dev/_D6XzfNkQQE/8TNKiNmsCAAJ
> Don't test on Ubuntu 14.04

- go/nogo.rst
It seems that `github.com/bazelbuild/rules_go/go/tools/analysis` has been moved to `golang.org/x/tools/go/analysis`
> Fix nogo example import path in nogo.rst

- go/private/context.bzl
- go/private/rules/cgo.bzl
cgo runs the compiler over a test file as part of the build process.  It then parses the compiler errors.  This requires the compiler to be configured well enough to work for cgo.
-fdiagnostics-color is another way to enable color support on GCC.  This adds colors unconditionally to the output (bazel doesn't present a TTY, so to get colors with bazel, you need to force them on).
-fmax-errors=... is a way to prevent GCC from completely flooding your terminal when something goes wrong.  A missed semicolon or misplaced {} can cause thousands of lines of errors.  This can stop showing errors before cgo sees all the errors it is looking for.  We want to strip it out too.
> Fix cgo build failures with specific GCC flags

- go/core.rst
- go/private/actions/archive.bzl
- go/private/actions/compilepkg.bzl
- go/private/common.bzl
- go/private/context.bzl
- go/private/rules/binary.bzl
- go/private/rules/cgo.bzl
- go/private/rules/library.bzl
- go/private/rules/test.bzl
- go/tools/builders/cgo2.go
- go/tools/builders/compilepkg.go
- go/tools/builders/filter.go
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/add.m
- tests/core/cgo/add.mm
- tests/core/cgo/objc/BUILD.bazel
Objective C and C++ sources may now be compiled directly with
go_library, go_binary, and go_test without needing to use the cgo
legacy wrapper. The cpp toolchain must provide a compiler thats
supports these languages.
Appropriate flags will be passed to the compiler for each language,
but no additional objcopts, objcxxopts attributes are provided. These
are meant to accomodate CGO_CFLAGS, CGO_CXXFLAGS, and there is are no
CGO_MFLAGS, CGO_MMFLAGS directives. These attributes can be added if
necessary though.
Updates #1957
> go_library, go_test, go_binary: accept .m and .mm files

- tests/README.rst
- tests/core/README.rst
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/README.rst
- tests/core/cgo/cgo_link_dep.c
- tests/core/cgo/cgo_link_test.go
- tests/core/cgo/cgo_ref.go
- tests/core/nogo/README.rst
- tests/integration/README.rst
This seems to have been fixed by another change after reporting, so
let's just add a test for it.
Fixes #2067
> tests/core/cgo: verify cdeps used when linking _cgo_.o

- go/private/actions/link.bzl
- go/tools/builders/compilepkg.go
- tests/core/coverage/BUILD.bazel
- tests/core/coverage/README.rst
- tests/core/coverage/binary_coverage_test.go
* Include coverdata in arguments to link action
* Add coverdata as an input
Fixes #2127
> Fix link error when go_binary is instrumented for coverage

- WORKSPACE
This toolchain can be used to test CGo code on Linux with the LLVM toolchain.
> Update LLVM toolchain version

- go/private/actions/archive.bzl
- go/private/context.bzl
- go/private/providers.bzl
- go/private/rules/binary.bzl
- go/private/rules/nogo.bzl
- go/private/rules/test.bzl
- go/providers.rst
Go 1.13 is now stricter on the package path passed to
go tool compile -p. This means that go_library passed in go_binary.embed
fails to declare a main.main, as they now retain their import path. Fix
this by forcing a importmain=main on go_binary.
Fixes #2133
> Ensure go_binary.embed libraries' importpath is main

- go/tools/builders/compilepkg.go
- tests/core/c_linkmodes/BUILD.bazel
- tests/core/c_linkmodes/README.rst
- tests/core/c_linkmodes/crypto.go
- tests/core/c_linkmodes/crypto_test_dl.c
This test has a non-trivial dependency (golang.org/x/crypto) to check for more complex modes.
On master, this test currently fails. But it passes on 0.18.7.
> Add a dynamic load test for c-shared link mode

- go/tools/builders/compilepkg.go
- tests/core/c_linkmodes/BUILD.bazel
- tests/core/c_linkmodes/README.rst
- tests/core/c_linkmodes/c-archive_empty_hdr_test.c
- tests/core/c_linkmodes/empty.go
Previously, we didn't generate an export header when there wasn't any
cgo code.
Fixes #2132
> cgo: always generate export headers

- go/private/actions/compilepkg.bzl
- tests/core/race/racy/BUILD.bazel
> GoCompilePkg: don't pass bogus flags to assembler

- go/private/actions/link.bzl
- go/tools/bazel_testing/bazel_testing.go
- tests/core/README.rst
- tests/core/nogo/coverage/BUILD.bazel
- tests/core/nogo/coverage/README.rst
- tests/core/nogo/coverage/coverage_target_test.go
- tests/core/nogo/coverage/coverage_test.go
emit_link was referencing go.coverdata.data when go.coverage_enabled
was true but go.coverdata was None. This is the case for nogo, since
nogo binaries don't have an implicit reference on coverdata.
Fixes #2146
> nogo: ensure nogo binary can be built with coverage enabled

- proto/BUILD.bazel
Some of the proto-generated code depends on "github.com/gogo/protobuf/protoc-gen-gogo/descriptor", leading to the follow error a build time. This PR fixes it.
```
import of "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
Known dependencies are:
github.com/gogo/protobuf/gogoproto
github.com/gogo/protobuf/proto
github.com/gogo/protobuf/sortkeys
github.com/gogo/protobuf/types
google.golang.org/grpc
golang.org/x/net/context
github.com/golang/protobuf/ptypes/any
google.golang.org/genproto/protobuf/api
github.com/golang/protobuf/protoc-gen-go/plugin
github.com/golang/protobuf/protoc-gen-go/descriptor
github.com/golang/protobuf/ptypes/duration
github.com/golang/protobuf/ptypes/empty
google.golang.org/genproto/protobuf/field_mask
google.golang.org/genproto/protobuf/source_context …
```
> adding gogo proto descriptor to deps of gogo proto compiler

- go/private/actions/archive.bzl
There were code paths where `importmap` is undefined on line 157 and 174.
These errors only occur when cgo_archives is set on the source. 
I ran into this with some custom rules around GoSource.
> Fix "local variable 'importmap' is referenced before assignment"

- go/private/actions/link.bzl
- tests/core/go_binary/BUILD.bazel
- tests/core/go_binary/README.rst
- tests/core/go_binary/static_cgo_bin.go
- tests/core/go_binary/static_pure_bin.go
- tests/core/go_binary/static_test.go
By default on Linux, the Go linker may produce a static binary if no
packages require cgo. net and os both require cgo, so for non-trivial
programs, the external linker will NOT be used, and the internal
linker will produce a dynamically linked executable.
With this change, in static mode, we force external linking. We were
already passing -static to the external linker, but we weren't always
using the external linker.
Fixes #2168
> GoLink: force external link for static binaries

- BUILD.bazel
- go/platform/list.bzl
- go/private/context.bzl
- go/private/go_toolchain.bzl
- go/private/platforms.bzl
Previously, we defined separate cgo and non-cgo variants of
go_toolchain. The cgo variant depended on cgo_context_data, which
requires a C/C++ toolchain. However, go_toolchain is built in host
mode, so we always got a toolchain for the execution platform, not the
target platform. This broke cross-compilation with cgo.
With this change, we only declare a go_toolchain per platform,
regardless of cgo. go_context_data depends on cgo_context_data
if the cgo_off constraint is not set.
This means a C/C++ toolchain (for the correct platform) will be
required for the default target platform and platforms that have not
specifically opted out of cgo. Platforms declared in //go/toolchain
are already fine. However, users defining their own platforms may be
broken by this change.
Fixes #2166
> go_toolchain: move cgo_context_data dep to go_context_data

- README.rst
README has sha256 from 0.19.3 release. sha256 gotten from https://github.com/bazelbuild/rules_go/releases/tag/0.19.4
Fixes #2213
> Update sha256 checksum for 0.19.4 release

- go/private/actions/archive.bzl
- go/private/actions/asm.bzl
- go/private/rules/aspect.bzl
- go/private/rules/cgo.bzl
- proto/compiler.bzl
- proto/def.bzl
skylib to 0.8.0 or below. This allows interoperability with the federation.
Federation users will end up bringing in bazel-skylib at 0.9.0, because
they (by default) pin the version before rules_go.  Another way of putting it
is that users may now force load bazel-skylib at 0.9.0 or greater without
breaking rules_go.
This was tested along with an update to bazel-skylib 0.9.0. This was to
prove that the old_sets change will continue to do the right thing with
the next skylib release. We could combine that into this release, but
it is not strictly necessary.
Also: do not load sets.bzl in modules that do not need it.
> Use old_sets.bzl where sets are needed so that we do not have to pin

- README.rst
This was noted in the release notes for 0.19.0: https://github.com/bazelbuild/rules_go/releases/tag/0.19.0, but hard to find anywhere else.
> Update cross compile instructions when using cgo

- go/private/actions/archive.bzl
- proto/compiler.bzl
Skylib broke compatibility by renaming this module (from sets.bzl) and
replacing it with something that doesn't handle depsets (which is what
use we use it for). old_sets.bzl is removed to be removed in a future
release.
We don't really need this module anymore. Just use the depset
constructor directly.
Fixes #2157
> Remove dependency on skylib old_sets.bzl

- go/tools/bazel_testing/bazel_testing.go
> go/tools/bazel_testing: add BazelCmd and BazelOutput

- go/tools/bazel_testing/bazel_testing.go
- go/tools/bazel_testing/def.bzl
> go/tools/bazel_testing: don't treat test arguments as flags

- go/private/rules/cgo.bzl
Bazel does this, so that headers can be imported via their fully
qualified path.
> go/cgo: always include the current workdir via iquote

- go/tools/bazel_testing/bazel_testing.go
setupWorkspace returned a nil cleanup function if it encountered an
error. It's caller panicked when calling this before checking for an
error. Now, setupWorkspace returns a trivial cleanup function instead.
Also, cleanup now returns an error. If cleanup returns an error and
the code was 0, TestMain sets the exit code to 1.
Updates #2233
> go/tools/bazel_testing: don't panic on setup error

- README.rst
Also, remove build status from README.rst. It's currently failing due
to a bazel bug unrelated to rules_go, and it's generally not helpful
for users.
> Announce v0.20.0 and v0.19.6 releases [skip ci]

- README.rst
> Announce rules_go v0.20.1, v0.19.7 [skip ci]

- go/tools/builders/compilepkg.go
I came across this while poking around compilepkg to learn how to pull out the cgo-generated Go files from it for #512 and I might not have context on what its for. It's unused, but perhaps there was some expectation of future use?
> delete unused cgoarc flag from compilepkg builder

- go/tools/bazel/runfiles.go
When using this helper, I was noticing FindBinary returning directories that matched the expected binary name. Find binary should never return a directory.
> Skip directory matching in FindBinary

- go/platform/list.bzl
- go/private/compat/BUILD.platforms.v23.bzl
- go/private/compat/BUILD.platforms.v28.bzl
- go/private/compat/compat_repo.bzl
- go/private/platforms.bzl
- go/private/repositories.bzl
- go/toolchain/toolchains.bzl
- tests/core/cross/ios_select_test.go
os and cpu constraint settings and values are being removed from
@bazel_tools//platforms. They are currently available in the external
@platforms repo (now declared in go_rules_dependencies). So we should
reference those instead of @bazel_tools//platforms.
In order to support old Bazel versions (the current minimum is still
0.23.0), @io_bazel_rules_go_compat//platforms now declares aliases on
either @platforms or @bazel_tools//platforms.
Note that bazel-skylib 1.0.2 (the latest released version) is not
compatible with --incompatible_use_platforms_repo_for_constraints yet,
so not all rules_go tests pass with that flag yet.
Updates bazelbuild/bazel#8622
> go_compat_repo: alias constraint values and settings to bazel_tools or platforms

- go/tools/bazel_testing/def.bzl
Conditionally include the Bazel testing library. 
When using something like
```
```
with a directory of Bazel tests, Gazelle will automatically add this target as a
dep and duplicate entries is a build error.
> Conditionally include Bazel testing library only if needed

- go/tools/builders/nogo_main.go
Since `act.exec()` might panic it is better to `defer w.Done()`
> nogo: defer wg.Done()

- go/private/context.bzl
I'm still not 100% clear on the exact interaction, but this was precipitated by trying to do a Bazel build of something with a `host` Go toolchain that was on a read-only mount. When doing so, builds would fail with an error trying to `go install vendor/golang.org/x/net/nettest`, since it couldn't open the `nettest.a` file in the host Go toolchain for writing. My strong suspicion here is that the `stdlib` builder isn't setting a `GOPATH`, so it's trying to write to the file in `GOROOT`, which it can't actually do since that's read-only.
Either way, this fixes things and feels pretty low-impact.
> Clear GOPATH environment variable in builder

- .bazelci/presubmit.yml
- go/private/repositories.bzl
- go/private/rules/cgo.bzl
- tests/core/c_linkmodes/BUILD.bazel
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/objc/BUILD.bazel
- tests/legacy/cgo_select/BUILD.bazel
- tests/legacy/examples/cgo/cc_dependency/BUILD.bazel
- tests/legacy/transitive_data/BUILD.bazel
* All C/C++/ObjC test targets are now declared with rules_cc.
* Extra targets around "c-archive" and "c-shared" binaries are
declared with rules_cc.
* Consequently, rules_cc is now declared in go_rules_dependencies.
Fixes #2318
> Migrate to rules_cc

- .bazelci/presubmit.yml
This verifies rules_go works with this flag after updating
bazel_toolchains.
Fixes #2321
> Test with --incompatible_restrict_string_escapes

- go/tools/builders/generate_test_main.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/README.rst
- tests/core/go_test/testmain_import_indirect_test.go
- tests/core/go_test/testmain_import_main_test.go
All imports which gazelle identified as test dependencies should be
imported in the test main package.
This way "hidden" global registrations are properly added to the binary.
One use-case is Ginkgo. It has its own wrappers for tests and rules_go
would miss them in some cases, which would lead to tests being not added to the binary.
Fixes #1999
> Import all pkg which tests depend on

- tests/legacy/transitive_data/transitive_data_test.go
To make the test runnable with `-test.v` set.
> Test: use flag.Args() instead of os.Args[1:]

- third_party/go_googleapis-directives.patch
Bazel will always override the external repository's WORKSPACE file by `workspace_file`, `workspace_file_content` or a created file with "workspace(name =`<name in repo rule>`)"
> Remove patching for WORKSPACE file

- go/core.rst
- go/private/rules/test.bzl
- go/tools/BUILD.bazel
- go/tools/builders/generate_test_main.go
- go/tools/testwrapper/BUILD.bazel
- go/tools/testwrapper/test2json.go
- go/tools/testwrapper/testdata/empty.json
- go/tools/testwrapper/testdata/empty.xml
- go/tools/testwrapper/testdata/report.json
- go/tools/testwrapper/testdata/report.xml
- go/tools/testwrapper/wrap.go
- go/tools/testwrapper/wrap_test.go
- go/tools/testwrapper/xml.go
- go/tools/testwrapper/xml_test.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/xmlreport_test.go
Based on the discussion in https://github.com/bazelbuild/rules_go/issues/236#issuecomment-577425507, add a testwrapper library that can be imported from the generated testmain.
The testlibrary has a Wrap function, that will check if the test was executed from Bazel. If it was, the wrapper function executes the binary itself, wraps some functionality like capturing stdout and exits with the exitcode from the child process. If the wrapper function decides to wrap, it does not return.
> Add XML testreport generation using testwrapper

- go/tools/testwrapper/BUILD.bazel
Post-submit test failed because #2348 was merged after #2356 was
tested.
> Fix //tests:buildifier_test

- go/tools/builders/compilepkg.go
- go/tools/builders/nogo_main.go
When calling the builder binary from starlark, the `args.use_param_file`
option is used to support long argument lists. For nogo, the builder
calls the nogo binary with a list of arguments for which the size is
proportional to what the builder was called with. Currently nogo isn't
called with a parameter file but instead gets it's arguments from the
commandline.
This change writes the nogo arguments to file and calls nogo with an
argument to read the parameter file for arguments.
References #2002.
> Use paramfile for invoking nogo

- third_party/go_googleapis-gazelle.patch
Re-generate the Gazelle patch after bazelbuild/bazel-gazelle#717.
Fixes #2387
> go_googleapis: fix dependencies

- go/private/platforms.bzl
This will add new targets in //go/platforms and //go/toolchains.
> go: add missing platforms from 'go tools dist list'

- .bazelci/presubmit.yml
- go/private/common.bzl
This only applies to the master branch, not to current release
branches.
This is needed for configuration transition support. 1.2.0 (the
current minimum) and 2.1.0 (the version before 2.2.0) both have build
failures triggered by transitions.
For #2219
> Set minimum supported Bazel version to 2.2.0

- go/BUILD.bazel
- go/platform/BUILD.bazel
- go/toolchain/BUILD.bazel
This is important for Stardoc, which insists on knowing about all transitively
loaded Starlark files.
Bug fix
When generating documentation for a rule that uses these rules using Stardoc,
compilation currently fails because not all transitively loaded files are present.
Fixes #
> Add missing Starlark files to “all_rules” targets.

- go/private/actions/archive.bzl
- go/providers.rst
These are thoroughly obsolete and have been deprecated for a while.
For #2448
> go: remove searchpaths and searchpath from GoArchive and GoArchiveData

- go/private/repositories.bzl
- proto/BUILD.bazel
- third_party/com_github_golang_protobuf-extras.patch
- third_party/com_github_golang_protobuf-gazelle.patch
- third_party/org_golang_google_protobuf-gazelle.patch
* Added org_golang_google_protobuf at v1.21.0 to
go_rules_dependencies. This contains the new protobuf runtime.
It doesn't seem like any *_gen rules are needed, so just using the
gazelle patch for now.
* Upgraded com_github_golang_protobuf to v1.4.0. The packages here are
wrappers org_golang_google_protobuf. Newly generated code should
work with the old interface. The *_gen targets are still in place,
but they're simpler.
* Added new dependencies for packages generated with
//proto:go_proto, //proto:go_grpc, and //proto:go_proto_bootstrap,
since the proto compiler imports more runtime packages.
* We're still using the compiler from com_github_golang_protobuf. It's
a wrapper for the new one. The new one doesn't support gRPC, and the
gRPC proto compiler doesn't exist yet. See …
> proto: upgrade go_proto_library to support APIv2

- go/toolchains.rst
* Fix typo in default value in `go_download_sdk`
* Change "Skylark" to "Starlark" to meet current name
Documentation
Small typo and wrong expressions.
Fixes #2458
> Fix small typo and obsolete expressions.

- go/tools/builders/compilepkg.go
When nogo exits unexpectedly, the error before was:
```
compilepkg: 
```
With this PR, it becomes:
```
compilepkg: nogo command 'bazel-out/k8-opt-exec-2B5CBBC6-ST-9c9985fc97d8f8bef19f5d79323610d073a386b599d7ca1532565183d6fe3142/bin/libdefault_nogo.so -p golang.org/x/crypto/blowfish -importcfg /mnt/jenkins/.cache/bazel/_bazel_jenkins/e1d11652acf0c5d23aa28905edcc7be3/sandbox/linux-sandbox/211391/execroot/__main__/bazel-out/k8-fastbuild-ST-9c9985fc97d8f8bef19f5d79323610d073a386b599d7ca1532565183d6fe3142/bin/external/org_golang_x_crypto/blowfish/importcfg273671022 -x bazel-out/k8-fastbuild-ST-9c9985fc97d8f8bef19f5d79323610d073a386b599d7ca1532565183d6fe3142/bin/external/org_golang_x_crypto/blowfish/go_default_library.x /mnt/jenkins/.cache/bazel/_bazel_jenkins/e1d11652acf0c5d23aa28905edcc7be3/sa …
```
> Improving nogo errors

- go/private/actions/binary.bzl
- go/private/context.bzl
- go/tools/bazel/runfiles.go
- tests/core/go_binary/BUILD.bazel
- tests/core/go_binary/README.rst
- tests/core/go_binary/prefix/BUILD.bazel
- tests/core/go_binary/prefix/prefix.go
A binary named "foo" will now create the executable "foo_/foo" to
avoid conflicting with subdirectories named "foo".
go.declare_file will no longer cause this problem when only path is
specified.
Fixes #2463
> go_binary: use file name less likely to be a prefix

- .bazelci/presubmit.yml
- BUILD.bazel
- go/config/BUILD.bazel
- go/nogo.rst
- go/private/BUILD.bazel
- go/private/context.bzl
- go/private/nogo.bzl
- go/private/repositories.bzl
- go/private/rules/nogo.bzl
- go/private/rules/transition.bzl
- tests/core/nogo/README.rst
- tests/core/nogo/config/README.rst
- tests/core/nogo/config/config_test.go
- tests/core/nogo/flag/BUILD.bazel
- tests/core/nogo/flag/README.rst
- tests/core/nogo/flag/flag_test.go
The nogo binary to use is now specified using a Starlark flag.
For example:
bazel build --@io_bazel_rules_go//go/config:nogo=@io_bazel_rules_go//:tools_nogo //:hello
.bazelrc is now the recommended way to set this flag. Setting nogo in
go_register_toolchains will still work, though that function may be
deprecated soon. The flag overrides the go_register_toolchains
argument when both are set.
Updates #2374
Fixes #2470
> nogo: migrate to configuration transitions

- .bazelci/presubmit.yml
- go/private/rules/nogo.bzl
- go/private/rules/transition.bzl
- tests/core/nogo/config/README.rst
- tests/core/nogo/config/config_test.go
nogo now uses an incoming-edge transition to reset all Go build
settings to their default values. This prevents nogo from being built
with an unusual link mode, as well as other issues.
This change uses some code from #2473, but it doesn't change how nogo
fits into the dependency graph.
Fixes #2470
> nogo: transition to default mode settings

- go/private/rules/binary.bzl
> Bug fix
run_shell requires bash which is not available on Windows
without a msys installation.
The shell was only used for "&&" anyway. We can just use
two separate actions.
Commands should be equivalent, except -trimpath=. is used
instead of -trimpath=$PWD. I tried building a binary and it
came out identical, so guessing it works either way.
Fixes # https://github.com/bazelbuild/rules_go/issues/2486
> Avoid use of run_shell in bazel rule.

- proto/core.rst
> go_proto_library: make importpath mandatory in documentation [skip ci]

- tests/core/race/race_test.go
Test case was added in #2502. #2509 enabled tests and caused it to
start failing. Skipped for now.
Updates #2518
> tests/core/race: disable cover_race on windows

- go/private/context.bzl
- go/private/mode.bzl
- tests/core/cross/BUILD.bazel
- tests/core/cross/README.rst
- tests/core/cross/def.bzl
Bootstrapping rules that don't depend on //:go_context_data or other
targets that provide GoConfigInfo should be allowed to call go_context
without error.
Fixes #2523
> go_context: allow go_config_info to be None

- proto/BUILD.bazel
Similar to #2160, adding descriptor to the gogo proto compiler without grpc
Fixes #1385
> Adding descriptor dependency to gogo proto compiler

- go/private/rules/nogo.bzl
- go/private/rules/transition.bzl
- go/tools/builders/BUILD.bazel
- proto/compiler.bzl
- tests/core/cross/README.rst
- tests/core/cross/proto_test.go
Go settings like linkmode, pure, and race shouldn't affect Go
tools. In particular, they shouldn't affect go-protoc (go_binary used
to invoke protoc), protoc-gen-go, or other user-specified binaries.
go_proto_compiler depends on these targets using 'cfg = "exec"', which
ensures they're built for the execution platform but doesn't change
other Go settings.
This PR renames nogo_transition to go_reset_transition, so it can be
used for tools other than nogo. It also introduces go_reset_target, a
rule that forwards Go providers from a target built with
go_reset_transition. go_proto_compiler is now a macro that stitches
one of these together with a _go_proto_compiler rule so both
transitions may be used.
Fixes #2538
> go_proto_compiler: reset go config when building go-protoc, plugins

- go/private/actions/stdlib.bzl
- go/private/rules/cgo.bzl
Bug fix
if cc toolchain has -lstdc++ in link_flags or link_libs,
go_library records these flags, along with clinkopts, in *.a(_go_.o),
and go_binary uses these ldflags to link.
if -lstdc++ exists, even if -Wl,-Bstatic,-lstdc++,-Bdynamic or
-static-libstdc++ is specified, libstdc++ is dynamically linked.
Thus, these is no way to make libstdc++ statically linked
for go binary.
This patch removes -lstdc++ or -lc++ if go_library cgo=True uses
-static-libstdc++ in clinkopts.
User would need to specify -lWl,-Bstatic,-lstdc++,-Bdynamic too,
since clang ignores -static-libstdc++ (clang++ only use the flag).
It also remove -lstdc++ or -lc++ when building std go libraries
(for --feature=race etc).
**Which issues(s) does this …
> allow libstdc++ static link

- go/private/rules/test.bzl
> Feature
This PR adds the `-s -w` linker flags for Go test binaries, and will omit the symbol table and DWARF data from the binary. This behaviour is consistent with the Go toolchain when running `go test pkg` and noticeably improves linker performance.
Fixes https://github.com/bazelbuild/rules_go/issues/2550
> go_test: Disable symbol table and DWARF for test binaries

- go/private/rules/test.bzl
For compatibility with Bazel 1.2.0
Updates #1877
> go_test: use skylib structs.to_dict to repack GoSource

- go/private/actions/archive.bzl
- go/private/actions/compile.bzl
- go/private/actions/compilepkg.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/compile.go
- go/tools/builders/compilepkg.go
- go/tools/builders/env.go
- go/tools/builders/importcfg.go
- go/tools/builders/link.go
- go/tools/builders/nogo_main.go
- go/tools/builders/pack.go
Fixes #1803 based on the review comments of #2199:
>  We could invoke the compiler without -linkobj. After it runs, the builder could copy the export data from the compiled .a file into the .x file. So the export data would appear in both archives.
So this PR:
* makes the .x file an archive
* makes nogo be able to read the archive to get the facts
* copies `__.PKGDEF` from .a file to .x file
* stops passing .a file and instead always and only passing .x file to compiler
Tested on Uber's Go monorepo. All builds and tests passed.
> Copy PKGDEF and nogo facts to the same archive

- go/tools/builders/env.go
Feature
`--verbose_failures` only prints out the command that Bazel rules call directly. If a binary calls several subcommands (e.g., compilepkg), we don't know which subcommand fails until we run the parent command manually. For failures that cannot be reproduced locally (e.g., the Windows errors of #2461), printing out the subcommand gives us better idea what could have gone wrong.
> Print out subcommand when it fails

- go/private/repositories.bzl
Bug fix
Updates the dependency on `github.com/mwitkow/go-proto-validators` to the latest patch release.
Fixes #2558.
> Bump go-proto-validators dependency

- go/private/actions/archive.bzl
- go/private/rules/test.bzl
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/README.rst
- tests/core/cgo/split_import_a.go
- tests/core/cgo/split_import_b.go
- tests/core/cgo/split_import_c.c
- tests/core/cgo/split_import_c.h
- tests/core/cgo/split_import_cgo.go
- tests/core/cgo/split_import_i_test.go
- tests/core/cgo/split_import_x_test.go
When a test contains both internal and external files, and the
external files indirectly import the library under test, some package
need to be recompiled so that the packages that import the library
under test are compiled with the internal test archive instead. This
was implemented in #2579.
That change caused a regression: the recompiled archives didn't
include input files from cdeps dependencies. This change adds a new
GoArchiveData field to track direct dependencies. That can be used to
rebuild a depset of all the needed files.
Fixes #2622
> go_test: pass cdeps files to linker after split test recompilation

- go/tools/builders/BUILD.bazel
- go/tools/builders/go_path.go
Bug fix
Windows has a limit of 256 characters for relative characters when using the syscalls the Go standard library uses. In a Bazel project I encountered recently I couldn't run the GoPath builder because of an `google.golang.org/grpc` dependency that included the file `bazel-out\x64_windows-fastbuild\bin\external\org_golang_google_grpc\reflection\grpc_reflection_v1alpha\grpc_reflection_v1alpha_go_proto_\google.golang.org\grpc\reflection\grpc_reflection_v1alpha\reflection.pb.go`, which even with my very short bazel root of `C:\tmp\bzl` was too long to open, and resulted in the error message `GoPath: open bazel-out\x64_windows-fastbuild\bin\external\org_golang_google_grpc\reflection\grpc_reflection_v1alpha\grpc_refl …
> Use absolute paths in GoPath builder (mainly for Windows compatibility)

- go/tools/builders/compilepkg.go
Bug fix
The current way to create xTempDir uses relative paths. They are too long for Windows. At the same time, `workDir` in compilePkg is a temp dir. We don't need to create another temp dir to store nogo facts and export data
Fixes #2641 
> Reusing workDir to store nogo facts and export data

- go/private/actions/archive.bzl
Bug fix
If a custom Go rule generates more than one library, or otherwise
changes the name of the GoLibrary, the emitted archive will still have
the _ctx.label.name. To deconflict, use the library's name as the
emitted archive's name.
In the normal case, this is already the default, so it shouldn't hurt.
In the [very work in progress PR here](https://github.com/u-root/gobusybox/pull/23/files) I create an aspect that applies to go_binary rules. It takes either its srcs, or every embed'ed library's sources and rewrites them such that the go_binary is importable as a go_library. (The transformation is documented [here](https://github.com/u-root/gobusybox#command-transformation).)
This means every go_binary this is …
> archive: use library's name for archive name

- go/private/BUILD.sdk.bazel
Other
To run the CockroachDB node, you need [to provide an archive of time zones from your environment](https://www.cockroachlabs.com/docs/v20.1/known-limitations.html#location-based-time-zone-names). And if you\`re using Bazel, it would be very convenient to use `zoneinfo.zip` from the go sdk provided by the role_go.
With this export you can refer to this archive like this `"@go_sdk//:lib/time/zoneinfo.zip"`.
> Export zoneinfo from go sdk.

- go/private/context.bzl
- go/tools/builders/asm.go
- go/tools/builders/builder.go
- go/tools/builders/compile.go
- go/tools/builders/compilepkg.go
- go/tools/builders/cover.go
- go/tools/builders/env.go
- go/tools/builders/generate_test_main.go
- go/tools/builders/info.go
- go/tools/builders/link.go
- go/tools/builders/nogo_main.go
- go/tools/builders/pack.go
- go/tools/builders/protoc.go
This lets arguments contain newlines.
Fixes #2635
> go: use "shell" params file format instead of "multiline"

- go/tools/builders/compilepkg.go
- go/tools/builders/env.go
Bug fix
`go tool compile` writes syntax errors to [stdout](https://github.com/golang/go/blob/a3868028ac8470d1ab7782614707bb90925e7fe3/src/cmd/compile/internal/syntax/parser.go#L361), including the one reported in #2592. Meanwhile, all regular output of subcommands should have been written to files. We should direct all stdout of subcommands to stderr, so we can find all errors in stderr. This mirrors behavior in the [go command](https://go.googlesource.com/go/+/refs/tags/go1.15.2/src/cmd/go/internal/work/exec.go#1958)
> Redirecting all stdout of subcommands to stderr

- go/tools/builders/env.go
If a command fails, we'll just print the command path without its
environment variables and arguments.
Fixes #2661
> go/tools/builders: make subcommand errors less verbose

- go/private/context.bzl
- go/toolchains.rst
attr["deps"] may be a list of either Targets or GoArchive.
Fixes #1784
> doc: improve documentation for go.library_to_source attr param

- go/private/rules/cgo.bzl
- tests/core/cgo/add.c
The go command uses -I for package directories, which makes
directories available for "" and <> includes. We should do the same.
We no longer use ctx.build_file_path, since that directory might not
actually provide any build files, and its value changed in Bazel
3.7.0.
Fixes #2685
> cgo: use -I instead of -iquote for source header directories

- .bazelci/presubmit.yml
- go/private/common.bzl
- go/private/rules/cgo.bzl
Other
Migrates cgo code away from deprecated Bazel cc Starlark apis.
Fixes #
See https://github.com/bazelbuild/bazel/issues/10860.
> Migrate to the modern linker input API.

- go/core.rst
- go/private/tools/path.bzl
- tests/core/go_path/BUILD.bazel
- tests/core/go_path/go_path_test.go
- tests/core/go_path/pkg/lib/BUILD.bazel
- tests/core/go_path/pkg/lib/transitive.go
This PR improves `go_path` in ~two~ one ways:
- ~add `go_archive_aspect` properties so that `include_pkg` are compiled with the right mode (since it consumes archives)~
- add `include_transitive` so that only the packages in `deps` are included in the GoPath. When used with `include_pkg`, this allows to only sandbox the needed packages, and thus invalidate potentially less.
When using gomobile's `gobind`, this reduces hot rebuild times by 2-3x, because less is invalidated.
> go_path: add include_transitive

- tests/core/cgo/BUILD.bazel
The macOS toolchain is gaining support for params files for link
commands. As part of this we're removing support for arguments with
leading `@`s. This change should be a no-op.
Compatibility with https://github.com/bazelbuild/bazel/pull/12265
> Update macOS -install_name linker flag

- README.rst
Documentation
The documentation for `go_proto_library` states that the `protos` attribute should be used instead of the old `proto` attribute. Updating the README might help with nudging people to use the new `protos` attribute.
N/A
N/A
> README.rst: use `protos` instead of `proto`

- go/config/BUILD.bazel
- go/private/actions/link.bzl
- go/private/context.bzl
- go/tools/builders/importcfg.go
- go/tools/builders/link.go
- tests/core/go_binary/package_conflict_test.go
We've promised to do this for more than two years, and the time has
finally come.
If more than one copy of a package with the same package path is
provided to the linker, the GoLink action now reports an
error. Distinct packages (for example, from multiple vendor
directories) may be disambiguated with the importmap attribute.
Fixes #1374
> link: make package conflicts into errors instead of warnings

- go/private/sdk.bzl
Go 1.13 is no longer supported by the Go team and is not receiving
security updates.
Fixes #2728
> Drop support for Go 1.13

- proto/BUILD.bazel
- proto/wkt/well_known_types.bzl
Since protobuf 3.14, the Well Known Types declare APIv2 package paths,
which means generated code that imports them will import APIv2
packages.
This PR is intended to be cherry-picked to the 0.23 and 0.24 release
branches. It may slow down builds, since both APIv1 and APIv2 packages
will be compiled; we can't tell which is needed during analysis.
Fixes #2721
> go_proto_library: add implicit dependencies on APIv2 packages

- go/tools/builders/compilepkg.go
- go/tools/builders/env.go
Feature
Improve the error messages seen by everyday users of rules_go
Fixes #2061
> Relative paths in error messages

- go/private/sdk.bzl
We determine the "SDK platform" by looking at the goos_goarch
subdirectory of pkg/tool. If the goroot has actually built the toolchain
for multiple platforms, then we just pick the first one and potentially
fail cryptically later.
Ideally, we would simply register toolchains for all of the host
platforms we find, but that is likely a much larger change. Until then,
provide a much clearer error message that we don't like finding multiple
platforms.
Fixes #2764
Bug fix
When pointing a `go_local_sdk` to a toolchain with multiple platforms this improves the error from a cryptic "no matching toolchains found for types @io_bazel_rules_go//go:toolchain" to "Error in fail: Could not detect SDK platform: found multiple …
> go_local_sdk: more strict SDK platform detection

- go/tools/builders/env.go
Use os.Stderr.Write instead of fmt.Fprint. The latter formats the
value as a []byte, not a string.
(This was due to my own bad review comment on #2736. Sorry.)
> go/tools/builders: don't format subcommand output as []byte

- go/tools/builders/compilepkg.go
- go/tools/builders/pack.go
In Go 1.16, 'go tool pack r' reports an error if the archive doesn't
already exist (arguably a bug). The builder relied on this behavior
(arguably also a bug).
The builder will now create an empty archive before calling
'go tool pack r'. Note that 'go tool pack c' has some extra
functionality (copying export data) beyond creating the archive, so we
can't use that directly.
Fixes #2762
> builder: support appending to non-existant archive

- go/tools/bzltestutil/init.go
This is a breaking change.
Partially-Reverts: 9c1568a7f510fe306a59f8d09e91579a71f5e08c
Fixes: #2776
> dont set TEST_TMPDIR to TMPDIR in the test runner

- go/tools/builders/pack.go
- go/tools/builders/protoc.go
C.f. #1382
Bug fix
Makes rules_go work on Windows with long filenames.
> Handle long filenames on Windows in a few more places.

- go/private/context.bzl
Bug fix
Enables coverage for `testonly` libraries.
Fixes #2786
Check the discussion in the issue.
Any suggestions on testing/documentation would be good to know...
> testonly should have coverage

- go/tools/builders/nogo_main.go
- tests/core/nogo/custom/custom_test.go
Feature
Report the analyzer name in the nogo diagnostic messages.
The additional data point should help the developer to investigate, and
if need be, suppress the error. This is especially useful to find nogo
checks that fail for third party dependencies.
Fixes #2674
The analyzer is appended in parentheses, similar to [golangci-lint](https://golangci-lint.run/)
Some sample output from `tests/core/nogo/custom_test.go`:
```
has_errors.go:4:2: package fmt must not be imported (importfmt)
has_errors.go:9:1: function must not be named Foo (foofuncname)
has_errors.go:10:2: function D is not visible in this package (visibility)
```
---
This change is [<img …
> nogo: mention analyzer name in diagnostic output

- README.rst
The release notes incorrectly labeled the latest release as 2020, where it should be 2021.
> fix incorrect release date

- go/private/sdk.bzl
This still fails several tests that assume x86-64, but it’s at least a starting
point.
Feature
This implements basic support for ARM64 macOS systems.
#2795
(This doesn't entirely fix the issue since some of the tests still fail)
> Add minimal support for ARM64 on macOS.

- README.rst
- WORKSPACE
Also, update examples in README.rst to use 1.16.
For #2820
> all: test with Go 1.16 in CI

- tests/legacy/asm_include/BUILD.bazel
Using the CPU “darwin” doesn’t work correctly on ARM-64.  Use the normal CPU
and operating system constraints from the \@platforms repository instead.
Bug fix
Slightly improve ARM64 support on macOS.
#2795 (not a complete fix, but a start)
> Fix CPU selector.

- tests/legacy/cgo_select/BUILD.bazel
These files are architecture-independent, so this works on ARM-64 without
further changes.
Bug fix
Slightly improve ARM64 support on macOS.
#2795 (not a complete fix, but a start)
> Include ARM64 in “select” calls.

- go/private/rules/transition.bzl
- go/private/tools/path.bzl
- go/tools/builders/BUILD.bazel
- proto/compiler.bzl
Bug fix
- Patch `go_reset_target` to properly forward `DefaultInfo.executable` via a symbolic link.
- Patch `go_proto*` rules to now use `ctx.executable`
- Pass `go_path` builder binary through `go_reset_target`
- Fix #2689
> Make go_reset_target forward DefaultInfo.executable and pass go_path into it

- go/private/sdk.bzl
Use 'tar' installed on the system to extract .tar.gz archives instead
of Bazel's download_and_extract. Go has at least one test with an
invalid unicode file name, and on some configurations (macOS with Docker
and some particular file system binding?), this causes an error.
Fixes #2771
> go_download_sdk: work around Bazel .tar.gz extraction bug

- tests/core/go_download_sdk/go_download_sdk_test.go
Since only Go 1.16 supports ARM-64 on macOS, switch to that version.
Bug fix
A bit of support for ARM-64.
#2795 (not a complete fix, but a start)
> Add ARM-64 version to go_download_sdk test.

- tests/core/go_binary/BUILD.bazel
- tests/core/go_binary/pie_darwin_amd64_test.go
- tests/core/go_binary/pie_darwin_test.go
It looks like on ARM-64, all binaries are position-independent, so this test
only succeeds on x86-64.
Bug fix
A bit of support for ARM-64.
#2795 (not a complete fix, but a start)
> Split up PIE tests.

- go/tools/builders/nogo_main.go
- tests/core/nogo/custom/custom_test.go
Bug fix
Go files could include `//line` comments that indicate the original location of the line. This functionality is used, among other things, cgo's code rewrite step. This commit changes the include/exclude_files logic to use the adjusted/original location, in order to better align with user expectations.
Fixes #2862
> nogo: properly check filename for inclusion/exclusion

- go/private/actions/compilepkg.bzl
- go/private/context.bzl
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/add.c
- tests/core/cgo/add.cpp
- tests/core/cgo/add.m
- tests/core/cgo/add.mm
Bug fix
The documentation for `go_library`, `go_binary`, etc., claims that certain compiler options are subject to "Make variable" substitution. However, this is not the case for the majority of cases: only `gc_goopts` and `gc_linkopts` were handled correctly. This commit fixes that behavior.
Fixes #2864
> Expand Make variables in c/cpp/cxx/clinkopts

- go/tools/bazel/bazel_test.go
- go/tools/bazel/runfiles.go
Bug fix
This PR fixes compatibility with a MANIFEST file generated for a rules_python binary. Python manifests can have "one-part" entries like `__init__.py ` where a line terminates with a space and does not map to another file.
Fixes #2866 
I wasn't sure about how exactly this fix should be tested. I think the "proper" test is actually an integration test as written over in https://github.com/samhowes/rules_go_runfiles_repro/blob/main/BUILD.bazel since this issue is really dependent on bazel's generation of a MANIFEST for python `__init__.py` modules ([see comment on runfiles_test.py](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab …
> Support python runfiles MANIFEST on windows

- go/tools/bazel/bazel.go
- go/tools/bazel/bazel_test.go
- go/tools/bazel_testing/bazel_testing.go
Bug fix
Fixes a bug 
Fixes #2886
This PR replaces #2882 (that one was done using github editor).  Based on feedback, created this PR.
Note, this function cannot easily be put into the `bazeltesting` package because it already has a `TestMain`.  As such, I put it in the `bazel` package where a number of utility functions used by `bazeltesting` already exist.
> [bazeltesting] Refactor to SpliceOSArgs utility function

- go/private/actions/link.bzl
- go/tools/builders/link.go
- tests/legacy/examples/stamped_bin/stamped_test.go
Feature
Support string interpolation in `x_defs`.
```bazel
go_binary(
x_defs = {
"myvar": "{BUILD_USER} built me at {BUILD_TIMESTAMP}",
}
)
```
Fixes #2075
> Support multiple keys in x_defs

- go/private/actions/stdlib.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/builder.go
- go/tools/builders/stdlib.go
- go/tools/builders/stdliblist.go
- go/tools/gopackagesdriver/BUILD.bazel
- go/tools/gopackagesdriver/aspect.bzl
- go/tools/gopackagesdriver/bazel.go
- go/tools/gopackagesdriver/bazel_json_builder.go
- go/tools/gopackagesdriver/driver_request.go
- go/tools/gopackagesdriver/flatpackage.go
- go/tools/gopackagesdriver/json_packages_driver.go
- go/tools/gopackagesdriver/main.go
- go/tools/gopackagesdriver/packageregistry.go
This commit introduces an aspect based `GOPACKAGESDRIVER` for `rules_go`.
It is rather clunky, but all VSCode + `gopls` features work with it:
- Completion
- Go to definition
- Go to references
- Quick lookup
- Inline documentation
It does not support static usage at the moment (for instance by running it inside an action for codegen tools), but it could with few additions.
The packages driver fundamentally works from the perspective of one or more targets. In order
for it to function properly, the targets must be specified in the packages driver configuration,
with environment variables.
These are:
- `GOPACKAGESDRIVER_BAZEL_TARGETS`: specifies specific targets, `//...` works too (although this is not recommended without tag filters). It is possible to set targets to something other than …
> go/tools: add gopackagesdriver

- go/platform/crosstool.bzl
- go/private/rules/transition.bzl
- go/tools/builders/stdlib.go
Reopens #2451
When an inbound `crosstool_top` and `cpu` are specified, some platforms
can be automatically inferred/detected.
Some legacy rules still implement configuration splits on
`crosstool_top` and `cpu` instead of platform constaints. This is the
case most notably for rules_apple and rules_android.
Add a generic platform matching system based on `crostool_top`/`cpu`.
Finally, add Apple and Android matchers.
Refs #2443
> Add automatic platform detection from inbound crosstool_top and cpu

- .bazelci/presubmit.yml
- go/private/common.bzl
* Bazel 4.0.0 is now the minimum supported version.
This is the LTS release.
* This is tested on Ubuntu 18.04, the oldest supported Ubuntu release.
* The latest version of Bazel is now tested on Ubuntu 20.04.
> Update Bazel and Ubuntu versions in CI configuration

- proto/core.rst
Documentation
Adds a missing preposition into the description of the embed attribute.
> proto/core: fix documentation typo

- .bazelci/presubmit.yml
Other: Bazel CI configuration change.
Disables a test that fails on Windows due to an unfixed upstream bug in Go.
Fixes #2911.
> Disable //tests/core/race:race_test on Windows

- go/private/sdk.bzl
- go/toolchains.rst
Feature
`go_wrap_sdk`'s `root_file` only accepts one Go SDK. This pull requests adds a new `root_files` attribute to accept multiple Go SDKs for multiplatform support similar to `go_download_sdk`
> Accepting multiple platform SDKs in go_wrap_sdk

- .bazelci/presubmit.yml
What type of PR is this?
Other: Bazel CI configuration change.
What does this PR do? Why is it needed?
Disables a test that fails on Windows due to an unfixed upstream bug in Go. See https://buildkite.com/bazel/rules-go-golang/builds/3158#c8bfc9aa-f9e7-4c3e-9b47-1332ab952b76
Which issues(s) does this PR fix?
Fixes #2911.
Other notes for review
> Disable //tests/core/cgo:race_test on Windows

- go/private/context.bzl
Bug fix
the cgo flag collection logic does not account for --linkopt configuration flag set for `rules_cc`. These flags are appended post-toolchain flags in bazel and are not expanded as part of the toolchain logic.
this PR appends these flags (accessible via the `cpp` fragment) to the options for the executable and shared library linking options.
Fixes #2923 
> Ensure command line linkopts are added to cgo link flags

- README.rst
- WORKSPACE
Also update versions in README.rst examples.
> Update to Go 1.17 in WORKSPACE

- .vscode/extensions.json
- .vscode/settings.json
- go/tools/builders/stdliblist.go
- go/tools/gopackagesdriver/BUILD.bazel
- go/tools/gopackagesdriver/aspect.bzl
- go/tools/gopackagesdriver/bazel.go
- go/tools/gopackagesdriver/bazel_json_builder.go
- go/tools/gopackagesdriver/build_context.go
- go/tools/gopackagesdriver/driver_request.go
- go/tools/gopackagesdriver/flatpackage.go
- go/tools/gopackagesdriver/main.go
- go/tools/gopackagesdriver/packageregistry.go
- go/tools/gopackagesdriver/utils.go
- tools/gopackagesdriver.sh
Feature
This PR introduces automatic target detection so that no user input
is required after the `GOPACKAGESDRIVER` setup. This effectively
deprecates the following environment variables:
- `GOPACKAGESDRIVER_BAZEL_TARGETS`
- `GOPACKAGESDRIVER_BAZEL_QUERY`
- `GOPACKAGESDRIVER_BAZEL_TAG_FILTERS`
It works as follows:
- for `importpath` queries, it will `bazel query` a matching `go_library`
matching it
- for `file=` queries, it will try to find the matching `go_library` in the
same package
- since it supports multiple queries at the same time, it will `union` those
queries and query that
Once the `go_library` targets are found, it will try to build them directly,
which should dramatically speed up compilation times, at …
> go/tools/gopackagesdriver: add automatic target detection

- .bazelci/presubmit.yml
- go/private/repositories.bzl
- go/private/rules/BUILD.bazel
- tests/core/c_linkmodes/BUILD.bazel
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/objc/BUILD.bazel
- tests/legacy/cgo_select/BUILD.bazel
- tests/legacy/examples/cgo/cc_dependency/BUILD.bazel
- tests/legacy/transitive_data/BUILD.bazel
- windows.rst
Long time ago Bazel was saying that cc_binary, cc_library, cc_test and the other cc_* rules should be imported from rules_cc.
However rules_cc was always saying that there is no need to use them yet.
After several discussions it was clarified that migration to bazelbuild/rules_cc was put on hold and there is not need to the users that they start using it.
One of the reasons why a person would not want to use rules_cc right now is because there is no release and there is no notion of what is a good commit:
bazelbuild/rules_cc#91
bazelbuild/rules_cc#68
The fact that rules_go depends on rules_cc forces any rules_go user to use rules_cc. Considering that rules_docker depends on rules_go, any rules_docker user is also forced to depend on rules_cc.
More information about the discussions: …
> Remove dependencie with bazelbuild/rules_cc

- go/private/rules/binary.bzl
- tests/integration/reproducibility/reproducibility_test.go
The goroot is encoded in the output binary, but the goroot is different
in different workspaces. As a result tool binaries (such as builder) are
not reproducible. Bazel will have cache misses for build involving
builder even if the resulting output from the build is reproducible.
Similar to go_binary builds, suppress the goroot path in go_tool_binary
output so that the result in reproducible.
> Bug fix
Like go_binary output, ensure go_tool_binary output is reproducible
Fixes #2951
> Suppress goroot path in tool builds

- go/tools/builders/cgo2.go
- tests/core/nogo/custom/custom_test.go
cgo2 merges sources and generated code under a common directory, however this directory is anonymous.
This breaks nogo's ability to easily include/exclude files as only the file's basename is retained.
This change embeds cgo/packagePath into the merged directory to make it easy to include/exclude sources being compiled by cgo.
Note: PR #2863 ensured that files //line: directives had their meaningful alt names included in nogo output. This is helpful, however for pure go files that are part of a package that uses cgo, there is nothing that adds //line: directives, and the builder will just copy/link pure files into the into the merged cgo folder.
> Bug fix
Makes the merged cgo temp directory include the package path …
> CGO merged directory should have usable name.

- go/private/rules/test.bzl
- tests/core/go_library/BUILD.bazel
- tests/core/go_library/embedsrcs_simple_test.go
Even though there already is testing coverage for go_test() with
embedsrcs using generated files and such, I can't seem to get one of the
most trivial cases to work. The file to be embedded doesn't get placed
in the sandbox during GoCompilePkg.
This change addresses this by explicitly copying the embedsrcs from the
internal source to the external, which seems to make things work
properly.
Bug fix
It fixes go_test() with embedsrcs. It's needed, because I want to use that feature.
I couldn't find any existing issues.
> Make go_test() with embedsrcs work

- go/private/common.bzl
Bug fix
This is probably needed to fix #2944, but it's not enough. With this PR, versioned dylib becomes a build error instead of a runtime error.
> Supporting versioned dylib in has_versioned_shared_lib_extension

- go/tools/builders/env.go
Bug fix
A clang based toolchain controlling compiler built-in directory via `--resource-dir` will not work in tandem with cgo enabled go toolchain.
This PR adds --resource-dir to the set of cgo compiler flags the builder transforms to absolute paths.
Fixes #2924
> -resource-dir flag for clang should be absolute

- go/tools/builders/generate_test_main.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/README.rst
- tests/core/go_test/fuzz_test.go
The GoTestGenTest action now produces testmain.go files compatible
with Go 1.18 and lower versions. In 1.18, the function
testing.MainStart accepts a new parameter, a list of fuzz targets. We
now find those targets and pass them in for Go 1.18 and higher.
Go 1.18 is still months away, and it's possible the API may change
before then. It's likely that FuzzTarget will be renamed. That should be a
minor change though. MainStart is carved out of the Go 1 compatibility
promise and is only meant to be called by code generated by 'go test',
which we're emulating here.
This change does not add full support for fuzzing. It is possible to
start the fuzzing engine by passing --test_arg=-test.fuzz=regexp
--test_arg=-test.fuzzcachedir=dir. However, if a crash is found,
there's nowhere for the fuzzing …
> go_test: add compatibility with fuzzing in Go 1.18+

- go/private/actions/cover.bzl
- go/tools/builders/compilepkg.go
During the invocation of `bazel coverage`, rules_go will rewrite the
source fils using `go tool cover -var ...` so that the variable can be
extracted for coverage statistic after test execution. For more
information on this, review the relevant Official Go Team's blog post (1)
The variable used by rules_go is following the `Cover_snake_case` naming
convention, which is natural to starlark and python, but not Golang.
For this reason, some static analysis could get triggered by the usage
of snake case naming variable while running over coverage source code.
The correct solution for this problem should be to make rules_go's
static analysis framework `nogo` to NOT run on the generated source code
and instead only run on the original source code.  However, replacing
underscore separators with …
> cover: use Z instead of underscore for variable name separator

- go/tools/builders/env.go
It contains the path of a file used at compile time to change the
behavior of sanitiziers.
Add its older name of -fsanitize-blacklist too.
> Bug fix
Support cgo with some additional C/C++ compiler flags.
> -fsanitize-ignorelist should have an absolute path

- go/tools/builders/cgo2.go
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/cc_libs_common.go
- tests/core/cgo/cc_libs_darwin_test.go
- tests/core/cgo/cc_libs_linux_test.go
Bug fix
The cgo command generates .c files that contain //line comments
referencing source files by absolute paths into the Bazel cache. As the
contents of these comments end up in the symbol table of the resulting
c-archive, this makes Bazel-built CGo binaries non-reproducible.
This is fixed by passing the -trimpath argument to cgo to trim the
Bazel execroot prefix from these paths.
Fixes #3010
> Trim absolute paths in files generated by cgo

- go/core.rst
- go/private/rules/test.bzl
- go/tools/bazel/bazel_test.go
- go/tools/bazel/runfiles.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/env_test.go
Feature
This allows setting environment variables before static initialisers
run, and which reference expanded locations.
Partially fixes #2921
> go_test: Add env attribute

- go/platform/apple.bzl
- go/platform/list.bzl
- go/private/actions/link.bzl
- go/private/mode.bzl
- go/private/platforms.bzl
- go/private/rules/binary.bzl
- go/tools/builders/cgo2.go
- go/tools/builders/link.go
Feature
Add first class support for `GOOS=ios`.
Up until now, `ios` was supported as `darwin_arm64` by Go. `GOOS=ios`
support was added in Go 1.16 [1].
1. https://golang.org/doc/go1.16
> Add first class support for GOOS=ios

- tests/integration/reproducibility/reproducibility_test.go
This allows us to find it at a known path.
It is no longer possible to access genfiles at a known path:
https://github.com/bazelbuild/bazel/pull/14049
Fixes #2967
Fixes #3024
> reproducibility_test: explicitly build the go_sdk builder

- BUILD.bazel
- go/modes.rst
- go/private/BUILD.bazel
Bug fix
Previously, debugging a `go_test` target was only possible with an explicit `--@io_bazel_rules_go//go/config:debug`.
Fixes https://github.com/bazelbuild/intellij/issues/2313, which I think is more of a `rules_go` issue.
> Always include debug symbols with -c dbg

- go/tools/bazel_testing/bazel_testing.go
> bazel_testing: fix workspace name regexp to accept \r\n line ending

- .bazelci/presubmit.yml
- WORKSPACE
- go/private/common.bzl
- go/private/repositories.bzl
- go/private/rules/BUILD.bazel
- go/private/rules/transition.bzl
Other
The Label constructor can be used to transform a label string such as @io_bazel_rules_go//foo:bar into the canonical label referencing this target from the repository in which it is called.
For example, `str(Label("@io_bazel_rules_go//foo:bar"))` returns `"@io_bazel_rules_go//foo:bar"` if rules_go is used as an external repository from another main workspace, but returns `"//foo:bar"` when rules_go is the main repository (e.g., when running the tests in the CI).
It doesn't resolve a bug, but simplifies the rules_go repository setup. This simplification will be especially useful when converting `rules_go` to a Bazel module in the future.
> Replace go_name_hack with a usage of Label

- go/private/nogo.bzl
> Bug fix
Changing this particular label to the str(Label(...)) pattern does not
behave as expected (https://github.com/bazelbuild/bazel/issues/14590).
It is thus safer to revert back to the old form for now and instead rely
on patches in a future renaming of io_bazel_rules_go to rules_go for the
BCR.
Work towards #3020.
@achew22 would probably be in the best position to review as this is a follow-up to https://github.com/bazelbuild/rules_go/pull/3038.
> Make one label repository-absolute again

- docs/go/core/rules.bzl
- docs/go/core/rules.md
- go/core.rst
- go/private/rules/test.bzl
- go/tools/builders/generate_test_main.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/README.rst
- tests/core/go_test/test_fail_fast_test.go
Feature
The following are now equivalent
```sh
> bazel test --test_runner_fail_fast //path/to/my/go/test
> bazel test --test_arg=-failfast //path/to/my/go/test
```
Fixes #3055 
> map bazel's --test_runner_fail_fast to go's -failfast

- docs/go/editors/vim.md
Documentation
It adds documentation for how to integrate the new-ish `$GOPACKAGESDRIVER` functionality with Vim, adding to [existing instructions for VS Code + Sublime](https://github.com/bazelbuild/rules_go/wiki/Editor-setup#3-editor-setup)
Fixes https://github.com/bazelbuild/rules_go/issues/3056
> Add editor setup instructions for Vim + vim-go

- go/private/sdk.bzl
We rely on the packaged zoneinfo zip in CRDB, found under
lib/time/zoneinfo.zip. When using the remote SDK macro, we untar the
entire archive into the sandbox. When pointing to a local SDK however,
we previously ignored everything under lib. It feels reasonable to also
symlink lib/ into the sandbox given they have valid symbols to build
against.
Bug fix
See commit message.
No filed issue.
> sdk: symlink everything under lib/ when using local SDK

- go/private/platforms.bzl
- go/private/sdk.bzl
> Feature
> Enable windows/arm64 go build with Bazel
Go for windows/arm64 is available from version 17. This patch adds the missing pieces to build go programs with bazel.
> enable windows/arm64 go build with bazel

- go/nogo.rst
- go/tools/builders/generate_nogo_main.go
- go/tools/builders/nogo_main.go
- tests/core/nogo/custom/custom_test.go
- tests/core/nogo/custom/flags/BUILD.bazel
- tests/core/nogo/custom/flags/README.rst
- tests/core/nogo/custom/flags/flags_test.go
> Feature
Allow nogo config to specify flags to be passed to each analyzer via `analyzer_flags`. The ability to provide flags to each
analyzer is something not currently supported by the driver, which makes it more troublesome to use configurable 
analyzers in a Bazel Go project.
#3081 
Being able to pass in a list of CLI arguments might add greater flexibility, but given the restrictive nature of Go's `FlagSet`
API, it is unlikely that any analyzers in the wild will support positional arguments and the like.
> Resolves #3081: add `analyzer_flags` to nogo config

- docs/go/core/defines_and_stamping.md
- go/private/actions/link.bzl
- go/private/common.bzl
- tests/core/starlark/common_tests.bzl
Feature
The PR improves local cache hit rate for workspaces that generate stable status variables but may stamp some targets with only volatile status variables.
Fixes #3078
I follow this strategy also in [rules_r](https://github.com/grailbio/rules_r/blob/9df1e588b20004ba4001563ce0490b87edd51624/R/internal/build.bzl#L296).
> Consider volatile and stable status files separately

- go/tools/builders/compilepkg.go
- tests/integration/reproducibility/reproducibility_test.go
> Bug fix
Some packages are not deterministic, rather they have different content hashes when rebuilt. This occurs when rules_go creates an `_empty.go` file to satisfy the compiler. In those cases, the empty file is created in the OS temp dir, which changes across compiler invocations. The path of this file changes the content hash of the resulting package, thus breaking caches and downstream builds. 
This PR changes the location of this tmp file to the output path of the package, such that it is the same output path across compiler invocations. 
Reproduction steps: 
```sh
bazel build //tests/core/go_library:empty 
md5 bazel-bin/tests/core/go_library/empty.a
rm -f  bazel-bin/tests/core/go_library/empty.a
bazel build …
```
> Use output dir for empty packages to be hermetic

- proto/compiler.bzl
Hey wonderful Bazel Go folks,
I was browsing the codebase and noticed both that the minimum Bazel version for rules_go is 4.2.1 (in the release notes) and also saw a section of code saying it should be deleted when Bazel minimum version >= 0.21.0. So I figured I should toss up a PR doing just that!
Looks like @jayconrod wrote the code originally. Tagging him in case he wants to weigh in with context. Maybe there's more dead code that should be deleted. But it looks like he might be busy and hasn't committed in a while, so I'd propose that we probably shouldn't wait synchronously on his reply.
Thanks for reading!
Chris
(ex-Googler)
> Remove legacy proto code for Bazel < 0.21

- go/tools/gopackagesdriver/aspect.bzl
- tests/core/starlark/packagedriver/BUILD.bazel
- tests/core/starlark/packagedriver/fixtures/a/BUILD.bazel
- tests/core/starlark/packagedriver/fixtures/a/a.go
- tests/core/starlark/packagedriver/fixtures/b/BUILD.bazel
- tests/core/starlark/packagedriver/fixtures/b/b.go
- tests/core/starlark/packagedriver/fixtures/c/BUILD.bazel
- tests/core/starlark/packagedriver/fixtures/c/c.go
- tests/core/starlark/packagedriver/fixtures/c/c_test.go
- tests/core/starlark/packagedriver/go_pkg_info_aspect_test.bzl
Bug fix
This PR consolidates two sets of data (`transitive_*` and `deps_transitive_*`) in `GoPkgInfo` into one set, and let `depset` to perform necessary deduplication. It also takes the approach proposed by @skevy in https://github.com/bazelbuild/rules_go/pull/3053#issuecomment-1070366256 to remove the duplicate JSON files written by `go_pkg_info_aspect` for `go_test`.
The test fixture was taken from https://github.com/csstaub/gopackagesdriver-repro, credits to @csstaub 
Fixes #2948
@aignas FYI
> Reducing duplicate information passed by go_pkg_info_aspect

- go/private/rules/binary.bzl
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/external_includes_test.go
Bug fix 
A CGo-generated header file from any repository, external or main, must
always be includeable via its path relative to its repository root.
Previously, this was not true for CGo targets in external repositories,
which required an additional `external/<repo name>/` prefix, thus
breaking references within the external repository.
Fixes #3109
> Fix include paths for CGo deps in external repositories

- extras/gomock.bzl
- go/def.bzl
- go/private/repositories.bzl
- tests/core/gomock/BUILD.bazel
- tests/core/gomock/client.go
- tests/core/gomock/client_test.go
- third_party/com_github_golang_mock-gazelle.patch
Performance optimization. This is also a breaking change from original `gomock` rule implementation, because it changes the types of `aux_files` attribute.
Running mockgen in source mode does not require all its dependencies in GOPATH. It only need the source file and some aux files. We can copy them to form a GOPATH structure without calling `go_path` rule. 
Before this patch:
```
Critical path (1.199 s):
Time Percentage   Description
0.46 ms    0.04%   action 'Writing file mocks_gomock_gopath~manifest'
250 ms   20.86%   action 'GoPath mocks_gomock_gopath'
949 ms   79.10%   action 'Action mocks.go'
```
After this patch:
```
Critical path (891 ms):
Time Percentage   Description
24.1 ms    2.70%   action 'Action …
```
> Avoid calling go_path rule in source mode

- extras/gomock.bzl
- tests/extras/gomock/BUILD.bazel
Bug fix
mockgen doesn't need a list of interface when in source mode. `gomock` rule should not require that either. Removing the  interfaces attribute from gomock source mode.
Alternatively, we can keep the attribute and make it non-mandatory, like https://github.com/jmhodges/bazel_gomock/pull/56.
> Removing interfaces attribute from gomock source mode

- go/private/rules/cgo.bzl
> Bug fix
Reverts changes in
https://github.com/bazelbuild/rules_go/pull/2445/files#diff-1fae1aeb9bbd89e02d89a880ef0d1122bd51b265bc281978f01c14fc27f41f47R191
Instead of using resolved shared library name, depend on symlinks that use mangled name.
More details in #2906
Fixes #2906
Would be great to add some test case for it, but it seems it reproduces using `--remote_download_minimal` for now. Possibly the issue does not show up without this option, because code is able to escape sandbox and see actual library, but don't have good way for reproducing it atm.
> Revert change to use resolved shared lib links

- extras/embed_data.bzl
rules_go has had a built in way to handle embedded for a while. Let's deprecate the non-standard way.
> Officially deprecate `go_embed_data`

- go/private/actions/compilepkg.bzl
- go/tools/builders/compilepkg.go
- tests/core/go_library/BUILD.bazel
- tests/core/go_library/embedsrcs_test.go
- tests/core/go_library/empty_main.go
Bug fix
Previously, embedsrcs under configuration roots different from that of
the Go target itself or its source files weren't found.
This is fixed by considering all combinations of roots of embedsrcs and
root-relative paths of source files and compilation outputs.
Fixes #3114
This blocks #3108, which causes the underlying bug to manifest itself in many simple situations.
> Find embedsrcs built in different configurations

- go/private/rules/nogo.bzl
- go/private/rules/transition.bzl
- go/tools/builders/BUILD.bazel
- proto/BUILD.bazel
- proto/compiler.bzl
- proto/def.bzl
- tests/core/transition/BUILD.bazel
- tests/core/transition/hermeticity_test.go
Bug fix
Reduces the number of essentially distinct configurations in which `protoc` as a dependency of `go_proto_library` is analyzed. 
Note that this may not (yet) result in a significant reduction of *rebuilds* since Bazel is not particular friendly to reset transitions at the moment: It encodes some information about the path of transitions taken into the build configuration, which e.g. prevents transitions from ever returning to the top-level target configuration. But this will be solved by https://github.com/bazelbuild/bazel/issues/14023, which is very actively being worked on. In the meantime, this change should at least not regress the current behavior further.
Fixes a …
> Reset Go settings for protoc dependencies

- go/private/mode.bzl
- go/private/rules/binary.bzl
- go/private/rules/wrappers.bzl
- tests/core/go_binary/BUILD.bazel
- tests/core/go_binary/non_executable_test.go
Bug fix
If a go_binary's `linkmode` is neither `normal` nor `pie`, the resulting
file can't be executed. In this case, `executable` should be set to
`False` on the go_binary rule so that Bazel doesn't create a runfiles
tree for the targets and does not include e.g. a resulting static
library in the runfiles of dependants.
> Let go_binary's executable bit depend on `linkmode`

- go/private/rules/BUILD.bazel
- go/private/rules/binary.bzl
- go/private/rules/library.bzl
- go/private/rules/test.bzl
- go/private/rules/transition.bzl
- tests/core/transition/hermeticity_test.go
Bug fix
By resetting Go-specific settings changed by go_transition to their previous values when crossing a non-deps dependency edge, e.g. srcs or data, dependencies through those edges are not affected by the change in Go settings. This has two advantages:
* Correctness: Previously, if a go_binary with `linkmode = "c-archive"`  used another go_binary to generate srcs, that go_binary would also be built as a c-archive and thus fail to run during the build. This was observed in https://github.com/bazelbuild/bazel/issues/14626.
* Performance: With the new Bazel flag `--experimental_output_directory_naming_scheme=diff_against_baseline`, transitions can return to the top-level configuration since the Starlark settings …
> Trim transitioned Go settings on non-Go dependencies

- go/tools/builders/compilepkg.go
- go/tools/builders/generate_test_main.go
- go/tools/bzltestutil/lcov.go
Bug fix
This PR adds a field `OriginalPanicOnExit` to `go/tools/bzltestutil. LcovTestDeps`, so it can restore the original paniconexit bit after calling `lcovAtExitHook()`. This allows testing Exec command using [this pattern](https://jamiethompson.me/posts/Unit-Testing-Exec-Command-In-Golang/).
> Restore original paniconexit0 flag after calling lcovAtExitHook

- .bazelci/presubmit.yml
- go/private/actions/stdlib.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/env.go
- go/tools/builders/stdliblist.go
- go/tools/builders/stdliblist_test.go
- tests/core/stdlib/stdlib_files.bzl
What type of PR is this?
This PR addresses comments for https://github.com/bazelbuild/rules_go/pull/3083
What does this PR do? Why is it needed?
It fixes go list invocations from bazel for go1.18, where std library uses go:embed
see https://github.com/bazelbuild/rules_go/pull/3083
Which issues(s) does this PR fix?
Fixes https://github.com/bazelbuild/rules_go/issues/3080
Other notes for review
updated the patch in our repo with this patch
verified that the targets that failed without the patch can build successfully
verified a rebuild of all our repo behaved as expected
> Fix gopackagesdriver for Go 1.18 by replicating stdlib and add test for stdliblist.go

- go/tools/builders/cgo2.go
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/provide_external_symbol.go
- tests/core/cgo/use_external_symbol.go
Bug fix
Fix linker error if go_library with cgo references unresolved symbol
Before this commit, if a go_library referenced an unresolved C symbol,
the build would fail with an error about an undefined symbol since
compilepkg.go tries to link all object files into an executable to be
consumed by cgo's -dynimport argument.
Since this library is never used for any purpose other than having its
symbols parsed by the cgo command, retry with additional linker flags
intended to make the linker ignore unresolved symbols. If they remain
missing in the real link step, they will still be reported as unresolved
there.
Fixes https://github.com/golang/go/issues/25832 for rules_go.
> Fix linker error if go_library with cgo references unresolved symbol

- go/private/actions/compilepkg.bzl
- go/tools/builders/compilepkg.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/same_package.go
- tests/core/go_test/same_package_test.go
compilepkg: fix race when run without sandbox
On platforms without sandbox execution support such as Windows, multiple
go_test targets declared in the same package would cause a race condition.
```
[
go_library(
name = "same_package_{}".format(i),
srcs = ["same_package.go"],
importpath = "github.com/bazelbuild/rules_go/tests/core/go_test/same_package_{}".format(i),
x_defs = {
"name": "{}".format(i),
},
)
for i in range(1, 80)
]
[
go_test(
name = "same_package_{}_test".format(i),
srcs = ["same_package_test.go"],
embed = [":same_package_{}".format(i)],
)
for i in range(1, 80)
]
```
For each of go_test targets, there would be internal archive and
external archive that needs to compile from source files.  However, due
to testfilter, external archive would end up without any Go source and
thus …
> compilepkg: fix race when run without sandbox

- README.rst
Many of the features listed under the "unsupported" section have since
been added. Also updates the minimum required version of Bazel mentioned
in the README to the correct value.
> Update introductory section of the README

- go/tools/gopackagesdriver/aspect.bzl
- go/tools/gopackagesdriver/flatpackage.go
> Bug fix
We kept running into weird issues with the gopackagesdriver tool because
it would often run into "cannot parse non-Go file", and point to a .s
file. After some digging I decided to compare the output of the driver
vs the output for `go list -json` (continue reading for full
comparison). As it turns out, the driver includes all srcs in both the
`GoFiles` and `CompiledGoFiles` pkg info output. However ".s" files
have their own section (because they're not Go files) in the regular go
list JSON output. This commit modifies the aspect to account for that.
Somewhat (trimmed for readability) full output for the package
github.com/dgraph-io/ristretto/z:
```jsonc
// go list -json github.com/dgraph-io/ristretto/z
{ …
```
> gopackagesdriver: separates "s" files in pkg info

- go/tools/builders/cgo2.go
- go/tools/builders/env.go
- go/tools/builders/info.go
- go/tools/builders/stdliblist.go
Bug fix
The rety logic introduced by 6ab73ec5b still emitted the stderr of the
failing compiler execution before the retry. Now, this output is cached
and only emitted if the retry also fails.
> Do not print to stderr if cgo linking succeeds after retry

- go/tools/builders/asm.go
- go/tools/builders/builder.go
- go/tools/builders/compile.go
- go/tools/builders/compilepkg.go
- go/tools/builders/cover.go
- go/tools/builders/env.go
- go/tools/builders/generate_test_main.go
- go/tools/builders/info.go
- go/tools/builders/link.go
- go/tools/builders/nogo_main.go
- go/tools/builders/pack.go
- go/tools/builders/protoc.go
- proto/compiler.bzl
Bug fix
Makes the `GoProtocGen` action use parameter files if the argument list gets too long.
Fixes #3188
Tested manually by temporarily setting `use_always = True` and running the tests.
> Use param files with go-protoc

- go/private/actions/link.bzl
- go/private/rules/binary.bzl
- tests/core/go_binary/non_executable_test.go
Bug fix
If a go_binary is built with a non-executable link mode such as
`c-archive`, its dependents currently pick up a runfile dependency on it
since its DefaultInfo specifies the resulting archive as an executable.
This is unnecessary as the dependent should be able to decide whether to
include the file (e.g. dynamic linking) or not (e.g. static linking).
With this commit, the executable field of the DefaultInfo is only
populated if the go_binary is built with an executable link mode.
Follow-up to #3143
> Don't include non-executable go_binary in dependent's runfiles

- go/tools/bazel/bazel_test.go
- go/tools/bazel/runfiles.go
These API have been deprecated since
Jun 3 2019 with 4442d82a001f378d0605cbbca3fb529979a1c3a6.
It has been 3 years since then, let's clean up the deprecation.
> runfiles: remove deprecated api

- tests/core/transition/hermeticity_test.go
Due to an incorrect JSON field name used in a test helper, the test
did not fail when a target is built in two configurations that differ
in rules_go settings.
> Fix failing open hermeticity test

- go/private/context.bzl
Bug fix
Makes rules_go rules build with `--features=layering_check` and other C/C++ features requiring special rule support.
Fixes #3093
> Exclude unsupported C/C++ features

- docs/go/extras/extras.md
- extras/gomock.bzl
- tests/extras/gomock/BUILD.bazel
Bug fix
Add a `kwargs` to gomock so it can take common attributes such as `visibility`
> Allow gomock to take Bazel common attributes

- go/private/context.bzl
- go/private/mode.bzl
- go/private/rules/binary.bzl
- go/private/rules/library.bzl
- go/private/rules/test.bzl
- go/private/rules/transition.bzl
- go/private/rules/wrappers.bzl
- tests/core/go_binary/BUILD.bazel
- tests/core/go_binary/configurable_attribute_bad_test.go
- tests/core/go_binary/configurable_attribute_good_test.go
Bug fix
As per https://github.com/bazelbuild/bazel/issues/15157 currently we
can't configure any transition-relevant attributes using select. This is
because we use self-transitions on targets, and when this happens,
configurable attributes aren't passed to the transition, so we make
incorrect transition decisions.
We only actually consult configuration data in `_go_context_data`, so we
only actually need to transition on the edges which (transitively) reach
a `_go_context_data`, which is `_go_context_data` itself and `deps`.
Fixes #3103
Fixes #3015
> Transition on edges not self

- go/tools/gopackagesdriver/aspect.bzl
- go/tools/gopackagesdriver/bazel.go
- go/tools/gopackagesdriver/bazel_json_builder.go
Bug fix
Also look for `go_transition_test`, not just `go_test` targets when generating dependency file info for test targets.
Also cleanup duplicate function in JSON builder (it was unused as far as I could tell).
Fixes #3015, to my knowledge (I have been using this patch locally for quite some time as a fix for it).
See https://github.com/bazelbuild/rules_go/issues/3015#issuecomment-1004988375
> Include go_transition_test in bazel aspect

- go/toolchains.rst
Fixes https://github.com/bazelbuild/rules_go/issues/3136.
Documentation
Fixes #
> Add an example for go_download_sdk.sdks

- go/tools/gopackagesdriver/aspect.bzl
- go/tools/gopackagesdriver/bazel_json_builder.go
This partially revert #3160, because #3116 removed `go_transition_test`.
@JamyDev @fmeum Please review.
> Remove references to go_transition_test

- go/tools/builders/asm.go
- go/tools/builders/compilepkg.go
This is required to produce linkable objects as of Go 1.19.
Fixes #3199
> asm: Pass package path with -p

- tests/core/cgo/generate_imported_dylib.sh
Small QOL change to ensure that generate_imported_dylib.sh runs would
always success even when an older version of the symlink exists locally.
> test cgo: ensure helper script works

- tests/legacy/examples/cgo/cc_dependency/BUILD.bazel
The CPU config setting didn't match for M1 Macs, which are darwin_arm64.
Instead, use a more modern @platforms condition for the special casing.
We should ultimately fix the underlying issue with linking on macOS
instead.
> Fix //tests/legacy/examples/cgo:cgo_lib_test on M1 Macs

- go/tools/gopackagesdriver/aspect.bzl
Bug fix
This lets the aspect generate .pkg.json files for well-known type
targets such as `@org_golang_google_protobuf//types/known/wrapperspb`.
Fixes #3239
> gopackagesdriver: Descend into go_proto_compiler's deps

- go/private/rules/test.bzl
- go/toolchains.rst
`_testmain_library_to_source` was introduced in 1c4f6fd1 and last usage
of this resolver was in 56e5592c.
```
> git log -S'_testmain_library_to_source' --oneline
56e5592c Move the test library rule to be go_test internal actions (#1267)
9031d58e Add GoContext (#1140)
1c4f6fd1 Fix aspect based proto builds (#1131)
```
Let's remove the unused resolver and replace the documentation with the
resolver that is actually being used.
> new_library: remove unused resolver

- BUILD.bazel
- go/BUILD.bazel
- go/constraints/amd64/BUILD.bazel
- go/private/context.bzl
- go/private/mode.bzl
Feature
The new constraints `//go/constraints/amd64:v1` to `v4` can be used to
mark a platform as supporting the corresponding level of `GOAMD64`.
To use the new feature, users would supply their own platform:
```starlark
platform(
name = "amd64_with_avx",
contraint_values = [
"@platforms//os:linux",
"@platforms//cpu:x86_64",
"@io_bazel_rules_go//go/constraints/amd64:v3",
],
)
```
and then specify the platform with `--platforms`.
Fixes #3248
> Add platform contraints for GOAMD64

- go/private/BUILD.sdk.bazel
Feature
Export support files needed for using Go's WebAssembly (WASM) output.  In particular, misc/wasm/wasm_exec.js contains glue code for making use of WASM output within Javascript.
No issue filed. Per contribution guidelines, this looked too minor to file an issue. Please let me know if an issue should be filed.
Without this change, my project (https://github.com/google/chrome-ssh-agent) needs to apply a patch as part of importing the rules_go repository.  This seems general-purpose enough that it should be applied in rules_go itself.
> Export support files needed for using Go's WebAssembly (WASM) output.

- go/private/BUILD.sdk.bazel
- go/private/go_toolchain.bzl
- go/private/sdk.bzl
- go/toolchain/BUILD.bazel
- go/toolchains.rst
- tests/bcr/bcr.patch
- tests/core/go_download_sdk/go_download_sdk_test.go
Feature
This PR adds a build flag `--@io_bazel_rules_go//go/toolchain:sdk_version`, that allows changing which go SDK version to use to build targets. Implementation details:
- Each go_sdk now has config_settings that specify different values of `sdk_version`. Eg. a `go1.17.3` SDK would declare a config_setting for `sdk_version="1"`, `sdk_version="1.17"`, `sdk_version="1.17.3"`, and `sdk_version=""`.
- Then each toolchain that is registered for an SDK will have a config_setting_group constraint that combines the above config_settings. In the example given above, the go1.17.3 SDK would have a toolchain that only gets selected if sdk_version is 1, 1.17, 1.17.3 or the empty string (default).
- If sdk_version flag is not …
> Add support for --@io_bazel_rules_go//go/toolchain:sdk_version flag.

- go/tools/gopackagesdriver/bazel_json_builder.go
Bug fix
This PR adds `go_binary` as a supported rule type, fixing a bug preventing features like autocomplete from working when using gopackagesdriver.
Fixes #3270
As discussed in #3270, The current implementation of `bazel_json_builder`
does not handle `go_binary` build rules. This means that when
`gopackagesdriver` attempts to be used on a file that is apart of a
`go_binary`, no build target is produced as the output of `bazel query`.
This prevents downstream utilities (`gopls`) from being able to provide
functionality such as autocompletion support.
I didn't see any tests to update, but let me know if I missed something and I'm happy to make changes.
> Add support for `go_binary` to gopackagesdriver.

- WORKSPACE
Other
We had a flag flip to enforce the use of constraints values from @platforms. `rules_go` still uses the older `bazel_toolchains` that links to RBE which caused the failure when the flag is flipped.
Please see https://github.com/bazelbuild/continuous-integration/issues/1404
> migrating to rbe_preconfig

- docs/go/core/BUILD.bazel
- docs/go/core/rules.bzl
- docs/go/core/rules.md
- go/def.bzl
- go/private/rules/BUILD.bazel
- go/private/rules/cross.bzl
- go/private/rules/transition.bzl
- tests/core/cross/BUILD.bazel
- tests/core/cross/README.rst
- tests/core/cross/non_executable_test.go
- tests/core/cross/sdk_version_test.go
Feature
This PR adds a `go_cross_binary` rule, that allows cross compiling `go_binary` generated targets to different platforms and/or different versions of the go SDK. See #3202 for the desired use case this supports. Implementation details:
- The `go_cross_binary` rule wraps a `go_binary` and transitions on `//command_line_option:platforms` and `@io_bazel_rules_go//go/toolchain:sdk_version` based on the `platform` and `sdk_version` attrs of the `go_cross_binary` rule. 
- Adds testing in `tests/core/cross` that ensures that `go_cross_binary` targets get built for the correct platform and sdk_version.
Fixes #3202
This is the second of two diffs to …
> Add `go_cross_binary` rule for cross-compilation.

- .bazelci/presubmit.yml
- go/private/actions/archive.bzl
- go/private/common.bzl
Feature
Bumping minimal Bazel version to 5.1.0, so we can use `runfiles.merge_all` and `repository_os.arch`, which unblocks #3282
Bazel 5.1.0 is already half a year old
cc @moisesvega
> Bumping minimal Bazel version to 5.1.0

- go/private/sdk.bzl
Bug fix
This PR makes rules_go gets the host architecture repository_ctx, which in turn get it from JVM. This is because Bazel determines default host platform from its JVM https://github.com/bazelbuild/bazel/blob/a380a157f658cc392f66f86b6aba340c461dc408/src/main/java/com/google/devtools/build/lib/bazel/repository/LocalConfigPlatformFunction.java#L63 and https://github.com/bazelbuild/bazel/blob/577cfbc8a2b0841cd67a918febe9e3c5fcb3882e/src/main/java/com/google/devtools/build/lib/util/CPU.java#L56
If rules_go determines the host platform by calling `uname`, we may run into an interesting situation when users accidentally runs an ARM64 version of Bazel binary, with comes with ARM64 JVM, in a terminal with Rosetta …
> Getting architecture from JRE

- MODULE.bazel
`toolchains_to_register` is deprecated.
> bzlmod: Use register_toolchains

- go/private/common.bzl
> Other
This appears completely unused, and it's in a private package. It confused me a bit when searching around for env var handling.
Fixes #
> Remove unused env_execute

- go/private/rules/library.bzl
- go/private/rules/test.bzl
Bug fix
This is required with coverage_output_generator v2.6 used by Bazel@HEAD, which filters LCOV files to contain only those source mentioned in the provider.
Fixes #3293
> Correctly forward InstrumentedFilesInfo from dependencies

- go/private/sdk.bzl
Bug fix
The top-level `VERSION` file does not exist in all Go SDK distributions, e.g. those shipped by Debian or Fedora.
Fixes #3295
> Parse Go SDK version out of `go version` instead of `VERSION`

- go/tools/bzltestutil/wrap.go
Without this, people are forced to look in the test.log file for output to stderr, rather than test.xml.
Allow finding all relevant test output in `test.xml` instead of requiring a look in `test.log`.
Fixes #3298.
> also write test stderr to json (xml) output file

- go/private/BUILD.sdk.bazel
- go/private/sdk.bzl
- go/toolchains.rst
- tests/core/go_download_sdk/go_download_sdk_test.go
Feature
See linked issue.
Fixes https://github.com/bazelbuild/rules_go/issues/3302.
> Allow to select Go SDK version from declared SDKs

- go/private/sdk.bzl
Other
Instead of calling `go version` unconditionally, we can check the existence of the VERSION file first. It's more efficient.
This is a follow-up for #3296.
> Use top level VERSION file when it exists

- go/private/sdk.bzl
https://golang.org/dl/ redirects to https://go.dev/dl/.
>
> Bug fix
> Feature
> Other
Fixes #
> update version manifest URL

- go/private/sdk.bzl
Bug fix
Adds a symlink to the `misc` directory in the implementation for local SDKs, so that the wasm files can be picked up.
Fixes #3312
> Symlink "misc" into repository for local_sdk.

- .bazelci/presubmit.yml
- .bazelrc
- go/platform/list.bzl
- go/private/BUILD.bazel
- go/private/BUILD.sdk.bazel
Other
https://github.com/bazelbuild/bazel/issues/8195
https://github.com/bazelbuild/bazel/issues/12932
https://github.com/bazelbuild/bazel/issues/12933
> Ensure compatibility with incompatible flags close to flipping

- .bcr/config.yml
- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
This uses the https://github.com/bazel-contrib/publish-to-bcr app.
> bzlmod: Set up automated BCR releases

- go/tools/gopackagesdriver/aspect.bzl
- go/tools/gopackagesdriver/flatpackage.go
Previously only ".s" assembly files were separated. There are other non-Go file types that could exist in a pkg dir so this handles them all and stores them in the OtherFiles package field as defined in
https://github.com/golang/tools/blob/91311ab3b8fbb39d8d1df146082b6313ec6e2d55/go/packages/packages.go#L314.
An example output snippet with the new logic against https://github.com/hybridgroup/gocv (trimmed for readability):
```
"GoFiles":
[
"/<usr>/.cache/bazel/_bazel_russomichael/0961bbf0241ac3833db3822167eb7327/external/io_gocv_x_gocv/calib3d.go",
...
"/<usr>/.cache/bazel/_bazel_russomichael/0961bbf0241ac3833db3822167eb7327/external/io_gocv_x_gocv/videoio_string.go"
],
"CompiledGoFiles":
[
"/<usr>/.cache/bazel/_bazel_russomichael/0961bbf0241ac3833db3822167eb7327/external/io_gocv_x_gocv/ca …
```
> gopackagesdriver: move non-Go files to OtherFiles (Fixes #3326)

- .bazelci/presubmit.yml
Versions yanked from the BCR would otherwise non-hermetically fail our pipelines.
> bzlmod: Allow yanked versions in CI

- go/tools/gopackagesdriver/bazel_json_builder.go
- go/tools/gopackagesdriver/main.go
Feature
adds two new env variables for the packages driver:
- `GOPACKAGESDRIVER_BAZEL_KINDS`: Tells the packages driver to also query for the specified kinds alongside `go_default_(binary|library|test)`
- `GOPACKAGESDRIVER_BAZEL_ASPECT`: Lets the consumer define a custom aspect, to support querying these other kinds
Combining these two, users can add support for custom rules which consume and emit Go files in a nonstandard way. At Uber, for example, we have a code generator uses a Go file as its source and generates a matching Go file with inlined content. 
Having both of these Go files in the resulting `GoArchive` will not work for the Go compiler (since they define the same variables/methods/structs/..), which in …
> feat(pkg-drv): allow setting custom aspect and kinds

- go/tools/gopackagesdriver/bazel_json_builder.go
- go/tools/gopackagesdriver/main.go
Other
In #3328 I made it so defining an aspect would overwrite the default one defined by rules_go. This means the custom aspect would need to duplicate the rules_go code and potentially manually merge any changes we do in rules_go every release.
Talking with @linzhp , he indicated that you can pass more than one aspect to `--aspects`, so in this case when additional aspects are defined they will be passed in and can export similar info to the default aspect.
> fix(packages-driver): allow defining additional aspects instead

- go/private/sdk.bzl
Bug fix
The previous code assumed that the output of `go version` was of the form:
```text
go version go1.18.3 linux/amd64
```
However, it can also potentially be of the form:
```text
go version devel go1.19-fd1b5904ae Tue Mar 22 21:38:10 2022 +0000 linux/amd64
```
Therefore, rather than reading the third argument to find the version (1.18.3 in this case), we instead now read the fourth argument if the third argument is `devel`.
Fixes #3331
> Add support for parsing Go development versions

- go/private/platforms.bzl
Bug fix
It matches GOARCH ppc64 to something so that rules_go would work on linux/ppc64.
Fixes #3335
ppc64 is the big endian version of 64-bit PowerPC.
While it is not very common these days, I think it makes sense to support ppc64 as long as Go itself supports ppc64.
> Match GOARCH ppc64 to @platforms//cpu:ppc as well.

- go/tools/gopackagesdriver/main.go
Bug fix / minor enhancement (?)
Default the driver response with `NotHandled` set to `true` so that if any errors are encountered during `bazel query` or otherwise, the language server will fallback to its default implementation.
Fixes #3334 by telling gopls to fallback if the gopackagesdriver can't `bazel query` about the requested file.
No other change is needed because any driver response with actual contents will be populated with `false` here: https://github.com/bazelbuild/rules_go/blob/master/go/tools/gopackagesdriver/json_packages_driver.go#L54
> gopackagesdriver: default to NotHandled:true for package queries

- go/tools/gopackagesdriver/bazel_json_builder.go
Bug fix
#3054 provides a suggested solution for resolving third party code. Made some adjustments to make it work and tested it with the following known cases:
- files in root of an external dependency: `external/com_github_package/file.go` (Resolves to `@com_github_package//:file.go`)
- files in subtree:  `external/com_github_package/sub/tree/file.go` (Resolves to `@com_github_package//sub/tree:file.go`)
- Any cases I missed for externals?
Fixes #3054
> fix(packagesdrv): resolve third party go packages

- go/runfiles/fs.go
- go/runfiles/global.go
- go/runfiles/runfiles.go
- tests/runfiles/fs_test.go
- tests/runfiles/runfiles_test.go
- tests/runfiles/testprog/main.go
Improves consistency with other runfiles libraries.
> Rename `Path` to `Rlocation` in runfiles library

- .bcr/source.template.json
This field is required even if its value is empty.
> bzlmod: Add missing `strip_prefix` field to `source.template.json`

- MODULE.bazel
- go/def.bzl
- go/private/BUILD.sdk.bazel
- go/private/BUILD.toolchains.bazel
- go/private/go_toolchain.bzl
- go/private/sdk.bzl
- go/toolchains.rst
Other (performance improvement)
Declares toolchains in a separate repository. For instance, if the SDK repository is `@go_sdk`, the toolchain rules will be defined in `@go_sdk_toolchains`. This avoids eagerly fetching `@go_sdk`, fixing #3196.
One caveat: `:sdk_version_setting` needs to be defined in the same repo as the toolchain rule, e.g. in `@go_sdk_toolchains`. I tried `target_settings = "@go_sdk//:sdk_version_setting"`, but that causes `@go_sdk` to be eagerly fetched again.
This means that `@go_sdk_toolchains` needs to know the SDK version. There are two possibilities:
* The user specifies the version up front, for instance via `go_register_toolchains(version = ...)`. In that case, `@go_sdk_toolchains` uses this …
> Declare toolchains in a separate repository

- go/private/tools/path.bzl
- tests/core/go_path/BUILD.bazel
- tests/core/go_path/cmd/bin/BUILD.bazel
- tests/core/go_path/pkg/lib/BUILD.bazel
- tests/core/go_path/pkg/lib/lib.go
When embedded files are generated, relativize fails because the file path starts with the output directory. Without the change in path.bzl, the test case fails as follows:
Error in fail: Path 'bazel-out/darwin-fastbuild/bin/tests/core/go_path/pkg/lib/renamed_embedded_src.txt' is not beneath 'tests/core/go_path/pkg/lib'
Bug fix
Fixes #3284
> go_path: support go:embed of generated files

- docs/go/extras/extras.md
- extras/bindata.bzl
- extras/embed_data.bzl
- extras/embed_data_deps.bzl
The deprecation warnings weren't complete and linked to an unrelated docs page.
> Properly deprecate `bindata`, `go_embed_data`, and `go_embed_data_deps`

- go/tools/gopackagesdriver/bazel_json_builder.go
Feature
When an IDE like VIM or VSCode queries for packages, some of these packages might report generated code as an import. When that import is followed we're now inside `bazel-out`, which means if the IDE wants to query for packages for this file (often the case in VIM, whereas VSCode tends to cache results better), the query will fail:
```
▶ echo {} | ./tools/gopadrv.sh file=/home/user/.cache/bazel/_bazel_jamy/b97476d719d716accead0f2d5b93104f/execroot/__main__/bazel-out/k8-fastbuild/bin/idl/path/to/pkg/pkg_go_thriftrw_/path/to/pkg/name/type/thriftrw-gen.go
INFO: Analyzed target @io_bazel_rules_go//go/tools/gopackagesdriver:gopackagesdriver (101 packages loaded, 9265 targets configured).
INFO: Found 1 target... …
```
> feat(pkg-drv): add support for generated files

- proto/core.rst
Documentation
https://github.com/bazelbuild/bazel/issues/3867 is fixed, so
instructions for vendored proto files need to be updated.
> Update docs regarding vendored proto files

- go/private/actions/link.bzl
As of clang 15.0.3 (via zig v0.10), when building with `race = "on"` on x86_64 Linux, we observe the following:
runtime/cgo(.text): relocation target memset not defined
Using an external linker when in race mode fixes that. Previously `linkmode=external` was set for windows-only race builds, now lets just apply it indiscriminately.
From my past experience, reporting a Go linker error when the external linker works has a high chance to get the ticket closed as unactionable; so it makes sense to just use an external linker, when it works.
> Bug fix
> go link: use external linker when in race mode

- go/tools/gopackagesdriver/bazel.go
- go/tools/gopackagesdriver/bazel_json_builder.go
- go/tools/gopackagesdriver/main.go
Bug fix
General bazel flags (eg `--output_base`) are required to be set before the action/command you'd like to run.
This PR adds the bazelFlags that are defined by the `GOPACKAGESDRVER_BAZEL_FLAGS` env variable into the Bazel struct, so we can prefix them ahead of the command to be ran. `GOPACKAGESDRVER_BAZEL_BUILD_FLAGS` and `GOPACKAGESDRVER_BAZEL_QUERY_FLAGS` are still appended at the end.
```
▶ bazel info --output_base=/some/path 
ERROR: --output_base=/some/path :: Unrecognized option: --output_base=/home/user/.cache/bazel/_bazel_jamy/b97476d719d716accead0f2d5b93104f_pkgdrv
▶ bazel --output_base=/some/path info 
bazel-bin: /some/path/execroot/__main__/bazel-out/k8-fastbuild/bin
bazel-genfiles: …
```
> fix(packagesdriver): bazelFlags should prefix the command

- go/tools/gopackagesdriver/aspect.bzl
Other
When people define custom aspects using my changes in #3328 it may be useful to use these common utils in those aspects without repitition.
N/A
> chore(gpd): export aspect utils for reusability

- go/nogo.rst
- go/tools/builders/nogo_main.go
- tests/core/nogo/custom/custom_test.go
This is useful for situations where you want to exclude/include the same directories for all the analyzers. Specifying a config for a particular analyzer will cause the _base config, if it exists, to be underlayed for that analyzer (ie, if the analyzer doesn't set an option, it will use the options specified by the _base config).
You can use it like so:
```
{
"_base": {
"exclude_files": {
"external/": "third_party",
"proto/": "generated protobuf"
}
},
"override":
"description": "oops, I actually don't want to exclude any files here...",
"exclude_files": {}
}
}
```
Feature
nogo: Add a _base key to be a default config for all Analyzers.
Partially addresses #2513
**Other notes for …
> nogo: Add a _base key to be a default config for all Analyzers.

- go/runfiles/runfiles.go
- tests/runfiles/runfiles_test.go
The check incorrectly discarded paths such as `foo/..bar`.
Also improve error messages.
Fixes #3374
> Fix normalization check for `Rlocation` path

- MODULE.bazel
- go/def.bzl
Depends on #3380 being merged first.
Suggested release notes:
```markdown
- Support fetching packages for generated code in the Go Packages Driver
- fix(gpd): Write large target patterns to file (#3372) by @JamyDev
- Fix normalization check for Rlocation path (#3378) by @fmeum
- Document that Rlocation can return relative paths (#3377) by @fmeum
- nogo: Add a _base key to be a default config for all Analyzers. (#3351) by @DolceTriade
- chore(gpd): export aspect utils for reusability (#3373) by @JamyDev
- fix(packagesdriver): bazelFlags should prefix the command (#3371) by @JamyDev
- Adding first example (#3317) by @chrislovecnm
- go link: use external linker when in race mode (#3370) by @motiejus
- Upgrade googleapis to 2022-11-21 by @linzhp
- Update README to use latest rules_go and …
```
> Release 0.37.0

- .bcr/metadata.template.json
Fixes https://github.com/bazelbuild/bazel-central-registry/pull/311#discussion_r1041304177
> bzlmod: Add missing repository metadata

- .bazelci/presubmit.yml
- examples/basic-gazelle/WORKSPACE
- examples/basic-gazelle/pkg/roll/BUILD.bazel
> examples: Update rules_go version for incoming incompatible change

- go/tools/builders/compilepkg.go
- go/tools/builders/link.go
If a compilation fails and we need to invoke an intermediate step, we need to ensure the intermediate files are available.
`-work` is meant exactly for that, but it is not always consulted. Lets consult it for a couple more files too.
> preserve intermediate files if `-work` is specified

- tests/core/coverage/lcov_coverage_test.go
`exec.Command` no longer implicitly looks in the current directory with Go 1.19.
> Adapt `lcov_coverage_test` to `exec.Command` change

- tests/core/coverage/lcov_coverage_test.go
filepath.Join(".", "Tool") is just "Tool" because the path is cleaned.
See https://go.dev/play/p/R1KWJ9612fN.
Build the relative path explicitly using "." + string(filepath.Separator) + "Tool".
> explicitly build relative path for Tool command in lcov_coverage_test

- WORKSPACE
- go/private/BUILD.sdk.bazel
- go/private/actions/compilepkg.bzl
- go/private/actions/link.bzl
- go/private/actions/stdlib.bzl
- go/private/providers.bzl
- go/private/rules/sdk.bzl
- go/private/sdk.bzl
- go/tools/builders/compilepkg.go
- go/tools/builders/link.go
- go/tools/builders/stdlib.go
- tests/core/boringcrypto/BUILD.bazel
- tests/core/boringcrypto/README.rst
- tests/core/boringcrypto/boringcrypto_test.go
- tests/core/coverage/lcov_coverage_test.go
Adds an option to go_register_toolchains and the various go_*_sdk functions to specify boringcrypto = True. Doing so builds the standard library and all library/binary packages using the GOEXPERIMENT=boringcrypto environment variable setting, which switches out the crypto implementation for boringcrypto on Go 1.19+.
> Feature
It adds support for building with boringcrypto, which was added in Go 1.19.
Fixes #
> Add support for building with boringcrypto

- go/private/BUILD.sdk.bazel
- go/private/actions/compilepkg.bzl
- go/private/actions/link.bzl
- go/private/actions/stdlib.bzl
- go/private/providers.bzl
- go/private/rules/sdk.bzl
- go/private/sdk.bzl
- go/toolchains.rst
- go/tools/builders/compilepkg.go
- go/tools/builders/link.go
- go/tools/builders/stdlib.go
- tests/core/boringcrypto/boringcrypto_test.go
The new `experiments` parameter on all SDK rules can now be used to enable Go experiments. This subsumes the previously special-cased `boringcrypto` support and allows us to push the duty to match the Go SDK version on the user.
> Generalize `boringcrypto` to `GOEXPERIMENT` support

- extras/bindata.bzl
- extras/embed_data.bzl
Become compatible with
`--incompatible_disable_starlark_host_transitions`, which will be
flipped in Bazel 7.
Work towards https://github.com/bazelbuild/bazel/issues/17032
(fixing the issue requires rules_go and bazel-gazelle releases)
> Replace `cfg = "host"` with `cfg = "exec"`

- go/private/rules/nogo.bzl
Bug fix
With --use_top_level_targets_for_symlinks, which is enabled by default in Bazel 6.0.0, self-transitioning top-level targets prevent the bazel-bin convenience symlink from being created. Since nogo targets are of this type, their presence would trigger this behavior. Work around this by excluding them from wildcards - they are still transitively built as a tool dependency of every Go target.
Fixes #3409
> Mark `nogo` targets as `manual` to keep top-level symlinks

- go/private/actions/link.bzl
- go/private/context.bzl
Refactoring
The original issue that this PR was trying to fix was fixed on zig side. This PR is reduced to a refactoring to:
* avoid adding both `-linkmode internal` and `-linkmode external` in some corner cases
* avoid using `-linkmode external` when external linker is not available
* add C toolchain to go_context as long as it's available, deferring to the link action to decide whether it should be passed down to the linker. This gives us more flexibility later on, for example, to use external linker even in pure mode.
> Refactoring the extld related logic

- MODULE.bazel
In practice, now that Bazel 6.0.0 has shipped, rules_go is working about as well as any other supported languages in the ecosystem. Also, if users find bugs with it, those are important and we'll fix them.
> chore: remove experimental warning from bzlmod module

- go/private/actions/archive.bzl
- go/private/actions/compilepkg.bzl
- go/private/rules/test.bzl
- go/tools/builders/compilepkg.go
- go/tools/builders/importcfg.go
Bug fix
Previously, we filtered out dependencies that needed recompiling (depend on embedded library) since internal tests can't import anything that imports itself.
However, if there is a dependency cycle that imports the embedded library transitively, a misleading error is thrown about the dependency not being provided when found in the import list.
```
Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
/private/var/tmp/_bazel_zplin/1b23f78923ad6c0028e8aab1a0a6d5fb/sandbox/darwin-sandbox/2/execroot/__main__/imports/client_test.go: import of "github.com/linzhp/bazel_examples/imports/testutils"
No dependencies were provided.
Check that imports in Go sources match …
```
> Add a clarifying error about dependency cycle found for internal tests

- .bazelci/presubmit.yml
- README.rst
- go/BUILD.bazel
- go/private/common.bzl
- go/private/rules/go_bin_for_host.bzl
- go/tools/BUILD.bazel
- go/tools/go_bin_runner/BUILD.bazel
- go/tools/go_bin_runner/main.go
- go/tools/go_bin_runner/process.go
- go/tools/go_bin_runner/process_unix.go
- tests/integration/go_bin_runner/BUILD.bazel
- tests/integration/go_bin_runner/go_bin_runner_test.go
This allows developers to use the `go` command provided by the registered toolchain to e.g. add dependencies to `go.mod`. This ensures that everyone uses the same version of Go and does not require a local installation of Go.
> Make the toolchain's `go` binary available as a target

- go/private/repositories.bzl
- third_party/go_googleapis-gazelle.patch
Other
The go_googleapis upgrade in 0.38.0 is too disruptive. It changes the Go import paths of the proto packages like `@go_googleapis//google/cloud/dialogflow/cx/v3` and `@go_googleapis//google/cloud/dialogflow/v2`, making it necessary to change a large number known imports in Gazelle (https://github.com/bazelbuild/bazel-gazelle/pull/1426), which means that people may not be able to upgrade to rules_go 0.38.0 until we release another version of Gazelle.
In addition, it requires other 3rd party packages to use the new import paths too. For example, it requires people to upgrade cloud.google.com/go/dialogflow/apiv2 to at least v1.19.0, which is less than 3 months old, to use the new import path.
We should explore a …
> Revert go_googleapis upgrade

- go/private/rules/transition.bzl
Refactoring
Transition labels are properly repo mapped with Bazel 5.4.0.
> Remove `filter_transition_label` workaround

- .bazelrc
- WORKSPACE
With bazel 7.x the darwin toolchain that supports iOS / Objective-C is moving out of bazel and into apple_support. This adds that toolchain since it's exercised for tests.
> Add new darwin CC toolchain for tests

- go/def.bzl
- go/private/BUILD.bazel
- go/private/BUILD.sdk.bazel
- go/private/BUILD.toolchains.bazel
- go/private/go_toolchain.bzl
- go/private/platforms.bzl
- go/private/sdk.bzl
Refactoring
As a macro, the code is cleaner and easier to reuse. In a follow-up change, it will be used to simplify toolchain registration with Bzlmod.
This commit also removes the public `declare_toolchains` macro. It seems to have been public only because it was accessed by the generated SDK repos. It has never been documented and subject to backwards incompatible changes in recent releases.
> Extract generated code from BUILD.toolchains.bazel into a macro

- docs/go/core/defines_and_stamping.md
- go/private/context.bzl
- tests/core/go_test/x_defs/BUILD.bazel
- tests/core/go_test/x_defs/x_defs_lib.go
- tests/core/go_test/x_defs/x_defs_test.go
Feature
Allows embedding rlocationpaths into binaries to allow them to find dependencies at runtime even when run from other tools, meaning that `args` and `env` can't be used for this purpose.
> Expand locations in `x_defs` values

- docs/go/core/defines_and_stamping.md
- go/BUILD.bazel
- go/private/context.bzl
- go/private/rules/go_bin_for_host.bzl
- go/tools/go_bin_runner/BUILD.bazel
- go/tools/go_bin_runner/main.go
- tests/core/go_test/x_defs/BUILD.bazel
- tests/core/go_test/x_defs/x_defs_lib.go
- tests/core/go_test/x_defs/x_defs_test.go
- tests/integration/go_bin_runner/go_bin_runner_test.go
Feature
Allows developers to build their own local convenience scripts around `go`, e.g. to run `go mod tidy` backed by a hermetic Go toolchain and without the need to hardcode the name of an SDK repository, which we want to get away from with Bzlmod.
This requires getting rid of the `env` attribute as it is not evaluated if the binary is run as a dependency of another target.
Since `//go` select a Go SDK suitable for the host, not the exec platform, we forbid its use in the exec configuration. As remarked in https://github.com/bazelbuild/rules_go/issues/2255, using raw `go` in a genrule is not a good idea to start with. …
> Make `//go` usable in scripts run with `bazel run`

- go/private/sdk.bzl
Bug fix
Previously, `go_sdk` would always restart after fetching and extracting the SDK, as seen in Bazel profiles:
The effectively doubles the amount of time it takes to run the rule implementation. [Repository rule restarts](https://docs.bazel.build/versions/5.0.0/skylark/repository_rules.html#when-is-the-implementation-function-executed) are discussed in https://github.com/bazelbuild/bazel-gazelle/issues/1175 but not resolved for `go_sdk`, or maybe this particular restart is a regression since that issue was resolved.
By adding debug `print`s, I determined that the restart is caused by this line:
https://github.com/bazelbuild/rules_go/blob/89e3296c36b789e8623e1178a59506547a98419e/go/private/sdk.bzl#L440
Moving the …
> Avoid repository rule restarts in go_sdk

- go/private/mode.bzl
Bug fix
Previously this would fail only during linking with an error such as:
```
external/go_sdk/pkg/tool/linux_amd64/link: internal linking requested but external linking required: buildmode=shared
```
> Improve error when linkmode requires cgo

- go/private/rules/cross.bzl
Bug fix
It confused users that this rule always created a file called `error`.
Fixes #3480
> Rename `error` script in `go_cross_binary`

- go/private/rules/transition.bzl
Reduces the number of distinct configurations as the order and multiplicity of tags doesn't matter.
> Canonicalize tags before transitioning

- go/private/rules/transition.bzl
- go/tools/internal/stdlib_tags/BUILD.bazel
- go/tools/internal/stdlib_tags/stdlib_tags.go
Bug fix
Since 8d309d5, all `gotags` were cleared from the configuration when building the standard library. This is not correct as some tags, such as `timetzdata`, do affect the standard library build.
This commit adds a tool that scrapes the list of build tags relevant for the standard library from Go SDK sources and keeps those tags that are relevant for Go 1.18-1.20.
Fixes #3456
> Keep build tags that affect the stdlib build

- go/tools/builders/env.go
- go/tools/builders/stdlib.go
- go/tools/builders/stdliblist.go
Bug fix
The `cgo` tool splits `CC` on unquoted whitespace, which can cause failures on Windows when `CC` points to an absolute path such as `C:\Program Files\some\compiler.exe`.
> Quote `CC` if it contains whitespace

- MODULE.bazel
- README.rst
- go/def.bzl
- go/private/repositories.bzl
- third_party/com_github_gogo_protobuf-gazelle.patch
- third_party/com_github_golang_mock-gazelle.patch
- third_party/com_github_golang_protobuf-gazelle.patch
- third_party/org_golang_google_genproto-gazelle.patch
- third_party/org_golang_google_protobuf-gazelle.patch
- third_party/org_golang_x_sys-gazelle.patch
- third_party/org_golang_x_xerrors-gazelle.patch
Prepare lease 0.39
This diff updates all dependencies in go/private/repositories.bzl **_except_** for `@go_googleapis`
This is because of issues relating to https://github.com/bazelbuild/bazel-gazelle/issues/1422
When tested downstream, many build failures arise from this upgrade. Therefore, we are keeping the version of this dependency stagnant while a better solution to these dependencies is explored. 
This PR was accomplished by running:
```
bazel run //go/tools/releaser -- upgrade-dep -mirror=false all      
```
And then reverting the changes to `@go_googleapis` and its patches.
This change was tested downstream in Uber's Go Monorepo
> prepare release 0.39

- .bazelrc
- WORKSPACE
This reverts #3460.
Bug fix
Revert cd9817098856f6b993937c2dd794a69850cd90ea to unblock rules_go release
Fixes #3498
@keith FYI
> Revert "Add new darwin CC toolchain for tests (#3460)"

- MODULE.bazel
Other
By updating gazelle to a version that maintains a central registry of gazelle overrides, specifying `build_file_proto_mode` on `github.com/gogo/protobuf` is no longer necessary.
This will allow us to get rid of the rules_go exception after the next rules_go release.
Fixes #
> bzlmod: Remove `build_file_proto_mode` attribute

- go/private/sdk.bzl
Bug fix
After 89e3296c36b789e8623e1178a59506547a98419e, we have renamed
_go_download_sdk to go_download_sdk_rule so that we could re-use the
implementation inside the Bazel Module Extension setup.
Update go_register_toolchains to pick up this change.
Fixes #3510
> go_register_toolchains: update sdk_kinds

- go/private/actions/BUILD.bazel
- go/private/actions/stdlib.bzl
- go/private/sdk.bzl
Bug fix
#3398 allowed people to use boringcrypto on 1.19 by ignoring the pre-compile stdlib when boringcrypto is request. However, #3401 over generalized the intention by ignore pre-compile stdlib for all experimental flags for all Go versions. In addition, rules_go add a "nocoverageredesign" experimental flag for Go 1.20. This means rules_go always ignores pre-compiled stdlib that users provide, even it's compiled correctly.
This restore the intention of #3398 by only ignoring pre-compiled stdlib on Go 1.19 with experiments. This allows people to add precompiled stdlib on 1.20+ to improve build performance.
> Ignore pre-compiled stdlib only on 1.19 with experiments

- go/private/actions/BUILD.bazel
- go/private/actions/compilepkg.bzl
- go/private/actions/stdlib.bzl
- go/private/actions/utils.bzl
- go/tools/builders/stdlib.go
Bug fix
When `//go/config:gc_goopts` is provided by user, we should also pass those flags to `go install` command when we are building stdlib. This PR also ignores the pre-compiled stdlib when `go_goopts` is provided, assuming the pre-compiled stdlib is compiled without any custom `go_goopts`.
> Pass gc_goopts to stdlib

- go/private/actions/stdlib.bzl
- go/private/common.bzl
- go/private/context.bzl
Bug fix
We never compile CGo with coverage instrumentation and the stdlib contains no user-provided C/C++ code, so linking coverage runtimes is never needed.
Work towards #3472 
(fixing the issue requires a change to Bazel)
> Drop coverage linker flags from stdlib build

- .bazelci/presubmit.yml
This was flipped in bazelbuild/continuous-integration#1579, but breaks `//tests/core/cgo:versioned_dylib_test`.
> Fix macOS CI after `--remote_download_minimal` flip

- .bazelci/presubmit.yml
Fixes failures such as:
https://buildkite.com/bazel/rules-go-golang/builds/5066#01878f4b-c637-4080-b1df-47ff2e0e5f63/276-300
caused by https://github.com/bazelbuild/continuous-integration/pull/1585.
> Fix Ubuntu CI after --remote_download_toplevel flip in Bazel CI 

- go/private/rules/binary.bzl
>
Bug fix
> Feature
> Other
On darwin, in repositories with many transitions configured such as
rules_go.git, the action GoToolchainBinaryBuild could be run multiple
times in parallel by Bazel.
Each of these actions would execute a command like this in a sandbox:
```
$GO build -o $OUTPUT -trimpath \
go/tools/builders/ar.go \
go/tools/builders/asm.go \
go/tools/builders/builder.go \
go/tools/builders/cgo2.go \
go/tools/builders/compilepkg.go \
go/tools/builders/cover.go \
go/tools/builders/edit.go \
go/tools/builders/embedcfg.go \
go/tools/builders/env.go \
go/tools/builders/filter.go \
go/tools/builders/filter_buildid.go \
go/tools/builders/flags.go \ …
```
> go_tool_binary: set GOMAXPROCS to 1

- README.rst
- docs/go/core/bzlmod.md
Documentation
Adds documentation on the Bzlmod API provided by rules_go and Gazelle.
> bzlmod: Add dedicated documentation

- go/tools/builders/generate_test_main.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/sharding_test.go
Bug fix
Bazel claims to check that this file has been touched when sharding tests. It currently doesn't, but that will change soon.
> Create TEST_SHARD_STATUS_FILE when sharding tests

- .bazelci/presubmit.yml
- .bazelrc
This simplifies the CI config and also ensures that the recent BwoB flip in CI is disabled in all runs.
> Move CI flags to .bazelrc and fix BwoB build

- .bazelci/presubmit.yml
>
Bug fix
Re-enable GoPath action to test against RBE now that symlinks are handled correctly.
Fixes #
> Re-enable go_path_test on RBE

- go/nogo.rst
>
> Bug fix
> Feature
Documentation
> Other
Explain basic usage of nogo to new user.
Also provide a quick comparison between `nogo` and other popular linters
such as golangci-lint
> nogo: provide usage doc

- BUILD.bazel
- go/config/BUILD.bazel
- go/modes.rst
- go/private/BUILD.bazel
- go/private/actions/link.bzl
- go/private/context.bzl
- go/private/rules/transition.bzl
- tests/core/strip/BUILD.bazel
- tests/core/strip/README.rst
- tests/core/strip/strip_test.go
Bug fix
The docs currently state:
> Strips symbols from compiled packages and linked binaries (using the ``-w`` flag). May also be set with the ``--strip`` command line option, which affects C/C++ targets, too.
This is not true. This option cannot be set at all (as far as I can tell). It is currently not exposed as a config flag and the global bazel option for stripping is not considered either.
This PR removes the `@io_bazel_rules_go//go/config:strip` config setting and always uses the global bazel setting `--strip` and `--compilation_mode` to deduce if stripping should be enabled.
As a little extension, I also changed the linker flags to also include `-s` if stripping is enabled.
**Which issues(s) does this PR …
> respect global strip config

- go/private/actions/stdlib.bzl
- go/tools/builders/stdliblist.go
Bug fix
The stdlib json currently is not populated with generated files. When CGO is being used, this means that the file list returned does not actually compile. This change adds `-compiled=true` to go list's output which results in the full set required to compile stdlib.
Fixes #3523
See #3524 for the companion PR.
> stdliblist: return generated files

- go/nogo.rst
https://github.com/bazelbuild/rules_go/pull/3534 left over some badly formated bullet points.
> Fix formatting in nogo usage doc

- go/private/actions/compilepkg.bzl
- go/private/actions/link.bzl
- go/private/actions/stdlib.bzl
- go/private/context.bzl
- go/tools/builders/compilepkg.go
- go/tools/builders/link.go
- go/tools/builders/stdlib.go
- tests/core/boringcrypto/boringcrypto_test.go
Bug fix
The environment variable `GOEXPERIMENT` must be defined at the execution of the builder.
Without that, the default build context `build.Default` used in the builder to filter files using build constraints will not be able to filter on a `goexperiment.x` build tag.
Fixes #3555
> Fix `goexperiment.*` build tags

- .bazelrc
- WORKSPACE
- tests/core/cross/proto_test.go
- tests/core/transition/hermeticity_test.go
> Fix tests with `--incompatible_disable_starlark_host_transitions`

- go/tools/bazel_testing/bazel_testing.go
- go/tools/builders/compilepkg.go
- tests/core/go_library/BUILD.bazel
- tests/core/go_library/README.rst
- tests/core/go_library/no_srcs_test.go
Bug fix
Isolating the empty `.go` files generated for targets without sources
and removing them after a build turned out not to solve issues with
concurrent unsandboxed builds causing races. Instead, just generate the
file in a temporary location, which for a truly empty file does not
result in (non-hermetic) source file paths being included in the
archive.
Along the way fix a potential source of non-hermeticity in
`go_bazel_test`.
Fixes #3558
> Create empty `.go` file in a random location 

- docs/go/core/bzlmod.md
- Documentation
- This PR fixes a typo that made the docs incorrect. There is no defs.bzl, only [def.bzl](https://github.com/bazelbuild/bazel-gazelle/blob/master/def.bzl).
> Fix typo in load statement for bzlmod docs

- .bazelci/presubmit.yml
- examples/basic-gazelle/.bazelrc
- examples/basic-gazelle/WORKSPACE
Other
Test basic-gazelle example with incompatible flags. Also update the version of Gazelle used by the example to get rid of a usage of `cfg = "host"`.
Fixes #3403
> Test basic-gazelle example with incompatible flags

- go/private/extensions.bzl
- go/private/sdk.bzl
- tests/bcr/MODULE.bazel
Feature
As discussed in [this issue](https://github.com/bazelbuild/bazel-gazelle/issues/1469), this PR makes the `go_sdk` module extension define a new repository called `go_host_compatible_sdk`.
This repository exposes the label of the first host compatible sdk declared by a module via the `download` or `host` tag (according to bazel's iteration order over modules).
The gazelle module could then rely on this toolchain for bootstrapping instead of always using `go_default_sdk`.
This PR is a first step toward closing https://github.com/bazelbuild/bazel-gazelle/issues/1469
- As discussed in the issue, this PR does not yet provide a way do use toolchains …
> go_sdk extension: create `go_host_compatible_sdk` repository

- go/private/sdk.bzl
Bug fix
The version check introduced in the previous commit did not take into account that dev versions of Bazel report an empty version string.
Fixes #3579 
> Fix `go_download_sdk` with Bazel dev versions

- go/tools/builders/BUILD.bazel
- go/tools/builders/nogo_main.go
- go/tools/builders/nolint.go
- go/tools/builders/nolint_test.go
- tests/core/nogo/nolint/BUILD.bazel
- tests/core/nogo/nolint/README.rst
- tests/core/nogo/nolint/nolint_test.go
https://github.com/bazelbuild/rules_go/issues/3561
Look for nolint comments and collect the ranges of where they apply. If a node immediately follows a range with the same column, expand the range to include the node.
Add tests that verify errors are filtered out.
Feature
Parses `//nolint` comments and filters out errors from nogo.
Fixes #3561 
> Implement //nolint parsing similar to golangci-lint

- go/private/actions/link.bzl
- go/private/actions/stdlib.bzl
Bug fix
For our C/C++ we have used --features=fully_static_link to produce static binaries. Prior to Go 1.20 this setting did not leak into the compiled Go binary (when using cgo). This PR restores the behavior we have seen with Go 1.19. For a go_binary we can individually decide whether or not to link it statically.
Fixes #3590
> stdlib: Do not pass -static to cgo

- go/private/actions/stdlib.bzl
- go/tools/builders/stdliblist.go
Bug fix
Defines an output_directory so the generated files get copied to execroot.
Make sure the path passed to GOCACHE are absolute and reverse the path back to execroot after getting the go list output
Fixes #3607
> Fix stdlib file outputs pointing to processwrapper

- go/private/extensions.bzl
Fixes failures such as the following if the root module never calls `module`:
```
go_download_sdk_rule(
Error in repository_rule: invalid user-provided repo name '__download_0': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter
```
> Fix `go_sdk` extension failure for unnamed root module

- proto/wkt/well_known_types.bzl
After https://github.com/bazelbuild/rules_go/pull/3595, @io_bazel_rules_go//proto/wkt only contains alias to pre-generated Go packages. Let's stop referring them so we can eventually remove them.
> replace references to //proto/wkt

- go/tools/builders/generate_test_main.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/filter_test_cases_test.go
Feature
This PR implements the functionality to skip tests via TESTBRIDGE_TEST_ONLY env field. TESTBRIDGE_TEST_ONLY will expect a comma-separated list of regex expressions. A prefix '-' to the regex specifies to excluded test case matching the filter (similar to [instrumentaion_filter](https://bazel.build/reference/command-line-reference#flag--instrumentation_filter).
For example:
To indicate tests to run all the tests except for TestFQNTaskFiler and TestTargetTaskFiler, provide the environment in go_test:
`env = {"TESTBRIDGE_TEST_ONLY":"-^TestFQNTaskFiler$,-^TestTargetTaskFiler$"}`
This is the opposite behavior of the existing behavior `go test -run`.
This is needed in order to skip flaky test cases in CI.
**Which …
> Implement functionality to skip tests via TESTBRIDGE_TEST_ONLY env

- MODULE.bazel
- go/def.bzl
Updating version strings for 0.41.0 release. For this release, I intentionally avoid upgrading dependencies, because we just updated them 2 weeks ago and it might bring additional disruption to an already disruptive release.
This release requires next release of Gazelle; and next release of Gazelle requires this release. @fmeum How to release new versions of two Bazel modules that depends on each other at the same time?
> Preparing 0.41.0 release

- tests/core/output_groups/compilation_outputs_test.go
Bazel now adds the repo mapping manifest to runfiles. It shows up in the output of `ListRunfiles` on Windows, where it should be ignored.
Fixes #3597
> Fix compilation_outputs_test on Windows with Bazel@HEAD

- tests/core/transition/hermeticity_test.go
`exec_tools` is a deprecated alias for `tools` with Bazel 6 and higher and may soon be removed from Bazel.
See https://github.com/bazelbuild/rules_go/issues/3597#issuecomment-1658009675
> Migrate `exec_tools` to `tools` on `genrule`

- tests/core/strip/strip_test.go
In Go 1.21.0, the stack trace contains a question mark `?` for
references.
>
> Bug fix
> Feature
> Other
Fixes #
> strip_test: fix expected stack trace for 1.21.0

- go/tools/gopackagesdriver/json_packages_driver.go
- go/tools/gopackagesdriver/main.go
go/packages is being changed to expect Compiler and Arch in its DriverResponse (see golang.org/cl/516917) because we can't expect the type of the types.Sizes returned by types.Sizes to be types.StdSizes. (The default it uses when Compiler and Arch aren't set is the set of types for gc,amd64, so there's no change in behavior if those fields aren't set, but we should set them. I'd also like to see if we can correctly provide the arch assuming it's not amd64. I left a question in the code asking about that.
For #3656
> go/tools/gopackagesdriver: pass Compiler and Arch in DriverResponse

- go/tools/builders/compilepkg.go
- tests/core/cgo/asm/BUILD.bazel
- tests/core/cgo/asm/asm_amd64.S
- tests/core/cgo/asm/asm_arm64.S
- tests/core/cgo/asm/cgoasm.go
- tests/core/cgo/asm/cgoasm_test.go
>
Bug fix
This changes compilepkg to use the C compiler for .S and .s files to use the C compiler, like go build does. Previously it would use the Go assembler, which is used for pure Go packages. This should help fix issue: https://github.com/bazelbuild/rules_go/issues/3411
I have added a cgo test for this issue that is intended to work with both arm64 and amd64 machines. I have only tested it on Linux amd64 and Darwin arm64. Without this change it fails to build with the following output. This fails to parse the assembly file because it uses the Go assembler.
```
ERROR: rules_go/tests/core/cgo/asm/BUILD.bazel:3:11: GoCompilePkg tests/core/cgo/asm/asm.a failed: (Exit 1): …
```
> compilepkg: cgo assembly uses the C compiler

- go/private/context.bzl
Enforce usage of the current toolchain and avoid downloading new
toolchains during build.
>
> Bug fix
> Feature
> Other
Fixes #
> go_context: set GOTOOLCHAIN to 'local'

- go/private/BUILD.sdk.bazel
- go/private/sdk.bzl
Include go.env file in the root of the sdk repo starting from Go 1.21.0.
Fixes #3665
> sdk.bzl: include go.env since 1.21.0

- go/private/extensions.bzl
Bug fix
Add the `experiments` argument of the `go_sdk.download` and `go_sdk.host` extensions.
This value will be given respectively to the `go_download_sdk_rule` and `go_host_sdk_rule` repository rule.
Fixes #3443
> bzlmod: Add missing experiments argument (#3443)

- go/private/repositories.bzl
- go/tools/fetch_repo/BUILD.bazel
- third_party/org_golang_x_tools_go_vcs-gazelle.patch
This is a part of #3654 that was carved out to make it smaller and easier to understand. 
The vcs part of golang.org/x/tools was removed from tools. The vcs code is still available in a separate module with a version marked as "deprecated". Let's use it for now.
Bug fix
- Use deprecated module golang.org/x/tools/go/vcs (the package was removed from golang.org/x/tools)
You can now upgrade golang.org/x/tools and rules_go will no longer try to use the vcs package from that module.
Note however, that updating golang.org/x/tools still triggers #3640.
To fix this, we need to update `golang.org/x/tools` in rules_go and use the new function signature (as shown in …
> use carved out module for x/tools/go/vcs

- extras/gomock.bzl
Poping argument "mockgen_model_library" from kwarg before passing in to _gomock_prog_exec rule.
Bug fix
For fixing error described in #3673
Fixes #3673
> Fix: update gomock.bzl by poping incompatible argument

- go/private/rules/test.bzl
- go/tools/builders/generate_test_main.go
- go/tools/bzltestutil/BUILD.bazel
- go/tools/bzltestutil/init.go
- tests/legacy/test_chdir/data_test.go
Bug fix
Go 1.21 clarified package initialization order and changed behavior: packages with lexicographically lower paths are now initialized earlier.
We need bzltestutil to initialize before user packages so it can change to the correct directory. To accomplish this, we set an importmap prefix that starts with '+', the lowest allowed character.
Fixes #3675
> bzltestutil: set importmap to fix run_dir

- go/tools/releaser/file.go
- go/tools/releaser/prepare.go
- go/tools/releaser/upgradedep.go
Most rules_go maintainers do not have direct access to Bazel team's
GSC bucket to upload this mirror. Let's disable it by default for
eventually removal.
Mirroring should be done by filing a requests in Bazel.git's Github
issues.
>
> Bug fix
> Feature
> Other
Fixes #
> releaser: turn off upload to mirror by default

- go/private/sdk.bzl
Bug fix
This is required with Go 1.21.1 as the `go` tool reads the `go.env` at the root of the SDK. Instead of explicitly symlinking that file, symlink all files except for the ones that already exist, e.g. because they were added by another SDK rule wrapped with `go_wrap_sdk`.
> Symlink all SDK files with `go_local_sdk`

- MODULE.bazel
- go/private/extensions.bzl
Bug fix
This ensures that the lockfile maintains separate instances of this extension for each OS/arch combination.
> Mark `go_sdk` module extension as `{os,arch}_dependent`

- go/def.bzl
This was accidentally left out of https://github.com/bazelbuild/rules_go/pull/3697
> update rules_go to 0.42.0 in go/def.bzl

- go/private/BUILD.sdk.bazel
- go/private/common.bzl
- go/private/rules/binary.bzl
- go/tools/builders/BUILD.bazel
- go/tools/builders/stdliblist.go
- go/tools/builders/stdliblist_test.go
- go/tools/gopackagesdriver/BUILD.bazel
- go/tools/gopackagesdriver/bazel_json_builder.go
Feature
Makes gopackagesdriver work under Bzlmod by relying on the query flag `--consistent_labels`, which is available in Bazel 6.4.0.
Fixes #3604 
Fixes #3659
> Fix matching between Starlark and query labels in gopackagesdriver

- README.rst
- examples/basic-gazelle/WORKSPACE
- go/toolchains.rst
This PR updates the documentation to reflect the new version of `rules_go` and `gazelle`
> update documentation for `0.42.0` release

- go/private/sdk.bzl
Feature
We want to use go_download_sdk, but it gets an unauthorized failure, so this adds netrc support to go_download_sdk. Our use case only requires using the default netrc, but if desired I can cover more cases like how it's done in [http_archive](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl#L116C10-L116C10)
https://github.com/bazelbuild/rules_go/issues/2560
Fixes #
> add netrc support to go_download_sdk

- .bazelrc
Fixes downstream failures of https://github.com/bazelbuild/bazel/issues/18958 until we complete the migration.
> Temporarily disable Bzlmod explicitly

- go/private/BUILD.sdk.bazel
Speculative fix for user reports of this error message showing up when using `//go`, which indicates that `go.env` is missing:
```
GOPROXY list is not the empty string, but contains no entries
```
Adding `go.env` to the `tools` files of the SDK rather than creating a new field on `GoSDK` for it may end up fixing latent bugs.
https://bazelbuild.slack.com/archives/CDBP88Z0D/p1696892815685419
> Include `go.env` in `//go` runfiles

- go/private/platforms.bzl
Bug fix
Updates the "arm" platform constraint to the latest bazel value - https://github.com/bazelbuild/bazel/issues/14982 for more context
Fixes #3728
> Update arm platform constraint to latest value in bazel.

- extras/gomock.bzl
- go/private/actions/compilepkg.bzl
- go/private/actions/link.bzl
- go/private/actions/stdlib.bzl
- go/private/common.bzl
- go/private/context.bzl
- go/private/go_toolchain.bzl
- go/private/rules/binary.bzl
- go/private/rules/go_bin_for_host.bzl
- go/private/rules/info.bzl
- go/private/rules/library.bzl
- go/private/rules/nogo.bzl
- go/private/rules/source.bzl
- go/private/rules/stdlib.bzl
- go/private/rules/test.bzl
- proto/compiler.bzl
- proto/def.bzl
Other - Migration
It sets go toolchain type inside affected actions. This is part of the migration of Automatic Exec Groups inside Bazel downstream.
Please check https://github.com/bazelbuild/bazel/issues/19981 for additional info.
> Add toolchain param to affected actions

- go.mod
- go.sum
- go/private/repositories.bzl
- go/tools/builders/nogo_main.go
- tests/integration/popular_repos/BUILD.bazel
- tests/integration/popular_repos/README.rst
- third_party/org_golang_x_sys-gazelle.patch
- third_party/org_golang_x_tools-gazelle.patch
>
> Bug fix
> Feature
> Other
```x/tools``` is too old to upgrade the linter such as golangci-linter. 
Fixes #3640
> upgrade tools

- go/private/context.bzl
> Feature
Prepare #3706 such that those changes can live solely within `proto/def.bzl`. This also makes it easier to maintain a downstream patch in order to test possible implementations under a real-world setting before upstreaming such a breaking change.
The `srcs` attribute already follows this approach. This PR only expands it to the `deps` attribute. The default behavior doesn't change.
> Also take library deps like srcs into account in go context

- README.rst
Documentation
It's hard to find `go_cross_binary` unless you already know it exists. This adds it to the relevant sections in the README.
Related thread on Bazel slack: https://bazelbuild.slack.com/archives/CDBP88Z0D/p1698892575577309
> Add go_cross_binary to README

- go/tools/builders/stdlib.go
- go/tools/builders/stdliblist.go
Make the gopackagesdriver work when using a C/C++ toolchain with sysroots. We need to turn the relative in flag like --sysroot into an absolute.
Address the todo by using the code already available in the stdlib.go as part of #1536.
Bug fix
On a high-level this makes gopls and the gopackagesdriver work again for Go versions without a pre-compiled stdlib and using an external toolchain. This is done by turning a "CGO_CFLAGS='--sysroot=external/sysroot'" into an absolute path like it is done in stdlib.go.
Fixes #1357 
I looked at the similarities of stdlib.go and stdliblist.go. We might refactor parts of the environment handling but keeping that …
> builder: Make paths absolute for stdliblist (#1357)

- go/tools/BUILD.bazel
- go/tools/bazel_testing/bazel_testing.go
- go/tools/gopackagesdriver/BUILD.bazel
- go/tools/gopackagesdriver/bazel.go
- go/tools/gopackagesdriver/bazel_json_builder.go
- go/tools/gopackagesdriver/json_packages_driver.go
- go/tools/gopackagesdriver/main.go
- go/tools/gopackagesdriver/packageregistry.go
- tests/integration/gopackagesdriver/BUILD.bazel
- tests/integration/gopackagesdriver/README.rst
- tests/integration/gopackagesdriver/gopackagesdriver_test.go
Other - Test cases
Validates the basic functionality for the Go Packages Driver, and sets up a framework to add additional tests in the future.
Two major changes were needed to support all testing platforms:
- For bazel <6.0 we need to use the old style labels. Currently it would always prefix with @ and fail the lookup on bazel 5.
- For Windows we need to adjust the paths returned from Bazel. I think because we're running inside MINGW the paths are unix like where everything starts with `\`, but `since` Bazel runs in Java it uses regular Windows paths (eg `C:\<some>\<path>`). So if we see a path like `\C:\<some>\<path>` we have to remove the leading `\` for go to be able tom resolve this path.
This should help …
> feat(gopackagesdriver): add base test case for go packages driver

- go/tools/gopackagesdriver/bazel_json_builder.go
Bug fix
Addresses an issue with Gopackagesdriver not using bazelQueryScope.
The packageQuery currently returns a bazel query formatted to find dependencies by import path (line 116, `kind("%s", attr(importpath, "%s", deps(%s)))`), so even if localQuery was restricted to the bazelQueryScope, it would not produce the same required output. It seems this behavior change happened after commit b84cd75.
Fixes #3687 
> Fix bazel query scope not being used

- go/tools/bazel_testing/bazel_testing.go
- go/tools/gopackagesdriver/flatpackage.go
- go/tools/gopackagesdriver/packageregistry.go
- tests/integration/gopackagesdriver/gopackagesdriver_test.go
Feature
xtests, also named external tests, are test cases that validate the public facing API of a package, even though the files are still located in the same package.
A sample folder structure:
> code.go -> `package code` -> has both public and private methods/interfaces of things
> code_test.go -> `package code` -> tests the private logic
> code_ext_test.go -> `package code_test` -> tests the public API
From what I gather, the go compiler is happy to handle this since the package names are different, but when the Go packages driver runs its aspect, we'll get all of this in one FlatPackage (since they're part of the `go_test` rule) with the same package ID. This causes Go internally to mark the `package code_test` …
> Add support for `xtest` packages in Go Packages Driver

- go/private/repositories.bzl
- go/tools/builders/nogo_main.go
- tests/integration/popular_repos/BUILD.bazel
- tests/integration/popular_repos/README.rst
- third_party/org_golang_x_tools-gazelle.patch
The new version of x/tools reverts a breaking change in https://github.com/golang/tools/commit/b9b97d982b0a16d0bc8d95fb1dc654120b0d4940, which will make the release less intrusive. We should upgrade this dependency before releasing the new rules_go version
> upgrade x/tools to 0.15.0

- go/tools/builders/BUILD.bazel
- go/tools/builders/read.go
- go/tools/builders/read_test.go
- go/tools/builders/read_test_fixture.go
Bug fix
Updates the embed parser to parse between single quotes. As it stands, the double quote rune `'"'` effectively halts embed parsing for a given file.
In the first commit, I've added a failing test using a fixture file with the double quote rune. The second commit resolves the failure and fixes the bug.
> bug fix: parse embeds in files that contain the double quote rune

- MODULE.bazel
- WORKSPACE
- go/BUILD.bazel
- go/def.bzl
- go/private/repositories.bzl
- third_party/org_golang_google_genproto-gazelle.patch
- third_party/org_golang_x_sys-gazelle.patch
This PR creates the 0.43.0 release for `rules_go`
> prepare release 0.43.0

- .bcr/presubmit.yml
This platform doesn't support `-std=c++14` with gcc, which is now the default in Bazel.
>
> Bug fix
> Feature
> Other
Fixes #
> Do not test on centos7

- README.rst
- examples/basic-gazelle/WORKSPACE
This PR updates the documentation to reflect the new version of `rules_go` and `gazelle`
> update documentation for 0.43.0 release

- go/tools/gopackagesdriver/flatpackage.go
- tests/integration/gopackagesdriver/gopackagesdriver_test.go
Bug fix
When I made the change to enable xtest style packages, I forgot to also suffix the package path. In certain cases this can make gopls segfault (since it conflicts with the base package). Adding the suffix fixes this issue.
Fixes #
> feat(packagesdriver): add _test suffix to pkgPath

- go/tools/builders/generate_test_main.go
- go/tools/bzltestutil/BUILD.bazel
- go/tools/bzltestutil/timeout.go
- go/tools/bzltestutil/wrap.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/timeout_test.go
Feature
By calling `panic` when a Bazel test times out, which is indicated by Bazel sending a SIGTERM, stack traces of all Go routines are printed, similar to the behavior of native `go test`.
Fixes #3746
> Panic when a test times out

- docs/go/core/bzlmod.md
- go/private/extensions.bzl
Feature
The `go_sdk` module extension now registers unnamed SDKs for all major execution platforms in addition to the host platform. This ensures that Go builds should "just work" if the exec platform is on this list, even if it differs from the host platform.
Fixes https://github.com/bazelbuild/rules_go/issues/3007
Fixes https://github.com/bazelbuild/rules_go/issues/3402
> Automatically register SDKs for common execution platforms

- MODULE.bazel
- go.mod
- go.sum
- go/private/repositories.bzl
- go/tools/releaser/file.go
- go/tools/releaser/upgradedep.go
- proto/BUILD.bazel
- proto/def.bzl
- proto/wkt/well_known_types.bzl
- tests/integration/googleapis/BUILD.bazel
- third_party/org_golang_google_grpc_cmd_protoc_gen_go_grpc.patch
- tools.go
Update
The module [`github.com/golang/protobuf`](https://pkg.go.dev/mod/github.com/golang/protobuf) has been superseded by the [`google.golang.org/protobuf`](https://pkg.go.dev/mod/google.golang.org/protobuf) and [`google.golang.org/grpc`](https://pkg.go.dev/mod/google.golang.org/grpc) modules, which contain an updated and simplified API, support for protobuf reflection, and many other improvements.
The `go_grpc_library()` macro maintains the current behavior of generating both the proto and the service definitions.
Fixes #3022
Supercedes #3437, #3783
> Update to modern protoc plugins

- tests/integration/grpc_plugin/BUILD.bazel
- tests/integration/grpc_plugin/README.rst
- tests/integration/grpc_plugin/hello.go
- tests/integration/grpc_plugin/hello.proto
- tests/integration/grpc_plugin/hello_test.go
Other: adding integration tests
This is a resurrection of https://github.com/bazelbuild/rules_go/pull/3783 now that https://github.com/bazelbuild/rules_go/pull/3761 has been merged. This PR is purely testing. It adds an integration test that exercises some of the novel codegen features of the protoc-gen-go-grpc plugin.
This:
- ensures that the plugin is working properly (and can be extended in order to validate new functionality)
- serves as a bit of "living documentation" for users to demonstrate how to use the new compiler
> Add integration tests for protoc-gen-go-grpc

- .bazelci/presubmit.yml
- BUILD.bazel
- MODULE.bazel
- docs/go/core/bzlmod.md
- go/def.bzl
- go/nogo.rst
- go/private/BUILD.bazel
- go/private/BUILD.nogo.bazel
- go/private/actions/compilepkg.bzl
- go/private/context.bzl
- go/private/extensions.bzl
- go/private/nogo.bzl
- go/private/rules/nogo.bzl
- go/tools/bazel_testing/bazel_testing.go
- tests/bcr/BUILD.bazel
- tests/bcr/MODULE.bazel
- tests/bcr/third_party/BUILD.bazel
- tests/bcr/third_party/lib.go
- tests/core/nogo/bzlmod/BUILD.bazel
- tests/core/nogo/bzlmod/README.rst
- tests/core/nogo/bzlmod/includes_excludes_test.go
- tests/core/starlark/BUILD.bazel
- tests/core/starlark/context_tests.bzl
Feature
See `bzlmod.md` for the details. This change is backwards compatible for WORKSPACE setups, but allows finer control over the set of targets nogo is applied to when using Bzlmod.
Fixes #3529 
> Add Bzlmod support for `nogo`

- go/tools/gopackagesdriver/packageregistry.go
Bug fix
In rare cases the root won't actually have a package in the registry, causing the lookup to panic, and subsequently cause gopls (or other tools) to fail their resolution, and likely try multiple times. 
Fixes #
Will add a test case shortly, hence the draft
> fix(gpd): don't panic on invalid root

- go/private/rules/test.bzl
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/cgo_required_test.go
This is a fairly simple change and the test is also simple. Without the addition test.bzl, the new cgo_required test fails to compile. It's more of a regression test than anything else.
Bug fix
Correctly filters test functions
Fixes #2763 
> Pass env to gentestmain so it will correctly filter

- MODULE.bazel
- go.mod
- go.sum
- go/def.bzl
- go/private/repositories.bzl
- third_party/org_golang_google_grpc_cmd_protoc_gen_go_grpc.patch
This PR prepares the new release of `rules_go` version `0.44.0`.
At this time we can't upgrade `x/tools` because releases after `0.15.0` remove [the persistent package](https://pkg.go.dev/golang.org/x/tools/internal/persistent)
> prepare release 0.44.0

- proto/BUILD.bazel
Suggestion from https://github.com/bazelbuild/rules_go/pull/3761#discussion_r1432062895
> Slightly tweak deprecation wording for //proto:go_grpc

- go/runfiles/directory.go
- go/runfiles/manifest.go
- go/runfiles/runfiles.go
- tests/runfiles/runfiles_test.go
Bug fix
These variables are needed by e.g. the Java launcher even when running with a manifest file. Match the logic of the Bazel-provided runfiles libraries.
Fixes https://bazelbuild.slack.com/archives/C01HMGN77Q8/p1701887957242259
> Always attempt to set RUNFILES_DIR and JAVA_RUNFILES in `runfiles.Env`

- .bcr/metadata.template.json
We need to add this to the `rules_go` file, rather than the BCR file.
[This commit](https://github.com/bazelbuild/bazel-central-registry/commit/3b4a13302dee3a676a07181976a56f6d4fe3dbee) automatically removed the [changes manually added to the BCR.](https://github.com/bazelbuild/bazel-central-registry/commit/f84d372dafb4228e864b867bf512b7ada005399c)
> add maintainers to metadata.json template

- MODULE.bazel
- go/def.bzl
This patch release is to include https://github.com/bazelbuild/rules_go/commit/43c40a9a596fcf37a5b7b0ae5f32832277393587 which reverts a change to forcefully upgrade genproto transitively, which is causing linker failures since `google.golang.org/genproto/googleapis/rpc` was separated from `google.golang.org/genproto`
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
link: package conflict error: google.golang.org/genproto/googleapis/longrunning: package imports google.golang.org/genproto/googleapis/rpc/status
was compiled with: @@gazelle~0.35.0~go_deps~org_golang_google_genproto//googleapis/rpc/status:status
but was linked with: @@gazelle~0.35.0~go_deps~org_golang_google_genproto_googleapis_rpc//status:status
```
> prepare patch release 0.44.1

- .bazelci/presubmit.yml
- go/private/BUILD.bazel
- go/private/context.bzl
- go/private/fake_bazel_features.bzl
- go/private/mode.bzl
- go/private/polyfill_bazel_features.bzl
- go/private/repositories.bzl
- tests/core/cross/BUILD.bazel
- tests/core/starlark/cgo/BUILD.bazel
- tests/core/starlark/cgo/cgo_test.bzl
Bug fix
Currently, if you transition a go_binary, you must have a C++ toolchain
for it even if it's building in pure mode without cgo.
By making this toolchain optional, we push the error from a
toolchain-resolution-time error to an analysis-time error only if a
toolchain is both _needed_ and not found.
This showed up in testing https://github.com/aspect-build/bazel-lib/pull/289
> Make C++ toolchain optional

- go/tools/bzltestutil/wrap.go
- tests/core/race/race_test.go
I believe this can happen because the goroutine is started before the command is started. Start the process first, then on success, start the signal handler. Add a test for regression.
I verified the test fails without my change to wrap.go and the race is from the signal handling goroutine.
Bug fix
It prevents a race detection when a test is timed out. We saw this a bunch and devs were really confused thinking there was a legit race detected.
Fixes #
> Fix a race detected only if a test times out

- go/tools/bzltestutil/timeout.go
Bug fix
Some tests need to send SIGTERM to child processes, which would cause panic in the timeout handler. A way to fix that is to call `signal.Reset(syscall.SIGTERM)` in TestMain to unregister the timeout handler. However, we need to make sure `signal.Reset(syscall.SIGTERM)` is called after `signal.Notify(c, syscall.SIGTERM)` in `RegisterTimeoutHandler()`. This PR moves the `signal.Notify(c, syscall.SIGTERM)` outside the goroutine so it's called synchronously before TestMain
> registering timeout handler synchronously

- proto/def.bzl
Feature
This makes the Gazelle implementation in bazelbuild/bazel-gazelle#1711 easier.
> Allow compilers to be overwritten in go_grpc_library()

- README.rst
- examples/basic-gazelle/WORKSPACE
This PR updates the documentation to reflect the new version of `rules_go` and `gazelle`
> update documentation for 0.44

- proto/BUILD.bazel
Bug fix
Until Gazelle emits `go_grpc_library`.
Work towards https://github.com/bazelbuild/bazel-gazelle/issues/1709
> Temporarily undo deprecation of `//proto:go_grpc`

- go/tools/bzltestutil/lcov.go
- tests/core/coverage/lcov_coverage_test.go
> Fix coverage collection with modified `COVERAGE_DIR` env variable

- go/tools/builders/env.go
Printing out the full command line args when a subcommand fails, so it's easier to debug.
> improving logging for subcommand failure

- MODULE.bazel
- go/def.bzl
This includes various bug fixes from 0.44.0. In the interest of compatibility we are not upgrading any dependencies for this release.
> release rules go 0.45.0

- tests/core/cgo/BUILD.bazel
`go_*` rules do not emit the module map files required for `layering_check`.
Work towards https://github.com/grailbio/bazel-toolchain/pull/246
> Disable `layering_check` feature in CGo tests

- go/tools/bzltestutil/timeout.go
- go/tools/bzltestutil/wrap.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/sigterm_handler_test.go
- tests/core/go_test/timeout_test.go
Bug fix
Feature
It replaces a call to `panic` in the timeout handler to just printing all stack traces, which removes the need to deregister the `SIGTERM` handler when the test relies on particular `SIGTERM` behavior at the cost of having Bazel kill the process after the grace period instead of the `panic` doing it right away.
Also removes the `SIGTERM` forwarding logic from the wrapper as it isn't needed: Bazel sends `SIGTERM` to all child processes.
Related to #3827 
> Print stack traces without panicking on test timeout

- go/tools/builders/compilepkg.go
- tests/core/nogo/generate/empty_test.go
Bug fix
6236dd80670cdfe1477a484e98e3f82dbcc28fe9 regressed the nogo exclusion logic for the empty `.go` file generated for targets that otherwise don't contain any `.go` files. The test had been silently disabled a while ago when the name pattern for the empty file was changed.
This is fixed by reintroducing the exclusion logic and making the test more strict.
Fixes #3828
> Fix regression in empty `.go` file filtering for nogo

- MODULE.bazel
- go/def.bzl
This includes various bug fixes from 0.45.0 and fixes the BCR publishing. In the interest of compatibility we are not upgrading any dependencies for this release.
> release patch version 0.45.1

- BUILD.bazel
- go/BUILD.bazel
- go/constraints/amd64/BUILD.bazel
- go/constraints/arm/BUILD.bazel
- go/private/context.bzl
- go/private/mode.bzl
Feature
This PR introduces support for specifying the ARM architecture level as `GOARM` via platform constraints, mirroring the implementation in #3251 which accomplished a similar objective for `GOAMD64`.
The constraint names are taken from here: https://go.dev/wiki/MinimumRequirements#arm
Fixes #1719
Verification:
`WORKSPACE`:
```starlark
local_repository(
name = "io_bazel_rules_go",
path = "/path/to/rules_go/fork",
)
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
go_rules_dependencies()
go_register_toolchains(version = "1.21.6")
```
`BUILD`:
```starlark
load("@io_bazel_rules_go//go:def.bzl", "go_binary", …
```
> Support custom `GOARM` architecture levels via platform constraints

- go/private/rules/test.bzl
- tests/core/go_test/x_defs/BUILD.bazel
- tests/core/go_test/x_defs/x_defs_lib.go
- tests/core/go_test/x_defs/x_defs_test.go
go_test is split into 2 compilation actions, one for internal test,
where package name of the test is the same with library package.
```bash
package foo
package foo
```
and external test where the package name is different.
```bash
package foo
package foo_test
```
Ensure that the compilation for external test has access to go_test's
data attribute.
> go_test: ensure external source compilation has data

- go/tools/builders/asm.go
- go/tools/builders/compilepkg.go
Bug fix
In go1.19 through go1.22-devel (as of https://github.com/golang/go/commit/6382893890b82bbc0439eade5b132d9d1b3fb3a7) a series of changes were made to the way assembly files' symabis are produced.
https://go-review.googlesource.com/c/go/+/523337
Most significantly, the packagename now *must* be passed to the assembler via the -p flag, even when generating only the symabis. The go build system does this, but Bazel Go rules have not, and this finally breaks in go1.22-devel as the compatibility code is removed.
Now, without specifying -p to the assembler when generating symabis, the output symabis file will contain something like:
```
def <unlinkable>.s2Decode ABI0
```
instead of
```
def …
```
> Fix invocation of assembler for go1.22

- .bazelci/presubmit.yml
- go/deps.bzl
- go/nogo.rst
- go/private/extensions.bzl
- go/private/nogo.bzl
- go/tools/bazel_testing/bazel_testing.go
- tests/core/nogo/includes_excludes/BUILD.bazel
- tests/core/nogo/includes_excludes/README.rst
- tests/core/nogo/includes_excludes/includes_excludes_test.go
- tests/core/nogo/nolint/nolint_test.go
- tests/core/nogo/vet/vet_test.go
> Feature
Currently, workspace users register nogo targets by abusing the go_register_toolchain() function, which calls go_register_nogo(). Instead, we should expose go_register_nogo to workspace users directly. This will allow workspace users and bzlmod users to use the same underlying code because go_register_nogo allows users to specify includes and excludes which you currently can't do with WORKSPACE.
Add a test to verify this functionality works in WORKSPACE too.
Fixes #3838
> nogo: Create a go_register_nogo wrapper for WORKSPACE users.

- MODULE.bazel
- go/def.bzl
Prepare the new minor release of rules_go `0.46.0`
We additionally test that the new Go version is compatible: https://github.com/bazelbuild/rules_go/pull/3853
> prepare minor release 0.46

- go/tools/builders/compilepkg.go
Bug fix
In https://github.com/bazelbuild/rules_go/pull/2135, the importmap passed to `emit_compilepkg` is `"main"` if `is_main` is set (typically via the `go_binary` rule). This value also gets sent to nogo, which is the wrong value to send for a `main` package:
<details>
<summary>Minimal reproduction using <code>x/tools/go/analysis/singlechecker</code></summary>
```go.mod
// go.mod
module sampletext
go 1.21.6
require golang.org/x/tools v0.18.0
require golang.org/x/mod v0.15.0 // indirect
```
```go
// main.go
package main
import (
"fmt"
"golang.org/x/tools/go/analysis"
"golang.org/x/tools/go/analysis/singlechecker"
)
var Analyzer = &analysis.Analyzer{
Name: "test", 
Doc:  "test", 
Run: func(p *analysis.Pass) …
```
> pass correct (non `"main"`) importpath to nogo for `main` package

- go/private/rules/go_bin_for_host.bzl
See https://github.com/bazelbuild/bazel/issues/14444#issuecomment-1945642624.
> Make exec cfg check for `//go` stricter

- go/private/rules/library.bzl
After https://github.com/bazelbuild/rules_go/pull/3789, there's no easy way to analyze the package information of a library file from a test using [`bazel.ListRunfiles`](https://pkg.go.dev/github.com/bazelbuild/rules_go/go/tools/bazel#ListRunfiles) without manually copying over the `.x` file somewhere.
This file is arguably more important to users than the machine code, and is generally small, so we should consider exporting it.
> [go_library] add .x file to declared output files in DefaultInfo

- MODULE.bazel
- go/private/sdk.bzl
The fix for Latin-1 encoded files was landed in [6.4.0] after being landed on Bazel [master].
We can conditionally use the old, unhermetic, `tar` workaround on modern Bazel versions.
[master]: https://github.com/bazelbuild/bazel/pull/18448
[6.4.0]: https://github.com/bazelbuild/bazel/pull/19765
Bug fix
We currently use a unhermetic `tar` workaround when a Go SDK URL ends with `.tar.gz` but modern Bazel versions work fine unpacking the `tar` archive. We can conditionally use the workaround.
N/A
None
> Remove Latin-1 workaround on Bazel 6.4.0+

- MODULE.bazel
- WORKSPACE
Follows our policy of using the latest patch release of the oldest supported minor version.
> Bump Go version to 1.21.8

- go/private/sdk.bzl
Bug fix
Since Golang 1.21, the initial minor version has a `.0` suffix e.g `1.21.0`. As a result, it breaks the default behaviour of `go_download_sdk`. 
By default (see the [doc](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go_download_sdk)), if no `version` is specified, then the latest version is used. After it searches for the highest Go version, it uses `_version_string` function to make small transformation. The deleted lines removes that `.0` suffix and will cause following error:
`Error in fail: did not find version 1.22 in https://go.dev/dl/?mode=json`
Fixes #3850
> Support Go version schema change since 1.21

- go/tools/gopackagesdriver/bazel.go
- go/tools/gopackagesdriver/bazel_json_builder.go
- go/tools/gopackagesdriver/packageregistry.go
> Bug fix
Adds method `bazelVersion.isAtLeast` to check that Bazel's version is greater than or equal to a given value. It assumes that if Bazel's version is the zero value, it's a development release, newer than anything being compared.
Replaced calls to `.compare` with `.isAtLeast`.
Fixes #3889
n/a
> gopackagesdriver: fix version check with Bazel development versions

- go/tools/builders/env.go
This reverts commit 55ea579a70958d66f24a907433978b21edd36b29 with a minor change in error formatting.
Fixed #3890
> Revert "improving logging for subcommand failure (#3824)"

- go/private/tools/path.bzl
- go/tools/gopackagesdriver/aspect.bzl
The to_json and to_proto methods on struct are deprecated and will be removed.
The "json" and "proto" builtin modules should be used instead.
This replaces instances of `foo.to_json()` with `json.encode(foo)`.
> Replace instances of to_json() method with json.encode(..)

- go/tools/builders/nolint.go
- go/tools/builders/nolint_test.go
Bug fix
Adds support for parsing nogo nolint directives that have explanation comments.
n/a
The nolint directive seems to be based off of golangci-lint's nolint directive. Golangci-lint covers explanation comments as part of the [nolintlint](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/README.md).
> add nogo parsing support for nogo explanations

- go/tools/builders/nogo_main.go
Feature
This PR makes it so that regular expressions in `only_files` and `exclude_files` are matched against relative paths. This allows use of anchored regexps.
Fixes #3250
This overwriting of stderr have caused a lot of surprise when I was trying to debug-print filenames from inside of nogo.
https://github.com/bazelbuild/rules_go/blob/aeb83e878033ef357642c87122e193df44da03fe/go/tools/builders/env.go#L140
> [nogo] match regexp againts relative paths

- go/private/actions/link.bzl
- go/private/context.bzl
Bug fix
This PR solves  GoLink actions issue, when we can't create static library if go toolchain depends on portable cc toolchain.
Prerequisites:
- was found on MacOS, but behavior is general
- go toolchain uses cc **portable** toolchain
GoLink action uses `link` tool under the hood. `link` tool calls `ar` tool for archiving jobs and `ar` tool is called by name.
GoLink action envs contains PATH variable containing path to cc_toolchain.
If `ar` tool is found in PATH absolute path, everything is fine. In case of relative path, `link` raises an error: "cannot execute tool by relative path".
This PR forces `link` tool to explicitly use `ar` tool from cc_toolchain if cc_toolchain provides it.
**Which issues(s) does this …
> GoLink action. Use -extar <ar path> if cc_toolchain provides ar path

- MODULE.bazel
- go/private/extensions.bzl
Setting the new `reproducible` parameter of [`module_ctx.extension_metadata`](https://bazel.build/rules/lib/builtins/module_ctx#extension_metadata) to `True` results in the `go_sdk` extension being omitted from the lockfile. This is especially useful since it depends on OS/arch and thus makes lockfile maintenance more difficult if present.
> Mark `go_sdk` extension as `reproducible`

- go/private/actions/archive.bzl
- go/private/actions/compilepkg.bzl
- go/private/rules/test.bzl
> go_test: use different mnemonic for compilation

- docs/go/core/bzlmod.md
>
> Bug fix
> Feature
Documentation
> Other
Add go.work support to the documentation
Fixes #
> Add go.work support to the documentation

- .bazelci/presubmit.yml
- WORKSPACE
- go/modes.rst
- go/private/mode.bzl
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/tag_purego.go
- tests/core/cgo/tag_purego_err.c
- tests/core/cgo/tag_purego_err.go
- tests/core/cgo/tag_test.go
- tests/integration/gazelle/gazelle_test.go
- third_party/org_golang_google_protobuf-gazelle.patch
The community has agreed[1] that "pure" builds of Go code should use the `purego` build tag.
This change adds that de-facto tag.
[1]: https://github.com/golang/go/issues/23172
Spun out from bazelbuild/bazel-central-registry#1629 to solve building of `circl`.
> feat(mode): add `purego` tag when `pure`

- go/tools/builders/generate_test_main.go
- go/tools/bzltestutil/BUILD.bazel
- go/tools/bzltestutil/timeout.go
Bug fix
This gives us a determinstic location to ignore for goleak, which we previously had, but was removed as part of #3920.
Fixes #3938
> generate_test_main: Move timeout handling back to bzltestutil

- .bazelci/presubmit.yml
- .bazelrc
- MODULE.bazel
- WORKSPACE
- go/tools/bazel_testing/bazel_testing.go
- proto/BUILD.bazel
- proto/compiler.bzl
- proto/private/BUILD.bazel
- proto/private/toolchain.bzl
- tests/bcr/MODULE.bazel
- tests/core/cross/proto_test.go
- tests/core/transition/hermeticity_test.go
Feature
With `--incompatible_enable_proto_toolchain_resolution`, users of `protoc` are expected to obtain it through `@rules_proto//proto:toolchain_type` instead of the Bazel command line flag `--proto_compiler`. This change adds support for this in a backwards compatible way.
Note that the above is actually a lie: The proper way to use `protoc` would be to go through a Go-specific `proto_lang_toolchain` and use the methods on `proto_common` to interact with `protoc`. Since rules_go has a very bespoke setup with customizable compilers and the need to apply reset transitions in case `protoc` *is* built from source, this would require major changes. We should revisit this after Proto toolchainization has been enabled …
> Add support for `--incompatible_enable_proto_toolchain_resolution`

- go/private/BUILD.sdk.bazel
- go/private/sdk.bzl
Bug fix
go_tool_binary() is completely oblivious of toolchains. The reason being that Go toolchains actually depend on their output. Adding a toolchain dependency would thus add a cyclic dependency. This is problematic, because it means that the actions with mnemonic GoToolchainBinaryBuild end up getting scheduled on arbitrary workers.
Address this by adding exec_compatible_with to the locations where go_tool_binary() is instantiated, namely the auto-generated BUILD files that are part of Go SDKs.
Fixes: #3942
> Add exec_compatible_with to @go_sdk//:builder

- MODULE.bazel
- go/def.bzl
- go/private/repositories.bzl
- third_party/org_golang_google_genproto-gazelle.patch
- third_party/org_golang_x_sys-gazelle.patch
- third_party/org_golang_x_tools-gazelle.patch
This PR prepares a minor release to allow downstream users to begin integrating with https://github.com/bazelbuild/rules_go/pull/3919
> prepare v0.48.0 release

- WORKSPACE
- go/private/actions/compilepkg.bzl
- go/private/actions/stdlib.bzl
- go/private/common.bzl
- go/private/context.bzl
- go/private/rules/test.bzl
- go/tools/builders/compilepkg.go
- go/tools/builders/env.go
- go/tools/builders/generate_test_main.go
- go/tools/builders/info.go
- go/tools/builders/link.go
- go/tools/builders/stdlib.go
- go/tools/builders/stdliblist.go
Feature
Path mapping improves disk/remote cache hit ratio by automatically removing the configuration-specific path segments (e.g. `k8-fastbuild-ST-12345678`) from action command lines before staging them for execution.
This commit makes the stdlib, compilepkg (assuming no cgo) and gentestmain actions compatible with path mapping, which is mostly automatic except that `GOROOT` now needs to be passed in via a flag rather than an environment variable.
See https://www.youtube.com/watch?v=Et1rjb7ixUU for more information on path mapping.
Can be tested via `--experimental_output_paths=strip` with Bazel last_green.
> Add support for path mapping

- go/private/context.bzl
Feature
This sentinel feature allows the C++ toolchain configuration to use distinct sets of flags when compiling Go rules.
See https://github.com/bazelbuild/rules_rust/commit/0e0241e9b0e4122f1e28a1ca0d358dd987f21971 for a similar change to `rules_rust`.
> Introduce rules_go_unsupported_feature

- .gitignore
- docs/go/core/bzlmod.md
- go/private/polyfill_bazel_features.bzl
- go/tools/go_bin_runner/BUILD.bazel
- go/tools/go_bin_runner/main.go
Feature
`bazel mod tidy` is run if supported and if relevant files change due to the command.
Fixes #3900
Fixes https://github.com/bazelbuild/bazel-gazelle/issues/1749
> Automatically run `bazel mod tidy` in `@rules_go//go`

- go/tools/builders/generate_test_main.go
Bug fix
When configuring nogo() to run the revive linter, we currently see builds of testmain.go files fail with the following error:
if block ends with call to os.Exit function, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
Let's restructure this code slightly, so that this is no longer an issue.
N/A
> Fix revive warning in testmain.go files

- .bazelci/presubmit.yml
- WORKSPACE
- go/modes.rst
- go/private/mode.bzl
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/tag_purego.go
- tests/core/cgo/tag_purego_err.c
- tests/core/cgo/tag_purego_err.go
- tests/core/cgo/tag_test.go
- tests/integration/gazelle/gazelle_test.go
- third_party/org_golang_google_protobuf-gazelle.patch
This reverts commit fcd6390936ac61d76b5c00f1f33a505045d11888.
`purego` regresses performance of certain third-party libraries (see https://github.com/bazelbuild/rules_go/issues/3959).
Work towards #3959
> Revert "feat(mode): add `purego` tag when `pure` (#3901)"

- docs/go/core/bzlmod.md
see https://github.com/enola-dev/enola/issues/713
Documentation
Fixes #3967
> docs: Discourage use `go_sdk.host()` in bzlmod.md (see #713)

- MODULE.bazel
- go/private/platforms.bzl
- go/private/repositories.bzl
This also updates `platforms` module dependency to 0.0.10
Bug fix
This PR adds support to cross-compile for linux/ppc64le target.
Fixes #854 and fixes #1186
> Add linux/ppc64le to GOARCH constraints

- go/tools/gopackagesdriver/bazel_json_builder.go
Bug fix
A query like `kind("go_library", ...)` also returns rules that are not go libraries but have `go_library` as a substring of the rule name, e.g. `not_a_go_library`. To fix that, add regex anchors.
This fixes a problem that has the same effects as issue #3805, but with a different cause. Here, the gopackagesdriver returns roots that are not even go targets.
The fix in #3806, when merged, would hide the effects of the bug addressed here, because the roots that are not go targets will also be filtered out. That also makes this fix here more difficult to test. But I still think it's worth fixing this bug.
See https://bazel.build/query/language#kind …
> gopackagesdriver: Make kind query regexes anchored

- MODULE.bazel
- go/def.bzl
To keep backward compatibility, we will not be upgrading dependencies this release. 
We will do some internal dependency upgrades before the next upgrade.
> prepare release 0.49.0

- .bazelci/presubmit.yml
- go/tools/bazel_testing/bazel_testing.go
Bazel CI is going to remove `macos_legacy` soon.
Removing `--nosystem_rc` in test setup to pick up `--host_jvm_args=-Djava.net.preferIPv6Addresses=true` set in `/private/etc/bazel.bazelrc` on Bazel CI's Mac VMs (ipv6-only).
Context: https://github.com/bazelbuild/continuous-integration/issues/1981#issuecomment-2230296824
> Migrate to macos_arm64

- go/private/go_toolchain.bzl
- tests/core/cross/sdk_version_test.go
Bug fix
Go release candidate versions are of the format `X.YrcZ`. (ex: https://github.com/golang/go/commit/30b6fd60a63c738c2736e83b6a6886a032e6f269)
Unfortunately, this format doesn't get matched properly in `go_toolchain.bzl` so it's not possible to use rc versions without patching `VERSION`, or you'll run into the error, for e.g., with the added test case:
```
no matching toolchains found for types @io_bazel_rules_go//go:toolchain
```
This PR adds a way to match `rc` versions for the toolchain.
> Support matching release candidate toolchain versions

- go/tools/builders/BUILD.bazel
- go/tools/builders/builder.go
- go/tools/builders/cc.go
- go/tools/builders/env.go
- go/tools/builders/stdlib.go
- go/tools/builders/stdliblist.go
- tests/integration/reproducibility/reproducibility_test.go
Bug fix
It fixes reproducibility issues reported in https://github.com/bazelbuild/rules_go/issues/3994 by lazy-expanding paths to absolute paths
Fixes #3994
> Lazy expand absolute path to avoid including them in the output

- go/private/actions/archive.bzl
- go/private/context.bzl
- go/private/rules/test.bzl
- go/providers.rst
Code cleanup. I don't see this being used and it seems it has not been for 6+ years.
Fixes #
> Remove orig_src_map

- go/private/actions/archive.bzl
- go/private/rules/test.bzl
- go/private/tools/path.bzl
- go/providers.rst
We don't need to make copies of the lists
Fixes #
> Cleanup GoArchiveData runfiles handling

- go/private/BUILD.sdk.bazel
- go/private/context.bzl
- go/private/providers.bzl
- go/private/rules/sdk.bzl
- go/private/sdk.bzl
Small cleanup. We can just encode the string in the repo rule instead of creating it for every go action.
Fixes #
> Tweak how we pass GOEXPERIMENT to actions

- go/private/actions/archive.bzl
- go/private/context.bzl
Cleanup
It seems odd to hang helpers off the `go` context because they still need to take `go` as a param. It's clearer to just import them.
Fixes #
> Remove get_nogo from context

- go/private/context.bzl
- go/providers.rst
This field was deprecated over 6 years ago, we can clean it up.
Simplify the providers.
Fixes #
> Remove cgo_deps from GoSource provider

- go/private/context.bzl
Code cleanup
It's a bit faster due to not allocating the array
Fixes #
> Prefer rfind to rpartition in go_context

- go/private/context.bzl
We can compute the PATH once instead of in every go action. We check for `PATH` in the existing env but since the existing env came from hardcoded dict and cgo_context_info.env, this should be equivalent. 
Fixes #
> Move PATH env-var computation to GoContextInfo

- go/private/actions/archive.bzl
- go/private/context.bzl
This will let us more efficiently merge `cover` with embedded sources, as well as avoid needing to convert to a tuple for the Archive.
Fixes #
> Turn source.cover into a depset

- docs/go/core/cross_compilation.md
Documentation
Add missing link to https://bazel.build/extending/toolchains#toolchain-definitions for the change introduced by https://github.com/bazelbuild/rules_go/pull/3986.
`None`
`None`
> docs: add missing anchor to Bazel toolchains definition

- go/private/actions/compilepkg.bzl
- go/private/actions/stdlib.bzl
- go/private/mode.bzl
starlark cleanup
Makes the handling of flags a bit more efficient
Fixes #
> Cleanup compilepkg flags handling

- go/private/actions/archive.bzl
- go/private/context.bzl
- go/private/rules/test.bzl
- go/private/tools/path.bzl
- go/providers.rst
- go/tools/gopackagesdriver/aspect.bzl
The documentation says it can differ from `srcs` "if processing tools such as cgo or cover are applied." but in practice I did not see it mutating in the code; I suspect this may have been true in an earlier iteration of the rules. I also put in an assert in the provider creation code if they are different at the end and it didn't fire.
Fixes #
> Remove orig_srcs

- go/private/context.bzl
`embed` should always have GoLibrary; `go_default_library` is gone and Gazelle always generated importpath
Fixes #
> Cleanup infer_importpath

- go/private/context.bzl
- go/private/rules/library.bzl
- go/private/rules/test.bzl
This looks like a 50-100ms speedup from avoiding the array allocation in infer_importpaths and reduced `getattr` calls. Is `getattr` slower than direct property access? (If not, we can avoid passing in the values from go_library)
Fixes #
> Cleanup importpath/importmap handling in go_context

- go/private/actions/archive.bzl
- go/private/context.bzl
- go/private/rules/test.bzl
- go/providers.rst
It looks like we are shuffling it between GoSource and GoArchive, but we only need it on the archive.
Fixes #
> Remove cgo_exports from GoSource

- go/tools/gopackagesdriver/bazel.go
- go/tools/gopackagesdriver/bazel_json_builder.go
- go/tools/gopackagesdriver/gopackagesdriver_test.go
- go/tools/gopackagesdriver/main.go
Bug fix
It allows gopackagesdriver to be called within a subdirectory of a workspace and properly resolve queries from gopls from IDEs like VSCode when they include relative references. For example, if you have the following repo/workspace structure:
```
WORKSPACE
project1/BUILD.bazel
project1/main.go
project2/BUILD.bazel
project2/main.go
...
```
If you run gopackagesdriver using bazel run from project1 directory and receive the following queries:
```
file=./main.go
./...
```
The existing code will try to resolve those queries against the root of the workspace, when instead we would expect it to resolve relative to the project1 directory.
Fixes #4001 
> Making gopackagesdriver correctly handle relative queries made from a subdirectory.

- go/private/actions/archive.bzl
- go/private/common.bzl
- go/private/rules/test.bzl
`as_tuple` was showing up in profiles, we can just call `tuple` directly. This exposed that we were flattening a depset which isn't necessary.
Fixes #
> Cleanup GoArchiveData usage of as_tuple

- go/private/context.bzl
- go/private/rules/binary.bzl
- go/private/rules/library.bzl
- go/private/rules/test.bzl
starlark cleanup
The current logic to grab all the providers is confusing; it runs the fallback logics even in the case when `go_context_data` is found. Easier to follow when we pass the data in explicitly, and a bit faster as well.
I also considered making a `go_context_v2` api that doesn't have all the fallbacks and using that to power `go_context`, but didn't do it for now.
Fixes #
> Remove more hasattr/getattr calls in go_context

- go/platform/apple.bzl
- go/private/context.bzl
- go/private/mode.bzl
starlark cleanup
Looks like we were adding the `gotags` from ctx.var multiple times when cgo was enabled. This led me to realize we can compute all tags at `GoConfigInfo` creation time.
Fixes #
> Speedup get_mode some more

- go/private/platforms.bzl
- go/tools/internal/stdlib_tags/stdlib_tags.go
Feature
Adds support for GOOS=wasip1 so that users can build wasi binaries using rules_go
Fixes https://github.com/bazelbuild/rules_go/issues/4046
None
> Support GOOS=wasip1

- go/private/tools/path.bzl
These methods obscure the types of vars and are slower than just calling the underlying function
Fixes #
> Remove as_list/as_iterable usage from go_path

- go/private/context.bzl
- go/private/rules/binary.bzl
- go/private/rules/test.bzl
Making the caller deal with a transitioned attribute is cleaner and will be necessary for proper starlark typing anyway
Fixes #
> Remove usage of _flatten_possibly_transitioned_attr in common case

- go/private/actions/archive.bzl
- go/private/actions/link.bzl
- go/private/context.bzl
- go/private/rules/transition.bzl
- go/tools/builders/importcfg.go
- go/tools/builders/link.go
Starlark cleanup and perf improvement - saves around 250ms on buildbuddy
- It's more efficient to ignore a duplicate archive inside the action vs in analysis phase
- I belive `_transitive_archives_without_test_archives` is no longer needed due to the `recompile_external_deps` machinery for tests
- This allows to remove some data from the providers as well
Fixes #
> Simplify duplicate importmap handling

- docs/go/core/rules.bzl
- docs/go/core/rules.md
- go/def.bzl
- go/private/rules/transition.bzl
`go_reset_target` is helpful when certain plugins or tool attributes to rules can't build under certain configurations. For example, many thrift plugins fail to build when a dependency of a `go_binary` with `c-shared` instrumentation.
To alleviate this issue, you can pass the tool to `go_reset_target`.
> make `go_reset_target` public

- go/private/context.bzl
It's difficult to tell where this issue is coming from without some reference to the resolver or the target this is originating from.
This PR updates the debug message to be more explicit.
Before:
```
DEBUG: /home/user/.cache/bazel/_bazel_tfrench/b97476d719d716accead0f2d5b93104f/external/io_bazel_rules_go/go/private/context.bzl:322:22: Detected Targets in `source["deps"]` as a result of _resolver. Please pass a list of `GoArchive`s instead, for examples `deps = [deps[GoArchive] for dep in deps]`. This will be an error in the future.
DEBUG: /home/user/.cache/bazel/_bazel_tfrench/b97476d719d716accead0f2d5b93104f/external/io_bazel_rules_go/go/private/context.bzl:322:22: Detected Targets in `source["deps"]` as a result of _resolver. Please pass a list of `GoArchive`s instead, for examples …
```
> [context.bzl] add more helpful debug message to resolver issue

- MODULE.bazel
- go/def.bzl
This will be merged, but we will end up cherry picking certain commits onto an `release-0.50` branch, which will not include all of the commits on master.
> prepare rules_go release 0.50.0

- go/private/rules/test.bzl
- tests/core/nogo/tests/tests_test.go
Bug fix
nogo should run on both the internal and external libraries compiled for a `go_test`, but didn't. It also shouldn't run on the generated `testmain.go` file, but did.
> Run nogo on internal and external tests libs, not testmain

- go/tools/builders/nogo_main.go
- tests/core/nogo/custom/custom_test.go
Bug fix
Previously, it was printed once by analyzer.
Fixes #4080
> Only print type-checking error once in nogo

- MODULE.bazel
- go/def.bzl
This PR prepares for the cherry-picked `0.50.1` patch release, which will include:
#4081 
#4082 
#4083 
These commits will be cherry-picked to the branch `release-0.50`
> prepare patch release 0.50.1

- go/private/context.bzl
> Always omit -pie from cc_toolchain linker flags

- go/tools/builders/stdlib.go
Bug fix
Go 1.23 introduces `go tool preprofile` (ref: https://github.com/golang/go/commit/e069587c8d530ec912614d138bbf59a1d1788fb9). This tool allows folks to do the heavy lifting of processing their CPU profile ahead of time, resulting in a pre-processed profile that leads to quicker PGO builds later.
The `--pgo` flag to the `go` command only accepts raw profiles due to https://github.com/golang/go/commit/081dc9fd8c9cf824f5caac3a03a1c8dfd86894c0 which makes the go command itself run the pre-processor on the input profile, which leads to errors if the given profile is already pre-processed. Since rules_go adds the `--pgo` flag when building the stdlib, this leads to errors when passing a pre-processed profile via …
> Use -gcflags=--pgoprofile instead of -pgo when building stdlib

- go/private/sdk.bzl
Bug fix
The versions.json file results from downloading a list of versions from go.dev. (https://go.dev/dl/?mode=json)
This API is meant to be updated for every Go release and will result in different outputs when rerun in the future.
By deleting the file, we make the behavior more reproducible: As long as a specific version is requested, this should result in reproducible behavior. (This assumes that go.dev does not replace released SDK artifacts, which should be a fair assumption).
This should help other ecosystems (including Nix) with packaging Bazel, since we want to depend on the output of `bazel vendor` (and pin it against an expected hash for a given platform).
none …
> make toolchains repo more reproducible

- go/tools/gopackagesdriver/driver_request.go
- go/tools/gopackagesdriver/flatpackage.go
- go/tools/gopackagesdriver/gopackagesdriver_test.go
- go/tools/gopackagesdriver/json_packages_driver.go
- go/tools/gopackagesdriver/main.go
- go/tools/gopackagesdriver/packageregistry.go
- go/tools/gopackagesdriver/utils.go
- Introduced the ability to handle in-memory overlays via map[string][]byte in gopackagesdriver, allowing files to be dynamically provided as overlays during package resolution.
- Updated ResolveImports to accept overlays and apply them when parsing Go files.
- Modified tests to include new overlay functionality, ensuring correct import resolution for files supplied via overlay maps.
- Refactored runForTest function to support DriverRequestJson input, making it more flexible for testing overlays.
- Applied overlays in both the JSONPackagesDriver and PackageRegistry, providing seamless integration with existing workflows.
This feature enhances package resolution by supporting temporary or unsaved files, making it useful for IDEs, linters, and test scenarios where in-memory file content is …
> feat(gpd): add overlay support for gopackagesdriver

- go/tools/go_bin_runner/main.go
Feature
When running `go get example.com/foo@v1.2.3`, the module `example.com/foo` will be added to `go.mod` with an `// indirect` comment, just like its transitive dependencies. This results in `go_deps` not being able to distinguish this explicitly requested new dep from other indirect deps that shouldn't be imported by the root module. Running `go mod tidy` or `go get` without arguments is required to have the comment removed after adding a reference to the new module in code.
This change makes it so that `bazel run @rules_go//go get example.com/foo@v1.2.3` marks the requested module as a direct dependency. This realizes https://github.com/golang/go/issues/68593 in our custom wrapper, thus making this command the …
> Mark deps explicitly added with `//go get` as direct

- go/tools/gopackagesdriver/flatpackage.go
There is no reason for **CompiledGoFiles** to have external tests and not **GoFiles**, but it's more consistent in the code to support this edge case.
> fix(gpd): add missing condition in MoveTestFiles()

- go/tools/gopackagesdriver/BUILD.bazel
- go/tools/gopackagesdriver/bazel.go
- go/tools/gopackagesdriver/gopackagesdriver_test.go
- go/tools/gopackagesdriver/main.go
This new environment variable can be used to explicitly give some flags for all bazel info, build and query commands, and complete the list of existing environment variables, i.e:
- GOPACKAGESDRIVER_BAZEL_FLAGS: Startup bazel flags.
- GOPACKAGESDRIVER_BAZEL_QUERY_FLAGS: Flags to give to all bazel query commands.
- GOPACKAGESDRIVER_BAZEL_BUILD_FLAGS: Flags to give to all bazel build commands.
> feat(gpd): support of GOPACKAGESDRIVER_BAZEL_COMMON_FLAGS env variable

- go/private/context.bzl
Bug fix
The `env_for_path_mapping` attribut of the go context should contain the `GOAMD64` and `GOARM` env values.
Fixes #4119
> fix(compile): add missing GOAMD64 and GOARM env values in goctx.env_for_path_mapping

- go/tools/builders/compilepkg.go
> Bug fix
The intention here should be to initialize a slice with a capacity of  `len(includeSet)`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
Fixes #
> fix: fix slice init length

- go/private/rules/wrappers.bzl
Feature
I'm doing some experiments, where I'm trying to parse rules_go's source code with Go Starlark so that I can analyze it. In the process I've noticed that there are some small constructs that Go Starlark doesn't seem to like. In both those cases It looks like Go Starlark works as intended.
n/a
> Make it easier to parse rules_go's .bzl files with Go Starlark

- go/runfiles/manifest.go
- tests/runfiles/runfiles_test.go
Feature
In Bazel 8.0.0 since https://github.com/bazelbuild/bazel/commit/7407cef3837b4fe14e48e1a925f9b886c0cc945d.
Fixes #
> Add support for spaces and newlines in runfiles paths

- BUILD.bazel
- go/private/BUILD.bazel
> Feature
//:cgo_context_data is in the dependency closure of pure go_binary targets. This PR adds a config_setting to detect when //go/config:pure is set to True and updates the places where //:cgo_context_data is selected.
Fixes #4145 
No breaking tests have been added, but the functionality can be seen on the pure targets in the test folder. e.g.
```
bazel cquery "somepath(//tests/core/go_binary:static_pure_bin, //:cgo_context_data)"
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 targets...
INFO: Empty query results
INFO: Elapsed time: 0.097s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed …
```
> feat: avoid cc toolchain selection (#4145)

- go/tools/builders/BUILD.bazel
- go/tools/builders/builder.go
- go/tools/builders/cc.go
- go/tools/builders/env.go
- go/tools/builders/env_test.go
- go/tools/builders/link.go
- tests/core/cgo/BUILD.bazel
- tests/core/cgo/cgo_abs_paths_test.go
> Bug fix
PR #4009 added a mechanism that uses a sentinel value as a placeholder for paths which need to be expanded to absolutes for compile operations. These paths end up embedded in `.a` files and come back to the linker during link operations. The previous PR replaces the `CC` tool with a pointer to `builder cc` which in turn substitutes the placeholder value for actual paths. Unfortunately this wasn't done for the linker, so the linker is receiving parameters like `--sysroot=__GO_BAZEL_CC_PLACEHOLDER__external/_main~_repo_rules~ubuntu_20_04_sysroot/` which is not valid. When a sysroot is configured this means that internally the linker won't be able to find the sysroot in some cases.
In almost comically bad …
> fix: properly expand absolute path placeholder for link calls

- go/private/actions/compilepkg.bzl
- go/private/context.bzl
A lot of the args between compilepkg and nogo are shared, so we can reuse the `Args` object. Cleaned up a few other things that showed up in profiles while I was here. 
Fixes #
> Speedup compilepkg args handling

- WORKSPACE
- go/private/nogo.bzl
- go/private/rules/binary.bzl
- go/runfiles/manifest.go
- go/tools/builders/nogo_main.go
- go/tools/releaser/prepare.go
- go/tools/releaser/upgradedep.go
- internal/BUILD.bazel
- tests/core/compatibility/BUILD.bazel
- tests/core/compatibility/README.md
- tests/core/compatibility/hello.go
- tests/core/go_proto_library_importpath/importpath_test.go
- tests/core/go_test/example_test.go
- tests/core/go_test/filter_test_cases_test.go
- tests/core/go_test/timeout_test.go
- tests/core/go_test/xmlreport_test.go
- tests/integration/reproducibility/reproducibility_test.go
Bug fix
`go_tool_binary` used to non-hermetically pick up rules_go's `go.mod` file when run unsandboxed, which resulted in it downloading a different toolchain and messing up version checks.
Also make `nogo_main.go` compatible with Go 1.19 and test with nogo (which requires fixing a bunch of violations).
Fixes #
> Fix `go_tool_binary` non-hermeticity and Go 1.19 incompatibility

- go/private/rules/cross.bzl
- go/private/rules/test.bzl
- go/private/rules/transition.bzl
- go/private/sdk.bzl
- proto/def.bzl
- tests/core/go_proto_library_importpath/BUILD.bazel
Removed some unused vars pointed by
https://github.com/cameron-martin/bazel-lsp (on not yet merged version).
Cleanup
> chore: removed some unused vars

- go/def.bzl
This PR prepare the `rc1` for the new rules go version
> prepare rules_go release 0.51.0-rc1

- go/tools/releaser/prepare.go
We need to allow pre-releases in order to release the `rc1` of version `0.51`
> fix(go/tools/releaser) allow prereleases

- MODULE.bazel
- WORKSPACE
- docs/doc_helpers.bzl
- go/private/repositories.bzl
- go/private/tools/files_equal_test.bzl
- go/tools/bazel_testing/bazel_testing.go
Bazel 8 deletes all native shell rules. In order for other rule repositories (i.e. rules_android) to use rules_go, the references to native sh_* must be converted to rules_shell's respective versions.
Unblocks https://github.com/bazelbuild/rules_android/issues/278
Bug fix
Adds rules_shell dep and properly loads sh_binary/test where applicable.
Without this PR, rule repositories cannot depend upon rules_go with Bazel 8.
Fixes #4181.
> Use rules_shell's sh_binary and sh_test

- go/def.bzl
- go/tools/releaser/prepare.go
Bug fix
Deprecates the `RULES_GO_VERSION` constant in favor of `bazel_dep` and keeps it at `0.50.0` for legacy consumers that may not be able to parse RC suffixes.
> prepare rules_go release 0.51.0-rc2

- .bcr/metadata.template.json
Reflect the move to the `bazel-contrib` org.
> Update BCR metadata

- go/private/rules/test.bzl
- tests/core/go_binary/BUILD.bazel
- tests/core/go_binary/testing_testing.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/testing_testing_test.go
Feature
This change adds in the necessary flags in `go test` to allow [`testing.Testing`] to work as expected.  According to the [upstream source], it is set with a `-X` option in the `go` tooling, so this change makes `rules_go` operate accordingly.
This should be safe for older Go versions too, given that the link command [docs](https://pkg.go.dev/cmd/link) say that the `-X` arg is not "effective" when the target variable is not defined in the code.
Tests are also provided, and `buildifier` moved around some unrelated lines.  I'd be happy to undo the unrelated changes.
[`testing.Testing`]: https://pkg.go.dev/testing#Testing
[upstream source]: https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/testing/testin …
> Support the go1.21 `testing.Testing()` function

- go/private/actions/binary.bzl
- go/private/common.bzl
- go/private/mode.bzl
Bug fix
[Go 1.24](https://go.dev/doc/go1.24#wasm) added support for `GOOS=wasip1 GOARCH=wasm go build -buildmode=c-shared`; however, the rules_go starlark code contained validation against this.
* Fixes validation error in newly supported go 1.24 wasip1-wasm tuple with -buildmode=c-shared.
* Removes lib prefix for wasip1 -buildmode=c-shared
* Adds `.wasm` suffix for wasi reactors built with `-buildmode=c-shared`
Fixes #4200
It looks like this could use a test (as simple as adding a new go file under `tests/core/c_linkmodes/`); however, the support for features added in this PR requires Go 1.24, which is not out yet. Updating …
> Support Go 1.24's wasip1 reactors

- go/private/context.bzl
- tests/core/cross/BUILD.bazel
Bug fix 
Providers and structs with the same fields don't compare equal
Fixes #4197
I wasn't able to figure out a repro in rules_go, it seems like it may rely on some transitions? Not sure we should block landing on this, it seems like this should be the right fix
> fix: Make context.mode always be GoConfigInfo

- README.rst
It was added eight years ago in #1014. Since then, Travis has become less popular, so it's not worth the burden of maintaining this section.
It's strange that we document this one particular CI platform and not others like CircleCI or GitHub Actions. Also, this documentation isn't really Go-specific.
> New Year's resolution
> chore: remove Travis-specific install docs

- go/private/rules/sdk.bzl
- go/private/sdk.bzl
Bug fix, see https://github.com/bazel-contrib/rules_go/pull/4022#issuecomment-2566548860
Reverts the behavior to the API while keeping the optimization
Fixes #
> Undo API-breaking change to go_sdk experiments attribute

- go/toolchains.rst
Documentation
This PR fixes a broken documentation link by updating the reference to the core file from `core.bzl` to `core.rst`. This ensures readers are directed to the correct documentation file when clicking on the core reference link in `toolchains.rst`.
None
None
> docs: update core link reference from .bzl to .rst

- README.rst
- docs/go/core/workspace.md
- go/tools/releaser/prepare.go
Current Bazel nightly versions (pre-releases of Bazel 9) will soon stop supporting this, so it shouldn't be the first docs we show new users.
Note, I've done the minimal touching of the content, converting ReStructured Text to Markdown.
Related to https://github.com/bazel-contrib/bazel-gazelle/issues/1715#issuecomment-1878663799 from a year ago.
> chore(docs): move WORKSPACE docs out of primary README

- .bazelci/presubmit.yml
While https://github.com/bazelbuild/continuous-integration/issues/2153 is still on going, this PR temporarily disable the failing macOS CI task, so the master branch is green
While I am on it, I also updated 
* The main Linux platform to ubuntu2404
* Bazel 6 test to use Debian 11 because Ubuntu 1804 is already EOF. Debian 11 is old enough to support Bazel 6 but still continue to receive security fixes
* rbe_ubuntu1604 to rbe_ubuntu2404
* all new MacBooks in the past 4 years are using ARM64. We can safely stop testing Intel Mac now
> Disable mac CI, update Linux

- go/private/actions/stdlib.bzl
- go/tools/builders/stdlib.go
Bug fix
When you enable the "msan" mode in configuration, go stdlib should also be built with the "msan" flag.
> Build stdlib with msan support

- MODULE.bazel
- go/tools/bazel_testing/BUILD.bazel
- go/tools/bazel_testing/bazel_testing.go
- go/tools/bazel_testing/def.bzl
- tests/core/cross/sdk_version_test.go
- tests/integration/gazelle/BUILD.bazel
- tests/integration/gazelle/gazelle_test.go
Other
`go_bazel_test` now works with `--enable_bzlmod` (tested manually with rules_go and gazelle).
Fixes #
> Get `go_bazel_test`s to pass with  Bzlmod

- docs/go/core/bzlmod.md
Documentation
**What does this PR do?**
Explicitly call out `go_sdk.host()` as an alternative to `go_sdk.download()` in the Bzlmod installation documentation, and point clearly to the nota bene associated with it.
Avoiding people from copying and pasting the code without understanding that `go_sdk.host()` should be omitted when using `go_sdk.download()` (as well as making sure that there's a clear pointer to its drawbacks).
N/A
> Improve the comment for `go_sdk.host()` in the installation docs

- MODULE.bazel
- go/private/repositories.bzl
- go/tools/bazel_testing/BUILD.bazel
> Use same Go SDK as Gazelle for `go_bazel_test`

- go/private/sdk.bzl
Before 6.4.0, there is a bug in Bazel when extracting archive with
special file names inside.
Since Bazel 6 is not the oldest supported LTS and 6.5.0 is already
released, we should be able to remove this logic safely.
> sdk: remove logic for Bazel versions below 6.4.0

- go/private/go_toolchain.bzl
- go/private/sdk.bzl
- go/toolchain/BUILD.bazel
- go/toolchains.rst
- tests/core/go_download_sdk/go_download_sdk_test.go
- tests/core/starlark/sdk_tests.bzl
Feature
This commit adds a new setting
--@io_bazel_rules_go//go/toolchain:sdk_name which can be used to select a registered Go toolchain via the name provided in go_download_sdk, go_wrap_sdk, etc.
This fixes the problem of selecting a toolchain where the same Go version is used, but different experiements are enabled or patches applied.
Fixes #4240
Works also as a workaround for #3582
> Add new setting //go/toolchain:sdk_name to allow the selection of a specific Go toolchain

- go/private/context.bzl
> Bug fix
The starlark `dict` already will return items in the order in which they where inserted on iteration. There is no need to explicitly sort the items. But it does break use cases, where the user has explicitly defined a order of `PATH` components. As for example is possible with the `env` attribute of `cc_args()` with the new `rule_cc` based toolchains.
Fixes #
> Keep order for PATH components

- go/tools/bzltestutil/testdata/timeout.json
- go/tools/bzltestutil/testdata/timeout.xml
- go/tools/bzltestutil/xml.go
Feature
When a test case is interrupted at timeout, we don't have the pass/fail/skip event to report elapsed time. However, we can parse them from the error message at the end to figure it out. The error message looks like:
```
panic: test timed out after 8s
running tests:
TestReport (8s)
TestReport/test_3 (2s)
```
Also, instead of reporting those test cases as "No pass/skip/fail event found for test", we can now report them as "Interrupted".
> Capturing elapsed time of interrupted test cases due to timeout

- go/tools/bzltestutil/test2json.go
Sync test2json from upstream Go. All the code changes are from golang/go. Only the comment was changed by this PR.
I tried to do that in #4250, but was blocked by a flaky test that was fixed in #4257. Retrying...
> Sync test2json from upstream Go

- extras/gomock.bzl
Bug fix
Imagine if you want to build mocks for interfaces that are only available on certain operating systems/hardware platforms. In those cases you simply want to add a "manual" tag to the gomock() target, and only rely on it getting built if the resulting Go source file is part of some go_library().
This change adds the "manual" tag to all of the hidden targets of this rule, meaning that their build is skipped completely if the main gomock() target is marked manual as well.
One that requires me to carry a local patch around on the github.com/buildbarn/bb-remote-execution side.
> Mark gomock() hidden targets manual

- go/tools/bzltestutil/testdata/empty.xml
- go/tools/bzltestutil/testdata/report.xml
- go/tools/bzltestutil/testdata/timeout.xml
- go/tools/bzltestutil/xml.go
- tests/core/go_test/xmlreport_test.go
Feature
This PR makes every test function a `<testsuite>` and every subtest a `<testcase>`. This allow us to record the start time of every test function, because only `<testsuite>` has a timestamp attribute. This approach is also consistent with [testify suite](https://pkg.go.dev/github.com/stretchr/testify/suite), each of which becomes a `<testsuite>`.
Note that in the test.xml, a test function is both a `<testsuite>` and a `<testcase>`. It has to be a `<testcase>` because the test function itself has its own duration that is independent of its subtests. Also, it can have assertions outside all subtests, it can fail even all its subtests succeed. If no subtest is used, every `<testsuite>` only has one `<testcase>`, …
> Grouping subtests using test suites in test.xml

- proto/wkt/well_known_types.bzl
go_features.proto was introduced with Go Protobuf v1.33.0 (March 2024): https://github.com/protocolbuffers/protobuf-go/commit/2040e8671baa910b9a9c91fa21a2543846772985
…but with the release of the Go Protobuf Opaque API in December 2024, more users will be interested in making use of this file to configure the generated API that their .proto files should use.
Without this change, building a go_proto_library() whose .proto sets the API level to the Opaque API as documented at https://protobuf.dev/reference/go/opaque-migration/ would fail with this error message:
compilepkg: missing strict dependencies:
…/execroot/_main/bazel-out/k8-fastbuild/bin/dumbdata_go_proto_/
github.com/cshabsin/nih/dumbdata_go_proto/dumb_data.pb.go:
import of "google.golang.org/protobuf/types/gofeaturespb"
No …
> Bug fix: proto: add gofeaturespb as well-known type; Go Protobuf ships it

- go/tools/bzltestutil/xml.go
Bug fix
When test cases use `t.Parallel()`, the duration of a test suite is more than that of the test case with the same name. For example, when we run this test:
```go
func TestParallel(t *testing.T) {
t.Run("Test 1", func(t *testing.T) {
time.Sleep(1 * time.Second)
})
t.Run("Test 2", func(t *testing.T) {
t.Parallel()
time.Sleep(2 * time.Second)
})
}
```
The log shows:
```
=== RUN   TestParallel
=== RUN   TestParallel/Test_1
=== RUN   TestParallel/Test_2
=== PAUSE TestParallel/Test_2
=== CONT  TestParallel/Test_2
--- PASS: TestParallel (1.00s)
--- PASS: TestParallel/Test_1 (1.00s)
--- PASS: TestParallel/Test_2 (2.00s)
PASS
```
`TestParallel/Test_2` took 2 seconds, but the test case `TestParallel` only took 1 …
> Calculating the test suite duraion from timestamps

- go/tools/builders/protoc.go
Bug fix
This PR fail the action if a plugin does not produce a valid Go file that it is supposed to produce. This disallows people to add gRPC plugin to a `go_proto_library` target that has no service definition, but avoids the cache poisoning due to bugs in proto plugins. Because Gazelle is able to switch between proto and grpc plugins depending on the existence of service definition, existing repos managed by Gazelle will not be affected.
Fixes #3949
Credits to @r-hang for coming up with the patch
> Fail when expected files are not produced by protoc

- docs/go/editors/vim.md
Documentation
Adds `gopls.build.workspaceFiles` to the Vim documentation, following the merge of the `build.workspaceFiles` option in [gopls v0.18.0](https://github.com/golang/tools/releases/tag/gopls%2Fv0.18.0), which aims to improve editor integration with Bazel projects.
Fixes #4289 
These configuration changes have already been applied to the https://github.com/bazel-contrib/rules_go/wiki/Editor-setup wiki page, so this is just keeping everything in-sync.
> add workspaceFiles to vim configuration documentation

- docs/go/core/bzlmod.md
- go/private/extensions.bzl
- go/private/sdk.bzl
- tests/bcr/.bazelrc
- tests/bcr/BUILD.bazel
- tests/bcr/MODULE.bazel
- tests/bcr/transition.bzl
- tests/bcr/wrap_test.go
Add all wrapped sdks to the beginning of the toolchains so any specific platforms override the downloaded toolchain.
Add a test that transitions to a different sdk from the downloaded version. The test asserts the correct version.
>
> Bug fix
Feature
> Other
Fixes #4300 
> Add wrap extension tag to implement go_wrap_sdk

- go/tools/builders/nogo_fix.go
- go/tools/builders/nogo_fix_test.go
Improve the report message to avoid confusing developers.
> Bug fix
Two issues:
- issue if there are no fixes at all, getFixes still produces "some suggested fixes are invalid or have conflicts with other fixes:". The right behavior is to not produce such message.
- if there are multiple suggested fixes, getFixes produces "some suggested fixes are invalid or have conflicts with other fixes:". A better solution is to, for each suggested fix, records how it fails (invalid or conflicting). 
Fixes #
> fix the reporting message for getFixes

- go/tools/bzltestutil/wrap.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/xml_panic_test.go
Bug fix
When rules_go runs a test that panics, it doesn't produce the final "FAIL" line, which the JSON converter relies on to flush the buffer at the end. This PR writes the "FAIL" line to the JSON converter whenever a test exits with a non-zero code to make sure the buffer is always flushed.
Fixes #4280
When a test fails normally, the test would produce the "FAIL" line. When this happens, the JSON converter would get two "FAIL" lines, and flush the buffer twice at the end, which is fine.
If we run a test with `go test` and it panics, the "FAIL" line is still produced. It is still a mystery why `bazel test` wouldn't produce the "FAIL" line. As …
> Producing "fail" event when a test case panics

- go/private/BUILD.sdk.bazel
Bug fix
The `crypto/internal/sysrand/internal/seccomp` package fails to compile with linux kernel sources prior to 3.17. It's an internal package that is only used by unit tests, so compiling it as part of the monolithic SDK target is a waste of time anyway, so just exclude it.
Fixes #4310
> fix(cgo): exclude crypto/internal/sysrand/internal/seccomp from SDK srcs

- extras/gomock.bzl
This `mnemonic` tag is added at the wrong place
> fix(gomock): add missing mnemonic to gomock action

- go/private/extensions.bzl
The SDK's repo name will be part of the builder path and as such part of every compile/linking action. Pick a generic name for the root module to allow caching these actions across modules.
This change assumes that every module other than the root module will have a name.
Fixes #4312
Bug fix
Pick the same repo name for the SDK download across different root modules. This matters as every compilation/linking will be done through the builder and the repo name is part of the path to the builder. After this change the path will be consistent across different root modules.
Fixes #4312
This code assumes that every non-root module has a name (e.g. imported via …
> go_sdk: Pick a consistent repo name to improve cachability

- MODULE.bazel
- docs/go/core/bzlmod.md
- go/private/extensions.bzl
- go/private/go_mod.bzl
- tests/core/from_go_mod_file/BUILD.bazel
- tests/core/from_go_mod_file/README.rst
- tests/core/from_go_mod_file/from_go_mod_file_test.go
Feature
Adds a `go_sdk.from_file` rule to the extension that allows modules to say that their SDK version should be read from their `go.mod` file.  This allows callers to avoid repeating themselves and stay within the Go tool environment for version specification, allowing better integration with other tools.
Fixes #4292
The toolchain version is selected based on the rules in https://go.dev/doc/toolchain
This change copies parts of the `go_mod.bzl` parser from the Gazelle repository:
https://github.com/bazel-contrib/bazel-gazelle/blob/master/internal/bzlmod/go_mod.bzl
A test based on the `go_download_sdk` test sets up a module-under-test with a `go.mod` …
> Add `go_sdk.from_file` to read the SDK version from `go.mod`.

- go/private/repositories.bzl
- go/tools/releaser/upgradedep.go
- third_party/com_github_golang_mock-gazelle.patch
- third_party/org_golang_google_genproto-gazelle.patch
- third_party/org_golang_google_grpc_cmd_protoc_gen_go_grpc.patch
- third_party/org_golang_google_protobuf-gazelle.patch
- third_party/org_golang_x_sys-gazelle.patch
Bump the versions of dependencies in repositories.bzl to match what's in
go.mod.
Specifically bumps:
- golang.org/x/sys
- google.golang.org/protobuf
- google.golang.org/grpc/cmd/protoc-gen-go-grpc
- google.golang.org/genproto
- github.com/golang/mock
Additionally add features to the `releaser` tool for updating to a specific version, rather than latest, so we can avoid further modifications to `go.mod`.
Fixes #4262
> deps: Get repositories.bzl in sync with go.mod

- go/tools/bzltestutil/xml.go
Bug fix
A test case/suite's duration can be nil in the test JSON. We should check it before dereference it.
Fixes #4318
> Checking test suite duration

- go/tools/builders/protoc.go
Bug fix
It's common for a `go_proto_library` to include proto files with and without service definitions at the same time. In this case, the gRPC plugins are needed, but some gRPC plugins don't generate the grpc.pb.go files if there is no service definition. 
Partially reverting #4287 to restore the previous behavior of creating an empty file
Fixes #4317
> Revert "Fail when expected files are not produced by protoc (#4287)"

- go/tools/builders/env.go
> Bug fix
This adds the -imacros flag to the set of cgo compiler flags that are transformed to absolute paths. Currently relative path values for -imacros will fail. 
No existing issue, just seems to be a missed flag.
I have been able to successfully test this locally using my existing cc toolchain.
> Add imacros to absolutized cgo env list

- docs/go/core/rules.md
- go/private/rules/cross.bzl
- go/private/rules/transition.bzl
Feature
Let user change the compilation mode with go_cross_binary.
This is useful to force a opt mode for a deployment or packaging
purposes.
> go_cross: allow transition on compilation_mode

- go/private/BUILD.sdk.bazel
Bug fix
In order to run code with GOOS=js GOARCH=wasm in the browser, you need to copy a `.js` file from the toolchain.
This file location was changed in Go 1.24, which is now also exported in this PR.
n/a
See also this info from the Go wiki:
> For Go 1.23 and earlier, the wasm support files needed in this article are located in misc/wasm, and the path should be replaced when performing operations with files such as lib/wasm/wasm_exec.js.
[source](https://go.dev/wiki/WebAssembly)
> Export new location of support files needed for using Go's WASM output.

- .bazelci/presubmit.yml
- .bazelrc
- MODULE.bazel
- WORKSPACE
- extras/gomock.bzl
- go/private/actions/compilepkg.bzl
- go/private/rules/binary.bzl
- go/private/rules/nogo.bzl
- tests/bcr/MODULE.bazel
- tests/core/cross/proto_test.go
- tests/core/transition/hermeticity_test.go
Incompatible change
This requires setting the `toolchain` on actions and updating protobuf.
Fix #4139
> Fix incompatibility with `--incompatible_auto_exec_groups`

- go/private/rules/test.bzl
- go/tools/builders/generate_test_main.go
- go/tools/bzltestutil/chdir/init.go
- tests/core/go_test/BUILD.bazel
- tests/core/go_test/README.rst
- tests/core/go_test/testmain_pwd_test.go
Bug fix
This PR adds a test to reproduce the issue described in #4335,
and proposes one possible fix for it:
leveraging an environment variable to help the subprocess determine
whether it was invoked by Bazel or directly.
The test fails without the proposed fix,
but it succeeds fine with `go test`.
Fixes #4335
The proposed fix is one possible way of doing this.
I welcome feedback from maintainers on other approaches here.
> Re-spawned test binary should not break PWD

- MODULE.bazel
- docs/go/core/workspace.md
- proto/compiler.bzl
- proto/def.bzl
- proto/gogo.bzl
- proto/private/toolchain.bzl
- tests/core/cross/proto_test.go
- tests/core/go_proto_aspect/BUILD.bazel
- tests/core/go_proto_library/BUILD.bazel
- tests/core/go_proto_library_importmap/BUILD.bazel
- tests/core/go_proto_library_importpath/BUILD.bazel
- tests/core/transition/hermeticity_test.go
- tests/integration/googleapis/BUILD.bazel
- tests/integration/grpc_plugin/BUILD.bazel
- tests/legacy/examples/proto/dep/BUILD.bazel
- tests/legacy/examples/proto/embed/BUILD.bazel
- tests/legacy/examples/proto/gogo/BUILD.bazel
- tests/legacy/examples/proto/gostyle/BUILD.bazel
- tests/legacy/examples/proto/grpc/BUILD.bazel
- tests/legacy/examples/proto/lib/BUILD.bazel
- tests/legacy/proto_ignore_go_package_option/BUILD.bazel
> Cleanup
Replaces rules_proto uses with com_google_protobuf. The former is deprecated.
> Remove rules_proto

- go/def.bzl
It's just a demo analyzer that serves as an example of the facts mechanism.
Context: https://bazelbuild.slack.com/archives/CDBP88Z0D/p1747334404309089?thread_ts=1747334404.309089&cid=CDBP88Z0D
> Disable `pkgfact` analyzer

- MODULE.bazel
- tests/bcr/MODULE.bazel
The repo contains a host-compatible SDK and thus doesn't behave correctly in multi-platform builds.
Fixes #4342
> Discourage references to the default SDK

- go/private/actions/archive.bzl
- go/private/actions/compilepkg.bzl
- go/tools/builders/cgo2.go
- go/tools/gopackagesdriver/BUILD.bazel
- go/tools/gopackagesdriver/aspect.bzl
- go/tools/gopackagesdriver/build_context.go
- go/tools/gopackagesdriver/gopackagesdriver_test.go
- go/tools/gopackagesdriver/pkgjson/BUILD.bazel
- go/tools/gopackagesdriver/pkgjson/main.go
- go/tools/gopackagesdriver/pkgjson/pkg_json.bzl
go/tools/gopackagesdriver: Filter cgo sources and add cgo processed files
The gopackagesdriver today fails to load Go programs
with cgo dependencies.
```
go-code/bazel-pkgdrv/external/com_github_mattn_go_sqlite3/backup.go:16:8: could not import C (no metadata for C)
```
These errors come from two sources:
- First, the gopackagesdriver includes cgo sources files in the
CompiledGoFiles response.
- Second, the gopackagesdriver response and CompiledGoFiles do not
contain cgo processed Go sources necessary to compile the program.
This change addresses both error points by
- Exposing the location of cgo generated artifacts in the rules_go archive object.
- Filtering out cgo source files from the CompiledGoFiles response, by
checking if the files import "C".
- Adding cgo processed files to the …
> go/tools/gopackagesdriver: Adding Cgo support

- go/private/actions/link.bzl
> Bug fix
Previously if we pass `-extldflags,-Wl,--thread` into command line, it will only recognizes `-Wl` and ignores `--thread`. 
#3921 
Fixes #
If we see `-Wl`, we can merge with next value in the list.
> fix: merge '-Wl,' with next value when

- MODULE.bazel
- WORKSPACE
- go/private/repositories.bzl
- go/private/rules/go_bin_for_host.bzl
- go/tools/bazel_benchmark/WORKSPACE.in
- go/tools/bazel_testing/bazel_testing.go
- go/tools/releaser/boilerplate.go
- tests/bcr/BUILD.bazel
- tests/bcr/MODULE.bazel
- tests/bcr/proto/BUILD.bazel
- tests/core/go_proto_aspect/BUILD.bazel
- tests/core/go_proto_library/BUILD.bazel
- tests/core/go_proto_library_importmap/BUILD.bazel
- tests/core/go_proto_library_importpath/BUILD.bazel
- tests/core/transitive_headers/a/BUILD.bazel
- tests/core/transitive_headers/b/BUILD.bazel
- tests/integration/googleapis/BUILD.bazel
- tests/integration/grpc_plugin/BUILD.bazel
- tests/legacy/examples/proto/dep/BUILD.bazel
- tests/legacy/examples/proto/embed/BUILD.bazel
- tests/legacy/examples/proto/gogo/BUILD.bazel
- tests/legacy/examples/proto/gostyle/BUILD.bazel
- tests/legacy/examples/proto/grpc/BUILD.bazel
- tests/legacy/examples/proto/lib/BUILD.bazel
- tests/legacy/proto_ignore_go_package_option/BUILD.bazel
Adapt to a Bazel breaking change
The `local_config_platform` repo is no longer available with Bazel@HEAD, so the host constraints have to be loaded from `@platforms//host`.
Also prepare the BCR test repo for Bazel@HEAD with `--incompatible_autoload_externally=` by applying buildifier lint fixes.
> Fix breakages with Bazel@HEAD and incompatible flags

- go/tools/gopackagesdriver/aspect.bzl
- go/tools/gopackagesdriver/pkgjson/main.go
- go/tools/gopackagesdriver/pkgjson/pkg_json.bzl
When testing the bazel driver, we ran into an error that flaged that the argument list as too long.
```
ERROR: ...json failed: (Exit -1): pkgjson failed: error executing Action command (from target //...) bazel-out/k8-opt-exec-ST-a828a81199fe/bin/external/io_bazel_rules_go/go/tools/gopackagesdriver/pkgjson/reset_pkgjson/pkgjson --id @//src/... --pkg_path ... (remaining 15 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Action failed to execute: java.io.IOException: Cannot run program "/home/user/.cache/bazel/_bazel_rhang/install/7e4ce7b0d69e79cb6bd84c7f9dfefe6b/process-wrapper" (in directory "/home/user/.cache/pkgdrv/0ddf1c72b811bee41d29991c732306ef72553747/sandbox/processwrapper-sandbox/29913/execroot/__main__ …
```
> go/tools/gopackagesdriver/pkgjson: Construct pkg json from file input

- go/tools/builders/nogo_main.go
- tests/core/nogo/custom/custom_test.go
Bug fix
We previously didn't show any error when an analyzer panicked and Bazel would show a "mandatory output not created" error for the nogo action.
> Gracefully handle a panicking analyzer

- go/private/rules/binary.bzl
Bug fix for Nix
The current implementation depends on `mktemp` and `rm` being in the PATH, which they're not on Nix. This alternative construction executes `go build` directly without run_shell or the coreutils deps.
While here, I set a few extra env vars to disable new Go features we don't want (GOTELEMETRY, GOENV).
If this works, we may be able to remove the Windows codepath.
Fixes #
> Drop non-hermetic deps in _go_tool_binary_impl

- .bazelci/presubmit.yml
- go/tools/bzltestutil/lcov.go
- tests/core/coverage/BUILD.bazel
- tests/core/coverage/reassign_flag_commandline_test.go
Bug fix
When run with `go test -cover`, the following test does not panic:
```
-- foo.go --
package foo
func foo() int {
return 42
}
-- foo_test.go --
package foo
import (
"flag"
"testing"
)
func TestReassign(t *testing.T) {
flag.CommandLine = flag.NewFlagSet("test", flag.ExitOnError)
_ = foo()
}
```
However, with `bazel coverage`, it does panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100f8dbe4]
goroutine 1 [running]:
github.com/bazelbuild/rules_go/go/tools/bzltestutil.ConvertCoverToLcov()
external/io_bazel_rules_go/go/tools/bzltestutil/lcov.go:39 +0x54
github.com/bazelbuild/rules_go/go/tools/bzltestutil.lcovAtExitHook …
```
> coverage: Don't panic if flag.CommandLine is reassigned

- proto/def.bzl
Other
It's relatively common for users to add `proto_library` to the `deps` of go_proto_library. The resulting error message (which complains about a missing attribute) is rather confusing, so let's improve it a bit.
somewhat arguably fixes #4069
> chore(go_proto_library): Improve error message on incorrect use.

- go/tools/gopackagesdriver/aspect.bzl
- go/tools/gopackagesdriver/bazel_json_builder.go
Bug fix
The stdlib_json_file contains paths of compiled cgo files, which are in the stdlib cache_dir. The gopackagesdriver reads those files, but this dependency was not explicitly declared previously.
Usually, it works despite the missing dependency. But when you have a Bazel cache configured, and then run `bazel clean` and run the gopackagesdriver again, Bazel will not restore the cache_dir from the Bazel cache. The gopackagesdriver then fails with an error like this:
error: unable to load JSON files: unable to resolve imports: open [...]/bin/external/rules_go+/stdlib_/gocache/a4/a4f91e8314b27a4bce0e8fbc01bb9736cb9ed10da747af722c5a4f2fcb1213a3-d: no such file or directory
This change adds a new output group …
> Request stdlib cache dir in gopackagesdriver

- go/private/rpath.bzl
- tests/bcr/BUILD.bazel
- tests/bcr/cgo_nestedmod.go
- tests/bcr/cgo_nestedmod_test.go
- tests/bcr/other_module/BUILD.bazel
- tests/bcr/other_module/bar.c
Bug fix
My company has a complicated, uncommon bazel set up with nested bazel modules. We also use cgo extensively and have many go tests and binaries that end up linking to shared C++ libraries generated via other bazel modules. When such go tests are run with rbe, they fail due to failure to locate the shared libraries within the runfiles directory.
On deeper investigation, I found that the existing `rpath` computation assumes that both the executable and the library are present within the working directory. In reality, the executable is present outside the working directory but within the runfiles directory.
Normalizing the paths with respect to the runfiles directory fixes the issue.
Relevant links:
- …
> Compute rpath correctly with nested bazel modules

- go/private/extensions.bzl
- go/private/sdk.bzl
- tests/bcr/MODULE.bazel
- tests/bcr/other_module/MODULE.bazel
Feature
This moves the download of the "all versions" JSON, which can't hit the repository cache, from each individual `go_download_sdk` into the module extension. If the current version of Bazel supports facts, this information will also be persisted in the lockfile, allowing for truly airgapped builds assuming an up-to-date download (formerly repository) cache.
See https://github.com/bazelbuild/bazel/pull/26198 for the PR that adds facts support to Bazel.
Fixes #3945 
> go_sdk: store SDK filenames and hashes in lockfile facts

- go/private/actions/compilepkg.bzl
- go/private/rules/test.bzl
- go/private/sdk.bzl
- go/tools/builders/compilepkg.go
- go/tools/builders/cover.go
- go/tools/builders/cover_test.go
- go/tools/builders/generate_test_main.go
- go/tools/bzltestutil/BUILD.bazel
- go/tools/bzltestutil/lcov.go
- go/tools/bzltestutil/lcov_test.go
- go/tools/coverdata/coverdata.go
- tests/core/coverage/coverage_test.go
- tests/core/from_go_mod_file/from_go_mod_file_test.go
- tests/core/go_download_sdk/go_download_sdk_test.go
go1.25 removes the current runtime code coverage system adopted by
rules_go (nocoverageredesign) https://go-review.googlesource.com/c/go/+/644997
which makes rules_go incompatible with the latest upcoming version of go.
The change completely adopts the new integration test friendly coverageredesign
system (https://go.dev/blog/integration-test-coverage) in rules_go.
Below I describe how the current rules_go coverage system currently works, what
changes in the new coverage redesign, and what needs to change as a result in
rules_go.
How nocoverageredesign currently works:
- rules_go invokes `go tool cover` to generate instrumented source files that
are then passed to the Go compiler (in compilepkg.go). Instrumented source
files update generated package variable counters.
- The rules_go …
> Support integration test coverage system (coverageredesign)

- .bazelci/presubmit.yml
- go/tools/builders/compilepkg.go
- tests/core/coverage/BUILD.bazel
- tests/core/coverage/issue4414_test.go
>
> Bug fix
> Feature
> Other
Fixes #
https://github.com/bazel-contrib/rules_go/issues/4412
> fix: instrumentForCoverage for empty outfiles

- go/tools/bazel/bazel.go
- go/tools/bazel/runfiles.go
A “deprecated” comment must be a separate paragraph, and there must be at least one other paragraph in the docstring.  Otherwise pkg.go.dev won’t mark the symbol as deprecated.
Documentation
Correctly marks the deprecated symbols as deprecated on pkg.go.dev.
Fixes #
> Fix “deprecated” comments.

- go.mod
- go/private/BUILD.sdk.bazel
- go/private/actions/compilepkg.bzl
- go/private/common.bzl
- go/private/go_toolchain.bzl
- go/private/rules/binary.bzl
- go/private/rules/transition.bzl
- go/tools/builders/compilepkg.go
- go/tools/builders/stdlib.go
- tests/bcr/BUILD.bazel
- tests/bcr/wrap_test.go
Fix for compatibility with Go 1.25
The `pack` command, which is no longer shipped as a prebuilt binary with Go 1.25, is now compiled from source together with the `builder` binary.
Conditional logic is avoided by always compiling `pack` from source, even on Go versions before 1.25. By enabling `go build` caching in `go_tool_binary`, the overhead compared to building just the `builder` binary is negligible.
ref: https://github.com/golang/go/issues/74080
fixes https://github.com/bazel-contrib/rules_go/issues/4398
> Compile `cmd/pack` from source and update to Go 1.25

- go/private/extensions.bzl
- go/private/sdk.bzl
- tests/bcr/MODULE.bazel
- tests/bcr/other_module/MODULE.bazel
Reverts bazel-contrib/rules_go#4393
The facts feature didn't get merged in time for Bazel 8.4.0 and without it this PR caused an eager fetch of the version list for the default SDK.
> Revert "go_sdk: store SDK filenames and hashes in lockfile facts"

- go/private/rules/test.bzl
- tests/core/output_groups/BUILD.bazel
- tests/core/output_groups/compilation_outputs_test.go
- tests/core/output_groups/lib_blackbox_test.go
> Bug fix
The PR makes external test archive included in `compilation_outputs` output group. This is necessary because currently, e.g., `bazel build --output_groups=compilation_outputs //foo/bar:bar_test` won't build test files that have `package bar_test` in them.
[Slack context](https://bazelbuild.slack.com/archives/CDBP88Z0D/p1756742089621919)
> Include blackbox tests in compilation_outputs group

- go/tools/builders/env.go
Bug fix
Since `--warning-suppression-mappings` points to a file path, it doesn't work with the additional sandboxing go introduces. This change adds the flag to `cgoAbsEnvFlags` to allow it to work during cgo compilation.
> Add --warning-suppression-mappings to cgoAbsEnvFlags

- go/tools/go_bin_runner/main.go
- tests/bcr/go_tool_test.sh
Bug fix
This PR fixes an inconsistency in how environment variables interact with `go_env`. Prior to this PR, environment variables could override settings in `go_env` within `go_repository`, but could not override `go_env` when invoking `@rules_go//go`.
Fixes #4462
> Allow environment variables to override `go_env` in `@rules_go//go`
